// @ts-nocheck
import { DifferentialSet } from "@/types/seed";

export const pediatricsDifferentials: DifferentialSet[] = [
  {
    id: "peds-diff-fever-infant",
    rotation: "pediatrics",
    chiefComplaint: "Fever in a Neonate / Young Infant (< 90 Days)",
    diagnoses: [
      {
        name: "Serious Bacterial Infection (SBI) — Bacteremia / Meningitis / UTI",
        likelihood: "must rule out",
        keyFeatures: [
          "Temperature ≥ 38°C (100.4°F) rectally in infant < 90 days = always concerning",
          "Most common SBI at this age: UTI (E. coli), bacteremia, meningitis (GBS, E. coli, Listeria in neonates; S. pneumo, N. meningitidis after 1–3 months)",
          "Ill appearance, poor feeding, irritability, bulging fontanelle (meningitis), petechiae/purpura (N. meningitidis)",
          "Work-up: CBC, BMP, UA with culture, blood culture, CSF analysis + culture — the 'sepsis work-up'",
        ],
        distinguishingFeatures: "Age < 28 days: full septic work-up + hospitalization + empiric antibiotics for ALL febrile neonates regardless of appearance. Age 29–90 days: risk-stratify using validated criteria (Rochester, Philadelphia, Boston, Step-by-Step, or PECARN febrile infant rules).",
        workUp: "CBC (ANC), UA + culture, blood culture, CSF (if < 28 days or high-risk), CRP, procalcitonin. PECARN febrile infant algorithm: if procalcitonin < 0.5 ng/mL + UA negative + ANC < 4,090 → low risk for SBI; can defer LP and observe in well-appearing 29–60 day olds.",
        treatment: "Neonates (< 28 days): ampicillin + gentamicin (or cefotaxime) IV, admit. Age 29–60 days (high-risk or ill): ceftriaxone IV + admit ± LP. Low-risk, well-appearing 29–60 day olds: shared decision-making — may observe with IM ceftriaxone and close follow-up in select settings.",
      },
      {
        name: "Viral Infection (Bronchiolitis, URI, Roseola/HHV-6)",
        likelihood: "common",
        keyFeatures: [
          "Most common cause of fever in young infants is viral",
          "RSV bronchiolitis: wheezing, tachypnea, rhinorrhea, URI season (Oct–Mar)",
          "Roseola (HHV-6): high fever 3–5 days → rash appears as fever breaks (rose-pink macular rash starting on trunk); most common cause of febrile seizures",
          "Enterovirus: summer/fall, may cause meningitis-like picture",
        ],
        distinguishingFeatures: "Viral infection cannot be reliably distinguished from SBI on clinical grounds in infants < 90 days — MUST exclude SBI with appropriate work-up before attributing fever to viral illness in this age group.",
        workUp: "Clinical + respiratory viral PCR panel if symptomatic. RSV antigen/PCR if bronchiolitis presentation.",
        treatment: "Supportive care. Acetaminophen 10–15 mg/kg PO/PR q4–6h (ibuprofen NOT safe < 6 months) for fever/comfort.",
      },
      {
        name: "Herpes Simplex Virus (HSV) Neonatal Disease",
        likelihood: "must not miss",
        keyFeatures: [
          "Perinatally acquired (vertical transmission during vaginal delivery from active maternal HSV-2 infection — often asymptomatic primary infection in mother)",
          "Presents at 1–4 weeks of life: three forms — (1) skin/eye/mouth (SEM), (2) CNS (encephalitis — seizures, lethargy, CSF pleocytosis, EEG temporal lobe changes), (3) disseminated (septic shock, liver failure, DIC, skin vesicles in 50%)",
          "Skin vesicles present in only 50% — absence does NOT exclude HSV",
          "Mortality: untreated disseminated HSV = 80%, untreated CNS = 50%",
        ],
        distinguishingFeatures: "Think HSV in any febrile neonate with seizures, CSF pleocytosis, elevated liver enzymes, or vesicular lesions. Key question: maternal history of genital herpes or HSV lesions at delivery (ask directly — often not volunteered).",
        workUp: "CSF HSV PCR, serum HSV PCR, surface swabs (conjunctival, nasopharyngeal, rectal), liver enzymes, CBC, coagulation studies.",
        treatment: "IV acyclovir 20 mg/kg q8h × 21 days (CNS/disseminated) or 14 days (SEM). Start empirically in any neonate with CSF pleocytosis or risk factors while awaiting PCR. Oral acyclovir suppression × 6 months after acute treatment reduces recurrence and neurologic sequelae.",
      },
    ],
    clinicalPearl:
      "The approach to febrile infants has evolved significantly with validated clinical decision tools (PECARN, Step-by-Step, BIDOS). In well-appearing infants 29–60 days: if procalcitonin < 0.5 ng/mL, ANC < 4,090/mm³, and urinalysis is negative — these infants have a very low risk for SBI (< 1%) and may not need LP before empiric treatment or observation. However, in neonates < 28 days old, there are NO validated tools to safely defer LP — all febrile neonates need full work-up and empiric antibiotics.",
    boardRecallTip: "Fever < 28 days = full septic work-up + ampicillin + gentamicin, admit. 29–60 days: risk stratify (PECARN). HSV neonatal: vesicles in only 50%; acyclovir 20 mg/kg q8h empirically. HHV-6 = roseola = most common cause of febrile seizures. Roseola: fever clears → rash appears.",
  },
  {
    id: "peds-diff-limp-child",
    rotation: "pediatrics",
    chiefComplaint: "Acute Limping in a Child",
    diagnoses: [
      {
        name: "Transient Synovitis (Toxic Synovitis) of the Hip",
        likelihood: "most common",
        keyFeatures: [
          "Most common cause of acute hip pain in children aged 3–10 years",
          "Sudden onset hip pain (referred to knee), limping, limited internal rotation, refusal to weight-bear",
          "Often follows a viral URI by 1–2 weeks",
          "Low-grade or no fever, ESR and CRP may be mildly elevated or normal, WBC normal",
          "Ultrasound shows hip joint effusion (small to moderate, echogenic)",
        ],
        distinguishingFeatures: "Kocher criteria help distinguish from septic arthritis: (1) fever > 38.5°C, (2) non-weight bearing, (3) ESR > 40, (4) WBC > 12,000. Kocher 0 criteria: < 0.2% probability of septic arthritis. Kocher 4 criteria: 99% probability.",
        workUp: "Hip ultrasound (effusion), CBC, ESR, CRP, blood culture (if concern for septic arthritis). X-ray to exclude AVN or Perthes.",
        treatment: "Rest, NSAIDs (ibuprofen), non-weight bearing. Resolves in 1–4 weeks. Recurrence in 15%.",
      },
      {
        name: "Septic Arthritis",
        likelihood: "must not miss",
        keyFeatures: [
          "Bacterial infection of joint space — orthopedic emergency (joint destruction within 24–48 hours if untreated)",
          "Most common cause: Staph aureus (all ages); Group B Strep (neonates); N. gonorrhoeae (adolescents — polyarthritis, dermatitis, tenosynovitis triad)",
          "High fever (> 38.5°C), ill appearance, severe pain, pseudoparalysis (refuses to move joint)",
          "Kocher criteria ≥ 2 or positive findings on US (large effusion, synovial thickening)",
        ],
        distinguishingFeatures: "Cannot reliably be distinguished from transient synovitis on clinical grounds alone. Decisive test: joint aspiration — WBC > 50,000 (PMN > 75%) = septic; glucose low; positive Gram stain/culture.",
        workUp: "Hip ultrasound, CBC, ESR, CRP, blood culture, joint aspiration (diagnostic + therapeutic). MRI if osteomyelitis suspected.",
        treatment: "Emergent surgical drainage (arthrotomy or arthroscopic lavage) + IV antibiotics (nafcillin or cefazolin for MSSA; vancomycin if MRSA risk or immunocompromised). Duration 2–4 weeks (IV→oral transition).",
      },
      {
        name: "Legg-Calvé-Perthes Disease (Avascular Necrosis of Femoral Head)",
        likelihood: "consider",
        keyFeatures: [
          "Idiopathic AVN of femoral head in children 4–10 years (peak 6 years), males 4:1",
          "Insidious onset hip pain with limp, limited internal rotation and abduction",
          "Early X-ray may be normal (bone scan or MRI more sensitive)",
          "Late X-ray: 'crescent sign' (subchondral fracture) → flattening and fragmentation of femoral head",
        ],
        distinguishingFeatures: "Gradual onset (vs acute septic arthritis). Low-grade or no fever. MRI/bone scan confirms early AVN before X-ray changes.",
        workUp: "Hip X-ray (AP + frog-leg lateral), MRI if X-ray normal, bone scan. Labs generally normal.",
        treatment: "Orthopedic referral. Goal: maintain femoral head sphericity in acetabulum. Non-weight bearing, physical therapy, Petrie casting, or surgical containment (pelvic/femoral osteotomy) for severe cases.",
      },
      {
        name: "Slipped Capital Femoral Epiphysis (SCFE)",
        likelihood: "common in obese adolescents",
        keyFeatures: [
          "Displacement of femoral head (capital epiphysis) posteriorly and inferiorly off femoral neck",
          "Age 11–14 years (during pubertal growth spurt), obese children, male predominance",
          "Hip pain with obligate external rotation — 'pizza sign' (when hip flexed, leg falls into external rotation)",
          "Frog-leg lateral X-ray: 'ice cream slipping off cone' — epiphysis displaced posterior-inferior",
          "Risk factors: obesity, hypothyroidism, growth hormone therapy, renal osteodystrophy",
        ],
        distinguishingFeatures: "Age (adolescent), obesity, external rotation deformity, specific X-ray findings. Any hip pain in an obese adolescent = SCFE until proven otherwise. May also present as knee pain (referred).",
        workUp: "Hip X-ray (AP + frog-leg lateral) — Southwick angle, Klein's line abnormal. Contralateral hip X-ray (bilateral in 20–40%).",
        treatment: "Non-weight bearing immediately (risk of complete slip and AVN with further movement). Surgical: in-situ pinning (single screw through physis). Prophylactic pinning of contralateral hip in high-risk patients.",
      },
      {
        name: "Osteomyelitis",
        likelihood: "consider",
        keyFeatures: [
          "Bacterial infection of bone — hematogenous spread to metaphysis (highly vascular in children)",
          "Fever, localized bone pain, tenderness, swelling, warmth; point tenderness over metaphysis",
          "Most common organism: Staph aureus (MRSA increasingly common). Neonates: GBS, Staph. Sickle cell: Salmonella (also Staph aureus — both must be covered)",
          "Labs: elevated WBC, ESR, CRP, blood cultures (positive in 50–60%). X-ray: early = normal; 7–10 days: periosteal reaction, lytic lesion. MRI = gold standard (bone marrow edema visible within 24–48 hours).",
        ],
        distinguishingFeatures: "Bone tenderness over metaphysis (not joint line). May have subperiosteal abscess or frank joint involvement. CRP > 2 mg/dL + ESR > 20 + fever + bone pain → MRI.",
        workUp: "MRI (gold standard), bone scan if MRI unavailable, blood cultures, CBC, CRP, ESR, wound/bone culture if surgery.",
        treatment: "IV antibiotics (nafcillin/oxacillin; vancomycin if MRSA risk). Surgical debridement if abscess, failed medical therapy, or chronic osteomyelitis.",
      },
    ],
    clinicalPearl:
      "SCFE is the most commonly missed orthopedic diagnosis in obese adolescents because hip pain is often referred to the knee — up to 25% of SCFE cases are initially diagnosed as knee pain. In any obese adolescent with knee or hip pain, obtain an AP pelvis and frog-leg lateral hip X-ray. The external rotation obligate deformity ('pizza sign') is pathognomonic when present. Urgent orthopedic referral — any further weight-bearing risks complete displacement and femoral head AVN.",
    boardRecallTip: "Transient synovitis = most common hip pain in children 3–10 (viral URI prodrome, low fever, self-limited). Kocher ≥ 2 criteria → joint aspiration (septic arthritis). SCFE: obese adolescent, external rotation, 'ice cream cone' on frog-leg X-ray → non-weight bearing + in-situ pinning. Sickle cell + bone pain → both Staph AND Salmonella.",
  },
  {
    id: "peds-diff-stridor",
    rotation: "pediatrics",
    chiefComplaint: "Stridor in a Child",
    diagnoses: [
      {
        name: "Croup (Laryngotracheobronchitis)",
        likelihood: "most common",
        keyFeatures: [
          "Age 6 months to 3 years, peak at 18 months. Fall/winter (parainfluenza virus type 1).",
          "Barky/seal-like cough + inspiratory stridor + hoarse voice + URI prodrome 1–3 days",
          "Symptoms worse at night; sudden onset, child may awaken from sleep",
          "Steeple sign on AP neck X-ray (present in 50%); clinical diagnosis",
        ],
        distinguishingFeatures: "Barky cough is the hallmark — not present in epiglottitis, foreign body, or peritonsillar abscess. Symptoms improve with cool air or racemic epinephrine.",
        workUp: "Clinical diagnosis. AP neck X-ray if uncertain (steeple sign). Pulse oximetry.",
        treatment: "Dexamethasone 0.6 mg/kg PO/IM × 1 dose (all severity). Racemic epinephrine nebulized for moderate-severe. Observe 2–4 hours post-epinephrine.",
      },
      {
        name: "Epiglottitis",
        likelihood: "must not miss — emergency",
        keyFeatures: [
          "Rapid onset (hours) in toxic-appearing child: high fever, drooling, tripod posturing (leans forward on hands), muffled 'hot potato' voice, dysphagia — NO barky cough",
          "Rare since Hib vaccine — still occurs in unvaccinated children or due to non-Hib H. influenzae, Strep pneumo, Staph aureus",
          "Thumb sign on lateral neck X-ray (swollen epiglottis) — if clinical suspicion, do NOT obtain X-ray; proceed directly to OR",
        ],
        distinguishingFeatures: "Tripod posturing + drooling + muffled voice + NO barky cough. Do NOT agitate, do NOT do throat exam, do NOT lie child down — may precipitate complete obstruction.",
        workUp: "Lateral neck X-ray ONLY if mild/stable; otherwise skip imaging. Direct laryngoscopy in OR (controlled airway).",
        treatment: "Airway is the priority: controlled intubation in OR with ENT + anesthesia standby. Ceftriaxone IV. Racemic epinephrine NOT effective for epiglottitis.",
      },
      {
        name: "Foreign Body Aspiration",
        likelihood: "common in toddlers",
        keyFeatures: [
          "Peak age: 6 months to 4 years. Classic history: sudden choking episode, may have fully resolved with transient distress",
          "Objects: nuts (peanuts most common), grapes, popcorn, small toys, coins",
          "Laryngeal/tracheal: biphasic stridor, cyanosis (life-threatening)",
          "Bronchial: unilateral wheeze, asymmetric air entry, CXR: asymmetric hyperinflation (air trapping) on expiratory film, mediastinal shift away from obstructed side",
        ],
        distinguishingFeatures: "Sudden onset without fever, history of choking. Unilateral wheeze not responding to bronchodilators. Asymmetric hyperinflation on expiratory CXR.",
        workUp: "AP + lateral CXR (inspiratory and expiratory or bilateral decubitus — to look for air trapping). Rigid bronchoscopy if high suspicion (even with normal CXR).",
        treatment: "Back blows and chest thrusts (Heimlich in child > 1 year) for complete obstruction. Rigid bronchoscopy for removal. Do NOT perform Heimlich on infants < 1 year (5 back blows + 5 chest thrusts).",
      },
      {
        name: "Bacterial Tracheitis",
        likelihood: "uncommon but serious",
        keyFeatures: [
          "Complication of viral croup (secondary bacterial infection). Staph aureus (including MRSA) most common pathogen.",
          "Toxic-appearing child with high fever, barky cough, stridor that does NOT respond to racemic epinephrine",
          "Classic: barky cough (like croup) but toxic appearance distinguishes it",
          "CXR: subglottic narrowing + irregular tracheal wall (pseudomembranes) + normal epiglottis",
          "Laryngoscopy: copious, tenacious mucopurulent exudate and pseudomembranes in trachea",
        ],
        distinguishingFeatures: "Barky cough (like croup) BUT toxic appearance + does NOT respond to steroids or epinephrine.",
        workUp: "AP/lateral neck and CXR, CBC (leukocytosis), blood cultures, tracheal cultures at intubation.",
        treatment: "Intubation (often required), IV antibiotics (vancomycin + clindamycin for MRSA/toxin coverage; ceftriaxone for H. flu), repeated suctioning of pseudomembranes.",
      },
      {
        name: "Laryngomalacia",
        likelihood: "most common cause of stridor in infants",
        keyFeatures: [
          "Most common cause of chronic stridor in infants (50–75% of laryngeal anomalies)",
          "Onset: birth to 4–6 weeks; worsens with feeding, agitation, supine position; improves prone",
          "Inspiratory stridor — soft, high-pitched, musical; intermittent; worse when feeding",
          "Flexible laryngoscopy: prolapse of omega-shaped epiglottis and arytenoid cartilages into airway on inspiration",
        ],
        distinguishingFeatures: "Chronic (not acute), present since birth. Worsens with feeds and crying, better prone. No respiratory distress at rest.",
        workUp: "Flexible nasopharyngoscopy (confirms diagnosis, rules out other lesions). Esophageal pH probe if GERD contributing.",
        treatment: "Most resolve spontaneously by 18–24 months. GERD treatment (acid reflux exacerbates laryngomalacia). Supraglottoplasty for severe cases with failure to thrive or apnea.",
      },
    ],
    clinicalPearl:
      "The key to stridor evaluation is determining if it is: (1) chronic vs acute, (2) inspiratory vs biphasic/expiratory, (3) associated with fever/toxic appearance vs afebrile, (4) positional. Chronic inspiratory stridor since birth = laryngomalacia. Acute + fever + barky cough = croup. Acute + fever + toxic + drooling + NO barky cough = epiglottitis (airway emergency). Acute + choking episode + NO fever + unilateral wheeze = foreign body aspiration. Acute + barky cough + toxic + no response to epinephrine = bacterial tracheitis.",
    boardRecallTip: "Croup: barky cough, parainfluenza, dexamethasone + racemic epinephrine. Epiglottitis: drooling + tripod + NO barky cough → OR immediately. Foreign body: sudden choking, asymmetric hyperinflation on expiratory CXR. Bacterial tracheitis: barky cough + toxic + not responding to steroids → Staph aureus. Laryngomalacia: birth, inspiratory stridor, worse with feeds, resolves 18–24 months.",
  },
  {
    id: "peds-diff-vomiting-infant",
    rotation: "pediatrics",
    chiefComplaint: "Vomiting in an Infant",
    diagnoses: [
      {
        name: "Gastroesophageal Reflux (GER) / GERD",
        likelihood: "most common",
        keyFeatures: [
          "Physiologic GER ('happy spitter'): frequent effortless regurgitation after feeds, adequate weight gain, not distressed — no treatment needed beyond reassurance and positioning",
          "GERD (pathological): poor weight gain, excessive crying/arching (Sandifer syndrome), apnea, recurrent aspiration pneumonia, esophagitis",
          "Non-bilious, effortless regurgitation (vs pyloric stenosis = projectile, vs malrotation = bilious)",
        ],
        distinguishingFeatures: "Regurgitation vs vomiting distinction. GER: effortless, not forceful. Happy spitter = physiologic GER. Arching, crying, weight loss, apnea = GERD requiring treatment.",
        workUp: "Clinical diagnosis in most cases. Upper GI series to exclude malrotation/anatomic abnormality. pH probe or impedance study for quantification.",
        treatment: "GER: thickened feeds (rice cereal in formula — not in breastfed infants), prone positioning when awake and supervised. GERD: H₂ blockers (ranitidine replaced by famotidine) or PPI if severe. Avoid routine PPI use in infants with uncomplicated regurgitation (AAP does not recommend).",
      },
      {
        name: "Pyloric Stenosis",
        likelihood: "common at 3–6 weeks",
        keyFeatures: [
          "Age 3–6 weeks, first-born males, non-bilious PROJECTILE vomiting (forceful, olive-pit size)",
          "'Hungry vomiter' — feeds eagerly immediately after vomiting, still hungry",
          "Metabolic: hypochloremic, hypokalemic metabolic alkalosis (paradoxical aciduria)",
          "Palpable olive-shaped mass in epigastrium (rarely palpated in practice — US confirms)",
        ],
        distinguishingFeatures: "Projectile (not effortless), non-bilious. Age 3–6 weeks. Metabolic alkalosis on BMP. US diagnostic.",
        workUp: "BMP (alkalosis), abdominal US (pyloric thickness ≥ 4 mm, length ≥ 17 mm). Nothing orally before correcting electrolytes.",
        treatment: "Correct electrolytes and hydration first (not surgical emergency). Ramstedt pyloromyotomy (laparoscopic preferred).",
      },
      {
        name: "Malrotation with Midgut Volvulus",
        likelihood: "must not miss — surgical emergency",
        keyFeatures: [
          "Bilious (green) vomiting in neonate is a SURGICAL EMERGENCY until proven otherwise",
          "Peak age: neonate to 1 month (75% present in first month of life)",
          "Volvulus: bowel twists on SMA → ischemia → 'current jelly' stool (late, ominous), peritonitis",
          "Upper GI series: 'corkscrew' duodenum, failure of duodenal-jejunal junction to cross midline (ligament of Treitz absent)",
        ],
        distinguishingFeatures: "Bilious vomiting = ALWAYS pathological in a neonate. Malrotation may be asymptomatic until volvulus occurs. X-ray: may show 'double bubble' pattern or paucity of bowel gas.",
        workUp: "Abdominal X-ray, upper GI series (gold standard for malrotation diagnosis). Ultrasound: SMV to the left of SMA ('whirlpool sign') suggests malrotation.",
        treatment: "Emergent surgical exploration and Ladd procedure (counterclockwise detorsion + broadening of mesenteric base + removal of Ladd's bands + appendectomy). Bowel resection if non-viable.",
      },
      {
        name: "Intussusception",
        likelihood: "common at 6 months to 3 years",
        keyFeatures: [
          "Telescoping of bowel — episodic colicky pain (draws knees to chest) + vomiting + currant-jelly stool (late)",
          "Peak age: 6–36 months. Lethargic infant with intermittent inconsolable crying.",
          "Ultrasound: target sign (bull's eye). Air enema: diagnostic + therapeutic (80–90% success).",
        ],
        distinguishingFeatures: "Episodic, colicky pain with complete resolution between episodes. Age 6 months to 3 years. Currant-jelly stool is late and ominous (ischemic bowel).",
        workUp: "Abdominal ultrasound (target sign). Air enema if US positive (both diagnostic and therapeutic).",
        treatment: "Air or contrast enema (80–90% success). Surgery if failed enema or peritonitis.",
      },
      {
        name: "Hirschsprung Disease (Aganglionic Megacolon)",
        likelihood: "consider in neonate with delayed meconium",
        keyFeatures: [
          "Failure to pass meconium within 48 hours of birth (98% of term neonates pass within 48h), abdominal distension, bilious vomiting",
          "Absence of ganglion cells (Auerbach's plexus) in distal colon → functional obstruction",
          "Associated with: Down syndrome (10% of Hirschsprung), RET proto-oncogene mutations",
          "Enterocolitis: life-threatening complication — explosive diarrhea after rectal exam (decompression), fever, toxicity",
        ],
        distinguishingFeatures: "Delayed meconium (> 48 hours) + abdominal distension in neonate. Explosive decompression on rectal exam. Contrast enema: narrow aganglionic segment → dilated proximal colon (transition zone).",
        workUp: "Contrast enema (water-soluble), rectal suction biopsy (definitive — absent ganglion cells, hypertrophied nerves), rectal manometry (absence of rectoanal inhibitory reflex).",
        treatment: "Surgical pull-through procedure (Swenson, Soave, Duhamel) — removes aganglionic segment. Bowel prep and colostomy in severe cases. Enterocolitis: IV antibiotics, rectal irrigations.",
      },
    ],
    clinicalPearl:
      "Bilious (green) vomiting in a neonate is always a surgical emergency until proven otherwise — it indicates obstruction at or below the ampulla of Vater. The differential includes malrotation with volvulus, duodenal atresia, jejunal/ileal atresia, and Hirschsprung disease. In contrast, non-bilious vomiting localizes the obstruction above the ampulla (pyloric stenosis, hypertrophic pyloric stenosis, gastric outlet obstruction). The color of the vomitus — bilious vs non-bilious — is one of the most important clinical distinctions in pediatric gastroenterology.",
    boardRecallTip: "Bilious vomiting in neonate = surgical emergency → upper GI series (malrotation/volvulus). Non-bilious projectile = pyloric stenosis (US, correct lytes before surgery). Hirschsprung: meconium > 48h + distension → rectal biopsy (absent ganglion cells). Intussusception: 6–36 months, episodic colic → US target sign → air enema.",
  },
];
