// @ts-nocheck
import { Guideline } from "@/types/seed";

export const pediatricsGuidelines: Guideline[] = [
  {
    id: "peds-gl-asthma-naepp",
    rotation: "pediatrics",
    name: "NAEPP EPR-4: Asthma Management Guidelines",
    organization: "National Asthma Education and Prevention Program (NAEPP)",
    year: 2020,
    keyRecommendations: [
      "Classify asthma severity before initiating therapy: Intermittent (symptoms ≤ 2 days/week, nighttime awakening ≤ 2×/month, FEV₁ ≥ 80%, no limitation of activity); Mild persistent (> 2 days/week but not daily, 3–4×/month nighttime); Moderate persistent (daily symptoms, > 1 nighttime/week, FEV₁ 60–80%); Severe persistent (continual symptoms, frequent nighttime, FEV₁ < 60%)",
      "Step 1 (intermittent): SABA PRN only — albuterol MDI with spacer 2 puffs as needed. Frequency > 2 days/week = inadequate control → step up",
      "Step 2 (mild persistent): Low-dose ICS daily — preferred controller. Alternatives: LTRA (montelukast) or cromolyn. Step 2 is the threshold for daily controller therapy.",
      "Step 3 (moderate persistent): Medium-dose ICS OR low-dose ICS + LABA (age ≥ 5 years). LABA must NEVER be used without ICS (Black box warning for asthma death with LABA monotherapy)",
      "Step 4: Medium-dose ICS + LABA; Step 5: High-dose ICS + LABA + biologics (omalizumab for allergic; mepolizumab, dupilumab for eosinophilic); Step 6: Step 5 + oral corticosteroids",
      "Assess and step down every 3 months if well-controlled for ≥ 3 months at current step",
      "Add SABA to any step as rescue. If SABA use > 2 days/week = not well controlled",
      "Preschool children (< 5 years): inhaled SABA + ICS (fluticasone 44 mcg) if mild persistent; LABA NOT approved < 5 years for asthma; LTRA as alternative to ICS in this age group",
    ],
    clinicalApplication:
      "In clinical practice, the EPR-4 update (2020) added guidance that using ICS-formoterol (budesonide-formoterol) as both a maintenance AND reliever ('MART' strategy) is an option for Steps 3–4 in adults and adolescents ≥ 12 years — this is based on SMART/GINA strategy evidence. Also emphasized: Treat-to-Control rather than Treat-to-Severity — titrate based on current control assessment, not initial classification. Annual influenza vaccine is recommended for all asthma patients.",
    boardRecallTip: "Step 2 = low-dose ICS (most important controller). LABA NEVER alone (black box). SABA > 2 days/week = not controlled → step up. Biologics at step 5 (omalizumab = allergic; mepolizumab/benralizumab = eosinophilic; dupilumab = eosinophilic or OCS-dependent).",
  },
  {
    id: "peds-gl-aom-aap",
    rotation: "pediatrics",
    name: "AAP Clinical Practice Guideline: Acute Otitis Media",
    organization: "American Academy of Pediatrics (AAP) / American Academy of Family Physicians (AAFP)",
    year: 2013,
    keyRecommendations: [
      "Accurate diagnosis requires: (1) Moderate-to-severe bulging of the TM OR new otorrhea not from otitis externa; OR (2) Mild TM bulging + acute ear pain + TM erythema — PLUS middle ear effusion (MEE). Erythema alone is insufficient.",
      "Watchful waiting (observation option): Appropriate for non-severe unilateral AOM in children ≥ 2 years OR non-severe unilateral/bilateral AOM in children 6–23 months with limited diagnostic certainty. Provide safety-net antibiotic prescription to fill if not improved in 48–72 hours.",
      "Immediate antibiotic treatment: age < 6 months; severe illness (T ≥ 39°C or severe otalgia ≥ 48h); bilateral AOM in child 6–23 months; AOM with otorrhea at any age.",
      "First-line antibiotic: amoxicillin 80–90 mg/kg/day ÷ BID (high-dose for Strep pneumo resistance). Duration: 10 days for < 2 years or severe disease; 7 days for 2–5 years; 5–7 days for ≥ 6 years.",
      "Treatment failure at 48–72h: amoxicillin-clavulanate 90/6.4 mg/kg/day ÷ BID × 10 days (covers beta-lactamase-producing H. flu and Moraxella).",
      "Penicillin allergy (non-severe): cefdinir, cefuroxime, or cefpodoxime. Severe allergy (anaphylaxis): azithromycin (limited H. flu coverage) or clindamycin.",
      "Tympanostomy tubes: for recurrent AOM (≥ 3 episodes in 6 months OR ≥ 4 in 12 months with ≥ 1 in past 6 months); chronic OME with bilateral hearing loss ≥ 40 dB; or OME > 3 months with developmental risk.",
      "Pain management: ibuprofen or acetaminophen; topical benzocaine drops may be used in children ≥ 2 years without perforation for short-term pain relief.",
    ],
    clinicalApplication:
      "The most impactful change in modern AOM management is the recognition that high-dose amoxicillin (80–90 mg/kg/day) is necessary to overcome intermediate-level penicillin resistance in Strep pneumo — this is achievable with oral dosing because amoxicillin achieves higher middle ear fluid concentrations than standard-dose penicillin. Second, the watchful waiting option has reduced unnecessary antibiotic use significantly — with a safety net, children not improving within 48–72 hours can fill their prescription without an additional clinic visit.",
    boardRecallTip: "AOM diagnosis: TM bulging + MEE + acute inflammation. High-dose amoxicillin 80–90 mg/kg/day first-line. Failure → amoxicillin-clavulanate. Recurrent AOM (≥ 3 in 6 months) → PE tubes. Watchful waiting OK for mild, unilateral AOM in children ≥ 2 years.",
  },
  {
    id: "peds-gl-kawasaki-aha",
    rotation: "pediatrics",
    name: "AHA Scientific Statement: Diagnosis, Treatment, and Long-term Management of Kawasaki Disease",
    organization: "American Heart Association (AHA)",
    year: 2017,
    keyRecommendations: [
      "Diagnostic criteria: fever ≥ 5 days + ≥ 4 of 5 principal features: (1) bilateral non-purulent conjunctival injection, (2) oral changes (strawberry tongue, lip cracking, pharyngeal erythema), (3) polymorphous rash, (4) extremity changes (erythema/edema palms and soles, desquamation in convalescence), (5) unilateral cervical lymphadenopathy ≥ 1.5 cm",
      "Incomplete KD: fever ≥ 5 days + 2–3 criteria → evaluate with CRP, ESR, echo. If CRP ≥ 3 mg/dL OR ESR ≥ 40 mm/hr → check supplemental lab criteria (Hgb below normal for age, platelets ≥ 450,000 after day 7, albumin ≤ 3 g/dL, elevated ALT, WBC ≥ 15,000, urine ≥ 10 WBC/hpf). ≥ 3 supplemental labs = treat; OR echo positive (z-score ≥ 2.5) → treat",
      "Treatment: IVIG 2 g/kg IV single infusion over 10–12 hours + aspirin 80–100 mg/kg/day ÷ QID until afebrile 48–72 hours → then aspirin 3–5 mg/kg/day × 6–8 weeks (or indefinitely if CAA)",
      "IVIG resistance (fever > 36 hours post-IVIG): second IVIG 2 g/kg; OR infliximab 5 mg/kg IV; OR methylprednisolone 30 mg/kg/day IV × 3 days for high-risk (Japanese risk score ≥ 5 — Kobayashi or Egami score)",
      "Echocardiography: baseline, 2 weeks, 6–8 weeks. If normal at 6–8 weeks, risk of late coronary involvement is low.",
      "Coronary artery aneurysm (CAA) classification: small (z-score 2.5–4.9), medium (z-score 5–9.9 or absolute 4–8 mm), giant (z-score ≥ 10 or absolute ≥ 8 mm)",
      "Giant aneurysm management: warfarin (target INR 2–3) or LMWH + low-dose aspirin; lifelong cardiology follow-up; stress testing, coronary angiography if stenosis suspected",
      "Defer live vaccines (varicella, MMR) for 11 months after high-dose IVIG; inactivated vaccines can be given normally",
    ],
    clinicalApplication:
      "The 2017 AHA update emphasizes that the classical diagnostic criteria were developed for epidemiological purposes and lack sensitivity — especially for infants < 6 months (who have the highest CAA risk despite often atypical presentation). Incomplete KD should be a clinical diagnosis supported by ancillary criteria and echocardiography, not a diagnosis of exclusion. The decision to treat is based on clinical judgment and echo findings, not strict adherence to criteria count. If a clinician suspects KD in any child with > 5 days of unexplained fever, echo should be strongly considered.",
    boardRecallTip: "KD criteria: fever ≥ 5d + ≥ 4 of CRASH-MC. IVIG 2 g/kg + aspirin. Echo at 0, 2 weeks, 6–8 weeks. IVIG resistance → second IVIG or infliximab. Giant CAA (≥ 8 mm) → warfarin + aspirin. Defer MMR/varicella 11 months.",
  },
  {
    id: "peds-gl-febrile-seizure-aap",
    rotation: "pediatrics",
    name: "AAP Practice Parameter: Febrile Seizures",
    organization: "American Academy of Pediatrics (AAP)",
    year: 2011,
    keyRecommendations: [
      "Simple febrile seizure definition: generalized tonic-clonic, duration < 15 minutes, one episode per febrile illness, full return to baseline consciousness, no neurological deficit",
      "Complex febrile seizure: focal features, duration > 15 minutes, recurrence within 24 hours, or failure to return to baseline",
      "Lumbar puncture strongly consider if: < 12 months (meningeal signs unreliable); 12–18 months (examination may not reliably predict meningitis); immunocompromised; pre-treated with antibiotics; complex febrile seizure; prolonged post-ictal state; ill appearance; or evidence of meningitis on exam",
      "Do NOT routinely order: EEG (does not predict future seizures or epilepsy in simple febrile seizures), neuroimaging (CT/MRI unless focal deficit or papilledema), serum electrolytes, glucose, CBC unless clinically indicated",
      "Antipyretics (acetaminophen, ibuprofen): do NOT prevent recurrence of febrile seizures. Give for comfort only. Parents should be counseled that the goal of fever management is comfort, not seizure prevention.",
      "Prophylactic antiepileptic therapy: NOT recommended for simple febrile seizures. Risk of side effects (sedation, behavioral change, cognitive impairment) outweighs benefit.",
      "Rescue benzodiazepine (rectal diazepam or intranasal midazolam) for home use in selected patients: children with febrile status epilepticus history or prolonged seizures; provide to families with instructions on when to use and when to call 911",
      "Risk factors for recurrence: age < 18 months, family history of febrile seizures, lower temperature at time of seizure, shorter duration of fever before seizure",
    ],
    clinicalApplication:
      "The most common mistake in managing febrile seizures is over-investigation and over-treatment driven by parental anxiety and clinician discomfort. The AAP guideline is clear: for a typical simple febrile seizure in a child who returns to baseline — no EEG, no imaging, no LP (unless meningitis risk factors present), and no prophylactic anticonvulsants. The workup should focus on identifying the CAUSE OF THE FEVER, not the seizure itself. The most feared diagnosis to exclude is bacterial meningitis — and this requires clinical judgment based on exam findings, age, and post-ictal course.",
    boardRecallTip: "Simple febrile seizure = no LP (unless < 12 months or meningeal signs), no EEG, no imaging, no prophylaxis. Antipyretics = comfort only (don't prevent recurrence). Recurrence risk: 30% overall. LP in < 12 months → meningeal signs unreliable. Complex febrile seizure → higher epilepsy risk (4–6%).",
  },
  {
    id: "peds-gl-wellchild-aap",
    rotation: "pediatrics",
    name: "AAP Bright Futures: Preventive Care and Well-Child Visit Schedule",
    organization: "American Academy of Pediatrics (AAP) / HRSA Bright Futures",
    year: 2022,
    keyRecommendations: [
      "Well-child visit schedule: Newborn (3–5 days), 1 month, 2 months, 4 months, 6 months, 9 months, 12 months, 15 months, 18 months, 24 months, 30 months (optional), 3 years, then annually 4–21 years",
      "Developmental surveillance at EVERY well-child visit — apply Developmental Surveillance Periodicity Schedule. Formal developmental screening (ASQ, M-CHAT-R) at 9, 18, and 30 months. Autism-specific screening (M-CHAT-R/F) at 18 and 24 months.",
      "Lead screening: universal blood lead level at 12 months and 24 months (or risk-based screening based on Medicaid enrollment or high-risk housing)",
      "Iron deficiency anemia screening: hemoglobin/hematocrit at 12 months; risk assessment at 4 months (supplemental iron for breastfed infants starting at 4 months)",
      "Hearing screening: newborn hearing screen before hospital discharge (UNHS); repeat at 4, 5, 6, 8, 10 years",
      "Vision screening: newborn (red reflex); instrument-based at 12–36 months; visual acuity screening at 3 years. Refer for ophthalmology if: leukocoria (white reflex — retinoblastoma), strabismus, or failed acuity screen",
      "Hypertension screening: blood pressure measurement at every well-child visit starting at age 3 (earlier if risk factors: obesity, renal disease, family history). Definition: BP ≥ 95th percentile for age/sex/height on 3 occasions",
      "Obesity/BMI: calculate BMI and plot on BMI-for-age chart at every visit from age 2. BMI ≥ 95th percentile = obesity; 85th–94th = overweight. Fasting lipid panel if BMI ≥ 85th percentile at age 9–11 and again at 17–21.",
      "Cholesterol screening (universal): fasting lipid panel at 9–11 years and 17–21 years (NHBPEP/AAP). Earlier if family history of premature CVD or hypercholesterolemia.",
      "Immunizations: follow current ACIP schedule",
    ],
    clinicalApplication:
      "The Bright Futures framework emphasizes 'surveillance' (longitudinal, ongoing assessment at every visit) as distinct from 'screening' (validated tools at specific ages). For developmental delays: surveillance + risk factors at any visit → refer for Early Intervention (EI, services for children birth–3 years under IDEA Part C) or Special Education (IDEA Part B, ages 3–21). Do not wait for formal screening visit if concerned. Remember: ASD screening (M-CHAT-R) is at 18 AND 24 months — not just 18 months. A borderline M-CHAT-R should be followed up with M-CHAT-R/F (Follow-up interview).",
    boardRecallTip: "M-CHAT-R at 18 and 24 months (ASD screening). ASQ at 9, 18, 30 months (general development). Lead level at 12 and 24 months. Hemoglobin at 12 months. BP starting at age 3. BMI-for-age from age 2. Lipid panel: universal at 9–11 years and 17–21 years.",
  },
  {
    id: "peds-gl-vaccine-acip",
    rotation: "pediatrics",
    name: "ACIP: Recommended Child and Adolescent Immunization Schedule",
    organization: "Advisory Committee on Immunization Practices (ACIP) / CDC",
    year: 2024,
    keyRecommendations: [
      "Hepatitis B (HepB): 3-dose series — birth, 1–2 months, 6–18 months. Birth dose within 24 hours for all medically stable newborns ≥ 2 kg.",
      "Rotavirus (RV): 2-dose (Rotarix) or 3-dose (RotaTeq) at 2, 4, (6) months. Do NOT start after 15 weeks (increased intussusception risk with delayed initiation).",
      "DTaP (diphtheria, tetanus, acellular pertussis): 5-dose series at 2, 4, 6, 15–18 months, 4–6 years. Adolescents: Tdap booster at 11–12 years, then Td booster every 10 years.",
      "Hib (H. influenzae type b): 3–4 dose series depending on brand at 2, 4, 6, 12–15 months.",
      "PCV15 or PCV20 (pneumococcal conjugate): 4-dose series at 2, 4, 6, 12–15 months. PCV20 preferred by ACIP 2023 (covers more serotypes). PPSV23 for high-risk children ≥ 2 years.",
      "IPV (inactivated poliovirus): 4-dose series at 2, 4, 6–18 months, 4–6 years.",
      "MMR (measles, mumps, rubella): 2 doses — 12–15 months and 4–6 years. Contraindicated in immunocompromised. Defer 11 months after IVIG.",
      "Varicella (VAR): 2 doses — 12–15 months and 4–6 years. Same contraindications as MMR.",
      "Hepatitis A (HepA): 2-dose series starting at 12–23 months; catch-up for unvaccinated children.",
      "Influenza (IIV): annually for all children ≥ 6 months. Children < 9 years receiving influenza vaccine for the first time: 2 doses, ≥ 4 weeks apart. LAIV (FluMist — intranasal live): age ≥ 2 years, not immunocompromised, no egg allergy (or mild only).",
      "HPV (human papillomavirus): 2-dose series if initiated at age 9–14 (dose 2 given 6–12 months later); 3-dose series if initiated ≥ 15 years (0, 1–2, 6 months). Recommended at 11–12 years.",
      "Meningococcal A, C, W, Y (MenACWY): 2 doses at 11–12 years and 16 years. High-risk (asplenia, complement deficiency, travel to endemic areas): start at 8 weeks.",
      "Meningococcal B (MenB): 16–18 years (shared decision-making); mandatory for high-risk (asplenia, complement deficiency, college freshmen in dorms — shared decision). 2-dose series (Bexsero) or 3-dose (Trumenba).",
      "RSV: Nirsevimab for infants in first RSV season; maternal Abrysvo at 32–36 weeks gestation. RSV-PreF (Abrysvo, mRESVIA) for adults ≥ 60 years.",
      "COVID-19: follow current ACIP/CDC COVID-19 vaccine recommendations (updated annually based on circulating variants).",
    ],
    clinicalApplication:
      "Key practical points: (1) Multiple vaccines at one visit are safe and recommended — combination vaccines (DTaP-IPV-HepB, DTaP-Hib-IPV) reduce number of injections. (2) Missed doses: always catch up — use the CDC Catch-up Immunization Schedule (never restart a series). (3) Minimum intervals between doses must be observed. (4) LAIV (live nasal flu) can be given same day as MMR/varicella but different sites; if not same day, separate injectable live vaccines by 28 days. (5) Preterm infants: vaccines given at chronological age (not corrected gestational age), with the exception of Hepatitis B (hold in infants < 2 kg unless mother HBsAg+).",
    boardRecallTip: "Birth: HepB. 2, 4, 6 months: HepB, RV, DTaP, Hib, PCV, IPV. 12–15 months: MMR, VAR, HepA, PCV, Hib. 4–6 years: DTaP, IPV, MMR, VAR. 11–12 years: Tdap, MenACWY, HPV. 16 years: MenACWY booster. MMR/VAR: defer 11 months post-IVIG.",
  },
];
