// @ts-nocheck
import { PhysicalExamFinding } from "@/types/seed";

export const pediatricsPhysicalExam: PhysicalExamFinding[] = [
  {
    id: "peds-pe-growth-assessment",
    rotation: "pediatrics",
    findingName: "Growth Assessment and Anthropometrics",
    description:
      "Growth assessment is the cornerstone of pediatric physical examination. Accurate measurement of weight, length/height, head circumference (< 3 years), and calculation of BMI (≥ 2 years) — plotted on age- and sex-specific growth curves — is mandatory at every well-child visit. Growth failure (failure to thrive, short stature, microcephaly) is often the first or only sign of underlying disease. The CDC growth charts (2000) are used for children ≥ 2 years; the WHO growth charts are recommended for children < 2 years (breastfed infants).",
    technique:
      "WEIGHT: Infants — calibrated digital scale, completely undressed (diaper removed). Children ≥ 2 years — standing scale, light clothing without shoes. RECUMBENT LENGTH (< 2 years): measuring board (infantometer) with parent holding head at fixed end and examiner extending legs — two-person technique required for accuracy. HEIGHT (≥ 2 years): stadiometer (wall-mounted preferred) — remove shoes, heels against wall, head in Frankfort plane (tragus of ear and inferior orbital rim horizontal). HEAD CIRCUMFERENCE: flexible measuring tape at maximal occipital protuberance posteriorly and frontal prominence anteriorly — at least 3 measurements, record maximum. PLOT ON CORRECT CHART: WHO for < 2 years; CDC for ≥ 2 years. Document percentiles and change over time.",
    normalFindings:
      "Normal growth velocity: Birth weight doubles by 4–5 months (6 kg); triples by 12 months (9–10 kg). Gains ~150–200 g/week in months 0–3; ~100 g/week months 4–6. Height: grows ~25 cm in year 1; ~12 cm in year 2; ~6–8 cm/year ages 3 and beyond until puberty. Head circumference: grows ~2 cm/month months 0–3; normal HC at birth 33–35 cm, reaches 47 cm by 12 months.",
    abnormalFindings: [
      "Failure to thrive (FTT) / Weight faltering: weight < 3rd percentile for age and sex, OR weight crossing 2 major percentile lines downward over time. Most common cause: inadequate caloric intake (non-organic FTT — 80%). Organic causes: malabsorption (celiac, CF), cardiac (CHD — 'cardiac cachexia'), renal (CKD), chronic infection, metabolic disease, child maltreatment.",
      "Short stature: height < 3rd percentile (or < −2 SD) for age and sex. Evaluate: mid-parental height, bone age (left hand X-ray), IGF-1, thyroid function, CBC, BMP. Common causes: familial short stature (constitutional), constitutional growth delay (bone age delayed, catch-up growth expected), growth hormone deficiency, hypothyroidism, Turner syndrome (XO — girls), Noonan syndrome, celiac disease.",
      "Macrocephaly: HC > 98th percentile. Causes: benign familial macrocephaly (measure parent HC), hydrocephalus (bulging fontanelle, sunset sign), megalencephaly (overgrowth syndrome — Sotos, Bannayan-Riley), subdural hematoma (child abuse — always consider in infant with macrocephaly + retinal hemorrhages).",
      "Microcephaly: HC < 2nd percentile (> 3 SD below mean). Causes: in utero infection (TORCH — CMV most common cause of congenital microcephaly), genetic syndromes (Angelman, Cri-du-chat), metabolic (PKU in untreated mothers), fetal alcohol syndrome, congenital Zika virus. Associated with intellectual disability.",
      "Obesity: BMI ≥ 95th percentile for age and sex. Overweight: BMI 85th–94th percentile. Screen for comorbidities: hypertension, dyslipidemia, prediabetes/type 2 diabetes (fasting glucose, HbA1c), sleep apnea, non-alcoholic fatty liver disease (ALT), depression, musculoskeletal complications.",
    ],
    clinicalPearl:
      "Mid-parental height (target height) calculation: Boys = [(father's height + mother's height + 13 cm) ÷ 2]; Girls = [(father's height + mother's height − 13 cm) ÷ 2]. Expected adult height range = mid-parental height ± 8.5 cm. A child's height trajectory should parallel the reference curve percentile — crossing 2 major percentile lines (5th, 10th, 25th, 50th, 75th, 90th, 95th) downward is abnormal and requires evaluation regardless of absolute percentile.",
    boardRecallTip: "FTT = weight < 3rd percentile or crossing 2 percentile lines down. Most common cause = inadequate intake (non-organic). FTT workup: caloric diary, CBC, BMP, UA, lead, TSH, celiac panel. Head circumference every visit until age 3. Microcephaly (< −3 SD) → TORCH infection (CMV most common).",
  },
  {
    id: "peds-pe-fontanelle",
    rotation: "pediatrics",
    findingName: "Fontanelle Assessment and Neonatal Head Examination",
    description:
      "The fontanelles are fibrous gaps between cranial bones that allow for brain growth and molding during delivery. The anterior fontanelle (AF) — diamond-shaped gap at the junction of coronal, sagittal, and metopic sutures — is the most clinically relevant. The posterior fontanelle (PF) — triangular, at junction of lambdoid and sagittal sutures — closes by 2–3 months. Fontanelle assessment provides critical information about intracranial pressure and hydration status.",
    technique:
      "POSITIONING: Examine with infant upright and calm (crying raises ICP and causes bulging — a normal response). Palpate gently with the flat of the finger pad, not the fingertip. Assess: (1) Size — measure in 2 perpendicular diameters (average AP × transverse); (2) Tenseness — soft/sunken vs flat/tensed vs bulging; (3) Pulsatility — gentle pulsation with heartbeat is normal; (4) Suture ridging — feel along all suture lines. Note: fontanelle is normally slightly sunken to flat when upright and calm.",
    normalFindings:
      "Anterior fontanelle: closes between 4 and 26 months (average 13–14 months; 96% closed by 24 months). Size at birth: average 2.1 × 2.1 cm (ranges widely). Soft, pulsatile, slightly concave when calm and upright. Posterior fontanelle: closes by 2 months. Sutures: may be slightly separated at birth (allow molding), should fuse by 6 months.",
    abnormalFindings: [
      "Bulging fontanelle: always abnormal when calm and upright. Causes: increased ICP (meningitis, hydrocephalus, subdural hematoma, cerebral edema, intracranial hemorrhage), hyponatremia, vitamin A toxicity, pseudotumor cerebri. In the febrile infant — bulging fontanelle + fever = bacterial meningitis until proven otherwise → LP required.",
      "Sunken fontanelle: dehydration (most common cause in ill infants), hypernatremia. Along with sunken eyes, decreased skin turgor, dry mucous membranes, and prolonged capillary refill → assess degree of dehydration.",
      "Delayed closure (still open after 18–24 months): hypothyroidism (most common endocrine cause), Down syndrome, rickets, hydrocephalus, increased intracranial pressure, achondroplasia.",
      "Premature closure / craniosynostosis: early fusion of one or more sutures → abnormal head shape: sagittal synostosis (most common) → scaphocephaly (elongated front-to-back, narrow); coronal synostosis → plagiocephaly (flattened on one side) or brachycephaly (bilateral); metopic synostosis → trigonocephaly (triangular forehead). Diagnosis: palpable ridge along fused suture; CT confirms. Treatment: surgical (cranial vault remodeling).",
      "Caput succedaneum: diffuse edema of soft tissue over the presenting part — crosses suture lines, present at birth, resolves in days. Distinguish from cephalohematoma (blood between periosteum and skull — does NOT cross suture lines, may take weeks to months to resolve, associated with subperiosteal hemorrhage; risk for hyperbilirubinemia).",
    ],
    clinicalPearl:
      "Positional plagiocephaly (flat head syndrome) is extremely common (up to 47% of infants) and results from external pressure on one area of the skull due to supine positioning (Back to Sleep campaign). It differs from craniosynostosis: positional plagiocephaly has NO palpable suture ridge, a characteristic 'parallelogram' head shape (ear on flattened side moves forward), and the forehead is prominent on the flattened side. Treatment: repositioning, tummy time awake and supervised, helmet therapy (if severe and persistent > 6 months). Craniosynostosis has a palpable ridge and abnormal head shape that worsens over time without surgery.",
    boardRecallTip: "Bulging fontanelle + fever = meningitis until proven otherwise → LP. Sunken = dehydration. Delayed closure > 18 months: hypothyroidism, Down syndrome, rickets. Craniosynostosis: palpable suture ridge + abnormal head shape → CT + surgery. Positional plagiocephaly: no ridge, parallelogram shape, treat with repositioning + tummy time.",
  },
  {
    id: "peds-pe-heart-murmur",
    rotation: "pediatrics",
    findingName: "Innocent vs Pathological Cardiac Murmurs in Children",
    description:
      "Heart murmurs are found in up to 80% of children at some point during childhood. The vast majority (> 80%) are innocent (functional, physiological, benign) murmurs produced by normal turbulent blood flow in the absence of structural heart disease. Distinguishing innocent from pathological murmurs is a core pediatric clinical skill. Most innocent murmurs can be diagnosed on clinical examination without echocardiography. The 8 S's of innocent murmurs and key red-flag features of pathological murmurs guide clinical decision-making.",
    technique:
      "AUSCULTATION: Use both diaphragm (high-frequency sounds — S₁, S₂, systolic murmurs) and bell (low-frequency — S₃, diastolic murmurs, tricuspid/mitral rumbles). Auscultate in quiet room with child calm. Positions: supine (supine murmurs louder), sitting (innocent murmurs often diminish), standing (HOCM worsens; MVP click moves earlier). Areas: Apex (mitral), LLSB (tricuspid, Still's, RVOTO), ULSB (pulmonary, PDA, ASD flow murmur), URSB (aortic). Assess: timing (systolic vs diastolic vs continuous), intensity (I–VI), quality (harsh/blowing/musical/vibratory), location, radiation, change with position and Valsalva.",
    normalFindings:
      "INNOCENT MURMURS — the 8 S's: (1) Soft (grade ≤ II/VI), (2) Short (not pan-systolic), (3) Systolic (never diastolic — all diastolic murmurs need echo), (4) Single (no other sounds), (5) Specific location (LSB, no radiation to neck or axilla), (6) Sweet (musical, vibratory — especially Still's murmur), (7) Sensitive to position (decreases sitting/standing), (8) Symptom-free. Most common innocent murmurs: (1) Still's murmur (musical/vibratory, grade II–III, LLSB, peaks in preschool age 3–6 years, decreases standing); (2) Pulmonary flow murmur (ejection quality, ULSB, adolescents and thin individuals); (3) Venous hum (continuous, obliterated by compressing the jugular vein or turning head); (4) Peripheral pulmonic stenosis (bilateral axillary radiation, newborn period only — resolves by 6 months).",
    abnormalFindings: [
      "RED FLAGS for pathological murmur (refer for echocardiography): grade ≥ III/VI with thrill (grade IV+), diastolic murmur (always pathological — AR, MR, PS, MS), holosystolic (pan-systolic) murmur, harsh quality, best heard at URSB with radiation to neck (aortic stenosis), left subclavicular radiation to back (coarctation of aorta), clicks (systolic ejection click = aortic/pulmonary stenosis, bicuspid aortic valve; mid-systolic click = mitral valve prolapse), cyanosis, abnormal S₂ (fixed splitting = ASD; absent P₂ = critical pulmonary stenosis), abnormal cardiac history/symptoms (chest pain, syncope, dyspnea, palpitations), family history of sudden cardiac death, genetic syndrome (Noonan, Williams, Down — VSD; Turner — bicuspid AV, coarctation).",
      "VENTRICULAR SEPTAL DEFECT (VSD): most common congenital heart defect (30–35%). Holosystolic, harsh, grade III–V, LLSB, ± thrill. Large VSD: signs of CHF (tachypnea, poor feeding, failure to thrive). Small VSD: loud murmur, asymptomatic, may close spontaneously. Echo: obligatory.",
      "ATRIAL SEPTAL DEFECT (ASD): soft systolic ejection murmur ULSB + fixed wide split S₂ (hallmark). May be asymptomatic for years. Right-to-left shunting → right heart enlargement → arrhythmia in adulthood.",
      "COARCTATION OF THE AORTA: systolic ejection murmur in left infrascapular area, blood pressure differential (arm BP > leg BP by > 10–20 mmHg), diminished/delayed femoral pulses, upper extremity hypertension. Associated with bicuspid aortic valve (50%), Turner syndrome.",
      "PATENT DUCTUS ARTERIOSUS (PDA): continuous 'machinery' murmur, left infraclavicular area. Wide pulse pressure. Premature infants: significant PDA → volume overload, CHF, need for indomethacin (closes PDA by inhibiting PGE₂) or surgical ligation.",
    ],
    clinicalPearl:
      "ALL diastolic murmurs, any murmur with a thrill (grade IV+), any holosystolic murmur, and any murmur with associated symptoms (cyanosis, exercise intolerance, chest pain, syncope) require echocardiography. The absence of a murmur does NOT exclude congenital heart disease — critical lesions like transposition of the great arteries (TGA) may have minimal or no murmur initially. All newborns with cyanosis should have a hyperoxia test (100% FiO₂) to distinguish cardiac (PaO₂ < 150 mmHg despite 100% O₂) from pulmonary causes (PaO₂ rises to > 200 mmHg).",
    boardRecallTip: "Innocent murmur: soft, systolic, no radiation, decreases standing, musical (Still's). Pathological: diastolic, holosystolic, thrill, click, cyanosis, radiation to neck/back. Fixed wide split S₂ = ASD. Continuous 'machinery' murmur = PDA. All diastolic murmurs → echo.",
  },
  {
    id: "peds-pe-developmental-milestones",
    rotation: "pediatrics",
    findingName: "Developmental Milestone Assessment",
    description:
      "Developmental surveillance at every well-child visit is mandated by the AAP Bright Futures guidelines. It includes four developmental domains: (1) Gross motor, (2) Fine motor/adaptive, (3) Language/communication (the most sensitive early predictor of developmental disability), and (4) Social-emotional/personal. The 2022 AAP updated milestone guidelines revised many milestones to reflect the 50th percentile (when 50% of children achieve it) vs the prior 75th–90th percentile benchmarks — making earlier identification of delays more feasible.",
    technique:
      "SURVEILLANCE: At every visit, ask open-ended developmental questions (What new things is your child doing? Any concerns about development, behavior, or learning?). FORMAL SCREENING: Ages and Stages Questionnaires (ASQ-3 and ASQ:SE-2) at 9, 18, and 30 months. M-CHAT-R/F at 18 and 24 months (autism-specific). OBSERVATION: during physical exam, observe child's interaction with parents, attention, exploration, motor skills, and communication. RED FLAGS (require immediate referral regardless of age): No social smile by 2 months, no babbling by 12 months, no single words by 16 months, no 2-word phrases by 24 months, loss of any previously acquired skills (regression at any age).",
    normalFindings:
      "KEY MILESTONES BY AGE (2022 AAP updated, 50th percentile): 2 months: social smile (responds to face), lifts head 45° prone, coos/vocalizes, briefly watches people. 4 months: laughs, rolls front-to-back, tracks objects 180°, reaches for objects. 6 months: sits with support, transfers objects hand-to-hand, babbles, reaches for caregiver. 9 months: sits independently, pulls to stand, pincer grasp developing, says 'mama/dada' non-specifically, waves bye-bye, stranger anxiety. 12 months: walks with support/cruising, pincer grasp complete, 1–3 words specifically, follows 1-step commands with gesture. 18 months: walks independently, scribbles, 5–10 words, points to indicate interest, uses spoon. 24 months: runs, kicks ball, 2-word phrases, 50+ words, identifies body parts, parallel play. 3 years: climbs stairs alternating feet, copies a circle, 3-word sentences, 75% intelligible speech to strangers. 4 years: hops on one foot, draws a person (3 body parts), tells stories, plays with other children.",
    abnormalFindings: [
      "LANGUAGE DELAY: most common developmental delay. Red flags: no babbling by 12 months, no words by 16 months, no 2-word phrases by 24 months, regression of language. Refer to: audiology (always first — rule out hearing loss, the most common correctable cause), speech-language pathologist, developmental pediatrics. Remember: speech delay + social concerns = autism screening (M-CHAT-R).",
      "AUTISM SPECTRUM DISORDER (ASD): Red flags — no social smile by 2 months, no gestures (pointing, waving) by 12 months, no words by 16 months, no 2-word phrases by 24 months, loss of any language, reduced eye contact, limited social engagement, repetitive behaviors, sensory sensitivities. Screening: M-CHAT-R at 18 and 24 months. Positive screen (score ≥ 3) → diagnostic evaluation by developmental pediatrician or multidisciplinary team. Early intervention (ABA therapy, speech, OT) is the cornerstone of ASD treatment.",
      "GLOBAL DEVELOPMENTAL DELAY (GDD): significant delay in ≥ 2 developmental domains (> 2 SD below mean). Occurs in 1–3% of children. Causes: genetic (Down syndrome, fragile X — most common inherited cause in males, Rett syndrome — in girls), metabolic (PKU, congenital hypothyroidism), structural brain anomalies, perinatal injury (hypoxic-ischemic encephalopathy), TORCH infections. Workup: chromosomal microarray (first-line genetic test, detects copy number variants), fragile X testing, metabolic screen, thyroid function, MRI brain.",
      "CEREBRAL PALSY (CP): non-progressive motor disorder due to brain injury in developing brain. Presents as: delayed motor milestones, abnormal tone (hypertonia or hypotonia), persistence of primitive reflexes beyond expected age. Types: spastic (most common — cortical/corticospinal injury), dyskinetic (basal ganglia), ataxic (cerebellar). Key primitive reflexes: Moro (startle) — normal until 4 months; asymmetric tonic neck reflex (ATNR) — normal until 4–6 months; persistence beyond 6 months is abnormal. Parachute reflex appears at 8–9 months — absent after 12 months is abnormal.",
    ],
    clinicalPearl:
      "The 2022 AAP revised milestone guidelines intentionally moved milestones to the 50th percentile to allow earlier identification of delays — a child who is not meeting the 50th percentile milestone should be monitored closely and screened, even if still within the range of 'normal.' The most important early language red flag is not the total word count, but the loss of previously acquired language (regression at any age is always abnormal and requires urgent evaluation for Rett syndrome, ASD, Landau-Kleffner syndrome, or metabolic disorder).",
    boardRecallTip: "Language milestones: babble by 12m, 1 word by 12m, 2-word phrases by 24m. Regression at any age = abnormal → urgent evaluation. ASD: M-CHAT-R at 18 and 24 months. GDD workup: chromosomal microarray + fragile X. Persistent primitive reflexes > 6 months = concerning for CP.",
  },
  {
    id: "peds-pe-newborn-exam",
    rotation: "pediatrics",
    findingName: "Systematic Newborn Physical Examination",
    description:
      "The newborn examination should be performed within the first 24 hours of life and again before hospital discharge (or at the first outpatient visit at 3–5 days). It follows a systematic head-to-toe approach with additional focus on birth-related findings and detection of critical congenital anomalies. The APGAR score (assessed at 1 and 5 minutes) evaluates immediate neonatal adaptation. Pulse oximetry screening for critical congenital heart disease (CCHD) is mandated in all US hospitals before discharge.",
    technique:
      "APGAR SCORE (1 and 5 minutes): Appearance (color), Pulse (HR), Grimace (reflex irritability), Activity (tone), Respiration — each 0–2 points; max score 10. Score 7–10 = reassuring; 4–6 = moderate depression; < 4 = severe depression. Repeat every 5 minutes until ≥ 7. CCHD PULSE OX SCREENING: SpO₂ in right hand (preductal) and either foot (postductal) at 24–48 hours. Fail: SpO₂ < 90% in either location, OR < 95% in both, OR > 3% difference between hand and foot. SYSTEMATIC EXAM: Skin → Head/eyes/ears/nose/throat → Neck → Chest/lungs → Heart/cardiovascular → Abdomen → Genitourinary → Musculoskeletal → Neurological/primitive reflexes.",
    normalFindings:
      "SKIN: vernix caseosa (protective fetal sebum), lanugo (fine hair), acrocyanosis (blue hands and feet — normal first hours if trunk pink). BIRTH MARKS: Mongolian spots (blue-gray pigmented macules over sacrum — common in dark-skinned infants; NOT bruising — document carefully to avoid child abuse confusion), salmon patch/nevus simplex ('stork bite' — erythematous flat lesion at nape, glabella, eyelids — fades over 1–2 years), milia (white keratin cysts on nose — resolve spontaneously), erythema toxicum neonatorum (benign pustular rash with eosinophils on smear — resolves in 2 weeks). REFLEX TESTING: Rooting (stroking cheek → turns toward stimulus), sucking, palmar grasp (finger in palm → grasps), Moro/startle (symmetric abduction and adduction), stepping, Babinski (plantar stimulation → toes fan up — normal in infants < 12 months), galant (stroke paraspinal muscles → lateral trunk flexion).",
    abnormalFindings: [
      "Cyanosis: central cyanosis (blue lips/tongue/trunk) is ALWAYS abnormal — evaluate immediately. CCHD screen: preductal-postductal SpO₂ difference. Hyperoxia test to distinguish cardiac from pulmonary. Differential: transposition of great arteries (TGA — most common cyanotic CHD presenting in first days of life), Tetralogy of Fallot (ToF — most common cyanotic CHD overall), total anomalous pulmonary venous return (TAPVR), pulmonary atresia.",
      "Hypotonia ('floppy infant'): decreased muscle tone. Central causes (most common): HIE, chromosomal disorders (Down syndrome — generalized hypotonia with upslanting palpebral fissures, epicanthal folds, single palmar crease, sandal gap toe), congenital hypothyroidism, metabolic disorders. Peripheral causes: spinal muscular atrophy (SMA) type 1 (Werdnig-Hoffmann — frog-leg posture, tongue fasciculations, absent DTRs, genetic testing SMN1 deletion), congenital myopathies, neonatal myasthenia gravis (transient from maternal antibody transfer).",
      "Cleft lip and palate: most common craniofacial anomaly. Look inside mouth — cleft palate can be isolated without visible cleft lip. Feeding difficulties (poor latch) → specialized cleft nipples, nasogastric feeds if severe. Associated with velocardiofacial syndrome (DiGeorge/22q11.2 deletion), Van der Woude syndrome.",
      "Ambiguous genitalia: failure to identify fetal sex on prenatal ultrasound, bilateral cryptorchidism (palpable testes absent bilaterally), virilized female genitalia (clitoromegaly), hypospadias with undescended testis. URGENT workup: congenital adrenal hyperplasia (CAH — 21-hydroxylase deficiency; salt-wasting CAH life-threatening by day 7–10; check 17-OHP, electrolytes), chromosomal karyotype, pelvic ultrasound, urology and endocrinology consult. Do NOT assign sex before evaluation.",
      "Hip dysplasia (DDH): Developmental dysplasia of the hip. Barlow maneuver (dislocates unstable hip — posterior push with adduction) and Ortolani maneuver (reduces dislocated hip — abduction with anterior pressure → palpable 'clunk'). Risk factors: female sex, firstborn, breech presentation, family history. Screening US at 6 weeks for risk groups. Pavlik harness if diagnosed < 6 months.",
      "Jaundice: visible at bilirubin ≥ 5–7 mg/dL. Physiologic jaundice: appears day 2–3, peaks day 4–5 (term) or day 5–7 (preterm), resolves by day 7–10. NON-physiologic (concerning): appears in first 24 hours (hemolytic disease — ABO or Rh incompatibility); persists > 2 weeks; rapidly rising (> 0.5 mg/dL/hr). Check total and direct bilirubin; plot on Bhutani nomogram for phototherapy threshold. Conjugated (direct) hyperbilirubinemia (direct bili > 1 mg/dL or > 20% of total) = ALWAYS pathological → evaluate for biliary atresia (acholic stools, dark urine, hepatomegaly), choledochal cyst, or neonatal hepatitis.",
    ],
    clinicalPearl:
      "Jaundice in the first 24 hours of life is ALWAYS pathological — it is not physiologic jaundice. The most common cause is hemolytic disease of the newborn (HDN) from ABO incompatibility (most common) or Rh incompatibility (most severe if untreated — hydrops fetalis). Any jaundice visible in the first 24 hours requires immediate total and direct serum bilirubin measurement, blood type, Coombs test, CBC, and reticulocyte count. Transcutaneous bilirubinometry is a screening tool — confirm with serum bilirubin if elevated.",
    boardRecallTip: "APGAR < 7 at 5 min → needs resuscitation assessment. CCHD screen: SpO₂ in right hand + foot; fail if < 90% or > 3% difference. Jaundice < 24 hours = pathological (hemolysis). Direct bili > 1 mg/dL = always pathological (biliary atresia → hepatoportoenterostomy [Kasai] before 60 days). DDH: Barlow + Ortolani maneuvers. Bilateral cryptorchidism = ambiguous genitalia workup (46XX CAH?).",
  },
];
