// @ts-nocheck
import { Procedure } from "@/types/seed";

export const pediatricsProcedures: Procedure[] = [
  {
    id: "peds-proc-lp",
    rotation: "pediatrics",
    name: "Lumbar Puncture (Pediatric)",
    overview:
      "Lumbar puncture (LP) — also called spinal tap — is the aspiration of cerebrospinal fluid (CSF) from the lumbar subarachnoid space. In pediatrics, it is most commonly performed to diagnose bacterial meningitis, viral encephalitis, and subarachnoid hemorrhage, and to measure opening pressure in pseudotumor cerebri. Proper positioning, adequate sedation/analgesia, and correct technique are critical to success. LP is safe in children when performed at the correct level and with appropriate precautions.",
    indications: [
      "Suspected bacterial or viral meningitis (diagnostic — CSF culture, cell count, chemistry)",
      "Suspected encephalitis (CSF PCR for HSV, enterovirus, arbovirus)",
      "Suspected subarachnoid hemorrhage when CT is negative (xanthochromia + RBC)",
      "Intracranial pressure measurement (pseudotumor cerebri / idiopathic intracranial hypertension)",
      "Intrathecal medication administration (chemotherapy, antibiotics)",
      "Neonatal sepsis evaluation — LP is part of the standard work-up in febrile neonates < 28 days",
    ],
    contraindications: [
      "ABSOLUTE: Signs of elevated ICP with impending herniation (papilledema, Cushing's triad — hypertension + bradycardia + irregular respirations, focal neurological deficit, altered consciousness); obtain CT head first",
      "ABSOLUTE: Infection overlying the puncture site (cellulitis, sacral abscess — risk of introducing infection into CSF)",
      "ABSOLUTE: Thrombocytopenia < 50,000 or coagulopathy (correct before proceeding; INR > 1.5 or PTT > 1.5× ULN)",
      "RELATIVE: Respiratory compromise in infant — lateral decubitus position safer than sitting position for infants at risk for apnea",
      "NOTE: LP should NEVER be delayed in a clinically unstable patient with suspected meningitis — give antibiotics first, LP after stabilization",
    ],
    equipment: [
      "Spinal needle: neonates/infants — 22-gauge, 1.5-inch needle; children — 22-gauge, 2.5-inch; adolescents — 22-gauge, 3.5-inch (always use a needle with a stylet)",
      "Sterile gloves, mask, gown, sterile drape",
      "Chlorhexidine or betadine skin preparation (avoid chlorhexidine on neonatal skin < 2 months — can cause skin burns)",
      "EMLA cream or LMX-4 (4% lidocaine cream) applied 60 minutes before procedure for topical anesthesia (elective LP); 1% lidocaine with 25-gauge needle for local infiltration",
      "Manometer with three-way stopcock (for opening pressure measurement — essential in IIH/pseudotumor workup)",
      "4 labeled CSF collection tubes (tube 1 = chemistry: glucose, protein; tube 2 = microbiology: Gram stain, culture; tube 3 = hematology: cell count with differential; tube 4 = additional: hold for repeat cell count, virology, cytology as needed)",
      "Bandage for post-procedure",
      "Sedation/analgesia supplies (intranasal dexmedetomidine, oral sucrose for neonates, or procedural sedation as appropriate)",
    ],
    procedure: [
      "PREPROCEDURE: Obtain informed consent. Review platelet count and coagulation studies if any concern. Apply EMLA cream 60 minutes before if elective. Gather all equipment and label CSF tubes 1–4 before starting.",
      "POSITIONING (most critical factor for success): LATERAL DECUBITUS (preferred for most children): child lies on side, knees drawn to chest, neck flexed toward knees — maximum spinal flexion opens the interspinous spaces. An assistant firmly holds the child in this 'C-shape.' SITTING POSITION: for older cooperative children or obese patients — leans forward hugging a pillow; easier to palpate landmarks but cannot measure accurate opening pressure (use lateral decubitus for opening pressure).",
      "LANDMARK IDENTIFICATION: Palpate the posterior superior iliac crests — an imaginary line connecting these landmarks (Tuffier's line) crosses at the L3–L4 interspace (safe level — below the conus medullaris, which ends at L1–L2 in children and L2–L3 in neonates). Mark the L3–L4 or L4–L5 interspace with a fingernail indent.",
      "STERILE PREP: Don mask and sterile gloves. Prep skin with povidone-iodine in concentric circles (use betadine for neonates, not chlorhexidine). Allow to dry 30–60 seconds. Apply sterile drape.",
      "LOCAL ANESTHESIA: Raise skin wheal with 25-gauge needle at marked interspace with 1% lidocaine. Change to longer 22-gauge needle and infiltrate deeper tissues along the needle trajectory — allow 2–3 minutes for anesthesia to take effect.",
      "NEEDLE INSERTION: Insert spinal needle (with stylet in place) at the L3–L4 interspace in the midline. Angle needle slightly cephalad (toward the patient's umbilicus — 10–15° in children; perpendicular in neonates). Advance slowly in small increments. Feel for a distinct 'pop' or give as the needle pierces the ligamentum flavum and dura. Remove the stylet to check for CSF flow every few millimeters.",
      "OPENING PRESSURE: If measuring opening pressure (essential for IIH/pseudotumor workup), attach the manometer with three-way stopcock immediately after CSF flow begins. Patient must be in lateral decubitus position, relaxed (crying falsely elevates pressure). Normal pediatric opening pressure: 10–20 cmH₂O (some sources 28 cmH₂O upper limit in children). Measure, then turn stopcock to collect CSF.",
      "CSF COLLECTION: Collect CSF by passive drip into the pre-labeled tubes (do NOT aspirate with a syringe — may cause herniation, needle displacement, or bloody tap). Collect: tube 1 (2 mL — chemistry), tube 2 (1 mL — microbiology), tube 3 (1 mL — hematology), tube 4 (remaining — hold). If fluorescent (xanthochromic) or bloody, note the progression from tube 1 to tube 4.",
      "COMPLETION: Replace the stylet before withdrawing the needle (reduces post-LP headache risk by preventing CSF leak through dural defect — pull stylet back and reinsert before removal). Apply pressure and sterile bandage. Document: needle gauge, interspace used, opening pressure, appearance of CSF, tubes collected.",
      "POST-PROCEDURE: Child may resume normal activity. Post-LP headache (positional, worse upright, better supine): manage with increased fluid intake, caffeine (older children), prone positioning; epidural blood patch for severe refractory cases. Monitor neurological status for 30–60 minutes.",
    ],
    interpretation: {
      title: "CSF Analysis — Pediatric Reference Values and Disease Patterns",
      rows: [
        {
          parameter: "Appearance",
          normal: "Crystal clear, colorless",
          abnormal: "Cloudy/turbid (bacterial meningitis, WBC > 200); xanthochromic yellow (SAH, elevated protein, prior LP); bloody (SAH vs traumatic tap)",
          significance: "Xanthochromia: centrifuge bloody CSF — yellow supernatant = SAH (bilirubin from hemoglobin breakdown takes 2–4h to develop); clear supernatant = traumatic tap",
        },
        {
          parameter: "Opening Pressure",
          normal: "Children: 10–28 cmH₂O (lateral decubitus, relaxed)",
          abnormal: "> 25–28 cmH₂O (elevated ICP — bacterial meningitis, IIH, hydrocephalus, venous sinus thrombosis); < 10 (intracranial hypotension — CSF leak, over-shunting)",
          significance: "IIH/Pseudotumor cerebri: opening pressure > 25 + papilledema + no mass lesion → acetazolamide + weight loss + repeat LP for symptomatic relief",
        },
        {
          parameter: "WBC Count",
          normal: "Neonates: 0–30 cells/mm³ (up to 60% PMN can be normal); Children: 0–5 cells/mm³ (all mononuclear)",
          abnormal: "PMN pleocytosis > 100 = bacterial; Lymphocytic pleocytosis 10–500 = viral/TB; Mixed early = may be bacterial or viral",
          significance: "Bacterial: > 1,000 PMN typical (range 100–10,000+). Viral: 50–500 lymphocytes. Early bacterial meningitis may show lymphocytic pattern — treat empirically.",
        },
        {
          parameter: "CSF Glucose",
          normal: "Children: > 50% of serum glucose (check serum glucose simultaneously). Absolute: > 40 mg/dL",
          abnormal: "< 40 mg/dL or < 40% of serum = hypoglycorrhachia (bacterial, TB, fungal, carcinomatous meningitis)",
          significance: "Ratio < 0.4 = strongly suggests bacterial or fungal meningitis. Viral meningitis = normal glucose. Bacterial: typically < 40 mg/dL.",
        },
        {
          parameter: "CSF Protein",
          normal: "Neonates: 20–170 mg/dL; Children: 15–45 mg/dL; Adolescents: 15–45 mg/dL",
          abnormal: "Bacterial: > 100–500 mg/dL; Viral: 50–100 mg/dL; TB/fungal: very high (> 500); GBS (Guillain-Barré): cytoalbuminous dissociation (protein ↑↑ with normal WBC)",
          significance: "Cytoalbuminous dissociation (protein > 100 + WBC < 10) in the pediatric age group = GBS until proven otherwise. Normal protein + high WBC = viral most likely.",
        },
        {
          parameter: "Gram Stain / Culture",
          normal: "No organisms; culture sterile",
          abnormal: "Positive Gram stain (50–90% sensitivity in untreated bacterial meningitis — lower after antibiotics). Gram + diplococci = S. pneumoniae; Gram − diplococci = N. meningitidis; Gram − rods = E. coli (neonates)",
          significance: "Culture remains positive for 2–4 hours after first antibiotic dose — do NOT withhold antibiotics while waiting for LP if meningitis suspected. Send blood cultures simultaneously.",
        },
        {
          parameter: "HSV / Enterovirus PCR",
          normal: "Negative",
          abnormal: "HSV PCR positive = herpes encephalitis (treat with acyclovir 20 mg/kg q8h for neonates, 10 mg/kg q8h for older children × 21 days for CNS disease)",
          significance: "Enterovirus PCR positive = aseptic meningitis (no specific treatment). CSF PCR more sensitive than culture for viral pathogens.",
        },
      ],
    },
    complications: [
      "Post-lumbar puncture headache (PLPHA): 10–30% of cases; positional, bifrontal/occipital, worse upright. Due to persistent CSF leak through dural defect. Treatment: hydration, caffeine, supine positioning; epidural blood patch for severe/refractory cases.",
      "Traumatic (bloody) tap: 20–30% of pediatric LPs (especially in infants). Corrected WBC formula: subtract 1 WBC per 500 RBC from traumatic blood. CSF glucose and protein less reliable. Repeat LP at different interspace or MRI if clinical suspicion persists.",
      "Failure to obtain CSF (dry tap): needle in wrong position, spasm, epidural fat in obese patients. Attempt L4–L5 interspace or use fluoroscopic/ultrasound guidance.",
      "Herniation: most feared complication — occurs if LP performed with pre-existing elevated ICP from mass lesion. CT head required before LP if: papilledema, focal deficit, altered consciousness, immunocompromised, new-onset seizures.",
      "Spinal cord injury: prevented by staying below L2–L3 (conus medullaris level) — always use L3–L4 or L4–L5.",
      "Infection (meningitis, discitis, epidural abscess): extremely rare with strict sterile technique.",
    ],
    clinicalPearl:
      "In a febrile neonate (< 28 days), LP is part of the MANDATORY evaluation — you cannot safely exclude meningitis on clinical grounds alone at this age. Meningeal signs (Kernig's, Brudzinski's) are absent and the fontanelle may not bulge in early neonatal meningitis. The neonatal CSF reference range differs dramatically from older children: up to 30 WBCs/mm³ with up to 60% PMNs, protein up to 170 mg/dL, and glucose > 40 mg/dL can all be within normal limits. Do NOT apply adult or older-child reference ranges to neonatal CSF — you will over-diagnose meningitis.",
    boardRecallTip: "L3–L4 or L4–L5 interspace (Tuffier's line = iliac crests = L3–L4). Lateral decubitus for opening pressure. CT before LP only if: papilledema, focal deficit, altered consciousness. Neonates: normal CSF can have up to 30 WBC and 170 protein. HSV: acyclovir 20 mg/kg q8h empirically for any neonate with pleocytosis.",
  },
  {
    id: "peds-proc-nrp",
    rotation: "pediatrics",
    name: "Neonatal Resuscitation (NRP) — Newborn Stabilization",
    overview:
      "Approximately 10% of newborns require some assistance to begin breathing at birth, and fewer than 1% need extensive resuscitation measures. The Neonatal Resuscitation Program (NRP) provides a systematic, evidence-based algorithm for stabilizing newborns in the delivery room. The sequence follows a rapid assessment of three questions: (1) Is the infant term gestation? (2) Does the infant have good tone? (3) Is the infant breathing or crying? If all three = yes → routine care (dry, stimulate, skin-to-skin). Any 'no' → resuscitation pathway.",
    indications: [
      "Apnea or gasping respirations at birth",
      "Heart rate < 100 beats per minute after drying and stimulation",
      "Persistent central cyanosis despite supplemental oxygen",
      "Preterm birth (< 37 weeks) — higher risk of respiratory distress and apnea",
      "Known risk factors: maternal diabetes, meconium-stained amniotic fluid (thick), multiple gestation, fetal anomalies, prolonged rupture of membranes",
      "Maternal medications: magnesium sulfate (can cause neonatal respiratory depression), opioids given < 4 hours before delivery",
    ],
    contraindications: [
      "No absolute contraindications to initiating NRP in the delivery room",
      "Withholding resuscitation considerations (case-by-case): confirmed lethal anomalies, gestational age < 22 weeks (institution-specific guidelines), parents' informed refusal after counseling",
    ],
    equipment: [
      "Radiant warmer (pre-warmed — set to 37°C)",
      "Warm blankets and hat for thermoregulation (hypothermia worsens outcomes — target axillary temp 36.5–37.5°C)",
      "Bulb syringe and suction catheter (10 Fr) — for routine suctioning if secretions obstruct airway",
      "Supplemental oxygen source + blender (start with 21% O₂ in term infants, 21–30% in preterm < 35 weeks)",
      "Pulse oximeter probe (pre-ductal = right hand) and cardiac monitor leads",
      "T-piece resuscitator (Neopuff) or flow-inflating/self-inflating bag with appropriate-sized mask (size 0 for premature, size 1 for term)",
      "Laryngoscope with size 0 (premature) or 1 (term) blade; endotracheal tubes (2.5–4.0 mm based on weight)",
      "Stylet, CO₂ detector (colorimetric — confirms ETT placement)",
      "Epinephrine: 1:10,000 concentration for IV (0.01–0.03 mg/kg); 1:10,000 for ETT (0.05–0.1 mg/kg — higher dose, less reliable)",
      "Umbilical catheter supplies (3.5 Fr for < 1 kg, 5 Fr for ≥ 1 kg) for emergency vascular access",
      "Normal saline 0.9% for volume expansion (10 mL/kg bolus)",
    ],
    procedure: [
      "INITIAL ASSESSMENT (< 30 seconds): Ask 3 questions — Term gestation? Good tone? Crying/breathing? If YES to all → routine care (warm, dry, clear secretions, assess color, skin-to-skin). If ANY 'no' → proceed to resuscitation pathway.",
      "INITIAL STEPS (30 seconds): Position: neck slightly extended (sniffing position — aligns airway). Warm and dry: place under radiant warmer, remove wet blankets, replace with dry warm blanket. For preterm < 32 weeks: place in polyethylene wrap BEFORE drying (reduces heat loss). Stimulate: rub back or flick feet. Clear airway: suction mouth then nose if secretions present (mouth first — prevents aspiration if nasal suctioning triggers gasping). MECONIUM-STAINED FLUID: if vigorous (good tone + strong cry + HR > 100) → routine care. If NOT vigorous → intubate and suction trachea before stimulating (ETT direct tracheal suction using meconium aspirator).",
      "ASSESS: After 30 seconds of initial steps — evaluate respirations, heart rate. Use CARDIAC MONITOR (most reliable for HR) or pulse oximetry. Auscultation acceptable initially but cardiac monitor preferred. Count HR for 6 seconds × 10 = beats per minute.",
      "POSITIVE PRESSURE VENTILATION (PPV): Indications: apnea/gasping OR HR < 100 after 30 seconds of initial steps. Technique: properly sized mask covering mouth and nose (seal check — squeeze and observe chest rise). Rate: 40–60 breaths/minute ('breathe — two — three, breathe — two — three'). Pressure: T-piece: set PIP 20–25 cmH₂O (term), PEEP 5 cmH₂O. Peak pressure confirmed by chest rise — not too high (barotrauma risk) not too low (ineffective). FiO₂: term = start 21%; preterm < 35 weeks = start 21–30%. Adjust by pulse oximetry. CHEST RISE ASSESSMENT: If no improvement in HR after 30 seconds PPV → MR SOPA (Mask adjustment, Reposition airway, Suction mouth/nose, Open mouth, Pressure increase, Alternative airway [intubate]).",
      "REASSESS (after 30 seconds PPV): If HR ≥ 100 + breathing: gradually wean PPV. If HR 60–99: continue PPV, consider intubation. If HR < 60 despite adequate ventilation (verified by chest rise): proceed to chest compressions.",
      "CHEST COMPRESSIONS: Indications: HR < 60 after 30 seconds of adequate PPV. Technique: 2-THUMB technique preferred (encircle chest with both hands, thumbs over lower third of sternum — NOT over xiphoid). Depth: 1/3 of AP diameter of chest. Rate: 3 compressions : 1 breath (3:1 ratio, unlike adult CPR 30:2) at 120 events/minute (90 compressions + 30 breaths/min). Increase FiO₂ to 100% when compressions start.",
      "INTUBATION: Consider when: PPV ineffective, prolonged resuscitation, chest compressions required, very preterm, suspected airway anomaly, diaphragmatic hernia (prevents gastric distension), surfactant administration. ETT size by weight: < 1 kg → 2.5 mm; 1–2 kg → 3.0 mm; 2–3 kg → 3.5 mm; > 3 kg → 3.5–4.0 mm. Depth of insertion (cm at lip) = weight (kg) + 6. Confirm: bilateral breath sounds, CO₂ detector color change (purple → yellow = CO₂ detected = in airway), HR improvement, CXR if stable.",
      "MEDICATIONS: If HR < 60 after 30 seconds of chest compressions + effective PPV (100% O₂): EPINEPHRINE: IV preferred (umbilical vein catheter or peripheral). IV dose: 0.01–0.03 mg/kg of 1:10,000 solution (= 0.1–0.3 mL/kg). ETT dose: 0.05–0.1 mg/kg (0.5–1 mL/kg of 1:10,000). Repeat IV epinephrine q3–5 min if HR remains < 60. VOLUME EXPANSION: if signs of acute blood loss or no response to epinephrine: NS 0.9% 10 mL/kg IV over 5–10 minutes. SODIUM BICARBONATE: rarely used acutely (prolonged resuscitation with documented severe metabolic acidosis — risk of IVH in preterm).",
      "DISCONTINUE RESUSCITATION: Consider discontinuing if: no cardiac activity after 20 minutes of adequate resuscitation (discuss with team and family — institution-specific guidelines). Apgar score at 10 minutes of 0 with maximal resuscitation = poor prognosis discussion warranted.",
      "POST-RESUSCITATION CARE: Transfer to NICU for infants requiring sustained resuscitation. Therapeutic hypothermia (33–34°C × 72 hours) for term/near-term infants ≥ 36 weeks with hypoxic-ischemic encephalopathy (HIE) — reduces death and disability by ~25%.",
    ],
    interpretation: {
      title: "APGAR Score — Assessment at 1 and 5 Minutes",
      rows: [
        {
          parameter: "Appearance (Color)",
          normal: "2 = Pink body and extremities",
          abnormal: "1 = Pink body, blue extremities (acrocyanosis); 0 = Completely blue or pale",
          significance: "Acrocyanosis (blue hands/feet with pink trunk) is normal in first few minutes. Central cyanosis (blue lips/tongue) = abnormal, requires supplemental O₂.",
        },
        {
          parameter: "Pulse (Heart Rate)",
          normal: "2 = > 100 bpm",
          abnormal: "1 = < 100 bpm; 0 = Absent",
          significance: "HR < 100 after initial stimulation = primary indication for PPV. HR < 60 after adequate PPV = begin chest compressions.",
        },
        {
          parameter: "Grimace (Reflex Irritability)",
          normal: "2 = Cough, sneeze, or vigorous cry with stimulation",
          abnormal: "1 = Grimace with stimulation; 0 = No response",
          significance: "Tests response to suctioning catheter in nares. Absent response in well-ventilated infant suggests neurological depression.",
        },
        {
          parameter: "Activity (Muscle Tone)",
          normal: "2 = Active flexion of all extremities",
          abnormal: "1 = Some flexion; 0 = Limp, no tone",
          significance: "Hypotonia at birth: HIE, prematurity, neuromuscular disease, anesthesia effects, metabolic disorder (congenital hypothyroidism, PKU).",
        },
        {
          parameter: "Respiration",
          normal: "2 = Strong cry, regular respirations",
          abnormal: "1 = Weak cry or irregular respirations; 0 = Absent",
          significance: "Absent or gasping respirations = immediate PPV. Apgar score is an assessment tool, NOT a guide to resuscitation — resuscitation decisions are made on real-time assessment, not Apgar score.",
        },
        {
          parameter: "Total Score Interpretation",
          normal: "7–10 = Reassuring (normal); 4–6 = Moderate depression; 0–3 = Severe depression",
          abnormal: "Score ≤ 6 at 5 minutes warrants continued resuscitation and NICU transfer. Score 0 at 10 minutes = poor prognosis.",
          significance: "IMPORTANT: Resuscitation decisions are made in real-time, NOT by waiting for 1-min Apgar score. Apgar score is assigned retroactively. An infant in distress should be receiving PPV before the 1-minute Apgar is calculated.",
        },
        {
          parameter: "Target SpO₂ by Minute of Life (Pre-ductal — Right Hand)",
          normal: "1 min: 60–65%; 2 min: 65–70%; 3 min: 70–75%; 4 min: 75–80%; 5 min: 80–85%; 10 min: 85–95%",
          abnormal: "SpO₂ below target range despite supplemental O₂ → increase FiO₂. Avoid hyperoxia in preterm infants (start 21–30% and titrate up)",
          significance: "Normal transition from fetal to neonatal circulation takes several minutes — SpO₂ of 60–65% at 1 minute of life is EXPECTED and does not require 100% O₂.",
        },
      ],
    },
    complications: [
      "Pneumothorax or pneumomediastinum from excessive ventilation pressures (prevent: verify chest rise with minimum pressure; CXR if sudden deterioration)",
      "Hypothermia — most common complication in premature infants (prevent with polyethylene wrap, warm environment, hat, radiant warmer, avoid wet blankets)",
      "Hypoglycemia post-resuscitation (check blood glucose within 30–60 minutes of birth in resuscitated infants; target ≥ 45 mg/dL)",
      "Endotracheal tube misplacement (right mainstem bronchus intubation — asymmetric breath sounds; esophageal intubation — no color change on CO₂ detector)",
      "Intraventricular hemorrhage (IVH) in preterm infants — avoid rapid fluid boluses, maintain normothermia, avoid hypercarbia and hypocarbia",
      "Hypoxic-ischemic encephalopathy (HIE) — refer to NICU for therapeutic hypothermia if criteria met (≥ 36 weeks + encephalopathy)",
    ],
    clinicalPearl:
      "Delayed cord clamping (DCC) is now recommended for at least 30–60 seconds in vigorous term and preterm infants — it significantly increases iron stores and hemoglobin at birth, reducing IDA in the first year of life and improving neurodevelopmental outcomes in preterm infants. If resuscitation is required, it is acceptable to clamp the cord immediately. For very preterm infants (< 28 weeks), umbilical cord milking may be considered as an alternative when DCC is not feasible. Thermoregulation is as important as airway management — hypothermia within minutes of birth significantly worsens HIE outcomes.",
    boardRecallTip: "NRP: Term + tone + cry? → routine care. No to any → dry/stimulate/position. HR < 100 → PPV. HR < 60 after PPV → chest compressions (3:1 ratio) + 100% O₂ + intubate. HR < 60 after compressions → epinephrine IV 0.01–0.03 mg/kg. Apgar at 1 and 5 minutes (not used to guide resuscitation). HIE ≥ 36 weeks → therapeutic hypothermia 33–34°C × 72h.",
  },
  {
    id: "peds-proc-developmental-screening",
    rotation: "pediatrics",
    name: "Developmental Screening — ASQ-3 and M-CHAT-R/F Administration",
    overview:
      "Developmental screening is a brief, standardized process used to identify children at risk for developmental delays or disorders. It is distinct from developmental surveillance (informal, ongoing monitoring) and diagnostic assessment (formal evaluation by a specialist). The AAP mandates formal developmental screening using validated instruments at 9, 18, and 30 months (or 24 months if 30-month visit is not held), and autism-specific screening at 18 and 24 months. The Ages and Stages Questionnaires, 3rd Edition (ASQ-3) is the most widely used general developmental screener. The Modified Checklist for Autism in Toddlers, Revised with Follow-Up (M-CHAT-R/F) is the standard autism-specific screener.",
    indications: [
      "Universal developmental screening at 9 months, 18 months, and 30 months (AAP Bright Futures mandate)",
      "Autism-specific screening at 18 months AND 24 months (two time points, not just one)",
      "Any well-child visit when a parent or provider raises a developmental concern",
      "Surveillance flags: regression of milestones (any age — always warrants screening), failure to achieve language milestones, social withdrawal, unusual repetitive behaviors, sensory sensitivities",
      "High-risk populations: preterm birth, low birthweight, NICU graduates, genetic syndromes, prenatal drug/alcohol exposure, parental depression, low socioeconomic status, adverse childhood experiences (ACEs)",
    ],
    contraindications: [
      "No contraindications to performing developmental screening",
      "Adjust interpretation for prematurity: use CORRECTED age (subtract weeks premature from chronological age) for ASQ scoring up to age 2 years for most domains. By 24 months corrected age, most premature infants are evaluated at chronological age.",
    ],
    equipment: [
      "ASQ-3 questionnaire appropriate for child's age interval (21 age-specific intervals, each covers a 30-day window) — available in English, Spanish, and other languages",
      "M-CHAT-R/F: two-page screener (20-item parent questionnaire); M-CHAT-R/F Follow-Up interview guide for borderline scores",
      "Pen/pencil; scoring sheet or electronic scoring system (ASQ-3 online platform available)",
      "Materials for validation observation during exam: small toys, blocks, picture books, cheerios/puffs (for fine motor/pincer grasp observation), bubbles",
      "Referral resources: local Early Intervention agency contact (Part C, IDEA — for children birth to 3 years), school district special education contact (Part B, IDEA — for children 3–21 years), speech-language pathology, occupational therapy, developmental pediatrics contacts",
    ],
    procedure: [
      "PRE-VISIT PREPARATION: Send ASQ-3 to parent/guardian 1–2 days before the visit (mail or electronic portal) — parents complete it at home where they can observe the child in a familiar setting. If not pre-completed, allow 10–15 minutes in the waiting room for parent completion. Select the correct age interval based on child's chronological age (or corrected age if premature < 24 months).",
      "ASQ-3 COMPLETION: Parent answers 30 questions across 5 domains — Communication (6 questions), Gross Motor (6), Fine Motor (6), Problem Solving (6), Personal-Social (6). Each item scored as: Yes = 10, Sometimes = 5, Not Yet = 0. Maximum score per domain = 60. Completion time: 10–15 minutes for parent; 2–3 minutes to score.",
      "ASQ-3 SCORING: Add item scores within each domain (Communication: __/60; Gross Motor: __/60; Fine Motor: __/60; Problem Solving: __/60; Personal-Social: __/60). Compare each domain score to age-specific cutoff scores (published in ASQ-3 technical manual or built into scoring software). Interpretation: Above cutoff = typically developing (reassure, rescreening at next well-child visit); At/near cutoff (within 2 SDs) = monitor (rescreening in 1–2 months or earlier if concern); Below cutoff = refer (specialty evaluation + Early Intervention referral).",
      "M-CHAT-R COMPLETION: Parent completes 20-item yes/no questionnaire specifically targeting autism warning signs. Takes 5 minutes. No age selection needed — used at 16–30 months (standard administration at 18 and 24 month visits).",
      "M-CHAT-R SCORING: Score 1 point for each 'at-risk' response (for most items, 'No' = at risk; items 2, 5, and 12 are reverse-scored where 'Yes' = at risk). Total score 0–2 = LOW RISK → routine rescreening at next visit. Total score 3–7 = MEDIUM RISK → complete M-CHAT-R/F Follow-Up interview (structured phone or in-person interview that clarifies ambiguous responses — reduces false positives by 50%). Rescored follow-up: 0–1 = low risk; 2+ = HIGH RISK → refer. Total score ≥ 8 (any score) = HIGH RISK → refer immediately (skip follow-up interview).",
      "M-CHAT-R/F FOLLOW-UP INTERVIEW: Conducted by trained provider by phone or at visit. Clarifies responses from the M-CHAT-R that may have been misunderstood. Goes through specific items with probing questions. Recalculate score after follow-up. Reduces false positives and improves positive predictive value.",
      "DOCUMENTATION: Document in the chart: (1) screening tool used and age interval, (2) score in each domain (ASQ-3) or total score (M-CHAT-R), (3) interpretation (pass/monitor/refer), (4) parent concerns, (5) clinical observations of developmental behaviors during visit, (6) plan (rescreening date or referral made).",
      "REFERRAL PROCESS: For FAILING ASQ-3 (below cutoff in any domain) or HIGH-RISK M-CHAT-R: (1) Refer to Early Intervention (EI) — children birth to 3 years — for evaluation; EI provides free services under IDEA Part C (speech therapy, OT, PT, developmental therapy). Families do NOT need a physician referral in most states — can self-refer. (2) Refer to audiology — ALWAYS rule out hearing loss as the cause of language delay. (3) Refer to developmental pediatrics or neurology for diagnostic evaluation of ASD or GDD. (4) Refer to primary care ophthalmology for vision concerns. Communicate urgency to family: 'Do not wait and see — early intervention provides the best outcomes.'",
      "EARLY INTERVENTION ELIGIBILITY: Under IDEA Part C, children birth–3 years are eligible if they have: (1) a diagnosed condition with high probability of developmental delay (Down syndrome, cerebral palsy, etc.), (2) developmental delay of ≥ 25% in one domain or ≥ 20% in 2 domains (state-specific), or (3) at risk for developmental delay (state-specific). An EI evaluation must begin within 45 days of referral. Services are provided in the natural environment (home, daycare). At age 3, transition to school-based services under IDEA Part B.",
    ],
    interpretation: {
      title: "Screening Score Interpretation and Action Thresholds",
      rows: [
        {
          parameter: "ASQ-3 Score: Above Cutoff",
          normal: "Score is above the age-specific cutoff in all 5 domains",
          abnormal: "N/A",
          significance: "Typical development — reassure family. Rescreening at next scheduled well-child visit. Continue developmental surveillance at every visit.",
        },
        {
          parameter: "ASQ-3 Score: At Cutoff (within 2 SDs above cutoff)",
          normal: "N/A",
          abnormal: "Score within 2 SD above cutoff = monitoring zone",
          significance: "Monitor closely. Provide developmental activities/resources (e.g., Zero to Three). Rescreening in 1–2 months. Consider referral if additional risk factors (hearing loss, prematurity, parental concern).",
        },
        {
          parameter: "ASQ-3 Score: Below Cutoff",
          normal: "N/A",
          abnormal: "Score below the age-specific cutoff in any domain = refer",
          significance: "Refer to EI (birth–3 years) or school district (≥ 3 years). Order hearing evaluation. Consider developmental pediatrics referral. Parental counseling: 'Early intervention is highly effective — the earlier the better.'",
        },
        {
          parameter: "M-CHAT-R Total 0–2",
          normal: "Low risk for autism",
          abnormal: "N/A",
          significance: "Routine care. Rescreen at next scheduled visit (18 months and 24 months). If parent concern persists, offer referral regardless of score.",
        },
        {
          parameter: "M-CHAT-R Total 3–7",
          normal: "N/A",
          abnormal: "Medium risk — administer M-CHAT-R/F Follow-Up interview",
          significance: "Follow-Up reduces false positives by 50%. If follow-up score ≥ 2 → refer for diagnostic ASD evaluation. If follow-up score 0–1 → monitor closely, rescreen at 24 months if < 24 months currently.",
        },
        {
          parameter: "M-CHAT-R Total ≥ 8",
          normal: "N/A",
          abnormal: "High risk for autism — refer immediately (skip follow-up interview)",
          significance: "Immediate referral to: developmental pediatrics, child psychiatry, or multidisciplinary ASD team for diagnostic evaluation. Also refer to EI for ABA therapy, speech, OT while awaiting diagnosis. Do not wait for diagnosis to initiate services.",
        },
      ],
    },
    complications: [
      "False positives: overreferral causes parental anxiety and strains EI resources. M-CHAT-R/F follow-up interview significantly reduces false positives.",
      "False negatives: missed developmental delays. Regular surveillance and multiple screening time points reduce false negatives. Parent concern should always prompt referral regardless of passing score.",
      "Cultural and language bias: ASQ-3 and M-CHAT-R have been validated in diverse populations but cultural differences in parental reporting and behavior expectations may affect scores. Use screeners in the family's primary language; consider cultural context.",
      "Screening anxiety: some parents become anxious about the process or a borderline result. Frame as 'helping your child get any extra support they might need early' — early intervention is empowering, not a diagnosis.",
    ],
    clinicalPearl:
      "A negative M-CHAT-R does NOT rule out ASD — it has a sensitivity of approximately 85–95% and specificity of 95%+ when the follow-up interview is used. Any parental concern about ASD, regardless of M-CHAT-R score, should prompt referral. ASD is a spectrum — some high-functioning children may have subtle early signs that are missed on a questionnaire-based screener. The screening principle is: 'When in doubt, refer out.' Early intensive behavioral intervention (ABA therapy) starting before age 3 years — ideally as early as 12–18 months — produces the best long-term outcomes for children with ASD.",
    boardRecallTip: "ASQ-3: 9, 18, 30 months — 5 domains, score below cutoff → refer to Early Intervention + audiology. M-CHAT-R: 18 AND 24 months — score 0–2 = low, 3–7 = follow-up interview, ≥ 8 = immediate referral. EI (Part C IDEA): birth–3 years, free, in natural environment. Always check hearing first in any language delay.",
  },
  {
    id: "peds-proc-tympanometry",
    rotation: "pediatrics",
    name: "Tympanometry and Pneumatic Otoscopy",
    overview:
      "Tympanometry and pneumatic otoscopy are complementary office-based procedures used to assess middle ear function and diagnose middle ear effusion, Eustachian tube dysfunction, and tympanic membrane (TM) perforation. They are essential for accurately diagnosing acute otitis media (AOM), otitis media with effusion (OME), and evaluating hearing loss in children. Pneumatic otoscopy assesses TM mobility by applying positive and negative pressure through the otoscope's pneumatic bulb. Tympanometry measures acoustic admittance (the ease with which sound energy flows through the middle ear system) and generates a tympanogram.",
    indications: [
      "Evaluation of otitis media (AOM vs OME — clinically critical distinction with treatment implications)",
      "Assessment of middle ear effusion (MEE) in children with recurrent ear infections",
      "Hearing loss evaluation — to determine if conductive (TM/middle ear pathology) vs sensorineural",
      "Pre-tympanostomy tube (PE tube) evaluation",
      "Post-treatment follow-up for AOM — confirming resolution of MEE",
      "Evaluation of Eustachian tube dysfunction (chronic negative middle ear pressure — Type C tympanogram)",
      "TM perforation detection (flat tympanogram with large ear canal volume)",
    ],
    contraindications: [
      "Otitis externa (inflammation of external ear canal — pain and edema may prevent probe insertion; also affects reliability of results)",
      "Active drainage or discharge from ear canal — cerumen, pus, or blood prevents seal formation",
      "Recent tympanostomy tube (PE tube) placement — Type B tympanogram is expected; tympanometry not diagnostic in this setting",
      "Known TM perforation when attempting pneumatic otoscopy with pressure (may cause pain and is not informative)",
    ],
    equipment: [
      "PNEUMATIC OTOSCOPY: Otoscope with pneumatic attachment (rubber bulb connected to sealed otoscope head); appropriate speculum sizes (2.5 mm, 4 mm) — must form an airtight seal in the ear canal; light source (otoscope battery must be fresh for bright visualization)",
      "TYMPANOMETRY: Tympanometer (handheld or desktop — e.g., Welch Allyn MicroTymp, Interacoustics AT235, or portable Grason-Stadler GSI TympStar); probe with soft ear tip (sized to form airtight seal — select appropriate size for child's ear canal: small for infants/toddlers, medium for older children); printer or electronic record for tympanogram output",
      "Cerumen removal supplies (curette or irrigation kit) — wax impaction must be cleared before accurate tympanometry",
      "Otoscope for visualization before tympanometry",
    ],
    procedure: [
      "PNEUMATIC OTOSCOPY — TECHNIQUE: Patient seated or in parent's lap (toddlers — parent holds child in lap facing examiner, wrapping arms around child's arms). Grasp pinna: in children > 3 years, pull pinna UP and BACK (same as adults). In infants/toddlers < 3 years, pull pinna DOWN and BACK (ear canal is more horizontal in young children). Gently insert speculum to obtain airtight seal in the outer ear canal (do not insert deeply — painful and unnecessary). With clear visualization of the TM, gently SQUEEZE the pneumatic bulb to apply positive pressure, then RELEASE to apply negative pressure. Observe TM movement.",
      "PNEUMATIC OTOSCOPY — INTERPRETATION: Normal TM mobility: brisk movement with small pressure changes (like a sail catching wind) — both with positive (inward) and negative (outward) pressure. Reduced or absent TM mobility: middle ear effusion (fluid behind TM reduces compliance — TM barely moves or does not move). Confirms MEE with > 90% specificity when combined with TM appearance.",
      "VISUAL TM ASSESSMENT (before tympanometry): Note: (1) Color — normal (pearly gray, translucent); erythematous (inflammation); amber/yellow (effusion/serous); white (scarring or cholesteatoma). (2) Position — neutral; retracted (negative middle ear pressure); bulging (AOM — most important sign of AOM). (3) Light reflex — present and cone-shaped (normal); absent or diffuse (effusion, scarring). (4) Landmarks — visible malleus handle and short process. (5) Perforations — visible hole in TM.",
      "TYMPANOMETRY — PATIENT PREPARATION: Explain to child/parent that the probe will be placed in the ear and will make a tone and change pressure — it should not hurt. Ensure quiet environment (crying and swallowing artifact the tracing). Check ear canal with otoscope first — remove cerumen if present (blocks probe, gives inaccurate results). Select correct probe tip size to form airtight seal.",
      "TYMPANOMETRY — PROCEDURE: Insert probe tip into ear canal to form an airtight seal (confirmed by the tympanometer's seal indicator). Press START — the device automatically: (1) plays a 226 Hz probe tone (standard; 1000 Hz for infants < 6 months — better sensitivity in flaccid infant TMs), (2) varies the air pressure from +200 to -300 daPa (decapascals), (3) measures acoustic admittance at each pressure point, (4) generates a tympanogram curve. The entire measurement takes 3–5 seconds. Print or save the tympanogram.",
      "TYMPANOMETRY — READING THE TYMPANOGRAM: X-axis = pressure (daPa); Y-axis = admittance (mL or mmho). Identify: (1) Peak location (tympanometric peak pressure — where maximum admittance occurs), (2) Peak height (static admittance), (3) Gradient (width at half-height — wider = flatter = more effusion), (4) Ear canal volume (ECV — volume between probe tip and TM; useful for detecting perforations).",
      "DOCUMENTATION: Record tympanogram type (A, B, or C), peak pressure (daPa), static admittance (mL), ear canal volume (mL), and gradient. Document bilaterally. Note any technical difficulties (poor seal, cerumen, uncooperative child). Correlate with otoscopic findings and symptoms.",
      "INTERPRETATION AND CLINICAL DECISION-MAKING: Combine tympanogram type with: (1) otoscopic findings (TM color, position, mobility on pneumatic otoscopy), (2) symptoms (ear pain, fever, hearing loss), (3) duration of findings, (4) hearing test results (if performed). Isolated Type B without symptoms or hearing loss: 'OME — monitor for 3 months before referral.' Type B bilaterally + hearing loss > 20 dB + > 3 months = referral to ENT for consideration of PE tubes.",
    ],
    interpretation: {
      title: "Tympanogram Types — Classification and Clinical Significance",
      rows: [
        {
          parameter: "Type A — Normal",
          normal: "Single well-defined peak near 0 daPa (between −99 and +99 daPa); normal static admittance (0.3–1.6 mL); normal gradient",
          abnormal: "N/A",
          significance: "Normal middle ear function. No middle ear effusion. Rules out OME with high reliability. Normal compliance of TM and ossicular chain.",
        },
        {
          parameter: "Type As — Shallow/Stiff",
          normal: "N/A",
          abnormal: "Peak at normal pressure but reduced peak height (admittance < 0.3 mL) — low compliance",
          significance: "Reduced TM mobility. Causes: otosclerosis (fixation of stapes footplate — rare in children), tympanosclerosis (calcification of TM from prior infections), ossicular fixation. Refer to audiology for formal hearing evaluation.",
        },
        {
          parameter: "Type Ad — Discontinuity/Hypercompliant",
          normal: "N/A",
          abnormal: "Very high peak (admittance > 1.6 mL) — hypercompliant TM",
          significance: "Flaccid TM or ossicular discontinuity (disruption of the ossicular chain). Seen after TM perforation (healed) or trauma. Referral to ENT for evaluation.",
        },
        {
          parameter: "Type B — Flat (No Peak)",
          normal: "N/A",
          abnormal: "No discernible peak across the full pressure range. Two sub-types: (1) Type B with NORMAL ear canal volume (0.3–1.0 mL) = middle ear effusion; (2) Type B with LARGE ear canal volume (> 2.0 mL) = TM perforation or PE tube patent",
          significance: "Type B + normal ECV = middle ear effusion (OME or AOM). Most important tympanometric finding in pediatrics. Bilateral Type B + hearing loss > 20 dB for > 3 months → ENT referral for PE tube evaluation. Type B + large ECV → check for TM perforation on otoscopy.",
        },
        {
          parameter: "Type C — Negative Pressure",
          normal: "N/A",
          abnormal: "Peak is present but displaced to negative pressure zone (< −99 daPa), indicating negative middle ear pressure",
          significance: "Eustachian tube dysfunction — negative middle ear pressure. Middle ear is sucking inward due to poor ET function. May precede effusion (pre-effusion state). Manage: decongestants have limited evidence; treat allergic rhinitis if present; auto-inflation (Valsalva, Otovent balloon); recheck in 4–6 weeks. If progressive retraction or cholesteatoma → ENT.",
        },
        {
          parameter: "Ear Canal Volume (ECV)",
          normal: "0.3–1.0 mL (infants); 0.5–1.5 mL (children)",
          abnormal: "> 2.0 mL with flat (Type B) tympanogram",
          significance: "Large ECV + Type B = patent PE tube OR TM perforation (ear canal volume includes volume of middle ear space beyond the perforation). Small ECV (<0.3 mL) = probe tip blocked by cerumen or canal wall → clean ear and repeat.",
        },
      ],
    },
    complications: [
      "Discomfort (brief) from pressure changes — rare, minimize by using appropriately sized probe tip and adequate seal",
      "Ear canal wall stimulation causing vasovagal response — very rare; have child seated during procedure",
      "Misleading results: cerumen impaction (always otoscope first), crying/swallowing (repeat when calm), incorrect probe tip size (poor seal → artifactual flat tracing misinterpreted as effusion)",
      "False-positive Type B in infants < 6 months: 226 Hz probe frequency underestimates compliance in infants with more compliant ear canals. Use 1,000 Hz probe tone for infants < 6 months for accurate results.",
    ],
    clinicalPearl:
      "The diagnosis of AOM requires BOTH middle ear effusion AND signs of acute infection (fever, otalgia, TM erythema/bulging). Tympanometry alone (Type B) only confirms MEE — it cannot differentiate AOM from OME. Pneumatic otoscopy adds the critical assessment of TM mobility and appearance (bulging, erythema). A child with Type B tympanogram + asymptomatic = OME (watchful waiting × 3 months per AAFP/AAP guidelines). A child with Type B + bulging TM + otalgia + fever = AOM (treat with antibiotics). Accurate diagnosis of AOM vs OME is the single most important factor in reducing inappropriate antibiotic prescribing.",
    boardRecallTip: "Type A = normal. Type B + normal ECV = effusion (AOM or OME). Type B + large ECV = perforation or patent PE tube. Type C = negative pressure = ET dysfunction. Infants < 6 months: use 1,000 Hz probe (not 226 Hz). Bilateral Type B + hearing loss > 20 dB × 3 months → ENT for PE tube evaluation.",
  },
];
