import type { Guideline } from "@/types";

export const internalMedicineGuidelines: Guideline[] = [
  {
    id: "im-gl-01",
    rotation: "internal-medicine",
    conditionName: "Heart Failure",
    guidelineName: "2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure",
    issuingOrganization: "ACC/AHA/HFSA",
    year: 2022,
    keyRecommendations: [
      "Classify HF by ejection fraction: HFrEF (EF ≤40%), HFmrEF (EF 41-49%), HFpEF (EF ≥50%).",
      "Stage A (at-risk): no structural disease — address risk factors aggressively.",
      "Stage B (pre-HF): structural disease without symptoms — initiate GDMT.",
      "Stage C (symptomatic HF): optimise quadruple GDMT (ACEi/ARB/ARNI + BB + MRA + SGLT2i).",
      "Stage D (advanced HF): consider LVAD, transplant listing, or palliative care.",
      "SGLT2 inhibitors (dapagliflozin, empagliflozin) are recommended for HFrEF and HFmrEF to reduce hospitalisations and CV death.",
    ],
    firstLine: [
      "ACE inhibitor (lisinopril) OR ARB (valsartan) — or upgrade to ARNI (sacubitril/valsartan) if tolerating ACEi/ARB",
      "Beta-blocker: carvedilol, metoprolol succinate, or bisoprolol (the only three with mortality benefit in HFrEF)",
      "Mineralocorticoid receptor antagonist (MRA): spironolactone or eplerenone (eGFR >30, K+ <5.0)",
      "SGLT2 inhibitor: dapagliflozin 10 mg daily or empagliflozin 10 mg daily",
    ],
    secondLine: [
      "Loop diuretic (furosemide) for volume overload — titrate to dry weight",
      "Hydralazine + isosorbide dinitrate for Black patients with persistent symptoms or ACEi/ARB intolerance",
      "Ivabradine for HR ≥70 bpm on maximally tolerated beta-blocker in sinus rhythm",
    ],
    thirdLine: [
      "Digoxin to reduce HF hospitalisations in persistent symptomatic HFrEF (narrow therapeutic window; not first-line)",
      "Vericiguat (sGC stimulator) for high-risk HFrEF with recent worsening event",
    ],
    nonPharmacologic: [
      "Sodium restriction: <2–3 g/day",
      "Fluid restriction: 1.5–2 L/day in advanced HF or dilutional hyponatraemia",
      "Daily weight monitoring — instruct patient to call if gain >2 lb in 24 h or >5 lb in 1 week",
      "Cardiac rehabilitation referral for eligible patients",
      "ICD implantation for EF ≤35% despite ≥3 months GDMT (NYHA class II–III) for primary prevention of SCD",
      "CRT-D for EF ≤35%, LBBB with QRS ≥150 ms, NYHA class II–III",
    ],
    whenToRefer: [
      "Cardiologist referral for newly diagnosed HFrEF or uncertain aetiology",
      "Advanced HF specialist when Stage D criteria met (recurrent hospitalisation, refractory symptoms on GDMT)",
      "Electrophysiology referral for ICD/CRT evaluation",
      "Palliative care referral for Stage D patients not candidates for advanced therapies",
    ],
    monitoringSchedule: [
      "BMP within 1–2 weeks of initiating/uptitrating ACEi/ARB/ARNI or MRA (monitor K+ and creatinine)",
      "BNP or NT-proBNP at baseline; recheck with clinical change",
      "Repeat echocardiogram after 3–6 months of GDMT optimisation to reassess EF",
      "Annual echocardiogram once on stable GDMT",
      "Clinic visit within 7–14 days of HF hospitalisation discharge",
      "Digoxin level if prescribed (target 0.5–0.9 ng/mL)",
    ],
    patientEducation: [
      "Recognise early warning signs: increased dyspnea, orthopnea, leg swelling, rapid weight gain",
      "Do not stop beta-blockers abruptly; contact provider before any medication changes",
      "SGLT2 inhibitors can cause genital mycotic infections — maintain genital hygiene",
      "Alcohol cessation strongly recommended in alcohol-induced cardiomyopathy",
      "Influenza and pneumococcal vaccinations are recommended",
      "Advance care planning discussion appropriate for all Stage C-D patients",
    ],
  },
  {
    id: "im-gl-02",
    rotation: "internal-medicine",
    conditionName: "COPD",
    guidelineName: "GOLD 2024 Global Strategy for Prevention, Diagnosis and Management of COPD",
    issuingOrganization: "GOLD (Global Initiative for Chronic Obstructive Lung Disease)",
    year: 2024,
    keyRecommendations: [
      "Diagnosis confirmed by post-bronchodilator FEV1/FVC <0.70 on spirometry.",
      "GOLD spirometric grades 1–4 based on FEV1 % predicted: ≥80% (mild), 50–79% (moderate), 30–49% (severe), <30% (very severe).",
      "ABCD assessment groups replaced by GOLD 2023 ABE groups: A (low symptoms, low exacerbations), B (high symptoms, low exacerbations), E (≥2 exacerbations or ≥1 hospitalisation).",
      "Initial pharmacotherapy is guided by symptom burden (mMRC/CAT score) and exacerbation history.",
      "Smoking cessation is the single most effective intervention to slow disease progression.",
      "Inhaler technique must be verified at every visit — poor technique is the most common cause of treatment failure.",
    ],
    firstLine: [
      "Group A: short-acting bronchodilator (SABA or SAMA) as needed — albuterol or ipratropium",
      "Group B: long-acting bronchodilator monotherapy — LAMA (tiotropium) preferred over LABA",
      "Group E: LAMA + LABA dual therapy (e.g., umeclidinium/vilanterol); add ICS if eosinophils ≥300 cells/µL",
    ],
    secondLine: [
      "LAMA + LABA + ICS triple therapy for Group E with persistent exacerbations on dual therapy",
      "Roflumilast (PDE-4 inhibitor) adjunct for FEV1 <50%, chronic bronchitis phenotype with frequent exacerbations",
      "Azithromycin 250 mg daily (3x/week) for former smokers with recurrent exacerbations — check QTc before initiating",
    ],
    thirdLine: [
      "Long-term oxygen therapy (LTOT) for resting SpO2 ≤88% or PaO2 ≤55 mmHg — use ≥15 h/day",
      "Non-invasive positive pressure ventilation (NPPV) for hypercapnic respiratory failure",
    ],
    nonPharmacologic: [
      "Smoking cessation counselling + pharmacotherapy (varenicline preferred) at every visit",
      "Pulmonary rehabilitation for mMRC ≥2 — improves exercise tolerance and quality of life",
      "Annual influenza vaccine; pneumococcal (PCV15/PCV20) vaccine; COVID-19 and Tdap vaccines",
      "Nutritional support for underweight patients; obesity management for obese patients",
      "Lung volume reduction surgery or bronchoscopic procedures for selected severe emphysema patients",
    ],
    whenToRefer: [
      "Pulmonology referral for diagnostic uncertainty, severe disease (GOLD 3–4), or frequent exacerbations",
      "Pulmonary rehabilitation program referral for any patient with dyspnea limiting activity",
      "Thoracic surgery referral for evaluation of bullectomy or lung volume reduction surgery",
      "Palliative care for end-stage COPD with refractory symptoms",
    ],
    monitoringSchedule: [
      "Spirometry at diagnosis and annually to monitor disease progression",
      "Pulse oximetry at each visit; ABG if SpO2 ≤92% to evaluate for LTOT candidacy",
      "CAT or mMRC score at each visit to quantify symptom burden",
      "6-minute walk test annually for functional capacity assessment",
      "Assess inhaler technique and adherence at every encounter",
    ],
    patientEducation: [
      "Smoking cessation is the most important step — offer resources at every visit",
      "Use rescue inhaler (SABA) for acute breathlessness; controller inhalers daily as prescribed",
      "Have a written COPD action plan — know when to start oral steroids and antibiotics",
      "Seek emergency care for severe dyspnea, cyanosis, or altered mental status",
      "Avoid respiratory irritants: smoke, dust, indoor air pollution, strong fumes",
      "Annual vaccinations reduce exacerbation risk significantly",
    ],
  },
  {
    id: "im-gl-03",
    rotation: "internal-medicine",
    conditionName: "Community-Acquired Pneumonia",
    guidelineName: "IDSA/ATS Consensus Guidelines on the Management of CAP in Adults",
    issuingOrganization: "IDSA/ATS",
    year: 2019,
    keyRecommendations: [
      "Diagnose CAP clinically (new infiltrate on CXR plus ≥2 of: fever/hypothermia, purulent sputum, leukocytosis/leucopenia, new cough/dyspnea/pleurisy) and stratify severity with CURB-65.",
      "CURB-65 scoring: Confusion, Urea >7 mmol/L (BUN >19 mg/dL), RR ≥30, BP systolic <90 or diastolic ≤60, Age ≥65. Score 0–1: outpatient; 2: short inpatient or close outpatient; ≥3: inpatient; ≥5: ICU consider.",
      "Blood cultures and sputum cultures should be obtained before antibiotics in hospitalised patients.",
      "Pneumococcal urinary antigen and Legionella urinary antigen in severe/ICU CAP.",
      "Procalcitonin can guide antibiotic de-escalation but should not delay empiric therapy.",
      "Duration of therapy: minimum 5 days; patient should be afebrile ≥48–72 hours before stopping.",
    ],
    firstLine: [
      "Outpatient, no comorbidities: amoxicillin 1 g TID OR doxycycline 100 mg BID OR azithromycin 500 mg day 1 then 250 mg days 2–5 (if low pneumococcal resistance)",
      "Outpatient with comorbidities (COPD, diabetes, CKD, heart failure, asplenia): respiratory fluoroquinolone (levofloxacin 750 mg daily) OR beta-lactam + macrolide combination",
      "Inpatient, non-ICU: beta-lactam (ampicillin-sulbactam or ceftriaxone) + azithromycin OR respiratory fluoroquinolone monotherapy",
      "ICU CAP: beta-lactam + azithromycin OR beta-lactam + respiratory fluoroquinolone",
    ],
    secondLine: [
      "MRSA coverage (add vancomycin or linezolid) if: prior MRSA infection, purulent sputum, cavitary lesion, recent influenza",
      "Pseudomonal coverage (piperacillin-tazobactam or cefepime) if: bronchiectasis, prior Pseudomonas infection, recent hospitalisation/antibiotics",
      "Oseltamivir if influenza confirmed or strongly suspected — within 48 h of symptom onset",
    ],
    nonPharmacologic: [
      "Supplemental oxygen to maintain SpO2 ≥94% (88–92% in COPD with CO2 retention)",
      "IV hydration for dehydration or inability to tolerate oral intake",
      "Incentive spirometry and early ambulation to reduce atelectasis and DVT risk",
      "Head of bed elevation ≥30° to reduce aspiration risk",
      "Smoking cessation counselling",
    ],
    whenToRefer: [
      "ICU admission for Infectious Disease/Pulmonology if meeting ATS major criteria (septic shock requiring vasopressors, mechanical ventilation)",
      "Infectious Disease consult for healthcare-associated or treatment-refractory pneumonia",
      "Pulmonology for recurrent pneumonia in same lobe (rule out endobronchial obstruction)",
    ],
    monitoringSchedule: [
      "Clinical response assessment at 48–72 hours — failure to improve warrants CXR repeat, broader coverage, and ID consult",
      "Follow-up CXR at 6–8 weeks to confirm radiographic clearance (rule out underlying malignancy)",
      "Blood cultures — notify if positive and narrow therapy accordingly",
      "O2 saturation monitoring every shift in hospitalised patients",
    ],
    patientEducation: [
      "Complete the full antibiotic course even if feeling better",
      "Pneumococcal and influenza vaccines reduce CAP risk — discuss at discharge",
      "Smoking cessation significantly reduces pneumonia risk",
      "Return precautions: worsening dyspnea, high fever recurrence, confusion, inability to keep medications down",
      "Most patients with CAP improve within 3–5 days; full radiographic resolution may take 4–8 weeks",
    ],
  },
  {
    id: "im-gl-04",
    rotation: "internal-medicine",
    conditionName: "DVT/PE (Venous Thromboembolism)",
    guidelineName: "CHEST Antithrombotic Therapy Guidelines / ASH 2020 VTE Guidelines",
    issuingOrganization: "CHEST / ASH",
    year: 2020,
    keyRecommendations: [
      "Use validated clinical prediction rules: Wells criteria for DVT/PE, Geneva score for PE.",
      "D-dimer is a high-sensitivity, low-specificity test — negative D-dimer with low pre-test probability rules out VTE.",
      "CTA pulmonary angiography (CTPA) is the gold-standard imaging for PE.",
      "Anticoagulate for minimum 3 months for provoked VTE (surgery, immobility, trauma) and ≥3–6 months for unprovoked VTE.",
      "Extended anticoagulation (indefinite) for unprovoked recurrent VTE, antiphospholipid syndrome, or active cancer.",
      "DOACs (rivaroxaban, apixaban) are preferred over warfarin for most patients with DVT/PE (except antiphospholipid syndrome).",
    ],
    firstLine: [
      "Apixaban 10 mg BID x 7 days then 5 mg BID (or 2.5 mg BID for extended therapy) — no bridging needed",
      "Rivaroxaban 15 mg BID x 21 days then 20 mg daily — no bridging needed",
      "Enoxaparin (LMWH) 1 mg/kg SQ BID — preferred in pregnancy and active cancer (switch to DOAC after 6 months in cancer)",
    ],
    secondLine: [
      "Warfarin (target INR 2–3) with LMWH bridging until INR therapeutic x 24 h for 2 consecutive readings — for patients with antiphospholipid syndrome (target INR 3.0) or DOAC intolerance",
      "Unfractionated heparin (UFH) IV infusion — preferred in massive PE, renal failure (eGFR <30), or when rapid reversal anticipated",
      "Fondaparinux 5–10 mg SQ daily for patients with heparin-induced thrombocytopenia (HIT)",
    ],
    thirdLine: [
      "Catheter-directed thrombolysis or surgical embolectomy for massive PE with hemodynamic instability not responding to resuscitation",
      "Systemic thrombolysis (alteplase 100 mg IV over 2 h) for massive PE with cardiac arrest or refractory shock",
      "IVC filter (retrievable) only if absolute contraindication to anticoagulation",
    ],
    nonPharmacologic: [
      "Compression stockings (30–40 mmHg) for symptomatic relief of DVT; limited evidence for PTS prevention",
      "Early ambulation safe and encouraged once anticoagulation initiated for DVT",
      "Supplemental oxygen for PE with hypoxia",
      "Bed rest not required for hemodynamically stable PE",
    ],
    whenToRefer: [
      "Hematology for thrombophilia workup (test ≥3 months after completing anticoagulation, not during warfarin therapy)",
      "Pulmonology/IR for catheter-directed thrombolysis consideration in submassive PE with RV strain",
      "Cardiothoracic surgery for massive PE unresponsive to thrombolysis",
      "Oncology to guide anticoagulation duration in cancer-associated VTE",
    ],
    monitoringSchedule: [
      "INR (if on warfarin): check every 2–3 days initially, then weekly until stable, then monthly",
      "CBC with DOACs: baseline and as clinically indicated (no routine therapeutic monitoring required)",
      "Renal function (eGFR) at baseline and periodically — dose adjust rivaroxaban/apixaban for CKD",
      "Repeat lower-extremity Doppler at 3 months to establish new baseline for future comparison",
    ],
    patientEducation: [
      "Take anticoagulant at the same time each day; do not skip doses",
      "Signs of bleeding: blood in urine/stool, prolonged bleeding from cuts, unusual bruising — seek emergency care",
      "Avoid NSAIDs and aspirin unless prescribed by your provider while on anticoagulation",
      "Warfarin patients: maintain a consistent vitamin K diet and report new medications",
      "Compression stockings reduce swelling and discomfort in leg DVT",
      "Discuss contraception — estrogen-containing contraceptives increase VTE risk",
    ],
  },
  {
    id: "im-gl-05",
    rotation: "internal-medicine",
    conditionName: "Acute Coronary Syndrome (NSTEMI/STEMI)",
    guidelineName: "2023 ACC/AHA Guideline for the Diagnosis and Management of ACS",
    issuingOrganization: "ACC/AHA",
    year: 2023,
    keyRecommendations: [
      "STEMI: immediate reperfusion — primary PCI is preferred (goal door-to-balloon ≤90 min); fibrinolysis if PCI not available within 120 min.",
      "NSTEMI/UA: stratify with HEART score or TIMI risk score; high-risk features warrant early invasive strategy within 24 h.",
      "Dual antiplatelet therapy (DAPT): aspirin 325 mg loading dose then 81 mg daily PLUS a P2Y12 inhibitor.",
      "Anticoagulation during ACS: UFH, LMWH, fondaparinux, or bivalirudin based on strategy and bleeding risk.",
      "High-intensity statin therapy initiated in all ACS patients regardless of baseline LDL.",
      "Beta-blockers initiated within 24 h if no contraindications (decompensated HF, heart block, active bronchospasm); ACEi started within 24 h if EF ≤40%, HF, diabetes, or anterior MI.",
    ],
    firstLine: [
      "Aspirin 325 mg chewed immediately, then 81 mg daily lifelong",
      "Ticagrelor 180 mg loading dose then 90 mg BID (preferred P2Y12 inhibitor in NSTEMI/STEMI) OR prasugrel 60 mg loading then 10 mg daily (PCI patients only, avoid if prior stroke/TIA)",
      "UFH bolus + infusion titrated to aPTT 50–70 sec during PCI",
      "High-intensity statin: atorvastatin 40–80 mg or rosuvastatin 20–40 mg initiated in hospital",
    ],
    secondLine: [
      "Enoxaparin 1 mg/kg SQ BID (alternative to UFH in NSTEMI managed medically)",
      "Fondaparinux 2.5 mg SQ daily for NSTEMI — reduced bleeding vs. UFH; add UFH bolus at time of PCI",
      "Clopidogrel 600 mg loading then 75 mg daily if ticagrelor/prasugrel contraindicated or unavailable",
      "Beta-blocker: metoprolol tartrate IV then oral if hemodynamically stable",
    ],
    thirdLine: [
      "ACE inhibitor or ARB (if ACEi intolerant) for LVEF ≤40%, HF, diabetes, or anterior MI",
      "Eplerenone or spironolactone (MRA) post-MI if EF ≤40% with HF symptoms or diabetes",
      "GP IIb/IIIa inhibitors (eptifibatide, tirofiban) reserved for high-risk NSTEMI going to PCI with large thrombus burden",
    ],
    nonPharmacologic: [
      "Supplemental oxygen if SpO2 <90% — avoid routine O2 in normoxic patients (associated with harm)",
      "Continuous cardiac monitoring, IV access, 12-lead EKG within 10 min of presentation",
      "NPO for anticipated PCI; head of bed 30°",
      "Cardiac rehabilitation referral before discharge — reduces mortality by 25%",
      "Smoking cessation with pharmacotherapy",
      "Dietary counselling: Mediterranean-style diet; sodium restriction if HF present",
    ],
    whenToRefer: [
      "Interventional cardiology emergent referral for all STEMI (activate cath lab immediately)",
      "Cardiology for all NSTEMI — timing of invasive vs. conservative strategy determined by risk score",
      "CT surgery for CABG candidates (left main disease, multi-vessel disease with diabetes, failed PCI)",
      "Cardiac rehabilitation program referral at discharge",
    ],
    monitoringSchedule: [
      "Serial troponins every 3 hours x 2 sets to confirm/rule out MI (high-sensitivity troponin protocol)",
      "Repeat 12-lead EKG at 15–30 min after initial, then with any chest pain recurrence",
      "Daily BMP while hospitalised (electrolytes, creatinine, glucose)",
      "Lipid panel fasting within 24 h of admission (LDL most accurate within first 24 h)",
      "Follow-up echocardiogram at 6–12 weeks to reassess LVEF",
      "Cardiology outpatient follow-up within 1–2 weeks of discharge",
    ],
    patientEducation: [
      "Take all cardiac medications daily — never stop aspirin or P2Y12 inhibitor without consulting cardiologist (risk of stent thrombosis)",
      "DAPT duration: bare-metal stent: minimum 1 month; drug-eluting stent: minimum 6–12 months",
      "Call 911 for any recurrent chest pain, pressure, jaw/arm pain, or sudden shortness of breath",
      "No driving for 1 week post-PCI (48 h if uncomplicated and not on P2Y12 inhibitor)",
      "Cardiac rehabilitation significantly improves outcomes — enroll within 35 days of discharge",
      "Nitroglycerin SL 0.4 mg every 5 min x 3 for chest pain — if no relief after 3 doses, call 911",
    ],
  },
  {
    id: "im-gl-06",
    rotation: "internal-medicine",
    conditionName: "Atrial Fibrillation",
    guidelineName: "2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation",
    issuingOrganization: "ACC/AHA/ACCP/HRS",
    year: 2023,
    keyRecommendations: [
      "Classify AF: first-detected, paroxysmal (<7 days, self-terminating), persistent (>7 days), long-standing persistent (>12 months), permanent.",
      "Calculate CHA2DS2-VASc score for stroke risk: Congestive HF, Hypertension, Age ≥75 (2 pts), Diabetes, Stroke/TIA (2 pts), Vascular disease, Age 65–74, Sex category (female).",
      "Anticoagulation recommended for CHA2DS2-VASc ≥2 in males or ≥3 in females; consider for score 1 (male) or 2 (female).",
      "DOACs preferred over warfarin for non-valvular AF (all reduce stroke with lower ICH rates).",
      "Rhythm control preferred in younger symptomatic patients, HFrEF, or first-detected AF — catheter ablation now recommended earlier in the algorithm.",
      "Rate control target: resting HR <80 bpm for symptomatic patients; lenient target <110 bpm may be acceptable in asymptomatic, stable patients.",
    ],
    firstLine: [
      "Anticoagulation: apixaban 5 mg BID (2.5 mg BID if 2 of: age ≥80, weight ≤60 kg, Cr ≥1.5) or rivaroxaban 20 mg daily with evening meal",
      "Rate control: metoprolol tartrate/succinate or bisoprolol (preferred in HFrEF); diltiazem or verapamil (avoid in HFrEF with reduced EF)",
      "Rhythm control: cardioversion (DC or pharmacologic) after ≥3 weeks anticoagulation OR if <48 h onset with low thrombus risk confirmed on TEE",
    ],
    secondLine: [
      "Flecainide or propafenone for pill-in-pocket rhythm control in paroxysmal AF without structural heart disease",
      "Amiodarone for rhythm control in HFrEF or structural heart disease (most effective antiarrhythmic; significant toxicity profile)",
      "Dronedarone for paroxysmal/persistent AF with normal EF and no recent decompensated HF",
      "Digoxin as adjunct rate control agent (avoid in Wolff-Parkinson-White; narrow therapeutic window)",
    ],
    thirdLine: [
      "Catheter ablation (pulmonary vein isolation) — first-line rhythm control option in many symptomatic patients; superior to antiarrhythmic drugs for maintaining sinus rhythm",
      "Left atrial appendage occlusion (Watchman device) for patients with high stroke risk and contraindication to long-term anticoagulation",
      "AV node ablation + permanent pacemaker for rate control failure in permanent AF",
    ],
    nonPharmacologic: [
      "Weight loss: even 10% body weight reduction significantly reduces AF burden",
      "Treat underlying precipitants: hyperthyroidism, sleep apnea (CPAP), hypertension, alcohol reduction",
      "Moderate aerobic exercise — excessive endurance exercise is a risk factor for AF",
      "Alcohol cessation or strict limitation (even 1 drink/day increases AF risk by 8%)",
    ],
    whenToRefer: [
      "Cardiology/Electrophysiology for catheter ablation evaluation in symptomatic AF",
      "Cardiology for all new AF requiring cardioversion",
      "Hematology or anticoagulation clinic if complex anticoagulation management (antiphospholipid syndrome, mechanical valve)",
      "Sleep medicine for evaluation and treatment of OSA (comorbid in >30% of AF patients)",
    ],
    monitoringSchedule: [
      "INR weekly until therapeutic (2.0–3.0) x 2 consecutive readings, then monthly (warfarin)",
      "BMP (renal function, potassium) at baseline and every 6 months on anticoagulation",
      "Thyroid function (TSH) at diagnosis and annually — hyperthyroidism is reversible cause of AF",
      "Resting HR at every visit; Holter or event monitor to assess rhythm control efficacy",
      "Echocardiogram at baseline and with change in clinical status",
    ],
    patientEducation: [
      "Never stop anticoagulation without provider guidance — stroke risk increases dramatically within days of cessation",
      "DOACs must be taken every day — missing doses is not safe",
      "Report palpitations, dizziness, near-syncope, or worsening dyspnea promptly",
      "Alcohol, caffeine in excess, and stimulants may trigger AF episodes",
      "AF with rapid ventricular rate causing dyspnea or hypotension requires emergency evaluation",
      "Wear a medical ID bracelet indicating anticoagulant use",
    ],
  },
  {
    id: "im-gl-07",
    rotation: "internal-medicine",
    conditionName: "Stroke Prevention",
    guidelineName: "AHA/ASA Guidelines for the Prevention of Stroke in Patients with Stroke and TIA",
    issuingOrganization: "AHA/ASA",
    year: 2021,
    keyRecommendations: [
      "Secondary stroke prevention requires identifying stroke mechanism (cardioembolic, large-artery atherosclerosis, small-vessel, cryptogenic) to guide therapy.",
      "Antithrombotic therapy is the cornerstone of secondary prevention for non-cardioembolic stroke.",
      "For TIA or minor ischemic stroke: DAPT (aspirin + clopidogrel) for 21 days, then antiplatelet monotherapy (POINT/CHANCE trials).",
      "Cardioembolic stroke (AF): anticoagulation with DOAC — start 4–14 days after ischemic stroke (timing depends on stroke size/hemorrhagic transformation risk).",
      "Blood pressure control to <130/80 mmHg reduces recurrent stroke risk by 25–30%.",
      "High-intensity statin therapy initiated for all atherosclerotic ischemic stroke regardless of LDL level (target LDL reduction ≥50%).",
    ],
    firstLine: [
      "Non-cardioembolic stroke/TIA antiplatelet: aspirin 81–325 mg daily OR clopidogrel 75 mg daily",
      "TIA and minor ischemic stroke (within 24 h): aspirin 162–325 mg + clopidogrel 75 mg (with 300 mg loading dose) x 21 days then clopidogrel monotherapy (CHANCE/POINT protocol)",
      "Cardioembolic (AF): apixaban 5 mg BID or rivaroxaban 20 mg daily — start 4–14 days post-stroke",
      "High-intensity statin: atorvastatin 80 mg daily or rosuvastatin 40 mg daily",
    ],
    secondLine: [
      "Aspirin + extended-release dipyridamole (Aggrenox) 25/200 mg BID — alternative antiplatelet for non-cardioembolic stroke",
      "Warfarin (INR 2–3) for antiphospholipid antibody syndrome or mechanical heart valve (INR 2.5–3.5)",
      "Carotid endarterectomy (CEA) or carotid artery stenting (CAS) for ipsilateral carotid stenosis ≥70% — ideally within 2 weeks of TIA/minor stroke",
    ],
    thirdLine: [
      "Cilostazol alternative antiplatelet in Asian populations (from trial data)",
      "Ticagrelor as alternative to clopidogrel if clopidogrel resistance suspected (CYP2C19 poor metabolizer)",
      "PFO closure in select cryptogenic stroke patients age <60 with high-risk features",
    ],
    nonPharmacologic: [
      "Blood pressure control — DASH diet, sodium restriction, regular aerobic exercise",
      "Smoking cessation — stroke risk returns to near baseline within 5 years of cessation",
      "Diabetic management: A1c <7% reduces microvascular disease; aggressive glycemic control has not shown additional stroke risk reduction",
      "Dietary modifications: Mediterranean diet associated with reduced stroke recurrence",
      "Sleep apnea treatment (CPAP) in patients with OSA",
    ],
    whenToRefer: [
      "Neurology referral for all TIA/ischemic stroke within 24–48 h for secondary prevention workup",
      "Vascular surgery or neurointerventional for carotid stenosis evaluation (CEA vs. CAS)",
      "Hematology for hypercoagulable state evaluation in cryptogenic stroke, especially age <50",
      "Cardiology/Electrophysiology for cryptogenic stroke — prolonged cardiac monitoring (implantable loop recorder) to detect paroxysmal AF",
    ],
    monitoringSchedule: [
      "Blood pressure monitoring at every visit — home readings are valuable for titration",
      "Fasting lipid panel 4–6 weeks after statin initiation to confirm adequate LDL reduction",
      "HbA1c every 3 months if diabetes is present",
      "Antiplatelet adherence assessed at every visit — medication non-adherence is the leading cause of recurrent stroke",
      "Neurological follow-up within 1 week of TIA to complete workup (cardiac monitoring, vascular imaging)",
    ],
    patientEducation: [
      "Recognise FAST (Face drooping, Arm weakness, Speech difficulty, Time to call 911) and act immediately",
      "Never stop antiplatelet or anticoagulant medication without discussing with your provider",
      "Blood pressure and cholesterol control are the most modifiable stroke risk factors",
      "Diabetes management is critical — poorly controlled diabetes doubles stroke risk",
      "Report any new neurological symptoms — TIA is a medical emergency requiring same-day evaluation",
    ],
  },
  {
    id: "im-gl-08",
    rotation: "internal-medicine",
    conditionName: "Gout",
    guidelineName: "2020 ACR Guideline for the Management of Gout",
    issuingOrganization: "ACR (American College of Rheumatology)",
    year: 2020,
    keyRecommendations: [
      "Treat-to-target (T2T) strategy: titrate urate-lowering therapy (ULT) to serum uric acid (SUA) <6 mg/dL; target <5 mg/dL for patients with tophi or frequent flares.",
      "ULT should be initiated after the first gout flare in patients with: CKD stage ≥3, SUA ≥9 mg/dL, urolithiasis, or tophi.",
      "For most patients with recurrent flares (≥2/year), start ULT and continue indefinitely.",
      "Anti-inflammatory prophylaxis (colchicine or NSAID) should be co-prescribed for at least 3–6 months after initiating ULT to prevent mobilisation flares.",
      "Allopurinol is the preferred first-line ULT — start at low dose (100 mg daily; 50 mg in CKD) and titrate every 2–4 weeks.",
      "HLA-B*5801 testing recommended before allopurinol in Southeast Asian and Black patients due to risk of severe cutaneous adverse reactions (SCAR).",
    ],
    firstLine: [
      "Acute flare: colchicine 1.2 mg then 0.6 mg one hour later, then 0.6 mg BID until flare resolves (most effective if started within 24 h)",
      "Acute flare alternative: NSAID (indomethacin 50 mg TID or naproxen 500 mg BID) x 5–7 days with PPI",
      "ULT: allopurinol — start 100 mg daily, titrate by 100 mg every 2–4 weeks (max 800 mg/day) to SUA <6 mg/dL",
    ],
    secondLine: [
      "Febuxostat 40 mg daily titrated to 80 mg if SUA target not reached — 2nd line due to CV mortality signal (use with caution in established CVD)",
      "Oral prednisone 0.5 mg/kg/day x 5–10 days for acute flare when colchicine and NSAIDs contraindicated",
      "Pegloticase IV infusion for refractory/tophaceous gout with SUA >6 mg/dL on maximal conventional ULT",
      "Probenecid uricosuric agent (2nd line ULT in patients with underexcretion phenotype, eGFR >45, no urolithiasis)",
    ],
    thirdLine: [
      "IL-1 inhibitors (anakinra, canakinumab) for refractory acute gout when all other treatments contraindicated",
      "Intra-articular or intramuscular corticosteroid injection for monoarticular flare when systemic therapy contraindicated",
    ],
    nonPharmacologic: [
      "Dietary modifications: reduce purine-rich foods (red meat, organ meats, shellfish, high-fructose corn syrup)",
      "Alcohol limitation: avoid beer and spirits (moderate wine consumption less harmful)",
      "Adequate hydration: 2–3 L water daily to reduce uric acid crystal precipitation",
      "Weight loss in obese patients reduces SUA and flare frequency",
      "Low-fat dairy consumption associated with lower SUA levels",
    ],
    whenToRefer: [
      "Rheumatology for refractory gout, tophaceous gout unresponsive to conventional ULT, or consideration of pegloticase",
      "Nephrology if CKD significantly limits ULT choices or dosing",
      "Orthopedic surgery for tophus drainage or joint damage requiring intervention",
    ],
    monitoringSchedule: [
      "SUA level every 2–4 weeks during ULT dose titration until target achieved (<6 mg/dL)",
      "SUA every 6 months once at goal to ensure target maintained",
      "CBC, BMP (creatinine, LFTs) at baseline and every 6–12 months on allopurinol",
      "Febuxostat: monitor LFTs at baseline and periodically; cardiovascular risk assessment",
      "Colchicine: monitor CBC and creatinine every 6–12 months (toxicity risk with CKD)",
    ],
    patientEducation: [
      "Start colchicine at first sign of a flare — do not wait for flare to peak",
      "ULT must be taken daily without interruption — stopping causes SUA fluctuations and can trigger flares",
      "Flares may transiently worsen when starting ULT — this is expected and does not mean the medication is not working",
      "Dietary changes alone rarely achieve SUA <6 mg/dL; medication is almost always necessary",
      "Stay well-hydrated; avoid dehydration triggers (diuretics, excessive alcohol, strenuous exercise)",
      "Report any skin rash, especially while starting allopurinol — can rarely cause life-threatening DRESS syndrome",
    ],
  },
  {
    id: "im-gl-09",
    rotation: "internal-medicine",
    conditionName: "Sepsis",
    guidelineName: "Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2021",
    issuingOrganization: "Surviving Sepsis Campaign (SCCM/ESICM)",
    year: 2021,
    keyRecommendations: [
      "Sepsis-3 definition: life-threatening organ dysfunction caused by dysregulated host response to infection — use SOFA score (acute increase ≥2 points from baseline).",
      "Septic shock: sepsis PLUS vasopressor requirement to maintain MAP ≥65 mmHg AND serum lactate >2 mmol/L despite adequate fluid resuscitation.",
      "Initiate the 1-hour bundle: measure lactate, obtain blood cultures (x2) before antibiotics, administer broad-spectrum antibiotics, initiate IV fluid resuscitation.",
      "Blood cultures (2 sets from 2 different sites) must be collected before first antibiotic dose — do not delay antibiotics >45 min to obtain cultures.",
      "Broad-spectrum antibiotics should be administered within 1 hour of sepsis recognition.",
      "Reassess antibiotic therapy daily for de-escalation based on culture results, clinical improvement, and procalcitonin trending.",
    ],
    firstLine: [
      "IV crystalloid resuscitation: 30 mL/kg balanced crystalloid (lactated Ringer's preferred over normal saline) within 3 hours — reassess with dynamic fluid responsiveness measures",
      "Broad-spectrum antibiotics within 1 hour: piperacillin-tazobactam 4.5 g IV q8h + vancomycin 25–30 mg/kg IV for MRSA coverage in undifferentiated sepsis",
      "Vasopressor (if MAP <65 mmHg after fluids): norepinephrine 0.01–0.5 mcg/kg/min (first-line vasopressor in septic shock)",
    ],
    secondLine: [
      "Vasopressin 0.03 units/min added to norepinephrine (second vasopressor) to raise MAP or reduce norepinephrine dose",
      "Corticosteroids: hydrocortisone 200 mg/day continuous infusion or 50 mg IV q6h for septic shock requiring increasing vasopressors (not responsive to fluids and moderate-dose vasopressors)",
      "Thiamine 200 mg IV q12h in suspected thiamine deficiency (alcoholism, prolonged hospitalisation, malnutrition)",
    ],
    thirdLine: [
      "Epinephrine as third vasopressor for refractory septic shock",
      "Angiotensin II (Giapreza) as adjunctive vasopressor in high vasopressor requirements",
      "IVIG considered in streptococcal or staphylococcal toxic shock syndrome",
    ],
    nonPharmacologic: [
      "Source control: drain abscess, debride infected tissue, remove infected lines/catheters within 6–12 hours",
      "Lung-protective ventilation if mechanically ventilated: tidal volume 6 mL/kg IBW, plateau pressure <30 cmH2O",
      "Conservative fluid strategy after initial resuscitation — avoid fluid overload",
      "VTE prophylaxis with UFH or LMWH once coagulopathy corrected",
      "Glucose management: insulin infusion if blood glucose >180 mg/dL — target 140–180 mg/dL",
    ],
    whenToRefer: [
      "ICU admission for all septic shock patients and sepsis with acute organ dysfunction",
      "Infectious Disease consult for source identification, antibiotic stewardship, and management of resistant organisms",
      "Interventional Radiology for abscess drainage or infected fluid collection",
      "Surgery for surgical source control (perforated viscus, necrotising fasciitis, infected prosthetic material)",
    ],
    monitoringSchedule: [
      "Serum lactate at 2 hours — target >10% reduction from baseline; repeat at 4 hours if lactate still elevated",
      "Hourly urine output (Foley catheter) — target ≥0.5 mL/kg/h",
      "MAP monitoring continuously via arterial line in vasopressor-dependent patients",
      "Blood cultures x2 before antibiotics; follow up all positive results and adjust coverage",
      "Daily CBC, BMP, LFTs, PT/INR — organ function trend guides clinical decisions",
      "Procalcitonin serial measurements to guide antibiotic de-escalation (every 48–72 h)",
    ],
    patientEducation: [
      "Sepsis is a life-threatening emergency caused by the body's own response to infection",
      "Early treatment (antibiotics within 1 hour) dramatically improves survival — time is critical",
      "Post-sepsis syndrome is common: fatigue, cognitive difficulties, depression may persist months after discharge",
      "Vaccinations (flu, pneumococcal, COVID-19) help prevent infections that can lead to sepsis",
      "Recognise sepsis warning signs after discharge: high fever/chills, rapid heart rate, confusion, decreased urine output — go to ED immediately",
    ],
  },
  {
    id: "im-gl-10",
    rotation: "internal-medicine",
    conditionName: "Acute Kidney Injury",
    guidelineName: "KDIGO Clinical Practice Guideline for Acute Kidney Injury",
    issuingOrganization: "KDIGO (Kidney Disease: Improving Global Outcomes)",
    year: 2012,
    keyRecommendations: [
      "AKI definition: increase in serum creatinine ≥0.3 mg/dL within 48 h OR increase ≥1.5x baseline within 7 days OR urine output <0.5 mL/kg/h for ≥6 h.",
      "Staging: Stage 1 (Cr ≥0.3 or 1.5–1.9x; UO <0.5 mL/kg/h for 6–12 h), Stage 2 (Cr 2.0–2.9x; UO <0.5 for ≥12 h), Stage 3 (Cr ≥3.0x or ≥4 mg/dL or RRT; UO <0.3 for ≥24 h or anuria ≥12 h).",
      "Identify and treat the cause: pre-renal (volume depletion, low CO), intrinsic renal (ATN, glomerulonephritis, interstitial nephritis), post-renal (obstruction).",
      "FENa <1% suggests pre-renal cause; FENa >2% suggests intrinsic renal. FEUrea <35% more useful if recent diuretics given.",
      "Contrast-associated AKI: pre-hydration with isotonic saline; avoid nephrotoxins; minimise contrast volume.",
      "Renal replacement therapy (RRT) indications: severe metabolic acidosis, refractory hyperkalemia (K+ >6.5), volume overload unresponsive to diuretics, uremic symptoms (encephalopathy, pericarditis), drug toxicity.",
    ],
    firstLine: [
      "Fluid resuscitation with isotonic crystalloid (LR or NS) for pre-renal AKI — 250–500 mL IV bolus with reassessment",
      "Discontinue all nephrotoxic medications: NSAIDs, aminoglycosides, contrast agents, ACEi/ARB (hold until AKI resolved in hemodynamically unstable patients)",
      "Treat underlying cause: relieve urinary obstruction with Foley catheter or nephrostomy tube for post-renal AKI",
    ],
    secondLine: [
      "Loop diuretics (furosemide) to manage volume overload in AKI — not proven to improve outcomes or prevent need for RRT",
      "Vasopressors for hemodynamic instability contributing to pre-renal AKI (septic shock: norepinephrine)",
      "Sodium bicarbonate for severe metabolic acidosis (pH <7.15) as bridge to RRT or if RRT unavailable",
    ],
    thirdLine: [
      "Continuous renal replacement therapy (CRRT) preferred in hemodynamically unstable patients in ICU",
      "Intermittent hemodialysis (IHD) for hemodynamically stable patients with severe AKI",
      "Emergent dialysis for life-threatening hyperkalemia or uremic emergency",
    ],
    nonPharmacologic: [
      "Strict intake and output monitoring (Foley catheter in severe AKI)",
      "Daily weights to monitor fluid balance",
      "Dietary potassium restriction (<2 g/day) and phosphorus restriction if elevated",
      "Protein restriction (0.8–1.0 g/kg/day) in AKI without dialysis — avoid excessive restriction",
      "Avoid contrast and nephrotoxins until renal function recovered",
    ],
    whenToRefer: [
      "Nephrology consult for all Stage 2–3 AKI or when cause uncertain",
      "Emergent nephrology for AKI with severe hyperkalemia, uremia, or volume overload requiring RRT",
      "Urology for post-renal obstruction requiring nephrostomy or ureteral stent",
      "Rheumatology for rapidly progressive glomerulonephritis (RPGN) — requires urgent renal biopsy",
    ],
    monitoringSchedule: [
      "BMP every 6–12 hours in hospitalised AKI: creatinine, BUN, potassium, bicarbonate, phosphorus",
      "Strict hourly urine output via Foley catheter",
      "Daily weight and strict fluid balance",
      "EKG for hyperkalemia (peaked T waves, wide QRS, sine wave pattern) — treat emergently if present",
      "Nephrology follow-up within 2–4 weeks of discharge — 10–20% of AKI episodes do not fully recover",
    ],
    patientEducation: [
      "Kidney injury can often be reversed if treated quickly — report decreased urination or leg swelling promptly",
      "Avoid NSAIDs, ibuprofen, and naproxen — these reduce blood flow to the kidneys",
      "Stay well-hydrated, especially in hot weather, with illness, or before procedures requiring contrast",
      "Ask your doctor before starting any new medication — many drugs are harmful to kidneys",
      "Follow up with nephrology after discharge to ensure kidney function returns to baseline",
    ],
  },
  {
    id: "im-gl-11",
    rotation: "internal-medicine",
    conditionName: "Chronic Kidney Disease",
    guidelineName: "KDIGO 2022 Clinical Practice Guideline for Evaluation and Management of CKD",
    issuingOrganization: "KDIGO (Kidney Disease: Improving Global Outcomes)",
    year: 2022,
    keyRecommendations: [
      "CKD defined by GFR <60 mL/min/1.73m² OR markers of kidney damage (albuminuria, hematuria, structural abnormalities) for >3 months.",
      "Stage by GFR (G1–G5) AND albuminuria category (A1: <30, A2: 30–300, A3: >300 mg/g creatinine) — both determine prognosis and management intensity.",
      "RAAS inhibition (ACEi or ARB) recommended for CKD with diabetes and albuminuria A2–A3 (eGFR ≥25 mL/min).",
      "SGLT2 inhibitors (dapagliflozin) strongly recommended for CKD with or without diabetes with uACR ≥200 mg/g (or heart failure comorbidity) to reduce CKD progression and cardiovascular events.",
      "Blood pressure target: <120/80 mmHg (intensive) per SPRINT criteria — pragmatic target <130/80 mmHg.",
      "Refer to nephrology when eGFR <30 mL/min/1.73m², rapid progression (decline >5 mL/min/year), or diagnostic uncertainty.",
    ],
    firstLine: [
      "RAAS blockade: ACE inhibitor (lisinopril) or ARB (losartan) for CKD with proteinuria — do not combine ACEi + ARB",
      "SGLT2 inhibitor: dapagliflozin 10 mg daily for CKD (eGFR ≥25 mL/min) with uACR ≥200 mg/g",
      "BP control: amlodipine or chlorthalidone as adjunct antihypertensives if RAAS therapy alone insufficient",
      "Statin therapy for all CKD patients ≥50 years (or younger with additional CV risk)",
    ],
    secondLine: [
      "Finerenone (non-steroidal MRA) for diabetic CKD with uACR ≥30 mg/g on maximally tolerated RAAS therapy — reduces CKD progression and CV events",
      "Loop diuretic (furosemide) for volume overload in CKD — thiazides less effective when eGFR <30",
      "GLP-1 receptor agonists (semaglutide) for diabetic CKD — additional cardiorenal protective benefit",
    ],
    thirdLine: [
      "Erythropoiesis-stimulating agents (ESAs) for CKD anemia with Hgb <10 g/dL — target Hgb 10–11.5 g/dL (avoid >13 g/dL; increased stroke/thrombosis risk)",
      "IV iron supplementation preferred over oral for CKD on dialysis; oral iron for non-dialysis CKD if tolerated",
      "Phosphate binders (calcium carbonate, sevelamer) for hyperphosphatemia in CKD Stage 4–5",
    ],
    nonPharmacologic: [
      "Protein restriction: 0.6–0.8 g/kg/day for non-dialysis CKD to reduce progression; 1.0–1.2 g/kg/day for dialysis patients",
      "Sodium restriction: <2 g/day to control BP and reduce proteinuria",
      "Potassium restriction: <2 g/day if hyperkalemic tendency",
      "Phosphorus restriction in advanced CKD (stage 4–5): limit dairy, processed foods, dark colas",
      "Regular aerobic exercise (150 min/week) — improves CV outcomes and slows CKD progression",
    ],
    whenToRefer: [
      "Nephrology referral when eGFR <30 mL/min (G4–G5) — prepare for renal replacement therapy planning",
      "Nephrology for rapid GFR decline (>5 mL/min/year), unexplained AKI on CKD, or diagnostic uncertainty",
      "Transplant evaluation when eGFR approaches 20 mL/min — early referral improves access to pre-emptive transplantation",
      "Endocrinology for complex diabetic management in CKD (insulin dosing adjustments, medication safety)",
    ],
    monitoringSchedule: [
      "eGFR and uACR every 3 months for CKD G4–G5 or A3; every 6 months for G3/A2; annually for G1–G2/A1",
      "BMP: potassium and creatinine within 1–2 weeks of initiating or dose-adjusting RAAS therapy or SGLT2i",
      "CBC for anemia evaluation every 3–6 months in CKD Stage 3b–5",
      "PTH, calcium, phosphorus, and 25-OH vitamin D annually beginning in CKD Stage 3",
      "Fasting lipid panel annually",
    ],
    patientEducation: [
      "CKD is usually irreversible but progression can be significantly slowed with medications and lifestyle changes",
      "Controlling blood pressure and blood sugar are the most important strategies to protect kidney function",
      "Avoid NSAIDs, ibuprofen, and naproxen — they worsen kidney function even with short-term use",
      "Stay hydrated but do not overhydrate — follow fluid guidance from your nephrologist",
      "A kidney dietitian referral is recommended — diet management is critical in advanced CKD",
      "Discuss dialysis and transplantation options early — preparation takes months to years",
    ],
  },
  {
    id: "im-gl-12",
    rotation: "internal-medicine",
    conditionName: "Diabetic Ketoacidosis (DKA)",
    guidelineName: "ADA Standards of Medical Care in Diabetes – DKA Management Protocol",
    issuingOrganization: "ADA (American Diabetes Association)",
    year: 2023,
    keyRecommendations: [
      "DKA diagnostic criteria: blood glucose >250 mg/dL, arterial pH <7.3 (or venous pH <7.35), serum bicarbonate <18 mEq/L, and moderate or greater ketonemia/ketonuria.",
      "Three main management pillars: (1) IV fluid resuscitation, (2) insulin infusion, (3) electrolyte replacement — especially potassium.",
      "Do NOT start insulin until potassium ≥3.5 mEq/L — hypokalemia worsens dramatically with insulin therapy.",
      "Anion gap = Na – (Cl + HCO3); normal 8–12. Calculate corrected sodium: measured Na + 1.6 × [(glucose – 100)/100].",
      "Resolution criteria: glucose <200 mg/dL AND (HCO3 ≥15 OR venous pH >7.3 OR anion gap ≤12) — do not rely on glucose normalisation alone.",
      "Continue IV insulin infusion for 1–2 hours after first SQ dose to prevent gap reopening (insulin overlap).",
    ],
    firstLine: [
      "IV fluid: 1 L NS over 1 hour initially; then 0.45% NaCl at 250–500 mL/h or 0.9% NaCl 250–500 mL/h based on corrected Na+ — switch to D5W 0.45% NaCl when glucose <200–250 mg/dL",
      "Potassium replacement: if K+ 3.5–5.0 mEq/L, add 20–40 mEq KCl/L to IV fluids; replace K+ before insulin if <3.5 mEq/L",
      "Insulin: regular insulin infusion at 0.1 units/kg/h (after potassium ≥3.5); titrate to decrease glucose by 50–75 mg/dL/h",
    ],
    secondLine: [
      "Bicarbonate therapy: only if pH <6.9 — 100 mEq NaHCO3 in 400 mL water + 20 mEq KCl over 2 h; repeat pH in 2 h — routine use is not recommended and may worsen hypokalemia",
      "Phosphate replacement only if PO4 <1 mg/dL with cardiac dysfunction or respiratory compromise — routine replacement not indicated",
      "Transition to subcutaneous insulin when DKA resolved and patient tolerating oral intake: give SQ dose 1–2 hours before stopping insulin infusion",
    ],
    thirdLine: [
      "Identify and treat precipitating cause: infection (obtain cultures, start antibiotics), medication non-adherence, new T1DM diagnosis, SGLT2 inhibitor-associated euglycemic DKA",
      "ICU level care for altered mental status, pH <7.0, or haemodynamic instability",
    ],
    nonPharmacologic: [
      "Nil by mouth initially — advance to oral diet when nausea resolves and mental status clear",
      "Cardiac monitoring (telemetry) for potassium and EKG changes (peaked T waves in hyperkalemia, flat T, U waves in hypokalemia)",
      "Foley catheter for strict urine output monitoring in obtunded patients",
      "Hourly blood glucose monitoring during insulin infusion",
      "Frequent neurological assessments — cerebral oedema is a rare but life-threatening complication, especially in children",
    ],
    whenToRefer: [
      "ICU transfer for severe DKA (pH <7.0, AMS, haemodynamic instability, respiratory failure)",
      "Endocrinology consult for new T1DM diagnosis, recurrent DKA (medication adherence, insulin regimen optimisation), or technology-based diabetes management (insulin pump)",
      "Nephrology if significant AKI persists after fluid resuscitation",
      "Social work/diabetes education for patients with barriers to medication access or adherence",
    ],
    monitoringSchedule: [
      "Blood glucose every hour during insulin infusion",
      "BMP (Na, K, Cl, HCO3, BUN, Cr, glucose) every 2–4 hours until anion gap closed",
      "Venous blood gas every 2–4 hours (pH, bicarbonate) — anion gap closure more important than pH normalisation",
      "Serum ketones at baseline and every 4 hours until resolved",
      "Phosphorus and magnesium at baseline — replace if critically low",
      "EKG at baseline and with potassium abnormalities",
    ],
    patientEducation: [
      "Never stop insulin entirely when sick — 'sick day rules': take basal insulin, check ketones, stay hydrated",
      "Know the warning signs of DKA: nausea/vomiting, abdominal pain, fruity breath, excessive thirst, confusion",
      "Keep a glucagon kit and ketone test strips at home",
      "Contact your provider immediately if glucose >250 mg/dL with positive urine/serum ketones",
      "Identify personal DKA triggers: illness, stress, missed insulin — have a clear sick-day action plan",
      "Follow up with endocrinology within 1 week of hospitalisation — review insulin regimen and identify prevention strategies",
    ],
  },
];
