// @ts-nocheck
import { PhysicalExamFinding } from "@/types/seed";

export const womensHealthPhysicalExam: PhysicalExamFinding[] = [
  {
    id: "wh-pe-001",
    rotation: "womens-health",
    findingName: "Pelvic Examination (Complete)",
    description:
      "The complete pelvic examination includes four components: external genitalia inspection, speculum examination with cervical visualization, bimanual examination, and rectovaginal examination. It is essential for evaluating gynecologic complaints, performing cervical cancer screening, assessing pelvic organ prolapse, and evaluating pelvic pain, vaginal discharge, or abnormal bleeding. Consent, patient positioning (dorsal lithotomy), adequate lighting, and a warm speculum are foundational to a successful and comfortable exam.",
    technique:
      "1. External inspection: examine the mons pubis, labia majora, labia minora, clitoris, urethral meatus, vaginal introitus, perineum, and perianal region for lesions, discoloration, atrophy, excoriation, or masses. 2. Speculum exam: select appropriate speculum (Graves for multiparous patients — wider blades; Pederson for nulliparous, adolescent, or post-menopausal patients — narrower blades); insert with blades closed in oblique orientation, rotate to horizontal, and gently open to visualize the cervix. Note cervical appearance, os shape (nulliparous = small, round; multiparous = fish-mouth/slit), discharge (color, consistency, odor), lesions, polyps, or ectropion. Collect specimens for Pap smear, GC/chlamydia NAAT, or wet prep as indicated before removing speculum. 3. Bimanual exam: lubricate gloved index and middle fingers and insert into vagina; place other hand on lower abdomen; palpate uterus for size (normal = 8 cm, pear-shaped), position (anteverted, anteflexed is normal; retroverted is a normal variant in 20%), consistency (soft in pregnancy — Hegar's sign at 6–8 weeks), mobility, and tenderness; sweep adnexa bilaterally to assess ovaries (normally walnut-sized, slightly tender, mobile) and detect masses. 4. Rectovaginal exam: insert index finger into vagina and middle finger into rectum simultaneously; assess uterosacral ligaments (nodularity suggests endometriosis), posterior uterine wall, rectovaginal septum, cul-de-sac, and rectal mucosa; evaluate for masses, tenderness, or induration.",
    normalFindings:
      "External genitalia without lesions, atrophy consistent with age, normal pubic hair distribution. Vaginal mucosa pink and moist, rugated. Cervix smooth, pink, small round (nulliparous) or fish-mouth (multiparous) os, no discharge or lesions. Uterus anteverted, firm, normal size (non-pregnant: 7–8 cm), non-tender, freely mobile. Ovaries approximately 3 × 2 × 2 cm, slightly tender to palpation, no masses. Adnexa without fullness or discrete masses. Rectovaginal septum smooth, no nodularity on uterosacral ligaments.",
    abnormalFindings: [
      "PID: uterine tenderness, cervical motion tenderness (CMT), bilateral adnexal tenderness; purulent cervical discharge; fever; elevated WBC — classic triad must have at least one element present",
      "Ovarian cyst: unilateral adnexal fullness or discrete mass; may be tender (hemorrhagic cyst, torsion) or non-tender (functional cyst, benign teratoma); requires ultrasound characterization",
      "Uterine fibroids (leiomyomata): enlarged, irregular, firm ('lumpy-bumpy') uterus; non-tender unless degenerating; uterus may be significantly enlarged (12–18+ weeks size); submucosal fibroids may not be palpable",
      "Pregnancy: soft, globular uterus; fundal height palpable above pubic symphysis after ~12 weeks; bluish-purple cervical and vaginal discoloration (Chadwick's sign); cervical softening (Goodell's sign at 4–6 weeks); uterine isthmus softening (Hegar's sign at 6–8 weeks)",
      "Endometriosis: nodularity on uterosacral ligaments on rectovaginal exam; fixed retroverted uterus; adnexal tenderness or mass (endometrioma); tenderness worsened pre-menstrually",
      "Cervical polyp: smooth, red, pedunculated protrusion from cervical os — often causes post-coital spotting; usually benign but should be removed and sent for pathology",
      "Vaginal atrophy (genitourinary syndrome of menopause): pale, smooth, thin vaginal epithelium; loss of rugae; introital narrowing; cervix may be flush with vaginal vault; pH > 5",
    ],
    clinicalPearl:
      "Always palpate the adnexa before moving to the contralateral side; adnexal tenderness that is clearly unilateral is more suspicious for ovarian pathology or ectopic pregnancy than bilateral tenderness, which is more consistent with PID. A retroverted uterus is a normal anatomic variant found in ~20% of women but can cause dyspareunia and be mistaken for adnexal pathology on bimanual exam — ultrasound clarifies anatomy when uncertain.",
    boardRecallTip:
      "Graves speculum = multiparous; Pederson = nulliparous/postmenopausal. Hegar's sign = softening of uterine isthmus (pregnancy). Chadwick's sign = blue-purple cervix/vagina (pregnancy). CMT (chandelier sign) = PID. Nodularity on uterosacral ligaments = endometriosis.",
  },
  {
    id: "wh-pe-002",
    rotation: "womens-health",
    findingName: "Cervical Motion Tenderness (CMT) and PID Assessment",
    description:
      "Cervical motion tenderness (CMT), colloquially called the 'chandelier sign' because patients jump toward the chandelier in pain, is a hallmark finding of pelvic inflammatory disease (PID). PID is an ascending infection of the upper genital tract (endometrium, fallopian tubes, ovaries, parametria) most commonly caused by Neisseria gonorrhoeae and Chlamydia trachomatis, although polymicrobial infection including anaerobes, G. vaginalis, and enteric organisms is increasingly recognized. Untreated PID leads to tubo-ovarian abscess (TOA), ectopic pregnancy, chronic pelvic pain, and infertility.",
    technique:
      "1. With the patient in lithotomy position and after speculum exam (collect GC/chlamydia NAAT swabs), perform bimanual examination. 2. Gently grasp the cervix between the examining fingers and move it side to side (laterally) and anteroposteriorly. 3. CMT is present when this motion elicits significant pain. 4. Assess uterine tenderness by applying upward pressure on the uterine fundus. 5. Assess adnexal tenderness by sweeping each adnexal region and noting if there is pain or fullness. 6. CDC minimum diagnostic criteria for PID (empiric treatment should be initiated if at least one of the following is present in a sexually active patient with no other identifiable cause): CMT, OR uterine tenderness, OR adnexal tenderness. 7. Additional supportive criteria that increase specificity: oral temperature > 38.3°C, cervical mucopurulent discharge, abundant WBCs on saline microscopy of vaginal secretions, elevated CRP or ESR, documented gonorrhea or chlamydia infection. 8. For suspected TOA: obtain pelvic ultrasound (transvaginal preferred) to identify complex adnexal mass with thick-walled ring and internal echoes.",
    normalFindings:
      "No pain or minimal discomfort with lateral or anterior-posterior cervical motion. Uterus non-tender with bimanual palpation. Adnexa without tenderness or palpable masses. Cervical os closed with no mucopurulent discharge.",
    abnormalFindings: [
      "CMT (cervical motion tenderness): significant pain with cervical manipulation — minimum criterion for empiric PID treatment per CDC when combined with appropriate clinical context",
      "Mucopurulent cervical discharge: yellow-green discharge from cervical os; may be associated with N. gonorrhoeae or C. trachomatis cervicitis; presence increases specificity for PID",
      "Tubo-ovarian abscess (TOA): palpable adnexal mass (often tender, unilateral or bilateral), fever, elevated WBC; on transvaginal US — complex thick-walled adnexal mass with internal echoes and debris; requires inpatient IV antibiotics (clindamycin + gentamicin); if no clinical improvement in 72 hours, consider CT-guided drainage or surgical intervention",
      "Fitz-Hugh-Curtis syndrome (perihepatitis): right upper quadrant pain (pleuritic chest pain at times) caused by perihepatic inflammation from ascending PID; may precede or accompany pelvic symptoms; LFTs typically normal; CT or laparoscopy shows 'violin string' adhesions between liver capsule and anterior abdominal wall",
      "Endometritis: uterine tenderness in the absence of adnexal findings; fever, abnormal uterine bleeding, or foul vaginal discharge; particularly common in the postpartum setting or after instrumentation",
    ],
    clinicalPearl:
      "The CDC recommends treating empirically for PID if any one of the minimum criteria is present and no other cause is identified — the threshold for treatment is intentionally low because the consequences of untreated PID (infertility, chronic pain, ectopic pregnancy) far outweigh the risk of over-treating. Outpatient PID treatment: ceftriaxone 500 mg IM single dose + doxycycline 100 mg PO BID × 14 days + metronidazole 500 mg PO BID × 14 days. Admit for IV therapy if: TOA, pregnancy, failed outpatient therapy, unable to tolerate oral medications, or surgical emergency cannot be excluded.",
    boardRecallTip:
      "CDC minimum PID criteria (need only 1): CMT OR uterine tenderness OR adnexal tenderness — treat empirically. TOA → IV clindamycin + gentamicin. Fitz-Hugh-Curtis = perihepatic 'violin string' adhesions from ascending PID = RUQ pain. Outpatient: ceftriaxone + doxycycline + metronidazole × 14 days.",
  },
  {
    id: "wh-pe-003",
    rotation: "womens-health",
    findingName: "Obstetric Abdominal Examination",
    description:
      "The obstetric abdominal examination is performed at every prenatal visit from approximately 16–20 weeks gestation onward. It includes fundal height measurement, Leopold's maneuvers to assess fetal presentation and position, and auscultation of fetal heart tones. These findings track fetal growth, identify malpresentations requiring further evaluation, and confirm fetal well-being. Consistent technique and serial measurements are more valuable than any single data point.",
    technique:
      "1. Fundal height (FH): with the patient supine (slightly left lateral tilt after 20 weeks to avoid aortocaval compression), place the zero end of a tape measure at the pubic symphysis and measure to the top of the uterine fundus in centimeters. Normal: FH in cm approximates gestational age in weeks between 20–38 weeks (e.g., 28 cm = approximately 28 weeks). Perform with a consistent examiner and technique — inter-examiner variability is significant. 2. Leopold's Maneuvers (4 maneuvers): Maneuver 1 (Fundal Grip): face the patient's head; palpate the fundus with both hands to identify fetal part (smooth, round, ballottable = fetal head; irregular, softer = breech/buttocks). Maneuver 2 (Umbilical Grip): slide hands down both sides of the uterus; identify the fetal back (firm, smooth, resistance) on one side and fetal small parts/extremities (irregular, knobby) on the other — determines fetal lie (longitudinal vs transverse) and position (back on maternal left vs right). Maneuver 3 (Pawlik's Grip): grasp the lower uterine segment between thumb and index finger just above the symphysis; identify presenting part — ballottable (unengaged) vs fixed (engaged). Maneuver 4 (Pelvic Grip): face the patient's feet; place both hands on the lower uterine segment pointing toward the pelvis; feel for the cephalic prominence — if hands converge = occiput posterior position; if hands diverge = occiput anterior. 3. Fetal heart tones (FHT): Doppler ultrasound detects FHT at 10–12 weeks gestation; fetoscope (Pinard horn) or stethoscope detects at 18–20 weeks. Normal FHR 110–160 bpm. Auscultate in the quadrant where the fetal back is located (Leopold's 2nd maneuver). 4. Document findings: FH, fetal lie, presentation (vertex/cephalic, breech, transverse/shoulder), position, engagement (floating/unengaged vs engaged), and FHR.",
    normalFindings:
      "Fundal height within 2 cm of gestational age in weeks (20–38 weeks). Longitudinal lie with vertex (cephalic) presentation in > 96% of term pregnancies. Fetal back felt as firm resistance on one side. Presenting part (vertex) felt in lower uterine segment, engaged or floating. FHR 110–160 bpm, regular. Single fetus confirmed by clinical examination (though ultrasound is definitive).",
    abnormalFindings: [
      "Fundal height lagging > 2 cm below gestational age: suggests intrauterine growth restriction (IUGR/FGR) — refer for growth ultrasound and umbilical artery Doppler; also consider oligohydramnios, incorrect dating",
      "Fundal height exceeding gestational age by > 2 cm: suggests fetal macrosomia, polyhydramnios (amniotic fluid index > 24 cm), multiple gestation, or incorrect dating — refer for ultrasound evaluation",
      "Non-vertex presentation at or beyond 36 weeks: breech (frank breech — hips flexed, knees extended, most common; complete breech — hips and knees flexed; footling breech — foot presenting), transverse lie — discuss external cephalic version (ECV) at 36–37 weeks if no contraindications; C-section for persistent breech at term in most centers",
      "Absent or abnormal fetal heart tones: FHR < 110 bpm (bradycardia) or > 160 bpm (tachycardia) requires further evaluation; absent FHT at expected gestation requires urgent ultrasound to confirm viability",
      "Asymmetric or irregular fundal contour: may indicate uterine fibroids, fetal malposition, or uterine anomaly",
    ],
    clinicalPearl:
      "The 'rule of thumb' — FH in cm = weeks of gestation — applies only between 20 and 38 weeks; after 38 weeks FH may plateau or decrease as the fetal head engages into the pelvis. Discordance between FH and gestational age of > 3 cm (lagging or excess) by consistent measurement warrants ultrasound, but a single measurement discordance of 1–2 cm is clinically acceptable. External cephalic version (ECV) for breech presentation is most successful at 37 weeks, has a 50–60% success rate, and significantly reduces the cesarean delivery rate.",
    boardRecallTip:
      "FH (cm) = weeks gestation 20–38 weeks. FH lagging > 2 cm = IUGR/oligohydramnios. FH excess > 2 cm = macrosomia/polyhydramnios/twins. Leopold's: 1st = identify fundal pole; 2nd = fetal back; 3rd = presenting part; 4th = flexion/engagement. Doppler FHT at 10–12 weeks; fetoscope at 18–20 weeks.",
  },
  {
    id: "wh-pe-004",
    rotation: "womens-health",
    findingName: "Breast Examination",
    description:
      "The clinical breast examination (CBE) is a systematic physical examination of the breast tissue, nipple-areolar complex, and regional lymph nodes. While its role as a standalone screening tool is debated, CBE remains clinically important for evaluating symptomatic patients presenting with a breast mass, nipple discharge, skin changes, or pain. It complements radiologic imaging and is essential for characterizing lesions identified on mammography or ultrasound. Proper technique, systematic coverage, and accurate documentation of findings are critical for clinical and medicolegal purposes.",
    technique:
      "1. Patient positioning: (a) Upright seated — inspect both breasts with arms at sides, hands pressed on hips (contracts pectoralis), and arms raised above head. (b) Supine with ipsilateral arm raised above head and a folded towel under the ipsilateral shoulder (flattens breast tissue). 2. Visual inspection (seated): compare breast size, symmetry, shape, skin changes, nipple position, and discharge. Look for skin dimpling, nipple retraction, erythema, edema, scaling, or ulceration. 3. Palpation technique (supine): use the vertical strip (lawnmower) technique covering from the clavicle to the inframammary fold, from the sternum to the posterior axillary line. Use the pads (not tips) of the 2nd, 3rd, and 4th fingers in small circular motions at three depths (superficial, intermediate, deep). Include the axillary tail (tail of Spence). Apply continuous overlapping circular motions without lifting fingers off the skin. 4. Nipple examination: gently compress the nipple between two fingers to assess for discharge; if discharge present, note color (clear, milky, serous, bloody), laterality (unilateral vs bilateral), and whether spontaneous or expressible. 5. Lymph node examination: examine ipsilateral axillary (anterior/pectoral, central, posterior/subscapular, lateral/brachial, apical) and supraclavicular nodes; support the patient's arm with your non-examining hand to relax pectoral muscles; note size, consistency, mobility, and tenderness. 6. Document any mass: size (cm), location (clock position and distance from nipple), depth, consistency (soft/firm/hard/rubbery), shape (round/irregular), mobility (freely mobile/fixed to skin/fixed to chest wall), tenderness, and associated skin changes.",
    normalFindings:
      "Symmetric breast tissue, no skin dimpling, no nipple retraction, no discharge. Breast tissue varies with menstrual cycle — often more nodular and tender pre-menstrually (fibrocystic changes). No dominant discrete mass. No axillary, supraclavicular, or infraclavicular lymphadenopathy. Nipples everted bilaterally (congenitally inverted nipples are a normal variant if longstanding).",
    abnormalFindings: [
      "Peau d'orange (orange peel skin): skin edema with follicular dimpling resembling orange peel; caused by dermal lymphatic invasion by carcinoma (inflammatory breast cancer) or obstruction of cutaneous lymphatics; highly suspicious for malignancy",
      "Nipple retraction (new onset): skin/duct tethering from underlying malignancy; distinguishable from congenital inversion (bilateral, longstanding) — new unilateral nipple retraction requires urgent evaluation with mammogram and ultrasound",
      "Paget's disease of the nipple: eczematous, erythematous, scaling, crusting of the nipple-areolar complex; caused by underlying ductal carcinoma in situ (DCIS) or invasive cancer extending to the skin; does not respond to topical steroid — biopsy required",
      "Malignant mass characteristics: hard, irregular, poorly defined borders, fixed to skin or chest wall, non-tender, skin dimpling or tethering, associated lymphadenopathy — requires biopsy regardless of imaging",
      "Benign mass characteristics: soft to firm, smooth, well-circumscribed, freely mobile, may be tender (especially pre-menstrually); fibroadenoma (young women — firm, rubbery, mobile 'breast mouse'), fibrocystic changes (bilateral, lumpy, tender, worse pre-menstrually), simple cyst (fluctuant, compressible)",
      "Bloody or unilateral spontaneous nipple discharge: concerning for intraductal papilloma (most common benign cause) or DCIS/carcinoma; requires cytology and imaging; milky bilateral discharge = galactorrhea (check prolactin and TSH)",
    ],
    clinicalPearl:
      "Any new, dominant, discrete breast mass in a woman of any age requires triple assessment: clinical breast examination, breast imaging (mammogram ± ultrasound), and tissue diagnosis (fine needle aspiration or core needle biopsy). A negative mammogram does NOT exclude malignancy in a patient with a suspicious mass — a palpable mass with negative imaging still requires biopsy. The risk of malignancy in a palpable mass with negative mammogram is approximately 3%, which is clinically unacceptable without tissue diagnosis.",
    boardRecallTip:
      "Triple assessment for any breast mass: CBE + imaging + tissue biopsy. Peau d'orange = inflammatory breast cancer (dermal lymphatic invasion). Paget's nipple = DCIS. New nipple retraction = malignancy until proven otherwise. Malignant = hard/fixed/irregular. Benign = soft/mobile/smooth (fibroadenoma). Bloody discharge = papilloma or DCIS.",
  },
  {
    id: "wh-pe-005",
    rotation: "womens-health",
    findingName: "Assessment of Cervical Dilation and Bishop Score",
    description:
      "Cervical examination in late pregnancy assesses the readiness of the cervix for labor — its 'ripeness' or favorability for induction. The Bishop score is a standardized scoring system that quantifies cervical findings to predict the likelihood of successful labor induction. A favorable cervix (Bishop score ≥ 6) suggests the patient will progress well with oxytocin induction. An unfavorable cervix (Bishop score < 6) requires cervical ripening before or concurrent with oxytocin augmentation. Digital cervical exam is also used to assess active labor progress and to perform amniotomy.",
    technique:
      "1. Obtain consent and ensure the patient has an empty bladder. 2. Position patient in dorsal lithotomy. 3. With a sterile glove and water-soluble lubricant, insert the index and middle fingers gently into the vagina toward the posterior fornix. 4. Locate the cervix — posterior in early labor (pointing toward the sacrum), mid or anterior as labor progresses. 5. Assess FIVE Bishop score components: (a) DILATION: assess the internal os opening — 0 = closed; 1 = 1–2 cm; 2 = 3–4 cm; 3 = ≥ 5 cm. (b) EFFACEMENT: estimate percentage of cervical shortening relative to uneffaced length (~3–4 cm) — 0 = 0–30%; 1 = 40–50%; 2 = 60–70%; 3 = ≥ 80%. (c) STATION: assess level of presenting part relative to ischial spines — 0 = −3; 1 = −2; 2 = −1 to 0; 3 = +1 to +2. (d) CONSISTENCY: 0 = firm; 1 = medium; 2 = soft. (e) POSITION: 0 = posterior; 1 = mid; 2 = anterior. 6. Total the score (maximum 13). 7. For active labor: confirm presentation and position, note any cord or fetal parts. 8. Note: avoid digital exam if placenta previa is suspected (risk of hemorrhage) or preterm premature rupture of membranes (PPROM) if not in active labor (infection risk).",
    normalFindings:
      "Term (≥ 39 weeks) nulliparous patient at 36 weeks: cervix typically posterior, firm, 0% effaced, closed, at -3 station (Bishop score 0–2, unfavorable). Term multiparous patient may have a more favorable cervix (1–2 cm dilated, partially effaced) without being in labor. Active labor is defined as regular contractions with cervical change at ≥ 6 cm in the active phase (per ACOG 2014 labor guidelines).",
    abnormalFindings: [
      "Bishop score < 6 (unfavorable cervix): cervical ripening recommended before oxytocin induction — pharmacologic options include prostaglandin E2 (dinoprostone gel/insert — Cervidil/Prepidil) or misoprostol (PGE1) 25 mcg vaginally q4 hours; mechanical options include Foley balloon catheter or osmotic dilators (laminaria); note: misoprostol contraindicated with prior uterine scar (VBAC attempt) due to uterine rupture risk",
      "Bishop score ≥ 8 in nulliparous or ≥ 6 in multiparous: favorable cervix — proceed with oxytocin induction; success rate similar to spontaneous labor",
      "Arrested active phase: no cervical change for ≥ 6 hours with adequate contractions (≥ 200 Montevideo units), or ≥ 4 hours with inadequate contractions — diagnose labor arrest; consider operative vaginal delivery or cesarean delivery",
      "Arrested second stage: no descent with pushing for ≥ 3 hours (nulliparous with epidural), ≥ 2 hours (multiparous with epidural) — consider operative vaginal delivery (vacuum or forceps) or cesarean",
      "Cervical dilation in preterm: painless cervical dilation < 37 weeks (especially if associated with bulging membranes) = cervical insufficiency — consider cervical cerclage if < 24 weeks with prior history; if in active preterm labor, administer betamethasone (< 34 weeks), magnesium sulfate for neuroprotection (< 32 weeks), consider tocolysis",
    ],
    clinicalPearl:
      "The Bishop score was originally developed to predict the success of elective induction and remains clinically useful, though its predictive value for labor outcome is moderate at best. A Bishop score of ≥ 6 is generally considered favorable, but multiparous patients with a score of 4–5 often progress well with oxytocin alone. Never perform a digital cervical exam in a patient with painless vaginal bleeding until placenta previa has been excluded by ultrasound — a digital exam through a previa can trigger catastrophic hemorrhage.",
    boardRecallTip:
      "Bishop score components: Dilation (0–3) + Effacement (0–3) + Station (0–3) + Consistency (0–2) + Position (0–2) = max 13. Score ≥ 6 = favorable (induce with oxytocin). Score < 6 = ripen cervix first (misoprostol/Cervidil). NO digital exam with placenta previa. Misoprostol contraindicated with prior uterine scar (rupture risk).",
  },
];
