// @ts-nocheck
import type { QuizQuestion } from "@/types";

export const womensHealthQuiz: QuizQuestion[] = [
  {
    id: "wh-q-001",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 28-year-old woman at 36 weeks gestation presents with a BP of 158/104 mmHg on two readings 4 hours apart, severe headache, and 2+ proteinuria on dipstick. She has no prior history of hypertension. Which of the following is the most appropriate next step in management?",
    options: [
      { label: "A", text: "Administer oral labetalol and discharge home with close outpatient follow-up in 48 hours" },
      { label: "B", text: "Administer magnesium sulfate 4g IV loading dose and initiate delivery planning" },
      { label: "C", text: "Obtain 24-hour urine protein and repeat BP in one week" },
      { label: "D", text: "Start oral nifedipine and schedule repeat BP check in 2 days" },
    ],
    correctAnswer: "B",
    explanation: "This patient has preeclampsia with severe features (BP ≥ 160/110 mmHg on two readings ≥ 4 hours apart, severe headache). At 36 weeks gestation, the definitive management is delivery. Magnesium sulfate 4g IV loading dose followed by 1–2 g/hr maintenance is indicated for seizure prophylaxis (eclampsia prevention). Antihypertensive therapy (IV labetalol or hydralazine, or oral nifedipine) is also required for acute BP control. Expectant management (discharging home) is inappropriate with severe features at ≥ 34 weeks. 24-hour urine protein is no longer required for the diagnosis if spot urine protein:creatinine ratio ≥ 0.3 — do not delay management waiting for this result.",
    relatedConditionId: "wh-preeclampsia",
  },
  {
    id: "wh-q-002",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 32-year-old woman at 10 weeks gestation presents with vaginal bleeding and lower abdominal cramping. Transvaginal ultrasound shows an empty uterus and a left adnexal mass measuring 3.2 cm with a complex echogenic ring. Serum β-hCG is 2,800 mIU/mL. What is the most likely diagnosis?",
    options: [
      { label: "A", text: "Inevitable abortion" },
      { label: "B", text: "Complete abortion" },
      { label: "C", text: "Ectopic pregnancy" },
      { label: "D", text: "Heterotopic pregnancy" },
    ],
    correctAnswer: "C",
    explanation: "The triad of empty uterus on transvaginal US + adnexal mass + positive β-hCG is ectopic pregnancy until proven otherwise. The discriminatory zone for transvaginal US is β-hCG 1,500–3,500 mIU/mL — at 2,800 mIU/mL, an intrauterine pregnancy should be visible if present. The left adnexal 'ring of fire' appearance on color Doppler (echogenic ring around adnexal mass) is the classic US finding for tubal ectopic. Inevitable abortion would show an open cervical os with intrauterine gestational sac. Complete abortion would show an empty uterus with a history of passed tissue. Heterotopic pregnancy (simultaneous IUP + ectopic) is rare (1:30,000 natural conception, higher with ART).",
    relatedConditionId: "wh-ectopic",
  },
  {
    id: "wh-q-003",
    rotation: "womens-health",
    category: "Management",
    difficulty: "hard",
    stem: "A 25-year-old woman is diagnosed with an unruptured ectopic pregnancy at 6 weeks gestation. β-hCG is 1,200 mIU/mL and the adnexal mass measures 2.8 cm on transvaginal US. She is hemodynamically stable and desires future fertility. Which of the following is the most appropriate treatment?",
    options: [
      { label: "A", text: "Methotrexate 50 mg/m² IM single-dose protocol" },
      { label: "B", text: "Surgical salpingectomy via laparoscopy" },
      { label: "C", text: "Expectant management with serial β-hCG monitoring" },
      { label: "D", text: "Mifepristone 200 mg PO followed by misoprostol" },
    ],
    correctAnswer: "A",
    explanation: "This patient meets criteria for methotrexate (MTX) single-dose protocol: hemodynamically stable, unruptured ectopic, no contraindications (renal/hepatic disease, immunodeficiency, thrombocytopenia, pulmonary disease, breastfeeding), β-hCG < 5,000 mIU/mL, mass ≤ 3.5 cm, no cardiac activity. MTX is a folic acid antagonist (dihydrofolate reductase inhibitor) that halts trophoblastic cell division. After a single 50 mg/m² IM dose, serial β-hCG is checked at day 4 and day 7 — a 15% decline from day 4 to day 7 indicates treatment success. Surgical salpingectomy is appropriate for ruptured ectopic, hemodynamic instability, failed MTX, contraindications to MTX, or patient preference. Mifepristone/misoprostol is for termination of an intrauterine pregnancy, not ectopic. Expectant management has limited evidence and is only appropriate for very low and declining β-hCG levels.",
    relatedConditionId: "wh-ectopic",
  },
  {
    id: "wh-q-004",
    rotation: "womens-health",
    category: "Pharmacology",
    difficulty: "easy",
    stem: "A 38-year-old woman presents for contraceptive counseling. She has a history of migraine with aura, smokes 10 cigarettes per day, and has a BMI of 32. Which contraceptive method is MOST appropriate for this patient?",
    options: [
      { label: "A", text: "Combined oral contraceptive pill (COCP)" },
      { label: "B", text: "Contraceptive patch (ethinyl estradiol/norelgestromin)" },
      { label: "C", text: "Levonorgestrel-releasing IUD (Mirena)" },
      { label: "D", text: "Vaginal ring (NuvaRing)" },
    ],
    correctAnswer: "C",
    explanation: "Migraine WITH aura is a USMEC Category 4 (absolute contraindication) for all combined hormonal methods (COCPs, patch, ring) at any age — it increases stroke risk due to estrogen-induced procoagulant effect. Additionally, smoking ≥ 15 cigarettes/day at age ≥ 35 is another Category 4 for combined hormonal methods (though at age 38 smoking any amount with migraine with aura makes estrogen contraindicated). The levonorgestrel IUD (progestin-only, no estrogen) is USMEC Category 1 for migraine with aura and safe in this patient. It also provides excellent pregnancy protection (> 99%), reduces menstrual bleeding, and requires no daily adherence. Copper IUD would also be appropriate. All options A, B, D contain estrogen and are absolutely contraindicated.",
    relatedConditionId: "wh-contraception",
  },
  {
    id: "wh-q-005",
    rotation: "womens-health",
    category: "Guidelines",
    difficulty: "medium",
    stem: "A 27-year-old woman presents for her annual exam. Her last Pap smear 3 years ago was normal. She has never had an HPV test. Per current ACS 2020 guidelines, which cervical cancer screening strategy is most preferred for a 27-year-old?",
    options: [
      { label: "A", text: "Pap smear alone every 3 years" },
      { label: "B", text: "Co-testing (Pap + HPV) every 5 years" },
      { label: "C", text: "Primary hrHPV testing alone every 5 years" },
      { label: "D", text: "No screening needed — begin at age 30" },
    ],
    correctAnswer: "C",
    explanation: "Per ACS 2020 guidelines, the preferred screening strategy for individuals aged 25–65 is primary high-risk HPV (hrHPV) testing alone every 5 years. Co-testing (Pap + HPV) every 5 years is an acceptable alternative. Pap smear alone every 3 years is acceptable but less preferred. Screening now begins at age 25 (not 21 for the preferred HPV-primary strategy, though ACOG still recommends Pap at 21–25). Since this patient is 27 and her last Pap was 3 years ago and normal, she is due for primary HPV testing now. Option D is incorrect — screening starts at 25, not 30.",
    relatedConditionId: "wh-cervical-cancer",
  },
  {
    id: "wh-q-006",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 26-year-old woman presents with irregular periods, excess facial hair, acne, and difficulty conceiving for 18 months. BMI is 34. Fasting glucose is 108 mg/dL. Labs show LH:FSH ratio of 3:1 and elevated free testosterone. Transvaginal ultrasound shows 18 small follicles per ovary in a 'string of pearls' pattern. What is the diagnosis and what criterion confirms it?",
    options: [
      { label: "A", text: "Hypothalamic amenorrhea — diagnosed by low LH, FSH, and estrogen" },
      { label: "B", text: "PCOS — confirmed by Rotterdam criteria (2 of 3: oligo-ovulation, hyperandrogenism, polycystic ovaries on US)" },
      { label: "C", text: "Premature ovarian insufficiency — confirmed by FSH > 40 IU/L on two occasions" },
      { label: "D", text: "Hyperprolactinemia — confirmed by prolactin > 100 ng/mL" },
    ],
    correctAnswer: "B",
    explanation: "This patient has PCOS confirmed by Rotterdam criteria (2003) requiring at least 2 of 3 criteria: (1) Oligo/anovulation (irregular periods, 18 months anovulatory infertility), (2) Clinical or biochemical hyperandrogenism (facial hair, acne, elevated free testosterone), (3) Polycystic ovarian morphology on US (≥ 12 follicles per ovary 2–9 mm, or ovarian volume > 10 mL — updated 2018 threshold: ≥ 20 follicles per ovary). She has all three. The elevated LH:FSH ratio (> 2:1) is a classic but NOT required finding. Metabolic complications include insulin resistance (fasting glucose 108 = impaired fasting glucose), type 2 DM, metabolic syndrome. Management: weight loss (5–10% can restore ovulation), metformin (insulin sensitizer), OCPs (for cycle regulation/hyperandrogenism), clomiphene/letrozole (for ovulation induction in infertility). Hypothalamic amenorrhea shows low LH/FSH/estrogen in underweight/athletes. POI shows elevated FSH > 40. Hyperprolactinemia shows galactorrhea + elevated prolactin.",
    relatedConditionId: "wh-pcos",
  },
  {
    id: "wh-q-007",
    rotation: "womens-health",
    category: "Management",
    difficulty: "hard",
    stem: "A 29-year-old G1P1 woman delivers a term infant via spontaneous vaginal delivery. 15 minutes after delivery of the placenta, estimated blood loss reaches 1,200 mL and the uterus is palpated as boggy and soft despite fundal massage. Oxytocin 10 units IM has been given. What is the most appropriate next medication?",
    options: [
      { label: "A", text: "Misoprostol 800 mcg per rectum" },
      { label: "B", text: "Methylergonovine 0.2 mg IM" },
      { label: "C", text: "Carboprost (hemabate) 250 mcg IM" },
      { label: "D", text: "Tranexamic acid 1g IV" },
    ],
    correctAnswer: "A",
    explanation: "This patient has postpartum hemorrhage (PPH) from uterine atony (4 T's: Tone = most common at 80%). After oxytocin (first-line), the next step is a second uterotonic. Misoprostol 800–1000 mcg PR/SL/buccal is a prostaglandin E1 analogue that is highly effective, inexpensive, heat-stable (no refrigeration), and is recommended by WHO as the next-line agent after oxytocin failure. The WOMAN trial (2017) showed tranexamic acid (TXA) 1g IV reduces death from bleeding by 31% when given within 3 hours of delivery — it would be appropriate to add TXA as well, but misoprostol as the next uterotonic is the most appropriate NEXT step. Methylergonovine is contraindicated in hypertension (ergot alkaloid causes vasoconstriction — contraindicated in preeclampsia). Carboprost (15-methyl-PGF2α) is contraindicated in asthma. Since no contraindications are listed here, misoprostol is the best universal next agent.",
    relatedConditionId: "wh-pph",
  },
  {
    id: "wh-q-008",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 24-year-old woman presents for her first prenatal visit at 10 weeks. Her glucose challenge test (1-hour 50g GCT) at 24 weeks is 152 mg/dL. Which of the following is the most appropriate next step?",
    options: [
      { label: "A", text: "Diagnose GDM and begin insulin immediately" },
      { label: "B", text: "Perform a 3-hour 100g OGTT for confirmatory testing" },
      { label: "C", text: "Repeat the 1-hour GCT in 4 weeks" },
      { label: "D", text: "Diagnose GDM and begin dietary modifications" },
    ],
    correctAnswer: "B",
    explanation: "A 1-hour 50g GCT ≥ 140 mg/dL (some institutions use ≥ 130 mg/dL for higher sensitivity) is a positive screen requiring confirmatory testing with the 3-hour 100g OGTT. The OGTT is the diagnostic test. Carpenter-Coustan criteria (ACOG-recommended): ≥ 2 of the following values are required for GDM diagnosis: Fasting ≥ 95, 1-hour ≥ 180, 2-hour ≥ 155, 3-hour ≥ 140 mg/dL. If only 1 value is abnormal = impaired glucose tolerance of pregnancy (some institutions treat). A GCT of 152 mg/dL is abnormal but does not by itself diagnose GDM — confirmation is required. Alternative two-step approach using a 75g 2-hour OGTT is recommended by WHO/IADPSG (one abnormal value suffices): fasting ≥ 92, 1-hour ≥ 180, 2-hour ≥ 153 mg/dL. First-line treatment for GDM is medical nutrition therapy (MNT) + exercise; insulin is added if glucose targets not met in 1–2 weeks.",
    relatedConditionId: "wh-gdm",
  },
  {
    id: "wh-q-009",
    rotation: "womens-health",
    category: "Management",
    difficulty: "medium",
    stem: "A 42-year-old woman undergoes a screening mammogram. The radiologist reports a 1.2 cm mass with irregular margins and microcalcifications. The BI-RADS category assigned is 5. What does this mean and what is the next step?",
    options: [
      { label: "A", text: "BI-RADS 5 = highly suggestive of malignancy (≥ 95% PPV) → tissue biopsy required" },
      { label: "B", text: "BI-RADS 5 = probably benign → 6-month follow-up imaging" },
      { label: "C", text: "BI-RADS 5 = additional imaging needed → breast MRI" },
      { label: "D", text: "BI-RADS 5 = normal → return for routine annual screening" },
    ],
    correctAnswer: "A",
    explanation: "BI-RADS (Breast Imaging Reporting and Data System) categories: 0 = incomplete (additional imaging needed); 1 = negative (routine screening); 2 = benign (routine screening); 3 = probably benign (6-month short-interval follow-up); 4 = suspicious (biopsy should be considered — 4A low suspicion, 4B moderate, 4C high); 5 = highly suggestive of malignancy (PPV ≥ 95% — biopsy required); 6 = known biopsy-proven malignancy. BI-RADS 5 with irregular margins, microcalcifications = highly suspicious. Core needle biopsy (ultrasound-guided or stereotactic) is required for tissue diagnosis. Triple assessment: imaging + clinical exam + biopsy — all three must be concordant. A negative mammogram does NOT rule out malignancy in a symptomatic patient.",
    relatedConditionId: "wh-breast-cancer",
  },
  {
    id: "wh-q-010",
    rotation: "womens-health",
    category: "Pharmacology",
    difficulty: "medium",
    stem: "A 30-year-old woman is breastfeeding her 3-week-old infant and requests contraception. She has no history of hypertension or migraines. Which of the following is MOST appropriate?",
    options: [
      { label: "A", text: "Combined oral contraceptive pill — start immediately" },
      { label: "B", text: "Levonorgestrel IUD — can be inserted immediately postpartum before discharge" },
      { label: "C", text: "Combined oral contraceptive pill — safe to start at 21 days postpartum" },
      { label: "D", text: "DMPA (Depo-Provera) injection — avoid during breastfeeding" },
    ],
    correctAnswer: "B",
    explanation: "The levonorgestrel-releasing IUD (Mirena) or copper IUD can be inserted immediately postpartum (within 10 minutes of placental delivery) or at any time postpartum. Progestin-only methods (LNG-IUD, copper IUD, progestin-only pill, implant) are USMEC Category 1 for breastfeeding — no restriction on use. Combined hormonal methods (COCPs, patch, ring) are USMEC Category 4 for breastfeeding women < 21 days postpartum (VTE risk is highest), Category 3 for 21 days to < 6 weeks postpartum, and Category 2 after 6 weeks postpartum. The primary concern is VTE risk with estrogen in the hypercoagulable postpartum state, and potential effect on milk supply. DMPA (Depo-Provera) is actually USMEC Category 1 immediately postpartum for breastfeeding women — it does NOT reduce milk supply after the first few days. Therefore B is best because she's at 3 weeks postpartum (COCPs would be Category 3) and the IUD can be placed immediately.",
    relatedConditionId: "wh-contraception",
  },
  {
    id: "wh-q-011",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "hard",
    stem: "A 56-year-old postmenopausal woman presents with postmenopausal bleeding (PMB). She has a BMI of 41, hypertension, and type 2 diabetes. Transvaginal ultrasound shows endometrial thickness of 12 mm. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Reassure the patient that endometrial thickening is common with obesity" },
      { label: "B", text: "Start progesterone therapy to oppose the effect of endogenous estrogen" },
      { label: "C", text: "Perform endometrial biopsy (EMB) to rule out endometrial cancer" },
      { label: "D", text: "Repeat transvaginal US in 6 months" },
    ],
    correctAnswer: "C",
    explanation: "Postmenopausal bleeding requires endometrial evaluation — endometrial cancer must be ruled out. The threshold for endometrial biopsy in PMB: endometrial thickness ≥ 4–5 mm (some guidelines use > 4 mm). This patient has 12 mm — well above the threshold. This patient also has multiple risk factors for endometrial cancer (estrogen excess): obesity (adipose tissue aromatizes androstenedione → estrogen — the most significant endogenous estrogen source in postmenopausal women), type 2 diabetes, hypertension — the classic triad of risk factors. Other risk factors: nulliparity, early menarche, late menopause, unopposed estrogen therapy, tamoxifen use. Endometrial biopsy (Pipelle device) in office has > 90% sensitivity for endometrial cancer. If EMB is non-diagnostic or patient cannot tolerate, refer for hysteroscopy with D&C.",
    relatedConditionId: "wh-endometrial",
  },
  {
    id: "wh-q-012",
    rotation: "womens-health",
    category: "Management",
    difficulty: "medium",
    stem: "A 34-year-old woman at 34 weeks gestation has a blood pressure of 162/108 mmHg. She is being treated with magnesium sulfate. Her deep tendon reflexes are now absent on examination. Urine output is 15 mL/hr. What is the most appropriate immediate action?",
    options: [
      { label: "A", text: "Increase the magnesium infusion rate to achieve therapeutic levels" },
      { label: "B", text: "Stop the magnesium infusion and administer calcium gluconate 1 g IV" },
      { label: "C", text: "Administer furosemide to improve urine output" },
      { label: "D", text: "Obtain stat magnesium level and continue current infusion" },
    ],
    correctAnswer: "B",
    explanation: "Loss of deep tendon reflexes (DTRs) is a sign of magnesium toxicity — DTRs are lost at serum magnesium levels of approximately 7–10 mEq/L (therapeutic range is 4–7 mEq/L). The progression of magnesium toxicity: loss of DTRs → respiratory depression (> 12 mEq/L) → cardiac arrest (> 15 mEq/L). DTR loss is the critical warning sign and requires IMMEDIATE action: stop the magnesium infusion and give calcium gluconate 1 g IV (10 mL of 10% solution) as the antidote. Reduced urine output (oliguria < 25–30 mL/hr) in preeclampsia impairs magnesium excretion, leading to toxic accumulation. Do not increase the infusion (A) or wait for a level (D) — DTR loss requires immediate cessation and antidote. Furosemide (C) could worsen hypovolemia in preeclampsia and is not the priority.",
    relatedConditionId: "wh-preeclampsia",
  },
  {
    id: "wh-q-013",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 35-year-old woman presents with worsening pelvic pain for several years that is worse with menses, and dyspareunia. She has been unable to conceive for 2 years. Pelvic exam reveals nodularity along the uterosacral ligaments and a fixed retroverted uterus. CA-125 is mildly elevated at 52 U/mL. What is the most likely diagnosis and what is the GOLD STANDARD for confirmation?",
    options: [
      { label: "A", text: "Ovarian cancer — confirmed by CT-guided biopsy" },
      { label: "B", text: "Endometriosis — confirmed by laparoscopy with biopsy" },
      { label: "C", text: "Uterine fibroids — confirmed by transvaginal ultrasound" },
      { label: "D", text: "PID — confirmed by cervical culture" },
    ],
    correctAnswer: "B",
    explanation: "The clinical picture is classic for endometriosis: dysmenorrhea, dyspareunia, infertility, nodularity on uterosacral ligaments (implants), fixed retroverted uterus (adhesions), and mildly elevated CA-125. CA-125 is non-specific (elevated in endometriosis, PID, ovarian cancer, fibroids, menstruation) and not used to diagnose or exclude endometriosis. The GOLD STANDARD for definitive diagnosis is laparoscopy with direct visualization and biopsy — classic findings are 'powder-burn' or 'gunshot' lesions (blue-black endometrial implants), endometriomas ('chocolate cysts'), and adhesions creating a 'frozen pelvis.' Treatment: medical (hormonal suppression: COCPs, progestins, GnRH agonists/antagonists, danazol) or surgical (laparoscopic excision/ablation). Ovarian cancer: CA-125 is more markedly elevated, postmenopausal, and requires surgical staging. Fibroids would show an enlarged irregular uterus on exam/US, not uterosacral nodularity. PID presents acutely with fever, CMT, discharge.",
    relatedConditionId: "wh-endometriosis",
  },
  {
    id: "wh-q-014",
    rotation: "womens-health",
    category: "Physical Exam",
    difficulty: "easy",
    stem: "During a pelvic exam on a 22-year-old sexually active woman, you note a small, round, smooth, red, velvety area around the cervical os that bleeds when touched with a swab. She is on combined oral contraceptives. What is the most likely finding and what is the appropriate management?",
    options: [
      { label: "A", text: "Cervical carcinoma — urgent colposcopy and biopsy required" },
      { label: "B", text: "Cervical ectropion — reassure the patient, no treatment required" },
      { label: "C", text: "Nabothian cysts — observe, no treatment needed" },
      { label: "D", text: "Cervicitis from N. gonorrhoeae — treat empirically with ceftriaxone" },
    ],
    correctAnswer: "B",
    explanation: "Cervical ectropion (cervical erosion) occurs when columnar epithelium from the endocervical canal extends onto the ectocervix. It appears as a red, velvety, friable area around the cervical os that bleeds easily on contact. It is a normal variant, extremely common in adolescents, young women, and those on oral contraceptives (estrogen promotes eversion of the transformation zone). It causes no symptoms beyond occasional post-coital spotting or increased vaginal discharge. No treatment is required. It should be distinguished from cervicitis (mucopurulent discharge, positive STI swabs) and from cervical cancer (older patient, irregular mass, friable with irregular borders — biopsy warranted). Nabothian cysts are smooth, white/yellow retention cysts on the cervix — also benign.",
    relatedConditionId: "wh-cervical-cancer",
  },
  {
    id: "wh-q-015",
    rotation: "womens-health",
    category: "Labs",
    difficulty: "medium",
    stem: "A 24-year-old woman presents with a 6-week history of amenorrhea after a regular 28-day cycle. A urine pregnancy test is positive. Serum β-hCG is 450 mIU/mL. Transvaginal ultrasound shows no intrauterine sac. What is the most appropriate next step?",
    options: [
      { label: "A", text: "Diagnose ectopic pregnancy and proceed with methotrexate immediately" },
      { label: "B", text: "Repeat β-hCG in 48 hours and repeat transvaginal US when β-hCG exceeds the discriminatory zone" },
      { label: "C", text: "Schedule emergent laparoscopy for suspected ectopic" },
      { label: "D", text: "Diagnose early intrauterine pregnancy and schedule routine OB follow-up" },
    ],
    correctAnswer: "B",
    explanation: "At a β-hCG of 450 mIU/mL, this is below the discriminatory zone (1,500–3,500 mIU/mL for transvaginal US) — it is too early to reliably see an IUP even if one is present. No diagnosis can be made at this point (this could be: very early IUP, PUL — pregnancy of unknown location, or early ectopic). The correct approach is serial β-hCG monitoring every 48 hours. In a normal viable IUP, β-hCG should rise ≥ 53% (often cited as 'approximately doubles') in 48 hours. In ectopic pregnancy, rise is typically < 53% but can mimic IUP. In spontaneous abortion, β-hCG falls. Once β-hCG exceeds the discriminatory zone, repeat TVUS. A stable patient with β-hCG 450 and no concerning clinical features (no pain, no hemodynamic instability) does NOT warrant immediate methotrexate or laparoscopy — this would risk treating a normal early IUP.",
    relatedConditionId: "wh-ectopic",
  },
  {
    id: "wh-q-016",
    rotation: "womens-health",
    category: "Management",
    difficulty: "hard",
    stem: "A 45-year-old woman with BRCA1 mutation and no personal history of cancer presents for counseling. She had her last mammogram 6 months ago (negative). What is the recommended cancer surveillance strategy for BRCA1 carriers without cancer history?",
    options: [
      { label: "A", text: "Annual mammogram starting at age 40, no other special screening needed" },
      { label: "B", text: "Annual breast MRI AND annual mammogram starting at age 25 (or 10 years before youngest affected relative), RRBSO by 35-40 years" },
      { label: "C", text: "Bilateral prophylactic mastectomy immediately — no surveillance needed" },
      { label: "D", text: "Annual breast MRI only — mammogram is not recommended due to radiation risk" },
    ],
    correctAnswer: "B",
    explanation: "BRCA1 carriers have a lifetime breast cancer risk of 55–72% and ovarian cancer risk of 44–46%. NCCN guidelines for BRCA1 carriers: (1) Annual breast MRI + annual mammogram beginning at age 25–30 (MRI is more sensitive in dense breasts); (2) Clinical breast exam every 6 months; (3) Risk-reducing bilateral salpingo-oophorectomy (RRBSO) between ages 35–40 (BRCA1) or 40–45 (BRCA2), after completion of childbearing — reduces ovarian cancer risk by > 90% and breast cancer risk by 50% if premenopausal; (4) Chemoprevention option: tamoxifen or raloxifene (SERMs) to reduce breast cancer risk. Surveillance ALONE (without RRBSO) is an option for patients who decline surgery. Annual mammogram alone (A) is insufficient for high-risk carriers. Both MRI and mammogram are recommended together (D is incorrect). Immediate bilateral mastectomy is an option but not mandated — patient autonomy in decision-making.",
    relatedConditionId: "wh-breast-cancer",
  },
  {
    id: "wh-q-017",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 19-year-old woman presents with lower abdominal pain, fever of 38.6°C, and a purulent vaginal discharge for 3 days. On pelvic exam, you find cervical motion tenderness and bilateral adnexal tenderness. GC/Chlamydia NAAT swabs are pending. What is the most appropriate initial management?",
    options: [
      { label: "A", text: "Wait for NAAT results before initiating treatment to target specific pathogen" },
      { label: "B", text: "Treat empirically for PID with ceftriaxone 500 mg IM + doxycycline 100 mg BID × 14 days + metronidazole 500 mg BID × 14 days" },
      { label: "C", text: "Admit for IV antibiotics — all PID cases require inpatient treatment" },
      { label: "D", text: "Treat for bacterial vaginosis with metronidazole 500 mg BID × 7 days" },
    ],
    correctAnswer: "B",
    explanation: "PID management: the CDC recommends empirical treatment when ANY one of the minimum criteria is present (CMT OR uterine tenderness OR adnexal tenderness) in a sexually active woman with no other identifiable cause — do NOT wait for culture results. This patient has CMT + adnexal tenderness + fever + purulent discharge. Outpatient treatment (CDC 2021): ceftriaxone 500 mg IM single dose (covers GC) + doxycycline 100 mg PO BID × 14 days (covers chlamydia) + metronidazole 500 mg PO BID × 14 days (covers anaerobes/BV). All PID cases do NOT require admission — indications for inpatient IV therapy: TOA, pregnancy, failed outpatient treatment, inability to take PO medications, surgical emergency cannot be excluded, severe illness. BV alone would not explain CMT or fever. Waiting for cultures delays treatment and increases risk of long-term complications (infertility, ectopic pregnancy, chronic pelvic pain).",
    relatedConditionId: "wh-pid",
  },
  {
    id: "wh-q-018",
    rotation: "womens-health",
    category: "Guidelines",
    difficulty: "medium",
    stem: "A 38-year-old woman at 41+2 weeks gestation has an uncomplicated pregnancy. Biophysical profile is 8/8 and amniotic fluid index is 7 cm. Bishop score is 4. She asks if she can wait longer. According to current ACOG guidance, what is the most appropriate recommendation?",
    options: [
      { label: "A", text: "Allow pregnancy to continue to 42 weeks with twice-weekly fetal surveillance" },
      { label: "B", text: "Recommend induction of labor now — delivery recommended by 41+0 to 42+0 weeks" },
      { label: "C", text: "Perform cesarean delivery given unfavorable Bishop score" },
      { label: "D", text: "Schedule induction at 43 weeks unless fetal surveillance becomes abnormal" },
    ],
    correctAnswer: "B",
    explanation: "ACOG (2021) recommends delivery by 41+0 weeks (41 weeks 0 days) and no later than 42+0 weeks for uncomplicated pregnancies. The ARRIVE trial (2018) demonstrated that induction at 39 weeks in low-risk nulliparous women did NOT increase C-section rates and actually slightly reduced them. At 41+2 weeks, the risk of stillbirth increases significantly (2–3× higher than at 40 weeks). The Bishop score of 4 is unfavorable (< 6), indicating cervical ripening is needed before or concurrent with oxytocin induction — this is NOT an indication for cesarean delivery. Cervical ripening agents: misoprostol, dinoprostone (Cervidil/Prepidil), or mechanical (Foley balloon). Waiting to 43 weeks is associated with significantly increased perinatal morbidity and mortality. Twice-weekly NST/BPP surveillance is standard for post-dates management but does not replace the recommendation for delivery by 42 weeks.",
    relatedConditionId: "wh-postdates",
  },
  {
    id: "wh-q-019",
    rotation: "womens-health",
    category: "Pharmacology",
    difficulty: "medium",
    stem: "A woman delivers at 38 weeks and her newborn has respiratory distress. She tells you she received betamethasone injections during the pregnancy. At what gestational age and for what indication is antenatal corticosteroid therapy recommended?",
    options: [
      { label: "A", text: "24–34 weeks gestation when preterm delivery is anticipated within 7 days — reduces RDS, IVH, and neonatal mortality" },
      { label: "B", text: "Any gestational age when preterm labor is suspected — reduces all neonatal complications" },
      { label: "C", text: "34–37 weeks gestation only — the period of highest risk for RDS" },
      { label: "D", text: "28–32 weeks only — beyond 32 weeks the lungs are sufficiently mature" },
    ],
    correctAnswer: "A",
    explanation: "Antenatal corticosteroids (betamethasone 12 mg IM × 2 doses 24 hours apart, OR dexamethasone 6 mg IM q12h × 4 doses) are recommended for pregnant women between 24+0 and 34+6 weeks gestation who are at risk for preterm delivery within 7 days. Benefits: reduces respiratory distress syndrome (RDS), intraventricular hemorrhage (IVH), necrotizing enterocolitis (NEC), and neonatal death. Late preterm steroids (34–36+6 weeks): a single course of betamethasone is recommended in this window by ACOG (2017) — reduces neonatal respiratory morbidity in the late preterm period. This patient received steroids presumably due to preterm labor risk earlier in pregnancy. A single rescue course can be given if initial course was > 14 days prior and gestational age is still < 34 weeks. Repeat courses beyond one rescue course are NOT recommended (associated with reduced fetal growth and head circumference).",
    relatedConditionId: "wh-preterm-labor",
  },
  {
    id: "wh-q-020",
    rotation: "womens-health",
    category: "Diagnosis",
    difficulty: "hard",
    stem: "A 62-year-old woman presents with progressive abdominal distension, early satiety, and unintentional weight loss of 12 lbs over 3 months. She is postmenopausal. Pelvic exam reveals a right adnexal mass. CA-125 is 890 U/mL (normal < 35). What is the most likely diagnosis and what is the surgical staging system used?",
    options: [
      { label: "A", text: "Endometrioma — treated with laparoscopic cystectomy" },
      { label: "B", text: "Ovarian cancer — staged using FIGO staging (I–IV) with surgical exploration" },
      { label: "C", text: "Ovarian torsion — emergency surgery required within 6 hours" },
      { label: "D", text: "Tubo-ovarian abscess — treat with IV clindamycin + gentamicin" },
    ],
    correctAnswer: "B",
    explanation: "The presentation is classic for ovarian cancer (epithelial, serous adenocarcinoma is the most common subtype): postmenopausal woman, progressive abdominal distension (ascites from peritoneal metastasis), early satiety (omental 'cake'), significant weight loss, adnexal mass, and markedly elevated CA-125 (> 35 U/mL, but > 500 is highly concerning, > 890 is alarming). CA-125 is elevated in 80% of epithelial ovarian cancers. Ovarian cancer is staged surgically using FIGO staging: Stage I (confined to ovaries), Stage II (pelvic extension), Stage III (peritoneal/retroperitoneal LN involvement — most common at diagnosis), Stage IV (distant metastasis including pleural effusion with malignant cells, liver parenchyma). Primary treatment: cytoreductive surgery (debulking) + platinum-based chemotherapy (carboplatin + paclitaxel). BRCA1/2 mutation testing for all epithelial ovarian cancer patients — guides maintenance therapy (PARP inhibitors: olaparib, niraparib). Endometrioma affects reproductive-age women; torsion presents acutely with severe pain; TOA presents with fever/leukocytosis in younger women.",
    relatedConditionId: "wh-ovarian-cancer",
  },
];
