import type { Guideline } from "@/types";

export const behavioralMedicineGuidelines: Guideline[] = [
  {
    conditionName: "Major Depressive Disorder",
    guidelineName: "Practice Guideline for the Treatment of Patients with Major Depressive Disorder",
    issuingOrganization: "American Psychiatric Association (APA)",
    firstLine: [
      "Pharmacotherapy AND/OR psychotherapy for mild-moderate MDD",
      "SSRIs or SNRIs as first-line pharmacotherapy (sertraline, escitalopram, fluoxetine preferred for favorable tolerability/interaction profiles)",
      "CBT (Cognitive Behavioral Therapy) as first-line psychotherapy — equivalent efficacy to antidepressants for mild-moderate MDD",
      "Combination of pharmacotherapy + CBT superior to either alone for moderate-severe MDD",
      "Adequate trial = therapeutic dose for minimum 4–8 weeks before assessing response",
    ],
    secondLine: [
      "If no/partial response after 4–8 weeks: optimize dose, then switch SSRI or switch class (SNRI, bupropion, mirtazapine)",
      "Augmentation strategies: add lithium, atypical antipsychotic (aripiprazole, quetiapine, brexpiprazole), or thyroid hormone (T3)",
      "Combination antidepressants: SSRI + mirtazapine (California rocket fuel), SSRI + bupropion",
      "Interpersonal Therapy (IPT) or Behavioral Activation as psychotherapy alternatives",
    ],
    thirdLine: [
      "Electroconvulsive Therapy (ECT): most effective treatment for severe treatment-resistant MDD, psychotic depression, or when rapid response needed (suicidal crisis, refusal to eat)",
      "Transcranial Magnetic Stimulation (TMS): FDA approved for TRD; outpatient; no anesthesia",
      "Esketamine (Spravato) intranasal: FDA approved for treatment-resistant MDD — administered in certified healthcare setting due to dissociation/sedation risk",
      "MAOIs (phenelzine, tranylcypromine): effective but significant interaction risk — last resort",
    ],
    nonPharmacologic: [
      "Cognitive Behavioral Therapy (CBT): 12–20 sessions, gold standard psychotherapy for MDD",
      "Interpersonal Therapy (IPT): focuses on grief, role transitions, interpersonal disputes",
      "Behavioral Activation: scheduled engagement in pleasurable activities (particularly for anhedonia)",
      "Mindfulness-Based Cognitive Therapy (MBCT): FDA endorsed for preventing MDD relapse — reduces recurrence by 43%",
      "Exercise: 3×/week aerobic exercise has antidepressant effect equivalent to sertraline in mild-moderate MDD",
      "Sleep hygiene: insomnia perpetuates depression — treat comorbid sleep disorder",
      "Light therapy: first-line for seasonal affective disorder (SAD); 10,000 lux, 30 min each morning",
    ],
    whenToRefer: [
      "Psychiatric hospitalization: active suicidal ideation with plan, intent, or access to means; inability to care for self; psychotic depression",
      "Psychiatry outpatient referral: treatment-resistant depression (failed ≥ 2 adequate trials), bipolar disorder suspected, psychotic features, comorbid substance use disorder",
      "TMS or ECT: refractory to ≥ 2 antidepressant trials with augmentation",
      "Emergency: patient with plan and access to firearms or means — crisis intervention or emergency evaluation",
    ],
    monitoringSchedule: [
      "PHQ-9 at baseline; repeat at 2, 4, 6, 8 weeks during initiation",
      "PHQ-9 score guides treatment: ≥ 10 = moderate depression; ≥ 15 = moderately severe; ≥ 20 = severe",
      "Full response: PHQ-9 score < 5; partial response: 50% decrease in score; non-response: < 25% decrease",
      "Suicidality assessment: EVERY visit using Columbia Suicide Severity Rating Scale (C-SSRS) or similar",
      "Continue antidepressant for minimum 6–12 months after first episode remission to prevent relapse",
      "Recurrent depression (≥ 2 episodes): consider indefinite maintenance therapy",
    ],
    patientEducation: [
      "Antidepressants take 4–8 weeks for full effect — do not stop early if side effects are mild",
      "Never stop antidepressants abruptly — taper over weeks to months to avoid discontinuation syndrome",
      "Sexual side effects from SSRIs are common and manageable — do not suffer in silence; alternatives exist",
      "Depression is a medical illness, not a character flaw or weakness",
      "Alcohol and recreational drugs worsen depression and interfere with medications",
      "Suicide risk assessment: ask directly about suicidal thoughts — asking does NOT increase risk",
      "Emergency contacts: provide crisis line number (988 in USA) at every visit",
    ],
  },
  {
    conditionName: "Bipolar I Disorder",
    guidelineName: "Practice Guideline for the Treatment of Patients with Bipolar Disorder",
    issuingOrganization: "American Psychiatric Association (APA) / Canadian Network for Mood and Anxiety Treatments (CANMAT)",
    firstLine: [
      "ACUTE MANIA: Lithium OR valproate (divalproex) + atypical antipsychotic (olanzapine, quetiapine, risperidone, aripiprazole) — combination more effective than monotherapy for severe mania",
      "ACUTE BIPOLAR DEPRESSION: Quetiapine monotherapy (Level 1 evidence), or lurasidone (+ lithium or valproate), or lithium or valproate monotherapy",
      "MAINTENANCE: Lithium (gold standard — reduces mania, depression, and suicide); valproate; lamotrigine (superior for depressive episodes but NOT mania)",
      "ANTIDEPRESSANT USE IN BIPOLAR: AVOID monotherapy without mood stabilizer (risk of triggering mania/rapid cycling) — use only adjunctively with mood stabilizer, and only for bipolar depression",
    ],
    secondLine: [
      "ACUTE MANIA — second-line monotherapy: haloperidol, ziprasidone, carbamazepine",
      "BIPOLAR DEPRESSION — second-line: lamotrigine (slow titration required due to rash risk), olanzapine-fluoxetine combination (OFC/Symbyax)",
      "MAINTENANCE — second-line: carbamazepine, quetiapine, lamotrigine (for depression prevention)",
      "Rapid cycling bipolar: valproate or lamotrigine preferred; avoid antidepressants; consider clozapine",
    ],
    nonPharmacologic: [
      "Psychoeducation: MOST IMPORTANT non-pharmacologic intervention — educate patient and family about illness, triggers, early warning signs",
      "Mood charting: daily tracking of mood, sleep, medications, stress, and energy levels",
      "Sleep regulation: disrupted sleep is a major trigger for mania — maintain consistent sleep schedule",
      "CBT for bipolar: relapse prevention, cognitive restructuring of grandiose thoughts",
      "Family-Focused Therapy (FFT): improves communication, reduces expressed emotion in family",
      "Avoid alcohol and substance use: powerful precipitants of mood episodes",
      "Interpersonal and Social Rhythm Therapy (IPSRT): regularize daily routines and sleep-wake cycles",
    ],
    whenToRefer: [
      "EMERGENCY/HOSPITALIZE: acute manic episode with psychosis, aggression, or inability to care for self; suicidal/homicidal ideation; bipolar depression with suicidal risk",
      "Psychiatry consultation: all newly diagnosed bipolar disorder patients",
      "Refractory cases: rapid cycling despite mood stabilizer, treatment-resistant bipolar depression — consider clozapine, ECT, or TMS",
      "Pregnancy: teratogenic medication concerns (valproate, lithium) — urgent psychiatric and OB/GYN consultation for medication optimization",
    ],
    monitoringSchedule: [
      "LITHIUM: serum level (trough, 12h post-dose) every 5–7 days after dose change until stable, then every 3–6 months. Target: 0.8–1.2 mEq/L (acute mania), 0.6–1.0 mEq/L (maintenance). BMP/Cr monthly × 6 months, then every 6 months. TSH every 6 months.",
      "VALPROATE: serum level every 5 days after dose change; target 85–125 mcg/mL. LFTs and CBC every 6–12 months.",
      "ATYPICAL ANTIPSYCHOTICS: Fasting glucose, HbA1c, lipids, weight, BP at baseline and every 3 months × 1 year, then annually.",
      "LAMOTRIGINE: no serum level monitoring required in routine practice. Monitor for rash (Stevens-Johnson syndrome) — titrate SLOWLY.",
      "Clinical monitoring: MDQ (Mood Disorder Questionnaire), PHQ-9 for depression, YMRS (Young Mania Rating Scale) at visits.",
    ],
    patientEducation: [
      "Bipolar disorder is lifelong — do not stop medications when feeling well (most relapses occur after self-discontinuation)",
      "Triggers for mania: sleep deprivation, stimulants, alcohol, spring/summer light changes, major life stressors, jet lag",
      "Warning signs of mania: decreased need for sleep without fatigue, increased energy, racing thoughts, rapid speech",
      "Warning signs of depression: increased sleep, withdrawal, hopelessness, suicidal thoughts",
      "Mood app tracking (e.g., eMoods): daily mood charting can help detect early episode onset",
      "Lithium: NEVER miss doses; stay well hydrated; avoid NSAIDs; report diarrhea/vomiting immediately",
      "Birth control: valproate-on-board requires highly effective contraception; discuss with OB/GYN",
    ],
  },
  {
    conditionName: "Schizophrenia",
    guidelineName: "Schizophrenia Patient Outcomes Research Team (PORT) / APA Practice Guidelines",
    issuingOrganization: "Schizophrenia PORT / American Psychiatric Association",
    firstLine: [
      "Antipsychotic medication is the cornerstone of treatment — most patients require lifelong therapy",
      "Second-generation (atypical) antipsychotics preferred as first-line due to lower EPS risk: risperidone, olanzapine, quetiapine, aripiprazole, ziprasidone, lurasidone, paliperidone",
      "First-episode psychosis: start at lower doses (hypersensitive to EPS and side effects); longer titration",
      "Adequate antipsychotic trial: therapeutic dose × 6–8 weeks before declaring non-response",
      "Long-acting injectable antipsychotics (LAIs): consider early — improves adherence, reduces relapse",
    ],
    secondLine: [
      "If inadequate response to 2 adequate antipsychotic trials: CLOZAPINE (gold standard for treatment-resistant schizophrenia — TRS)",
      "Adjunctive mood stabilizer (valproate): for agitation, hostility, impulsivity",
      "Adjunctive benzodiazepine: short-term for acute agitation or anxiety",
      "Augment antipsychotic with antidepressant: for persistent negative symptoms or comorbid depression",
    ],
    thirdLine: [
      "ECT: for treatment-resistant schizophrenia or catatonia",
      "Combination of two antipsychotics (polypharmacy): generally discouraged; may be considered in refractory cases under specialist guidance",
    ],
    nonPharmacologic: [
      "Coordinated Specialty Care (CSC): evidence-based team approach for first-episode psychosis (psychiatry + case management + supported employment + CBT + family education)",
      "CBT for psychosis (CBTp): reduces positive symptoms and distress; recommended alongside medication",
      "Social skills training: improves functioning and social cognition",
      "Supported Employment (Individual Placement and Support — IPS): most effective vocational rehabilitation for serious mental illness",
      "Family Psychoeducation: reduces relapse rates; includes all caregivers",
      "Cognitive Remediation: targets cognitive deficits (memory, attention, executive function)",
      "Illness management and recovery programs",
    ],
    whenToRefer: [
      "EMERGENCY: active psychosis with dangerous behavior, self-harm, or harm to others — emergency psychiatric evaluation + possible involuntary hold",
      "First-episode psychosis: ALL patients should receive specialty psychiatric care",
      "Treatment-resistant schizophrenia (TRS): refer to psychiatrist for clozapine initiation (requires REMS program — regular ANC monitoring)",
      "Medical emergencies: NMS (stop antipsychotic, call for emergent medical management)",
    ],
    monitoringSchedule: [
      "AIMS scale: baseline, then every 6–12 months (tardive dyskinesia screening)",
      "Metabolic monitoring (all atypicals): weight/BMI monthly × 6 months then quarterly; fasting glucose + HbA1c at baseline, 3 months, then annually; fasting lipids at baseline, then annually",
      "CLOZAPINE-specific (REMS mandatory): ANC monitoring — weekly × 6 months, then biweekly × 6 months, then monthly",
      "Prolactin: if symptomatic (galactorrhea, amenorrhea, sexual dysfunction) — especially with risperidone/paliperidone",
      "Clinical: PANSS (Positive and Negative Syndrome Scale) or BPRS (Brief Psychiatric Rating Scale)",
    ],
    patientEducation: [
      "Schizophrenia is a brain disorder — medication is essential, not optional",
      "Stopping medication is the #1 cause of relapse — even when feeling well, continue treatment",
      "Cannabis use dramatically worsens psychotic symptoms — abstinence is important",
      "Side effects (weight gain, sedation, sexual dysfunction) can be managed — do not stop without discussing",
      "Long-acting injections (LAIs) eliminate daily pill burden and improve adherence",
      "Community mental health resources, NAMI (National Alliance on Mental Illness) support groups",
    ],
  },
  {
    conditionName: "Generalized Anxiety Disorder",
    guidelineName: "Practice Guidelines for the Treatment of GAD",
    issuingOrganization: "American Psychiatric Association / WFSBP (World Federation of Biological Psychiatry)",
    firstLine: [
      "SSRIs (escitalopram, paroxetine, sertraline) or SNRIs (venlafaxine XR, duloxetine) — first-line pharmacotherapy",
      "CBT (Cognitive Behavioral Therapy): first-line psychotherapy; addresses worry, avoidance, and physiologic arousal. 12–15 sessions. Most durable response.",
      "Combination of SSRI/SNRI + CBT superior to either alone",
      "Buspirone: 5-HT1A partial agonist — anxiolytic without sedation, abuse potential, or withdrawal. Start 7.5 mg BID, titrate to 15–30 mg BID. Onset 2–4 weeks (not PRN). Good for patients with substance use history.",
    ],
    secondLine: [
      "Pregabalin (Lyrica): GABA analog; reduces anxiety rapidly; FDA approved in Europe for GAD; used off-label in USA",
      "TCAs (imipramine): effective but poor tolerability and overdose risk",
      "Benzodiazepines: SHORT-TERM use for acute anxiety relief while awaiting SSRI/SNRI onset; avoid long-term due to dependence risk",
      "Hydroxyzine: antihistamine with anxiolytic properties; non-habit-forming; useful for PRN anxiety or in patients avoiding benzos",
      "Beta-blockers (propranolol): for performance anxiety (autonomic symptoms — tremor, palpitations)",
    ],
    nonPharmacologic: [
      "CBT: worry exposure, cognitive restructuring, relaxation training, problem-solving",
      "Acceptance and Commitment Therapy (ACT): mindfulness-based; accepts anxiety without fighting it",
      "Progressive muscle relaxation (PMR) and diaphragmatic breathing techniques",
      "Mindfulness-Based Stress Reduction (MBSR): 8-week program with demonstrated anxiolytic efficacy",
      "Exercise: 150 min/week moderate aerobic exercise equivalent to anxiolytic pharmacotherapy in mild-moderate GAD",
      "Sleep hygiene and limiting caffeine, alcohol",
      "Biofeedback: heart rate variability training for autonomic regulation",
    ],
    whenToRefer: [
      "Psychiatry: GAD refractory to ≥ 2 medication trials + CBT, comorbid OCD, PTSD, or bipolar disorder, or substance use complicating treatment",
      "Psychology/therapy: all GAD patients benefit from CBT — facilitate referral at diagnosis",
      "Emergency: panic attacks with suspected cardiac etiology (first-time presentation should rule out arrhythmia, MI)",
    ],
    monitoringSchedule: [
      "GAD-7 scale: baseline, then 4–8 weeks after initiation, then every 3 months",
      "GAD-7 score ≥ 10 = moderate anxiety; ≥ 15 = severe",
      "Assess for comorbid depression (PHQ-9) — co-occurrence rate > 60%",
      "Monitor for substance use disorder: anxiety often drives self-medication",
      "Medication response: SSRIs/SNRIs take 4–6 weeks for anxiolytic effect (separate from antidepressant timeline)",
    ],
    patientEducation: [
      "Anxiety is real and treatable — the brain's threat detection system is overactivated",
      "Avoidance of anxiety triggers WORSENS anxiety over time — gradual exposure is key",
      "SSRIs may feel activating (increased anxiety) in the first 1–2 weeks — warn patients and push through",
      "Buspirone must be taken daily — it does NOT work as a PRN medication",
      "Caffeine and alcohol worsen GAD — reduce or eliminate",
      "Therapy (CBT) is the most durable treatment — medication prevents relapse but doesn't cure",
    ],
  },
  {
    conditionName: "PTSD",
    guidelineName: "VA/DoD Clinical Practice Guideline for the Management of PTSD",
    issuingOrganization: "U.S. Department of Veterans Affairs / Department of Defense (VA/DoD)",
    firstLine: [
      "Trauma-focused psychotherapy: FIRST-LINE treatment (superior to pharmacotherapy for PTSD)",
      "Prolonged Exposure (PE): repeatedly confronting trauma memories and safe trauma-related situations — gold standard",
      "Cognitive Processing Therapy (CPT): challenges maladaptive beliefs formed by trauma without requiring narrative exposure",
      "EMDR (Eye Movement Desensitization and Reprocessing): bilateral sensory stimulation during trauma processing — equivalent efficacy to PE/CPT",
      "Pharmacotherapy: sertraline or paroxetine (only FDA-approved medications for PTSD) — use for comorbid depression/anxiety or if patient refuses/unable to engage in psychotherapy",
    ],
    secondLine: [
      "Venlafaxine (SNRI): strong evidence, often used as first-line pharmacotherapy",
      "Prazosin: alpha-1 antagonist — specifically for PTSD-related nightmares and hyperarousal (reduces noradrenergic activation during sleep)",
      "Mirtazapine: effective for sleep, nightmares, and depressive symptoms",
      "Nefazodone (off-label): REM sleep normalization, may reduce nightmares",
    ],
    thirdLine: [
      "Mood stabilizers (lamotrigine, valproate): limited evidence",
      "Second-generation antipsychotics (risperidone, quetiapine): adjunctive for hypervigilance, insomnia, or psychotic features",
      "Ketamine: emerging evidence for treatment-resistant PTSD (not standard of care)",
    ],
    nonPharmacologic: [
      "Prolonged Exposure (PE): 8–15 sessions of imaginal exposure + in vivo exposure",
      "CPT: 12 sessions, written trauma accounts, challenging maladaptive cognitions (self-blame, world dangerousness)",
      "EMDR: bilateral eye movements during brief trauma memory exposure; 6–12 sessions",
      "Seeking Safety: integrated treatment for PTSD + substance use disorder",
      "Stress inoculation training",
      "Sleep hygiene + nightmare management (imagery rehearsal therapy for chronic nightmares)",
    ],
    whenToRefer: [
      "ALL PTSD patients: facilitate trauma-focused psychotherapy referral",
      "Psychiatry: complex PTSD, dissociative features, comorbid bipolar/psychosis, TBI comorbidity",
      "Emergency: active suicidal ideation (very high in PTSD) — safety assessment and crisis intervention",
      "Substance use: integrated dual diagnosis treatment (PTSD + SUD — treat simultaneously, not sequentially)",
    ],
    monitoringSchedule: [
      "PCL-5 (PTSD Checklist for DSM-5): baseline, then every 4 weeks during treatment. Score ≥ 33 = probable PTSD",
      "Columbia C-SSRS: suicide risk at every visit",
      "PHQ-9 for comorbid depression",
      "Alcohol/substance use assessment: AUDIT-C at every visit",
      "Sleep quality: Insomnia Severity Index (ISI) — sleep disturbance is a cardinal PTSD symptom",
    ],
    patientEducation: [
      "PTSD is a normal response to abnormal events — it is NOT a sign of weakness",
      "Therapy (PE, CPT, EMDR) works — trauma-focused therapy produces meaningful remission in 50–70% of patients",
      "Avoidance of trauma reminders maintains PTSD — therapy intentionally reduces avoidance",
      "Prazosin for nightmares: take 1 hour before bedtime; can cause orthostatic hypotension (rise slowly)",
      "Alcohol worsens PTSD symptoms and interferes with treatment — seek help for alcohol use",
      "988 Suicide & Crisis Lifeline: provide at every visit for veterans and high-risk patients",
    ],
  },
  {
    conditionName: "Attention-Deficit/Hyperactivity Disorder (ADHD)",
    guidelineName: "Clinical Practice Guideline for Diagnosis, Evaluation, and Treatment of ADHD in Children and Adolescents",
    issuingOrganization: "American Academy of Pediatrics (AAP)",
    firstLine: [
      "CHILDREN < 6 years: Behavior therapy FIRST — parent training in behavior management (medication second-line only if behavior therapy fails/insufficient)",
      "CHILDREN 6–11 years: FDA-approved medications AND behavior therapy (evidence strongest for combined treatment)",
      "ADOLESCENTS 12–18 years: FDA-approved medications + behavior therapy (medication often more accepted; ensure patient involvement in shared decision-making)",
      "ADULTS: Stimulants first-line. Methylphenidate (Ritalin, Concerta) or amphetamine-based (Adderall, Vyvanse) — both equally effective; choose based on tolerability",
    ],
    secondLine: [
      "Non-stimulant medications: atomoxetine (Strattera — SNRI; FDA approved for ADHD in children and adults; good for tic disorders, substance abuse hx, or anxiety comorbidity)",
      "Alpha-2 agonists: guanfacine ER (Intuniv) and clonidine ER (Kapvay) — adjunct or monotherapy when stimulants not tolerated or contraindicated (tics, substance abuse history, young children)",
      "Bupropion: off-label, effective for adults with comorbid depression",
      "TCAs (nortriptyline, desipramine): rarely used due to side effects and cardiac risk",
    ],
    nonPharmacologic: [
      "Behavioral therapy: positive reinforcement, token economy systems, structured routines, immediate consequences",
      "Parent training (PCIT — Parent-Child Interaction Therapy): most evidence-based for children < 6",
      "School accommodations (IEP/504 plans): extended test time, preferential seating, reduced homework, organizational aids",
      "CBT for adults with ADHD: organization skills, time management, emotional regulation",
      "Exercise: improves executive function and attention (aerobic exercise 30 min/day)",
      "Sleep optimization: ADHD and sleep disorders co-occur; treat sleep disorder",
    ],
    whenToRefer: [
      "Developmental pediatrics or child psychiatry: complex presentations, comorbid autism, learning disabilities, or treatment-refractory ADHD",
      "Psychiatry: ADHD + comorbid bipolar disorder, psychosis, or complex SUD",
      "Cardiology: before stimulant initiation if structural heart disease, arrhythmia, or significant family history of sudden cardiac death",
      "Neuropsychological testing: when diagnosis uncertain, learning disability suspected, or academic accommodations needed",
    ],
    monitoringSchedule: [
      "Vanderbilt Assessment Scale (teacher + parent): baseline, after dose change, then every 6 months",
      "ADHD Rating Scale or Conners scale in adults",
      "Height and weight: every 3–6 months (stimulants reduce appetite; monitor growth velocity in children)",
      "Blood pressure and heart rate: baseline, then every 6 months (stimulants raise both)",
      "Sleep assessment: every visit (stimulants worsen insomnia if dosed too late)",
      "Substance abuse screening: in adolescents and adults — stimulants have abuse potential",
    ],
    patientEducation: [
      "ADHD is neurodevelopmental — it does NOT go away but CAN be effectively managed",
      "Medication is not a crutch — it reduces symptoms to a level where therapy and skills-building become effective",
      "Stimulants have a low risk of addiction when used as prescribed — abuse risk is behavioral, not pharmacological",
      "Good sleep hygiene is essential — take medication early in the day; stimulant-related insomnia is common",
      "Dietary supplements (omega-3, zinc, iron): modest evidence — do not replace medication but may augment",
      "Exercise is a powerful non-pharmacologic intervention — encourage daily physical activity",
    ],
  },
];
