import type { Drug } from "@/types";

export const behavioralMedicinePharmacology: Drug[] = [
  {
    id: "bm-drug-sertraline",
    name: "Sertraline",
    brandName: "Zoloft",
    drugClass: "Selective Serotonin Reuptake Inhibitor (SSRI)",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Inhibits the serotonin transporter (SERT), blocking presynaptic reuptake of serotonin (5-HT) and increasing synaptic serotonin concentration. Has minimal effect on norepinephrine or dopamine reuptake. Also has weak sigma-1 receptor agonism.",
    indications: [
      "Major Depressive Disorder (MDD) — first-line",
      "Generalized Anxiety Disorder (GAD)",
      "Panic Disorder",
      "Social Anxiety Disorder",
      "Post-Traumatic Stress Disorder (PTSD) — FDA approved",
      "Obsessive-Compulsive Disorder (OCD)",
      "Premenstrual Dysphoric Disorder (PMDD)",
    ],
    dosing: {
      adult: "MDD: 50 mg/day initially; titrate by 25–50 mg every 1–2 weeks; range 50–200 mg/day. OCD may require up to 200 mg/day. PMDD: can dose cyclically (luteal phase only).",
      pediatric: "OCD (age 6–12): 25 mg/day initially; (age 13–17): 50 mg/day initially. Not FDA-approved for pediatric MDD but commonly used off-label.",
      renalAdjustment: "No adjustment needed for mild-moderate renal impairment.",
      hepaticAdjustment: "Use lower doses; caution in hepatic impairment (extensively metabolized by liver CYP2C19, CYP2D6, CYP3A4).",
    },
    sideEffects: {
      common: [
        "GI: nausea, diarrhea, dry mouth (often transient — take with food)",
        "Sexual dysfunction: decreased libido, anorgasmia, delayed ejaculation",
        "Insomnia or somnolence",
        "Headache",
        "Increased sweating",
        "Weight gain (typically modest)",
      ],
      serious: [
        "Serotonin syndrome: hyperthermia, clonus, agitation, tachycardia, diaphoresis (especially with MAOIs, tramadol, linezolid, triptans, dextromethorphan)",
        "Hyponatremia/SIADH: especially elderly — monitor sodium",
        "Suicidal ideation: FDA black box warning — increased risk in patients < 25 years old during first 1–4 weeks of therapy",
        "QTc prolongation: mild (less than citalopram/escitalopram); monitor in patients with cardiac disease",
        "Bleeding risk: SSRIs inhibit platelet aggregation — caution with NSAIDs, warfarin, aspirin",
        "Activation syndrome in bipolar disorder: may precipitate mania if given without mood stabilizer",
      ],
      blackBox:
        "Antidepressants increase risk of suicidal thinking and behavior in children, adolescents, and young adults (ages 18–24) with MDD and other psychiatric disorders. Monitor closely during first 4 weeks.",
    },
    contraindications: [
      "Concurrent or recent use of MAOIs (within 14 days — washout required to avoid serotonin syndrome)",
      "Concurrent use of pimozide (increases pimozide levels via CYP2D6 inhibition → QTc prolongation)",
      "Known hypersensitivity to sertraline",
    ],
    interactions: [
      "MAOIs: serotonin syndrome (lethal) — 14-day washout required",
      "Tramadol: increased serotonin syndrome risk + lowers seizure threshold",
      "Lithium: increased serotonin syndrome risk",
      "Warfarin: may increase INR — monitor PT/INR",
      "NSAIDs/aspirin: additive GI bleeding risk",
      "Triptans: theoretical serotonin syndrome risk (monitor)",
      "Alcohol: additive CNS depression",
      "Linezolid: serotonergic — CONTRAINDICATED",
    ],
    monitoring: [
      "Suicidality: assess weekly × 4 weeks, biweekly × next 4 weeks, then monthly",
      "PHQ-9 (depression) or GAD-7 (anxiety) at baseline and follow-up visits",
      "Serum sodium (Na) in elderly patients — risk of SIADH/hyponatremia",
      "Sexual function and weight at each visit",
      "Full therapeutic effect: 4–8 weeks (do not change dose prematurely; some patients need 12 weeks)",
      "If no response after 4–6 weeks at adequate dose → augment or switch",
    ],
    clinicalPearls: [
      "Sertraline is considered the safest SSRI in cardiac patients, liver disease, and in pregnancy (preferred SSRI in pregnancy — neonatal adaptation syndrome possible but manageable)",
      "Best tolerated SSRI overall — low drug interactions compared to fluoxetine and paroxetine",
      "SSRI-induced sexual dysfunction: consider switching to bupropion or mirtazapine if problematic; can add bupropion or sildenafil",
      "GI side effects are worse in the first 1–2 weeks — take with food and reassure patient",
      "Never stop abruptly — taper to avoid discontinuation syndrome (FINISH: Flu-like symptoms, Insomnia, Nausea, Imbalance, Sensory disturbances, Hyperarousal)",
    ],
    boardRecallTips: [
      "SSRI = first-line for MDD, GAD, OCD, PTSD, panic disorder, social anxiety",
      "Black box warning: increased suicidality in patients < 25 years old — monitor closely first 4 weeks",
      "SSRI + MAOI = serotonin syndrome (LETHAL) — 14-day washout required",
      "Sertraline = safest SSRI in pregnancy and cardiac disease",
      "Discontinuation syndrome (not with fluoxetine — long half-life): FINISH mnemonic",
      "SIADH/hyponatremia: SSRIs → most common in elderly women",
    ],
  },
  {
    id: "bm-drug-lithium",
    name: "Lithium",
    brandName: "Eskalith, Lithobid",
    drugClass: "Mood Stabilizer",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Exact mechanism not fully understood. Inhibits inositol monophosphatase (IMPase) and inositol polyphosphate 1-phosphatase, depleting inositol and reducing PKC and IP3 signaling. Also inhibits glycogen synthase kinase-3 (GSK-3β), affecting neuroplasticity, circadian rhythm, and neuroprotection. Modulates serotonin, dopamine, and glutamate neurotransmission.",
    indications: [
      "Bipolar I Disorder — acute mania (first-line) and maintenance",
      "Bipolar II Disorder — maintenance, prevents recurrence",
      "Augmentation for treatment-resistant depression (with antidepressant)",
      "Cluster headache prophylaxis (off-label)",
      "Neutropenia (stimulates granulopoiesis — off-label)",
    ],
    dosing: {
      adult: "Acute mania: 600 mg TID or 900 mg BID; target serum level 0.8–1.2 mEq/L. Maintenance: 300 mg TID to QID; target level 0.6–1.0 mEq/L. Draw trough level 12 hours after last dose.",
      pediatric: "Approved for bipolar disorder age ≥ 7. Start 300 mg BID-TID; titrate to therapeutic level.",
      renalAdjustment: "CRITICAL — lithium is renally excreted unchanged. Reduce dose proportionally to GFR. Avoid if GFR < 30 mL/min. Dose q8h with normal renal function, q12-24h with renal impairment.",
      hepaticAdjustment: "No hepatic adjustment needed (not metabolized by liver).",
    },
    sideEffects: {
      common: [
        "Tremor: fine resting tremor (dose-related) — manage with propranolol or dose reduction",
        "Polyuria and polydipsia: nephrogenic diabetes insipidus (lithium blocks ADH receptors in collecting duct) — treat with amiloride or low-dose thiazide",
        "Weight gain",
        "Hypothyroidism: 20–40% of patients — monitor TSH every 6 months",
        "Cognitive dulling, memory impairment",
        "GI: nausea, diarrhea (reduce dose, take with food, switch to extended-release)",
        "Acne and psoriasis exacerbation",
      ],
      serious: [
        "LITHIUM TOXICITY (narrow therapeutic index): Mild (1.5–2.0 mEq/L): coarse tremor, GI, confusion. Moderate (2.0–2.5 mEq/L): ataxia, slurred speech, muscle twitching, ECG changes. Severe (> 2.5 mEq/L): seizures, coma, cardiac arrhythmias, death",
        "SILENT: Nephrogenic DI, hypothyroidism, hyperparathyroidism",
        "Teratogenicity: Ebstein's anomaly risk (right-sided heart defect) — Category D. Discuss risk-benefit in pregnancy",
        "Sinus node dysfunction, QTc prolongation",
      ],
      blackBox: "None. However, lithium toxicity is life-threatening — serum monitoring is mandatory.",
    },
    contraindications: [
      "Severe renal impairment (GFR < 30 mL/min) — cannot clear lithium",
      "Severe cardiovascular disease",
      "Sodium depletion or dehydration states (increases lithium reabsorption → toxicity)",
      "First trimester pregnancy (relative — Ebstein's anomaly risk, though absolute risk is low)",
    ],
    interactions: [
      "NSAIDs (ibuprofen, naproxen): reduce renal lithium clearance → TOXICITY (acetaminophen is safe alternative)",
      "ACE inhibitors and ARBs: reduce lithium clearance → TOXICITY",
      "Thiazide diuretics: reduce lithium clearance → TOXICITY (paradox — also used to treat lithium-induced DI at low doses)",
      "Loop diuretics: safer than thiazides but still monitor",
      "Low sodium diet/dehydration: lithium reabsorbed with Na+ → TOXICITY",
      "Caffeine: increases lithium clearance (if stopped suddenly → toxicity)",
      "Haloperidol: additive neurotoxicity risk",
      "Metronidazole: increases lithium levels",
      "Theophylline: decreases lithium levels",
    ],
    monitoring: [
      "Serum lithium level: 12-hour post-dose trough. Acute mania target: 0.8–1.2 mEq/L. Maintenance target: 0.6–1.0 mEq/L. Check 5–7 days after any dose change, then every 3–6 months when stable.",
      "BMP (especially sodium and creatinine/GFR): baseline, then every 3–6 months",
      "Thyroid function (TSH, free T4): baseline, then every 6 months",
      "Calcium level: parathyroid stimulation → hypercalcemia",
      "ECG: baseline (especially age > 50)",
      "Urinalysis and urine osmolality: assess for nephrogenic DI",
    ],
    clinicalPearls: [
      "Lithium is the ONLY drug with proven anti-suicidal effects in bipolar disorder (reduces suicide mortality by 60%)",
      "TOXICITY TRIGGERS: dehydration, low-salt diet, diarrhea/vomiting, NSAID use, ACEi/ARBs, thiazide diuretics",
      "Treatment of toxicity: STOP lithium, aggressive IV normal saline hydration, hemodialysis for severe toxicity (level > 3.5 mEq/L or severe symptoms)",
      "Nephrogenic DI treatment: amiloride (preferred) or low-dose thiazide + ensure adequate Na intake",
      "Tremor: propranolol 10–20 mg TID or extended-release lithium formulation",
      "Lithium has 40 years of evidence for bipolar maintenance — most evidence of any mood stabilizer",
    ],
    boardRecallTips: [
      "Lithium target levels: ACUTE mania 0.8–1.2 mEq/L; MAINTENANCE 0.6–1.0 mEq/L",
      "Lithium toxicity: > 1.5 mEq/L = concern; > 2.5 mEq/L = severe (seizures/coma) → dialysis",
      "TOXICITY precipitants: NSAIDs, ACEi/ARBs, thiazides, dehydration, low Na diet",
      "Monitor: levels + Na/Cr (q3-6mo) + TSH (q6mo) + Ca",
      "Ebstein's anomaly: Lithium + pregnancy (right-sided heart defect) — Category D",
      "Anti-suicidal effect = LITHIUM (only mood stabilizer proven to reduce suicide mortality)",
      "Nephrogenic DI → amiloride (NOT vasopressin — ADH receptor blocked by lithium)",
    ],
  },
  {
    id: "bm-drug-haloperidol",
    name: "Haloperidol",
    brandName: "Haldol",
    drugClass: "First-Generation (Typical) Antipsychotic — High Potency",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Potent D2 receptor antagonist (primarily postsynaptic dopamine blockade in mesolimbic, mesocortical, nigrostriatal, and tuberoinfundibular pathways). Also blocks alpha-1 adrenergic and histamine H1 receptors to a lesser degree. High D2 affinity = effective antipsychotic + high EPS risk.",
    indications: [
      "Schizophrenia (acute and maintenance)",
      "Acute psychosis/agitation in any context",
      "Bipolar I disorder — acute mania (adjunct)",
      "Tourette syndrome (tics)",
      "Delirium (off-label — evidence-based)",
      "Nausea/vomiting (off-label)",
      "Intractable hiccups (off-label)",
    ],
    dosing: {
      adult: "Oral: 0.5–5 mg BID-TID (schizophrenia); acute agitation: 2–10 mg IM. IV: 0.5–5 mg slow IV push (off-label but commonly used in ICU delirium). Decanoate (IM depot): 10–15× daily oral dose, given monthly. Max 100 mg/day.",
      pediatric: "Tourette/behavioral disorders: 0.05–0.15 mg/kg/day in 2–3 divided doses.",
      renalAdjustment: "No formal adjustment needed.",
      hepaticAdjustment: "Use caution — extensively hepatically metabolized.",
    },
    sideEffects: {
      common: [
        "Extrapyramidal symptoms (EPS): most common side effect of high-potency typical antipsychotics",
        "Akathisia: subjective restlessness, inability to sit still (most distressing — treat with propranolol or benzodiazepine)",
        "Acute dystonia: sudden sustained muscle contraction (torticollis, oculogyric crisis, opisthotonos) — treat with benztropine 1–2 mg IM or diphenhydramine 50 mg IM",
        "Parkinsonism: bradykinesia, rigidity, resting tremor — treat with benztropine",
        "Sedation (less than low-potency antipsychotics)",
        "Orthostatic hypotension (less than chlorpromazine)",
      ],
      serious: [
        "Tardive Dyskinesia (TD): involuntary orofacial movements after long-term use; may be irreversible. Screen with AIMS scale. Treat with VMAT2 inhibitors (valbenazine/deutetrabenazine) or clonazepam",
        "Neuroleptic Malignant Syndrome (NMS): hyperthermia + LEAD PIPE RIGIDITY + altered mental status + autonomic instability (diaphoresis, tachycardia, labile BP). STOP antipsychotic → dantrolene + bromocriptine + supportive care",
        "QTc Prolongation → Torsades de Pointes: most common with IV administration. Monitor QTc (hold if > 500 ms). Risk increases with hypokalemia/hypomagnesemia",
        "Hyperprolactinemia: galactorrhea, amenorrhea, gynecomastia, sexual dysfunction",
      ],
      blackBox:
        "Increased mortality in elderly patients with dementia-related psychosis treated with antipsychotics (applies to ALL antipsychotics). NOT approved for dementia-related psychosis.",
    },
    contraindications: [
      "Parkinson's disease (worsens motor symptoms — avoid all D2 blockers; use quetiapine or clozapine if antipsychotic needed)",
      "Lewy Body Dementia: extreme sensitivity to D2 blockers → severe EPS, NMS, death",
      "Known QTc prolongation or concurrent QT-prolonging medications",
      "CNS depression (coma, alcohol intoxication)",
      "Known hypersensitivity",
    ],
    interactions: [
      "QT-prolonging drugs (methadone, fluoroquinolones, azithromycin, ondansetron): additive QTc prolongation → Torsades",
      "CNS depressants (opioids, benzodiazepines, alcohol): additive sedation/respiratory depression",
      "Lithium: additive neurotoxicity",
      "Anticholinergics: reduce EPS but worsen cognitive effects; can cause ileus",
      "Carbamazepine: induces haloperidol metabolism → reduced levels",
    ],
    monitoring: [
      "ECG: baseline QTc and periodically (especially with IV use or dose increases)",
      "AIMS scale: Abnormal Involuntary Movement Scale — screen for tardive dyskinesia every 6–12 months",
      "Metabolic parameters: weight, glucose, lipid panel (less metabolic syndrome risk than atypical antipsychotics)",
      "Prolactin level if symptomatic (galactorrhea, amenorrhea)",
      "Mental status: assess for EPS, akathisia, NMS signs at each visit",
    ],
    clinicalPearls: [
      "High-potency typical antipsychotics (haloperidol, fluphenazine): high EPS, low anticholinergic, low sedation, low hypotension",
      "Low-potency typical antipsychotics (chlorpromazine, thioridazine): low EPS, high anticholinergic, high sedation, high hypotension",
      "NMS vs. Serotonin Syndrome distinction: NMS = LEAD PIPE rigidity + slow onset (days); SS = clonus/hyperreflexia + fast onset (hours)",
      "Akathisia is the most common cause of antipsychotic non-adherence — always ask about restlessness",
      "Haloperidol decanoate IM monthly: for patients with poor oral adherence",
      "Avoid in Lewy Body Dementia (LBD): can cause sudden death — quetiapine or clozapine preferred if needed",
    ],
    boardRecallTips: [
      "High-potency typical = high EPS, low sedation (haloperidol, fluphenazine)",
      "Low-potency typical = low EPS, high sedation/anticholinergic (chlorpromazine)",
      "Acute dystonia → benztropine 1–2 mg IM (or diphenhydramine 50 mg IM)",
      "NMS = STOP drug → dantrolene + bromocriptine (dopamine agonist)",
      "NMS triad: hyperthermia + RIGIDITY + autonomic instability (vs. SS = clonus + rapid onset)",
      "Tardive dyskinesia = irreversible orofacial movements; treat with valbenazine (VMAT2 inhibitor)",
      "AVOID haloperidol in Parkinson's and Lewy Body Dementia",
      "QTc prolongation risk highest with IV haloperidol",
    ],
  },
  {
    id: "bm-drug-bupropion",
    name: "Bupropion",
    brandName: "Wellbutrin, Zyban",
    drugClass: "Norepinephrine-Dopamine Reuptake Inhibitor (NDRI)",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Inhibits neuronal reuptake of norepinephrine (NE) and dopamine (DA). Does NOT inhibit serotonin reuptake. Also antagonizes nicotinic acetylcholine receptors (nAChRs) — mechanism underlying smoking cessation effect. No significant antihistamine, anticholinergic, or alpha-adrenergic effects.",
    indications: [
      "Major Depressive Disorder (MDD) — first-line (especially when sexual dysfunction or sedation with SSRIs is problematic)",
      "Seasonal Affective Disorder (SAD) — FDA approved",
      "Smoking cessation — FDA approved (Zyban brand)",
      "ADHD (off-label)",
      "Bipolar depression (adjunct — with mood stabilizer)",
      "Sexual dysfunction induced by SSRIs (augmentation)",
      "Weight management (combined with naltrexone — Contrave formulation)",
    ],
    dosing: {
      adult: "IR: 100 mg BID initially, increase to 100 mg TID after 3 days (max 450 mg/day, no single dose > 150 mg). SR: 150 mg QAM × 3 days, then 150 mg BID (max 400 mg/day). XL: 150 mg QAM × 3–7 days, then 300 mg QAM (max 450 mg/day).",
      pediatric: "Not FDA-approved for depression in pediatrics; used off-label for ADHD.",
      renalAdjustment: "Reduce dose in severe renal impairment — metabolites may accumulate.",
      hepaticAdjustment: "Severe hepatic impairment: max 75 mg/day IR or 150 mg every other day XL.",
    },
    sideEffects: {
      common: [
        "Insomnia (take doses early in day — last dose by 2–3 PM)",
        "Agitation, anxiety, restlessness",
        "Dry mouth",
        "Headache",
        "Tachycardia/palpitations",
        "Constipation",
        "Weight loss (beneficial in many patients)",
        "NO sexual dysfunction (major advantage over SSRIs/SNRIs)",
        "NO weight gain (another advantage)",
      ],
      serious: [
        "SEIZURES: dose-dependent risk — most important side effect. Risk at doses > 450 mg/day. Absolute contraindication in patients with seizure disorders, bulimia/anorexia (electrolyte derangements lower seizure threshold), or heavy alcohol use",
        "Hypertension: monitor BP",
        "Neuropsychiatric symptoms: serious behavioral changes reported with smoking cessation use (FDA black box removed 2016 — evidence less compelling than feared)",
      ],
      blackBox: "Antidepressant-associated suicidality in patients < 25 years old. Neuropsychiatric symptoms with smoking cessation use (FDA black box warning removed from Zyban in 2016 based on EAGLES trial data).",
    },
    contraindications: [
      "Seizure disorder (current or history) — ABSOLUTE",
      "Bulimia nervosa or anorexia nervosa (electrolyte imbalance → lowers seizure threshold) — ABSOLUTE",
      "Abrupt alcohol or benzodiazepine withdrawal (seizure risk)",
      "Current or prior use of MAOIs within 14 days",
      "Known hypersensitivity",
    ],
    interactions: [
      "MAOIs: avoid (increased risk of hypertensive crisis and toxicity)",
      "Drugs that lower seizure threshold (antipsychotics, tramadol, theophylline): additive seizure risk",
      "CYP2D6 substrates: bupropion is a potent CYP2D6 INHIBITOR — increases levels of TCAs, SSRIs, opioids metabolized by 2D6 (codeine → morphine conversion impaired)",
      "Tamoxifen: bupropion inhibits CYP2D6 → reduces conversion to active metabolite (endoxifen) → reduced efficacy in breast cancer",
    ],
    monitoring: [
      "Blood pressure: baseline and follow-up (stimulant properties can raise BP)",
      "Mental status: assess suicidality especially in first 4 weeks",
      "Seizure risk assessment: review alcohol use, eating disorders, concurrent medications",
      "Weight (typically decreases — may be beneficial or problematic)",
      "Smoking cessation: use for 7–12 weeks; continue 12 weeks if successful for maintenance",
    ],
    clinicalPearls: [
      "Bupropion is the antidepressant to choose when: patient has sexual dysfunction from SSRIs, patient wants to quit smoking, patient needs to lose weight, patient has ADHD comorbidity",
      "The only antidepressant with ZERO sexual side effects and weight loss (not gain)",
      "SSRI-induced sexual dysfunction: add bupropion 150 mg/day XL (augmentation strategy — works well)",
      "Bulimia + bupropion = NEVER (even one binge/purge episode can cause hypokalemia → seizure)",
      "Doses must be split — never give > 150 mg IR or > 200 mg SR in a single dose (seizure risk)",
    ],
    boardRecallTips: [
      "NDRI = norepinephrine + dopamine reuptake inhibitor (NO serotonin effect)",
      "Advantages: NO sexual dysfunction, NO weight gain, smoking cessation",
      "CONTRAINDICATED: seizure disorder, bulimia/anorexia, MAOI use",
      "Seizure risk increases dose-dependently — max 450 mg/day; no single dose > 150 mg (IR)",
      "CYP2D6 INHIBITOR: reduces tamoxifen efficacy (avoid in breast cancer patients on tamoxifen)",
      "Smoking cessation: also varenicline (Chantix — partial nAChR agonist) and NRT",
    ],
  },
  {
    id: "bm-drug-valproate",
    name: "Valproic Acid / Divalproex Sodium",
    brandName: "Depakote (divalproex), Depakene (valproic acid)",
    drugClass: "Mood Stabilizer / Anticonvulsant",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Multiple mechanisms: (1) Blocks voltage-gated sodium channels, reducing neuronal firing. (2) Enhances GABA activity by inhibiting GABA transaminase (increases GABA levels) and stimulating glutamic acid decarboxylase. (3) Inhibits T-type calcium channels. (4) Inhibits histone deacetylase (HDAC) — epigenetic effects. Net effect: mood stabilization, anticonvulsant, antimigraine.",
    indications: [
      "Bipolar I disorder — acute mania (FDA approved, first-line)",
      "Bipolar maintenance (second-line after lithium in most guidelines, first-line for rapid cycling or mixed features)",
      "Seizure disorders: absence seizures, complex partial seizures, tonic-clonic seizures",
      "Migraine prophylaxis (FDA approved)",
      "Agitation in dementia (off-label)",
      "Schizoaffective disorder (adjunct)",
    ],
    dosing: {
      adult: "Acute mania: start 20–30 mg/kg/day divided BID-QID; target level 85–125 mcg/mL (or 50–125 mcg/mL for maintenance). Migraine prophylaxis: 500–1000 mg/day divided. Seizures: 10–15 mg/kg/day, titrate by 5–10 mg/kg/week.",
      pediatric: "Seizures in children ≥ 10 years: 10–15 mg/kg/day. Valproate has high teratogenicity risk — avoid in females of reproductive potential.",
      renalAdjustment: "No major adjustment needed; hemodialysis removes valproate.",
      hepaticAdjustment: "AVOID in hepatic disease — hepatotoxicity risk is highest in children < 2 years on polypharmacy.",
    },
    sideEffects: {
      common: [
        "GI: nausea, vomiting, diarrhea — take with food; divalproex has better GI profile than valproic acid",
        "Weight gain (significant — more than most mood stabilizers)",
        "Tremor (dose-related fine tremor)",
        "Hair loss (alopecia) — may be temporary; supplement with zinc and selenium",
        "Sedation",
        "Thrombocytopenia (dose-related) — monitor platelet count",
        "Hyperammonemia: even without liver disease — can cause confusion; treat with lactulose or L-carnitine",
      ],
      serious: [
        "HEPATOTOXICITY: fatal hepatic failure possible — mostly children < 2 years on polypharmacy. Check LFTs at baseline and periodically; watch for jaundice, RUQ pain",
        "TERATOGENICITY: HIGHEST risk of all anticonvulsants/mood stabilizers. Neural tube defects (spina bifida) 1–5%, cognitive impairment, autism spectrum disorder. Absolute contraindication in pregnancy if alternative exists. Supplement folic acid 4 mg/day if must use",
        "Pancreatitis: acute (check amylase/lipase if abdominal pain)",
        "DRESS syndrome: Drug Reaction with Eosinophilia and Systemic Symptoms",
        "Hyperammonemic encephalopathy: can occur without elevated LFTs",
      ],
      blackBox:
        "Hepatotoxicity (fatal), Teratogenicity (spina bifida, NTDs — AVOID in pregnancy), Pancreatitis.",
    },
    contraindications: [
      "PREGNANCY: highest teratogenic risk among mood stabilizers (neural tube defects, cognitive impairment, autism) — ABSOLUTE when alternatives exist",
      "Hepatic disease or significant hepatic dysfunction",
      "Known urea cycle disorders (hyperammonemia worsened)",
      "Known hypersensitivity",
    ],
    interactions: [
      "Lamotrigine: valproate DOUBLES lamotrigine levels by inhibiting glucuronidation → start lamotrigine at half dose when adding to valproate",
      "Carbapenem antibiotics (meropenem, ertapenem): dramatically reduce valproate levels → avoid or use alternative antibiotic",
      "Aspirin: displaces valproate from protein binding → increased free valproate levels",
      "Phenytoin: complex interaction — can increase or decrease phenytoin levels",
      "Warfarin: inhibits platelet function + may displace warfarin from protein binding → increased bleeding",
    ],
    monitoring: [
      "Serum valproate level: draw trough (before morning dose). Therapeutic range: 50–125 mcg/mL (some use 85–125 for acute mania). Check 5 days after dose change.",
      "LFTs (AST/ALT): baseline, then every 6–12 months",
      "CBC with platelet count: baseline, then every 6–12 months (thrombocytopenia risk)",
      "Ammonia level: if patient develops confusion (hyperammonemic encephalopathy)",
      "Pregnancy test in women of reproductive age before initiating and periodically",
      "Weight and BMI at each visit",
    ],
    clinicalPearls: [
      "Valproate is preferred over lithium in: RAPID CYCLING bipolar disorder, bipolar with MIXED FEATURES, patients with traumatic brain injury, patients with comorbid seizures, those who cannot tolerate lithium",
      "The valproate-lamotrigine interaction is HIGH YIELD: valproate INHIBITS lamotrigine metabolism → start lamotrigine at 25 mg every other day (instead of usual 25 mg/day) when adding to valproate",
      "Carbapenem antibiotics (meropenem, imipenem) can reduce valproate levels by up to 60–70% within days — avoid this combination in hospitalized psychiatric patients",
      "Teratogenicity: do not use valproate in women of reproductive age without extensive counseling, effective contraception, and documentation",
    ],
    boardRecallTips: [
      "Valproate for bipolar = preferred in RAPID CYCLING and MIXED FEATURES (lithium less effective)",
      "Black box warnings: HEPATOTOXICITY + TERATOGENICITY (NTDs) + PANCREATITIS",
      "Pregnancy: ABSOLUTE contraindication — highest NTD risk (spina bifida)",
      "Lamotrigine + valproate: HALVE lamotrigine dose (valproate inhibits its glucuronidation)",
      "Carbapenem antibiotics: AVOID with valproate (reduce levels 60–70%)",
      "Therapeutic level: 50–125 mcg/mL (trough, 12h post-dose)",
    ],
  },
  {
    id: "bm-drug-clonazepam",
    name: "Clonazepam",
    brandName: "Klonopin",
    drugClass: "Benzodiazepine (Long-Acting)",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Positive allosteric modulator of the GABA-A receptor. Binds to the benzodiazepine site on the GABA-A receptor complex (between alpha and gamma subunits), increasing the FREQUENCY of Cl⁻ channel opening in response to GABA. Net effect: neuronal hyperpolarization → CNS depression, anxiolysis, anticonvulsant, muscle relaxation.",
    indications: [
      "Panic disorder (FDA approved)",
      "Seizure disorders: absence seizures, myoclonic seizures, Lennox-Gastaut syndrome",
      "Acute anxiety episodes (short-term use)",
      "Akathisia from antipsychotics (off-label)",
      "Adjunct in bipolar disorder: acute mania agitation (short-term)",
      "REM sleep behavior disorder (off-label)",
      "Social anxiety disorder (off-label, second-line)",
    ],
    dosing: {
      adult: "Panic disorder: 0.25 mg BID initially, increase to 0.5–1 mg BID (max 4 mg/day). Seizures: 0.5 mg TID initially, titrate up to 20 mg/day. Akathisia: 0.5–1 mg BID. Acute anxiety: 0.5–1 mg PRN.",
      pediatric: "Seizures: 0.01–0.03 mg/kg/day divided BID-TID; max 0.05 mg/kg/day.",
      renalAdjustment: "No significant adjustment; metabolites renally cleared.",
      hepaticAdjustment: "Use with caution — hepatically metabolized; reduce dose in severe hepatic impairment.",
    },
    sideEffects: {
      common: [
        "Sedation and cognitive impairment (dose-dependent)",
        "Psychomotor slowing",
        "Anterograde amnesia",
        "Ataxia and falls (especially elderly — HIGH fall risk)",
        "Respiratory depression (dose-dependent, especially with opioids or alcohol)",
        "Tolerance develops over weeks to months",
        "Rebound anxiety between doses",
      ],
      serious: [
        "DEPENDENCE and WITHDRAWAL: physiologic dependence develops with regular use > 2–4 weeks. Abrupt withdrawal can cause SEIZURES, delirium, and death (more dangerous than opioid withdrawal). Taper slowly — 10% dose reduction per 1–2 weeks",
        "Respiratory depression: particularly with concurrent opioid use — FDA black box warning",
        "Paradoxical disinhibition: especially in children and elderly — increased agitation, aggression, impulsivity",
        "FALLS and HIP FRACTURES: major concern in elderly (Beers Criteria — avoid in age > 65)",
      ],
      blackBox:
        "Benzodiazepines combined with opioids can result in profound sedation, respiratory depression, coma, and death. Avoid concomitant use. Dependence, tolerance, and withdrawal syndromes.",
    },
    contraindications: [
      "Severe respiratory insufficiency (COPD, sleep apnea, respiratory depression)",
      "Acute narrow-angle glaucoma",
      "Concurrent opioid use (unless alternatives are inadequate — requires careful monitoring)",
      "Hepatic failure (severe)",
      "Known hypersensitivity to benzodiazepines",
    ],
    interactions: [
      "Opioids: CNS/respiratory depression → BLACK BOX WARNING",
      "Alcohol: additive CNS depression → severe respiratory depression",
      "Other CNS depressants (antihistamines, muscle relaxants, antipsychotics): additive sedation",
      "CYP3A4 inhibitors (azole antifungals, macrolides): increase clonazepam levels",
      "Valproate: synergistic anticonvulsant (may also increase risk of CNS depression)",
    ],
    monitoring: [
      "Mental status: assess cognitive function at each visit",
      "Respiratory function: O2 saturation if concurrent opioid use",
      "Dependence assessment: track dose escalation, assess for benzodiazepine use disorder",
      "CAGE-AID or AUDIT-C: screen for alcohol/substance use disorder before prescribing",
      "Taper schedule: document plan for gradual discontinuation if discontinuing",
      "Falls risk in elderly: fall assessment at each visit",
    ],
    clinicalPearls: [
      "Benzodiazepine receptor site: FREQUENCY of Cl⁻ channel opening increases (vs. barbiturates which increase DURATION — an important distinction)",
      "Benzodiazepine withdrawal is LIFE-THREATENING — seizures can occur 1–4 days after abrupt discontinuation of long-acting benzos. Never stop abruptly in dependent patients",
      "Clonazepam is longer-acting (t½ = 18–50 hours) than lorazepam (t½ = 10–20 hours) — less interdose rebound anxiety",
      "Preferred for REM sleep behavior disorder (acts on GABA receptors suppressing REM without atonia)",
      "Elderly patients: benzos are on the Beers Criteria (avoid in age > 65) — increased fall/fracture risk, cognitive impairment, paradoxical agitation",
    ],
    boardRecallTips: [
      "Benzodiazepines: increase FREQUENCY of Cl⁻ channel opening (barbiturates = DURATION)",
      "Clonazepam = long-acting BZD (t½ 18–50h); lorazepam = intermediate (10–20h)",
      "BZD withdrawal = LIFE-THREATENING (seizures/delirium); taper slowly",
      "BZD + opioids = BLACK BOX WARNING (respiratory depression/death)",
      "Beers Criteria: avoid benzos in elderly > 65 (falls, fractures, cognitive impairment)",
      "Flumazenil reverses BZD effects (competitive antagonist at BZD site) — short-acting, may need redosing",
      "Panic disorder first-line: SSRIs/SNRIs (long-term); BZDs for short-term or PRN use",
    ],
  },
  {
    id: "bm-drug-quetiapine",
    name: "Quetiapine",
    brandName: "Seroquel",
    drugClass: "Second-Generation (Atypical) Antipsychotic",
    rotationSlug: "behavioral-medicine",
    mechanism:
      "Antagonist at multiple receptors: D2 (moderate affinity — lower EPS risk), D1, 5-HT2A (high affinity — responsible for antidepressant-like effects and reduced EPS), H1 (high affinity — sedation), alpha-1 (hypotension), muscarinic M1 (anticholinergic). The active metabolite norquetiapine is a norepinephrine reuptake inhibitor (NRI) — contributes to antidepressant effects.",
    indications: [
      "Schizophrenia (acute and maintenance)",
      "Bipolar I disorder — acute mania (monotherapy)",
      "Bipolar depression (FDA approved — one of few agents with evidence for bipolar depression)",
      "Major Depressive Disorder — adjunctive therapy with antidepressant (FDA approved, XR formulation)",
      "Generalized Anxiety Disorder — adjunct (off-label but used commonly)",
      "Insomnia (off-label — low doses 25–50 mg; widely used but not FDA approved for this)",
      "Delirium (off-label)",
    ],
    dosing: {
      adult: "Schizophrenia: 150–750 mg/day in 2–3 divided doses. Bipolar mania: start 100 mg/day, increase by 100 mg/day to 400–800 mg/day. Bipolar depression: 300 mg/day at bedtime. MDD adjunct: 50–300 mg/day XR. Insomnia (off-label): 25–50 mg QHS.",
      pediatric: "Schizophrenia (age ≥ 13) and bipolar mania (age ≥ 10): start 25 mg BID, titrate to 400–600 mg/day.",
      renalAdjustment: "No adjustment needed.",
      hepaticAdjustment: "Start with lower doses — hepatically metabolized.",
    },
    sideEffects: {
      common: [
        "SEDATION: most common at low doses (strong H1 blockade) — use for insomnia benefit, but daytime somnolence is problematic",
        "Orthostatic hypotension (alpha-1 blockade) — especially on initiation",
        "Anticholinergic effects: dry mouth, constipation, urinary retention, blurred vision",
        "WEIGHT GAIN: significant (one of the highest-risk atypicals for metabolic syndrome)",
        "Dyslipidemia and hyperglycemia: metabolic syndrome risk",
      ],
      serious: [
        "METABOLIC SYNDROME: weight gain, dyslipidemia, new-onset T2DM — all atypical antipsychotics (clozapine and olanzapine worst, quetiapine intermediate risk)",
        "QTc prolongation (modest)",
        "Cataracts: lens changes reported with long-term use — baseline slit-lamp examination and every 6 months in long-term users",
        "Tardive dyskinesia: lower risk than typicals but can occur",
        "NMS: rare but possible",
      ],
      blackBox:
        "Increased mortality in elderly patients with dementia-related psychosis. Suicidality in patients < 25 years old. Do not use for dementia-related psychosis.",
    },
    contraindications: [
      "Concurrent use of QTc-prolonging drugs (monitor ECG)",
      "Known hypersensitivity",
      "Dementia-related psychosis (black box warning)",
    ],
    interactions: [
      "CYP3A4 inducers (carbamazepine, phenytoin, rifampin): reduce quetiapine levels significantly",
      "CYP3A4 inhibitors (ketoconazole, erythromycin): increase quetiapine levels",
      "QT-prolonging drugs: additive QTc risk",
      "CNS depressants: additive sedation",
      "Antihypertensives: additive hypotension",
    ],
    monitoring: [
      "Fasting glucose and HbA1c: baseline, then every 3 months × 1 year, then annually",
      "Fasting lipid panel: baseline, then every 3 months × 1 year, then annually",
      "Weight and BMI: at every visit (monthly initially)",
      "Blood pressure: baseline, then every 3 months initially",
      "AIMS scale: screen for tardive dyskinesia every 12 months",
      "ECG: baseline QTc",
      "Eye examination: baseline and every 6 months for lens changes (cataracts)",
    ],
    clinicalPearls: [
      "Quetiapine is preferred in Parkinson's disease and Lewy Body Dementia when antipsychotic is necessary (low D2 affinity = low EPS risk)",
      "One of few agents with FDA approval for BOTH acute bipolar mania and bipolar DEPRESSION",
      "Low-dose quetiapine (25–50 mg) is widely prescribed off-label for insomnia — sedation from H1 blockade, but associated with metabolic risks, falls in elderly, and carries black box warnings",
      "Metabolic monitoring is MANDATORY — glucose, lipids, weight at every visit",
      "Clozapine > Olanzapine > Quetiapine > Others for metabolic syndrome risk (roughly)",
    ],
    boardRecallTips: [
      "Atypical antipsychotics: D2 + 5-HT2A antagonism (lower EPS than typicals)",
      "Quetiapine: FDA approved for schizophrenia + bipolar mania + bipolar DEPRESSION + MDD adjunct",
      "METABOLIC syndrome monitoring = mandatory for ALL atypicals (glucose, lipids, weight)",
      "Preferred atypical in PARKINSON'S / LEWY BODY DEMENTIA (low EPS risk)",
      "Cataracts: unique quetiapine concern — slit-lamp exam monitoring",
      "Dementia + antipsychotics = BLACK BOX (increased mortality) — avoid if possible",
      "Highest metabolic risk: CLOZAPINE > olanzapine > quetiapine > risperidone > aripiprazole/ziprasidone",
    ],
  },
];
