import type { DifferentialSet } from "@/types";

export const familyMedicineDifferentials: DifferentialSet[] = [
  {
    rotation: "family-medicine",
    chiefComplaint: "Chest pain",
    differentials: [
      {
        rank: 1,
        conditionName: "Musculoskeletal Chest Pain (Costochondritis / Chest Wall)",
        likelihood: "common",
        distinguishingHistory: ["Sharp pain, reproducible with palpation or movement", "Worse with deep breathing or specific positions", "No radiation", "Recent physical activity or coughing illness"],
        distinguishingExam: ["Reproducible tenderness on palpation of costochondral junctions", "No diaphoresis or pallor", "Normal vital signs"],
        keyWorkup: ["Clinical diagnosis if classic findings", "EKG to exclude cardiac (if any doubt)", "Consider CXR to rule out pneumothorax"],
        redFlags: ["Pain radiating to jaw/left arm", "Diaphoresis or pallor", "Age >45 with cardiac risk factors"],
        clinicalPearl: "Reproducibility with palpation is the key feature. If pressing on the chest wall reproduces the pain exactly, it is likely musculoskeletal.",
      },
      {
        rank: 2,
        conditionName: "GERD / Esophageal Spasm",
        likelihood: "common",
        distinguishingHistory: ["Burning quality, substernal", "Worse after large meals, spicy/fatty food, lying down", "Relieved by antacids", "Associated with regurgitation"],
        distinguishingExam: ["Normal cardiac exam", "May have epigastric tenderness", "No reproducibility with palpation"],
        keyWorkup: ["Empiric PPI trial (2–4 weeks)", "EKG to exclude cardiac (if in doubt)", "EGD if alarm symptoms or refractory"],
        redFlags: ["Dysphagia (esophageal stricture or malignancy)", "Weight loss", "Response to nitroglycerin (can relieve esophageal spasm AND angina — not diagnostic)"],
        clinicalPearl: "GERD is the most common non-cardiac cause of chest pain. A positive PPI trial supports the diagnosis.",
      },
      {
        rank: 3,
        conditionName: "Stable Angina (CAD)",
        likelihood: "common",
        distinguishingHistory: ["Pressure/squeezing quality", "Triggered by exertion, stress, cold", "Relieved by rest or nitroglycerin in 5 minutes", "Duration 1–15 minutes", "Radiation to jaw, left arm, back"],
        distinguishingExam: ["Normal between episodes", "May have S4 gallop with LVH", "Risk factors: HTN, DM, smoking, dyslipidemia"],
        keyWorkup: ["EKG (may show LVH, prior MI changes)", "Stress testing (exercise EKG, nuclear, stress echo)", "Lipid panel, HbA1c, BMP", "Coronary CTA or coronary angiography for anatomy"],
        redFlags: ["Crescendo pattern (escalating frequency/severity)", "Rest pain >20 minutes (NSTEMI/UA)", "New ST changes on EKG"],
        clinicalPearl: "Classic angina requires all 3 criteria: (1) substernal chest discomfort, (2) provoked by exertion or stress, (3) relieved by rest or nitrates. 2 of 3 = atypical; 1 or fewer = non-cardiac.",
      },
      {
        rank: 4,
        conditionName: "Panic Disorder / Anxiety",
        likelihood: "common",
        distinguishingHistory: ["Discrete episodes of intense fear", "Associated with palpitations, dyspnea, derealization, paresthesias", "No consistent exertional trigger", "History of anxiety disorder", "Age <40, female"],
        distinguishingExam: ["Normal between episodes", "Normal EKG during evaluation", "Tachycardia may be present during attack"],
        keyWorkup: ["EKG (rule out arrhythmia)", "TSH (rule out hyperthyroidism)", "PHQ-4 or GAD-7 screening", "Holter monitor if palpitations prominent"],
        redFlags: ["New onset in >50 without prior anxiety history", "Syncope with palpitations (arrhythmia)"],
        clinicalPearl: "Panic attacks and ACS can be clinically indistinguishable. Always exclude cardiac causes, especially in patients >40 with cardiac risk factors, before attributing to panic.",
      },
      {
        rank: 5,
        conditionName: "Acute Coronary Syndrome (ACS / NSTEMI)",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Rest pain or worsening exertional pattern", "Duration >20 minutes", "Diaphoresis, nausea, dyspnea", "History of CAD or multiple risk factors"],
        distinguishingExam: ["Diaphoresis, pallor", "S3 gallop (LV dysfunction)", "Signs of heart failure (rales, JVD)"],
        keyWorkup: ["EKG immediately (ST depression, T-wave inversions, or new LBBB)", "Serial troponins q3–6h", "CBC, BMP, BNP", "Emergency cardiology consult"],
        redFlags: ["ST changes on EKG", "Rising troponin", "Hemodynamic instability", "Signs of heart failure"],
        clinicalPearl: "ACS must always be excluded first in chest pain evaluation. Troponin is the key biomarker — a single negative troponin does NOT rule out ACS. Serial measurement is required.",
      },
      {
        rank: 6,
        conditionName: "Pulmonary Embolism",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Pleuritic chest pain (sharp, worse with breathing)", "Dyspnea, tachypnea", "Risk factors: recent immobility, surgery, malignancy, pregnancy, OCP use, DVT history"],
        distinguishingExam: ["Tachycardia", "Tachypnea", "Low SpO2", "Leg asymmetry (DVT)"],
        keyWorkup: ["Wells criteria for pretest probability", "D-dimer (rule out if low/intermediate probability + negative)", "CT pulmonary angiography (gold standard)", "EKG (S1Q3T3, sinus tach)"],
        redFlags: ["SpO2 <90%", "Hemodynamic instability (massive PE)", "Syncope"],
        clinicalPearl: "Consider PE in any chest pain with dyspnea and no obvious cardiac cause, especially in patients with risk factors. The classic S1Q3T3 on EKG is specific but insensitive (occurs in ~20%).",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Cough (acute, <3 weeks)",
    differentials: [
      {
        rank: 1,
        conditionName: "Viral Upper Respiratory Infection (Common Cold)",
        likelihood: "common",
        distinguishingHistory: ["Runny nose, nasal congestion, sore throat", "Low-grade or no fever", "Symptom onset 1–3 days after exposure", "Duration typically 7–10 days"],
        distinguishingExam: ["Nasal turbinate edema, clear rhinorrhea", "Pharyngeal erythema without exudate", "Normal lung exam"],
        keyWorkup: ["Clinical diagnosis — no workup typically needed", "Consider Strep rapid test if exudative tonsillitis present", "CXR if fever >38.5°C + tachypnea + productive cough (rule out pneumonia)"],
        redFlags: ["Worsening after day 5 (secondary bacterial superinfection)", "Fever >40°C", "Stiff neck (meningitis)"],
        clinicalPearl: "The common cold is viral (rhinovirus, coronavirus) — antibiotics do NOT help and should NOT be prescribed. Set expectations: 7–10 days duration is normal.",
      },
      {
        rank: 2,
        conditionName: "Acute Bacterial Rhinosinusitis",
        likelihood: "common",
        distinguishingHistory: ["Cough with postnasal drip", "Facial pain/pressure/fullness", "Symptoms persisting >10 days or double worsening", "Purulent nasal discharge"],
        distinguishingExam: ["Facial tenderness over sinuses", "Purulent discharge on nasal exam", "Posterior pharyngeal mucus drip"],
        keyWorkup: ["Clinical diagnosis per IDSA criteria", "CT sinuses if recurrent or refractory (not for acute uncomplicated)"],
        redFlags: ["Orbital swelling (periorbital cellulitis)", "Severe headache + meningeal signs"],
        clinicalPearl: "Majority of sinusitis is viral. Reserve antibiotics for symptoms persisting >10 days, double worsening, or severe onset with fever and facial pain.",
      },
      {
        rank: 3,
        conditionName: "Asthma / Reactive Airway Disease",
        likelihood: "common",
        distinguishingHistory: ["Episodic cough, worse at night or with exercise", "History of atopy, eczema, allergic rhinitis", "Triggers: cold air, exercise, allergens", "Wheeze or chest tightness"],
        distinguishingExam: ["Expiratory wheezing on auscultation", "Prolonged expiratory phase", "Normal exam between episodes"],
        keyWorkup: ["Spirometry with bronchodilator reversibility", "Peak flow measurement", "Trial of SABA (diagnostic and therapeutic)"],
        redFlags: ["Silent chest (severe bronchospasm)", "SpO2 <90%", "Inability to speak in full sentences"],
        clinicalPearl: "Cough-variant asthma presents as ONLY cough without wheeze — it is the most commonly missed asthma presentation. Diagnose with spirometry or empiric SABA trial.",
      },
      {
        rank: 4,
        conditionName: "Community-Acquired Pneumonia",
        likelihood: "common",
        distinguishingHistory: ["Productive cough (purulent sputum)", "Fever ≥38.5°C, rigors", "Pleuritic chest pain", "Dyspnea"],
        distinguishingExam: ["Decreased breath sounds + dullness to percussion over affected area", "Egophony, whispered pectoriloquy", "Bronchial breath sounds", "Fever, tachycardia"],
        keyWorkup: ["CXR (infiltrate confirms diagnosis)", "CBC, BMP, blood cultures (if hospitalizing)", "CURB-65 to determine severity and disposition"],
        redFlags: ["SpO2 <90%", "CURB-65 ≥2 (hospitalization)", "Multilobar involvement"],
        clinicalPearl: "Do NOT make a clinical diagnosis of pneumonia without a CXR — clinical signs can be subtle, especially in elderly.",
      },
      {
        rank: 5,
        conditionName: "ACE Inhibitor-Induced Cough",
        likelihood: "less_common",
        distinguishingHistory: ["Dry, tickling, persistent cough", "Started after ACE-I initiation (days to months)", "No fever or other respiratory symptoms", "Resolves within 1–4 weeks of stopping ACE-I"],
        distinguishingExam: ["Normal lung exam", "No signs of infection"],
        keyWorkup: ["Discontinue ACE-I as diagnostic test", "Replace with ARB (losartan, valsartan) — same cardiovascular/renal benefit without cough"],
        redFlags: ["Cough persists >4 weeks after stopping ACE-I (look for another cause)"],
        clinicalPearl: "ACE-I cough is due to bradykinin accumulation (ACE normally degrades bradykinin). It occurs in 10–15% of patients, more commonly in women and Asians.",
      },
      {
        rank: 6,
        conditionName: "Pertussis (Whooping Cough)",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Catarrhal phase (1–2 weeks): mild URI symptoms", "Paroxysmal phase: severe coughing paroxysms ending in inspiratory 'whoop' + post-tussive emesis", "Adolescents/adults: may present as prolonged cough (>2 weeks) without classic whoop"],
        distinguishingExam: ["Paroxysmal coughing spells", "Post-tussive vomiting", "Normal lung exam between paroxysms", "Lymphocytosis on CBC"],
        keyWorkup: ["PCR swab (nasopharyngeal) — most sensitive within first 3 weeks", "Culture (gold standard but slow)", "CBC: lymphocytosis (absolute lymphocyte count >10,000)"],
        redFlags: ["Infants <6 months: apnea risk — hospitalize", "Post-tussive cyanosis"],
        clinicalPearl: "Think pertussis in any adult with cough >2 weeks that started with 'cold-like' symptoms. Vaccination does not confer lifelong immunity — waning immunity in adults explains adult pertussis cases.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Fatigue",
    differentials: [
      {
        rank: 1,
        conditionName: "Hypothyroidism",
        likelihood: "common",
        distinguishingHistory: ["Cold intolerance", "Weight gain", "Constipation", "Dry skin/hair", "Depression", "Myalgias"],
        distinguishingExam: ["Bradycardia", "Delayed relaxation phase of deep tendon reflexes", "Dry skin, coarse hair", "Periorbital or facial puffiness"],
        keyWorkup: ["TSH (elevated in primary hypothyroidism)", "Free T4 (low if overt)", "Anti-TPO antibodies (Hashimoto's)"],
        redFlags: ["Myxedema: hypothermia + AMS + bradycardia (medical emergency)", "Cardiac: bradycardia + pericardial effusion"],
        clinicalPearl: "TSH is the most sensitive screening test for thyroid dysfunction. A normal TSH virtually rules out primary hypothyroidism.",
      },
      {
        rank: 2,
        conditionName: "Anemia (Iron Deficiency or Other)",
        likelihood: "common",
        distinguishingHistory: ["Pallor", "Exertional dyspnea", "Palpitations", "Pica (iron deficiency specific)", "Heavy menstrual bleeding or GI symptoms"],
        distinguishingExam: ["Conjunctival pallor", "Tachycardia", "Systolic flow murmur", "Koilonychia (severe IDA)"],
        keyWorkup: ["CBC with differential", "Iron studies (ferritin, serum iron, TIBC)", "Reticulocyte count", "Peripheral blood smear"],
        redFlags: ["GI symptoms + IDA in male or postmenopausal female (colonoscopy + EGD)", "Hgb <7 with symptoms (transfusion threshold)"],
        clinicalPearl: "Ferritin is the single best test for iron deficiency — a ferritin <30 ng/mL is diagnostic. However, ferritin is an acute phase reactant and can be falsely elevated in inflammation.",
      },
      {
        rank: 3,
        conditionName: "Major Depressive Disorder",
        likelihood: "common",
        distinguishingHistory: ["Depressed mood most of the day, nearly every day", "Anhedonia (loss of interest)", "Sleep disturbance", "Appetite/weight change", "Difficulty concentrating", "Suicidal ideation"],
        distinguishingExam: ["Psychomotor retardation or agitation", "Flat affect", "Tearfulness", "PHQ-9 score ≥10"],
        keyWorkup: ["PHQ-9 screening tool", "TSH (rule out thyroid cause)", "CBC, BMP, UA (rule out medical cause)"],
        redFlags: ["Suicidal ideation with plan or intent (psychiatric emergency)", "Psychotic features (hallucinations, delusions)"],
        clinicalPearl: "Fatigue is the most common presenting complaint of depression in primary care — patients often do not spontaneously report depressed mood. Always screen with PHQ-2/PHQ-9.",
      },
      {
        rank: 4,
        conditionName: "Obstructive Sleep Apnea",
        likelihood: "common",
        distinguishingHistory: ["Non-refreshing sleep", "Snoring", "Witnessed apneas", "Excessive daytime somnolence (Epworth >10)", "Morning headaches"],
        distinguishingExam: ["Obesity (BMI ≥30)", "Large neck circumference", "Retrognathia", "Oropharyngeal crowding (Mallampati class III–IV)"],
        keyWorkup: ["STOP-BANG screening questionnaire", "Home sleep apnea test or polysomnography", "TSH (if suspected hypothyroidism contributing)"],
        redFlags: ["Oxygen nadir <80% on home sleep test", "New-onset or refractory hypertension", "Polycythemia (chronic hypoxemia)"],
        clinicalPearl: "OSA is dramatically underdiagnosed. Ask specifically about snoring and witnessed apneas — many patients do not volunteer this information.",
      },
      {
        rank: 5,
        conditionName: "Type 2 Diabetes Mellitus",
        likelihood: "common",
        distinguishingHistory: ["Polyuria, polydipsia", "Unintentional weight changes", "Recurrent infections", "Blurred vision", "Risk factors: obesity, family history"],
        distinguishingExam: ["Acanthosis nigricans (neck, axillae)", "Peripheral neuropathy signs", "BMI ≥30"],
        keyWorkup: ["Fasting glucose or HbA1c", "Urinalysis (glycosuria, proteinuria)", "Lipid panel, BMP"],
        redFlags: ["Fruity breath + nausea/vomiting + polyuria (DKA)", "Hyperglycemic hyperosmolar state (extreme thirst + altered consciousness)"],
        clinicalPearl: "Fatigue in T2DM is multifactorial: hyperglycemia impairs cellular glucose utilization, comorbid depression is common, and OSA frequently co-exists.",
      },
      {
        rank: 6,
        conditionName: "Chronic Kidney Disease",
        likelihood: "less_common",
        distinguishingHistory: ["Hypertension history", "Diabetes history", "Decreased urine output", "Nocturia", "Edema"],
        distinguishingExam: ["Pallor (renal anemia)", "Peripheral edema", "Hypertension", "Asterixis (uremia — late finding)"],
        keyWorkup: ["BMP (elevated creatinine, BUN)", "UA (proteinuria, casts)", "CBC (normochromic normocytic anemia)", "eGFR calculation"],
        redFlags: ["eGFR <15 (uremia)", "Hyperkalemia K+ >6", "Pericardial friction rub (uremic pericarditis — dialysis indication)"],
        clinicalPearl: "CKD-related anemia is normocytic normochromic anemia of chronic disease (erythropoietin deficiency). It does NOT respond to iron supplementation unless concurrent IDA exists.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Knee pain",
    differentials: [
      {
        rank: 1,
        conditionName: "Osteoarthritis of the Knee",
        likelihood: "common",
        distinguishingHistory: ["Gradual onset, >50 years", "Morning stiffness <30 minutes", "Pain worsens with activity and weight-bearing", "Relieved with rest", "Obesity, prior knee injury"],
        distinguishingExam: ["Crepitus on range of motion", "Bony enlargement (osteophytes)", "Decreased ROM", "No warmth or erythema", "Varus or valgus deformity (late)"],
        keyWorkup: ["X-ray (joint space narrowing, osteophytes, subchondral sclerosis)", "No blood tests needed for typical OA"],
        redFlags: ["Sudden joint effusion (rule out fracture, septic arthritis)", "Severe pain with any movement (fracture)"],
        clinicalPearl: "X-ray severity does NOT correlate with symptom severity — many patients with severe radiographic OA are relatively asymptomatic and vice versa.",
      },
      {
        rank: 2,
        conditionName: "Patellofemoral Pain Syndrome (Runner's Knee)",
        likelihood: "common",
        distinguishingHistory: ["Anterior knee pain", "Younger patient, active", "Worse with stairs, squatting, prolonged sitting ('theater sign')", "No effusion typically"],
        distinguishingExam: ["Pain on compression of patella against femoral groove (patellar grind/Clarke's sign)", "Patellar apprehension test (lateral subluxation fear)", "No joint line tenderness"],
        keyWorkup: ["Clinical diagnosis", "X-ray if concerned for bony pathology (Merchant/sunrise view for patella)"],
        redFlags: ["Patellar instability/dislocation history"],
        clinicalPearl: "The 'movie sign' (pain worsening with prolonged sitting in theater) is classic for PFPS — anterior knee pain that eases when you stand up.",
      },
      {
        rank: 3,
        conditionName: "Meniscal Tear",
        likelihood: "common",
        distinguishingHistory: ["Younger patient, athletic injury OR older patient with degenerative change", "Joint line pain (medial or lateral)", "Locking, clicking, giving way", "Knee swelling hours after injury"],
        distinguishingExam: ["Medial or lateral joint line tenderness", "Positive McMurray test", "Positive Thessaly test", "Effusion (hemarthrosis with tear)"],
        keyWorkup: ["MRI knee (diagnostic gold standard for soft tissue)", "X-ray to exclude bony pathology"],
        redFlags: ["Locked knee (bucket-handle tear — urgent orthopedics)"],
        clinicalPearl: "A 'pop' at the time of injury followed by rapid knee swelling (within 2 hours) suggests hemarthrosis — consider ACL tear or osteochondral fracture in addition to meniscal tear.",
      },
      {
        rank: 4,
        conditionName: "Gout (Pseudogout at Knee)",
        likelihood: "common",
        distinguishingHistory: ["Acute onset of severe pain, swelling, warmth", "May be preceded by dietary indiscretion, dehydration, surgery, or diuretic use", "History of prior gout attacks", "Middle-aged male or postmenopausal woman"],
        distinguishingExam: ["Significant erythema, warmth, swelling", "Exquisite tenderness", "Fever may be present"],
        keyWorkup: ["Joint aspiration (gold standard: monosodium urate crystals — needle-shaped, negatively birefringent)", "Serum uric acid (elevated in gout but can be normal during acute attack)", "CBC (elevated WBC)", "X-ray (soft tissue swelling, punched-out erosions in chronic gout)"],
        redFlags: ["High fever + WBC >50,000 in joint fluid (septic arthritis cannot be excluded without aspiration and culture)"],
        clinicalPearl: "ALWAYS aspirate a hot, swollen joint to exclude septic arthritis — gout and septic arthritis can coexist. The joint fluid WBC in gout is typically 10,000–100,000 (vs. >100,000 in septic arthritis).",
      },
      {
        rank: 5,
        conditionName: "Septic Arthritis",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Fever (may be absent in elderly/immunocompromised)", "Rapid onset", "Any underlying joint disease or recent joint procedure", "IV drug use", "Immunocompromised"],
        distinguishingExam: ["Exquisite tenderness", "Erythema, warmth, swelling", "Refusal to move joint", "Fever, tachycardia"],
        keyWorkup: ["URGENT joint aspiration — WBC >50,000 with >90% PMNs + positive Gram stain/culture = septic arthritis", "Blood cultures (50% positive)", "CBC, ESR, CRP", "X-ray"],
        redFlags: ["Any hot swollen joint in febrile or immunocompromised patient is septic arthritis until proven otherwise"],
        clinicalPearl: "Septic arthritis is a surgical emergency — delay in diagnosis causes rapid articular cartilage destruction. Never leave a hot swollen joint unevaluated with only clinical examination.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Low back pain",
    differentials: [
      {
        rank: 1,
        conditionName: "Acute Mechanical / Nonspecific Low Back Pain",
        likelihood: "common",
        distinguishingHistory: ["Acute onset (often with lifting or twisting)", "Limited to lumbar spine, no radiation below knee", "Improves with rest", "No neurologic symptoms"],
        distinguishingExam: ["Paraspinal muscle tenderness and spasm", "Reduced lumbar range of motion", "Normal neurologic exam", "No CVA tenderness"],
        keyWorkup: ["Clinical diagnosis — no imaging needed in first 6 weeks without red flags", "Reassurance and conservative management"],
        redFlags: ["Symptoms lasting >6 weeks without improvement", "Red flag symptoms (fever, weight loss, neurologic deficits, incontinence)"],
        clinicalPearl: "90% of acute mechanical LBP resolves within 4–6 weeks with conservative management. Avoid routine imaging — it increases patient anxiety and unnecessary procedures.",
      },
      {
        rank: 2,
        conditionName: "Lumbar Radiculopathy (Sciatica)",
        likelihood: "common",
        distinguishingHistory: ["Pain radiating below the knee in a dermatomal pattern", "L4: medial calf; L5: dorsum of foot, big toe; S1: lateral foot, heel", "Exacerbated by Valsalva (cough, sneeze)", "Paresthesias or weakness in leg"],
        distinguishingExam: ["Positive straight leg raise (SLR) at <45° highly suggestive", "Dermatomal sensory loss", "Reflex changes: L4 (knee jerk); S1 (ankle jerk)"],
        keyWorkup: ["Clinical diagnosis initially", "MRI lumbar spine (preferred — shows herniated disc, nerve root compression) if symptoms persist >6 weeks or with neurologic deficits"],
        redFlags: ["Bilateral leg weakness or saddle anesthesia (cauda equina)", "Progressive motor deficit"],
        clinicalPearl: "Pain radiating BELOW the knee (not just to the buttock) distinguishes true radiculopathy from referred pain. The crossed SLR (reproduces contralateral leg pain) is highly specific for disc herniation.",
      },
      {
        rank: 3,
        conditionName: "Lumbar Spinal Stenosis",
        likelihood: "common",
        distinguishingHistory: ["Older patient (>60)", "Neurogenic claudication: bilateral leg pain/weakness/heaviness with walking", "Relieved by sitting, flexion, or leaning forward (shopping cart sign)", "Worsened by extension (standing, walking downhill)"],
        distinguishingExam: ["Normal straight leg raise (distinguishes from disc herniation)", "Pain reproduced with lumbar extension", "Decreased reflexes", "Normal peripheral pulses (distinguish from vascular claudication)"],
        keyWorkup: ["MRI lumbar spine (shows spinal canal narrowing, ligamentum flavum hypertrophy)", "Ankle-brachial index (if vascular claudication considered)"],
        redFlags: ["Bowel/bladder dysfunction (cauda equina syndrome)"],
        clinicalPearl: "The key distinction: neurogenic claudication (spinal stenosis) is RELIEVED by flexion/sitting; vascular claudication is relieved by STANDING STILL.",
      },
      {
        rank: 4,
        conditionName: "Vertebral Compression Fracture",
        likelihood: "less_common",
        distinguishingHistory: ["Acute severe LBP after minor trauma or no trauma in elderly", "History of osteoporosis or corticosteroid use", "Postmenopausal woman or older man", "Point tenderness over spinous process"],
        distinguishingExam: ["Focal spinous process tenderness", "Loss of height", "Kyphosis"],
        keyWorkup: ["X-ray lumbar spine (anterior wedge compression — loss of vertebral height)", "DEXA scan (confirm osteoporosis)", "MRI if neurologic involvement or to differentiate acute vs. chronic fracture"],
        redFlags: ["Multiple compression fractures in young patient (malignancy, hyperparathyroidism)", "Neurologic deficits with fracture"],
        clinicalPearl: "Vertebral compression fractures are often painless and discovered incidentally on X-ray. When painful, they are exquisitely tender to percussion on the affected spinous process.",
      },
      {
        rank: 5,
        conditionName: "Cauda Equina Syndrome",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Severe LBP with bilateral leg weakness", "Saddle anesthesia (perianal, perineal numbness)", "Urinary incontinence or retention (most important sign)", "Fecal incontinence"],
        distinguishingExam: ["Saddle anesthesia on sensory exam", "Decreased anal sphincter tone on rectal exam", "Bilateral lower extremity weakness or absent reflexes"],
        keyWorkup: ["EMERGENCY MRI lumbar spine (do not delay for consent or routine scheduling)", "Urgent neurosurgical consultation"],
        redFlags: ["ANY urinary/fecal incontinence or retention + LBP = cauda equina until proven otherwise"],
        clinicalPearl: "Cauda equina syndrome is a SURGICAL EMERGENCY. Every hour of delay in decompression increases the risk of permanent bowel/bladder/sexual dysfunction. Do not wait — MRI and surgery tonight.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Headache",
    differentials: [
      {
        rank: 1,
        conditionName: "Tension-Type Headache",
        likelihood: "common",
        distinguishingHistory: ["Bilateral, band-like or pressing quality (non-pulsating)", "Mild to moderate intensity", "No nausea/vomiting", "Not aggravated by routine physical activity", "Stress, poor sleep, dehydration triggers"],
        distinguishingExam: ["Normal neurologic exam", "Pericranial muscle tenderness", "No photophobia/phonophobia (or mild, not both)", "No papilledema"],
        keyWorkup: ["Clinical diagnosis — no imaging if typical presentation", "No workup if headache has been the same for years"],
        redFlags: ["Sudden onset or 'worst headache of life'", "New pattern after age 50", "Position-related (worse lying down = raised ICP)"],
        clinicalPearl: "Tension-type headache is bilateral, pressing/tightening, and mild-to-moderate — the 'vice grip' around the head. Migraine is typically unilateral, pulsating, moderate-severe, with nausea.",
      },
      {
        rank: 2,
        conditionName: "Migraine Without Aura",
        likelihood: "common",
        distinguishingHistory: ["Unilateral, pulsating/throbbing", "Moderate to severe intensity", "Nausea +/- vomiting", "Photophobia AND phonophobia", "Lasts 4–72 hours", "Worsens with activity", "Menstrual trigger (menstrual migraine)"],
        distinguishingExam: ["Normal neurologic exam between attacks", "Photophobia during attack", "Phonophobia", "No papilledema"],
        keyWorkup: ["Clinical diagnosis using ICHD-3 criteria (5 attacks lasting 4–72h with ≥2 of: unilateral, pulsating, moderate-severe, worsened by activity; PLUS ≥1 of: nausea/vomiting, photophobia + phonophobia)", "No routine imaging for typical migraine"],
        redFlags: ["First/worst headache ever (thunderclap = SAH)", "Headache with fever + meningismus", "New focal neurologic symptoms"],
        clinicalPearl: "The 5-4-3-2-1 rule: 5 attacks, 4–72 hours, 3 POUNDING criteria (2 of: unilateral, throbbing, mod-severe, worsened by activity), 2 associated symptoms (nausea or photophobia + phonophobia), 1 diagnosis.",
      },
      {
        rank: 3,
        conditionName: "Cluster Headache",
        likelihood: "less_common",
        distinguishingHistory: ["Unilateral SEVERE periorbital/retro-orbital pain (9–10/10)", "Duration 15–180 minutes", "Occurs in clusters (daily attacks for weeks, then remission)", "Circadian pattern (often awakens patient at same time of night)", "Male predominance 3:1", "Associated autonomic features: ipsilateral lacrimation, nasal congestion, ptosis, miosis"],
        distinguishingExam: ["Agitated patient (unlike migraine — migraineurs prefer to lie still)", "Ipsilateral ptosis, miosis (partial Horner's)", "Ipsilateral rhinorrhea/lacrimation during attack"],
        keyWorkup: ["Clinical diagnosis", "MRI brain to exclude structural cause (especially pituitary lesion — can mimic cluster)"],
        redFlags: ["Pituitary apoplexy (sudden onset + visual changes + endocrine symptoms)"],
        clinicalPearl: "Cluster headache patients are AGITATED and pace during attacks (migraineurs prefer stillness). 100% O2 at 12–15 L/min via non-rebreather is the acute treatment of choice — works in 15 minutes.",
      },
      {
        rank: 4,
        conditionName: "Subarachnoid Hemorrhage",
        likelihood: "must_not_miss",
        distinguishingHistory: ["'Thunderclap headache' — worst headache of life, reaching maximal intensity within seconds", "May occur during exertion, sexual activity", "Nausea, vomiting, photophobia", "LOC or presyncope at onset"],
        distinguishingExam: ["Meningismus (neck stiffness, Kernig's, Brudzinski's)", "Papilledema (raised ICP)", "Fundoscopic: subhyaloid hemorrhage (Terson syndrome)", "Focal deficits (if associated AVM or vasospasm)"],
        keyWorkup: ["NON-CONTRAST HEAD CT immediately (90–95% sensitive if done within 6 hours)", "LP if CT negative but clinical suspicion high (xanthochromia, elevated RBCs that don't clear)"],
        redFlags: ["Thunderclap headache IS subarachnoid hemorrhage until proven otherwise — do not dismiss"],
        clinicalPearl: "The sentinel headache (warning bleed) occurs in 30–50% of SAH patients days to weeks before the major bleed. Missing the sentinel headache is a common missed diagnosis. NEVER dismiss a 'worst headache of life.'",
      },
      {
        rank: 5,
        conditionName: "Idiopathic Intracranial Hypertension (Pseudotumor Cerebri)",
        likelihood: "less_common",
        distinguishingHistory: ["Obese woman of childbearing age", "Diffuse headache, often positional (worse lying down)", "Pulsatile tinnitus", "Visual obscurations (brief vision loss)", "No focal neurologic deficits"],
        distinguishingExam: ["Papilledema (bilateral, key finding)", "CN VI palsy (false localizing sign)", "Visual field defect (enlarged blind spot)", "Normal mental status"],
        keyWorkup: ["MRI brain (rule out mass — normal or 'empty sella')", "LP: elevated opening pressure >25 cmH2O with normal CSF composition"],
        redFlags: ["Rapid progressive visual loss (urgent ophthalmology referral — optic nerve decompression)"],
        clinicalPearl: "Obesity is the single greatest risk factor. The triad: obese woman + papilledema + elevated CSF pressure with normal composition = IIH. Weight loss is the most effective long-term treatment.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Rash",
    differentials: [
      {
        rank: 1,
        conditionName: "Contact Dermatitis (Allergic or Irritant)",
        likelihood: "common",
        distinguishingHistory: ["Pruritic rash at site of contact with allergen/irritant", "Clear exposure history: poison ivy, nickel jewelry, latex, soap", "Allergic: delayed reaction (24–72h); Irritant: more immediate"],
        distinguishingExam: ["Erythema, vesicles, weeping in geometric/linear distribution matching contact area", "Well-demarcated edges", "No systemic features"],
        keyWorkup: ["Clinical diagnosis", "Patch testing for suspected allergic cause (dermatology referral)"],
        redFlags: ["Extensive involvement with systemic symptoms (anaphylaxis risk)", "Secondary infection signs"],
        clinicalPearl: "The linear distribution of poison ivy rash (following the scratch line from plant contact) is pathognomonic for allergic contact dermatitis.",
      },
      {
        rank: 2,
        conditionName: "Atopic Dermatitis (Eczema)",
        likelihood: "common",
        distinguishingHistory: ["Chronic, relapsing pruritic rash", "History of atopy (asthma, allergic rhinitis)", "Childhood onset common", "Triggered by irritants, stress, infections", "Dry skin"],
        distinguishingExam: ["Flexural distribution (antecubital, popliteal fossae)", "Lichenification with chronic disease", "Excoriation marks", "Xerosis (dry skin)"],
        keyWorkup: ["Clinical diagnosis using Hanifin-Rajka criteria or simplified criteria", "IgE levels (often elevated but not required)", "Patch test if contact allergy suspected"],
        redFlags: ["Eczema herpeticum (Kaposi varicelliform eruption): disseminated HSV in eczema — fever + punched-out erosions = emergency antiviral treatment"],
        clinicalPearl: "In infants, eczema involves the cheeks and extensor surfaces; in older children and adults, flexural areas predominate. Treatment: moisturizers + topical steroids; newer biologics (dupilumab) for moderate-severe.",
      },
      {
        rank: 3,
        conditionName: "Psoriasis (Plaque Type)",
        likelihood: "common",
        distinguishingHistory: ["Chronic, recurrent", "Silver-white scaly plaques", "Triggers: stress, infections, medications (beta-blockers, lithium, NSAIDs)", "Family history"],
        distinguishingExam: ["Well-demarcated erythematous plaques with silver scale", "Extensor surfaces (elbows, knees), scalp, lumbosacral area", "Auspitz sign (pinpoint bleeding on scale removal)", "Nail changes: pitting, onycholysis, oil spots"],
        keyWorkup: ["Clinical diagnosis", "Skin biopsy if uncertain", "Screen for psoriatic arthritis (joint pain, dactylitis, enthesitis)"],
        redFlags: ["Erythrodermic psoriasis (>90% BSA — medical emergency)", "Pustular psoriasis (systemic involvement)"],
        clinicalPearl: "Psoriasis and psoriatic arthritis are associated with metabolic syndrome and cardiovascular disease — screen these patients for diabetes, hypertension, and dyslipidemia.",
      },
      {
        rank: 4,
        conditionName: "Herpes Zoster (Shingles)",
        likelihood: "common",
        distinguishingHistory: ["Prodrome: burning/tingling pain 1–5 days before rash", "Dermatomal distribution (thoracic most common)", "Unilateral, does not cross midline", "History of prior varicella infection or vaccine", "Older or immunocompromised"],
        distinguishingExam: ["Grouped vesicles on erythematous base in dermatomal distribution", "Does NOT cross midline"],
        keyWorkup: ["Clinical diagnosis", "PCR swab for VZV if uncertain (immunocompromised or atypical presentation)"],
        redFlags: ["Herpes zoster ophthalmicus (V1 — nasociliary branch): vesicles on nose tip (Hutchinson's sign) + eye involvement — urgent ophthalmology", "Ramsay Hunt syndrome: CN VII + CN VIII involvement (facial palsy + otalgia + ear vesicles)"],
        clinicalPearl: "Treat within 72 hours of rash onset (or any time if new vesicles still appearing) with antivirals (acyclovir/valacyclovir) to reduce severity and risk of postherpetic neuralgia. Recommend Shingrix vaccine for all patients ≥50.",
      },
      {
        rank: 5,
        conditionName: "Cellulitis",
        likelihood: "common",
        distinguishingHistory: ["Acute onset unilateral redness, warmth, swelling", "May follow trauma, insect bite, tinea pedis", "Fever common", "Most often lower extremity"],
        distinguishingExam: ["Non-demarcated erythema, warm to touch", "Tender", "May have lymphangitis (red streaking)", "Regional lymphadenopathy"],
        keyWorkup: ["Clinical diagnosis", "CBC (leukocytosis)", "Blood cultures (if fever or immunocompromised)", "Consider ultrasound to exclude abscess requiring I&D"],
        redFlags: ["Pain out of proportion + skin necrosis + crepitus (necrotizing fasciitis — surgical emergency)", "Rapidly advancing edge despite antibiotics", "Orbital cellulitis (proptosis, ophthalmoplegia)"],
        clinicalPearl: "DVT can mimic or coexist with lower extremity cellulitis. Bilateral lower leg 'cellulitis' is almost never true cellulitis — consider bilateral DVT, venous stasis, or lipodermatosclerosis.",
      },
      {
        rank: 6,
        conditionName: "Meningococcemia",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Young patient (college students, daycare)", "Fever + headache + stiff neck", "Rapidly spreading purpuric/petechial rash", "Septic appearance"],
        distinguishingExam: ["Non-blanching petechiae and purpura (palpable purpura)", "Fever, hypotension, tachycardia", "Meningismus"],
        keyWorkup: ["Blood cultures IMMEDIATELY (before antibiotics if possible)", "LP (if no papilledema/no herniation signs)", "CBC (leukocytosis), CMP, coagulation studies (DIC)", "Emergency antibiotics (ceftriaxone 2g IV) — do NOT delay for LP"],
        redFlags: ["Non-blanching petechial/purpuric rash in febrile patient = meningococcemia until proven otherwise — this is a dermatologic EMERGENCY"],
        clinicalPearl: "The glass test: non-blanching rash does not fade when you press a glass against it. Blanching = vasodilation; non-blanching = hemorrhage (petechiae/purpura). Non-blanching + fever = antibiotics now, workup later.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Elevated blood pressure (found incidentally)",
    differentials: [
      {
        rank: 1,
        conditionName: "Essential (Primary) Hypertension",
        likelihood: "common",
        distinguishingHistory: ["No identifiable underlying cause", "Positive family history", "Obesity, sedentary lifestyle, high-sodium diet", "Adult >30–40 years", "Gradual onset"],
        distinguishingExam: ["Elevated BP on ≥2 readings", "May have LVH signs (loud S4, displaced PMI)", "Fundoscopic: AV nicking, copper wiring (chronic HTN)"],
        keyWorkup: ["Confirm BP on 2 separate occasions or use ABPM/home BP monitoring", "Basic workup: BMP, CBC, UA, fasting glucose, lipid panel, EKG"],
        redFlags: ["BP >180/120 (hypertensive urgency/emergency)", "End-organ damage signs"],
        clinicalPearl: "Primary HTN is a diagnosis of exclusion — rule out secondary causes (especially in young patients, resistant HTN, or hypokalemia) before committing to lifetime antihypertensive therapy.",
      },
      {
        rank: 2,
        conditionName: "White-Coat Hypertension",
        likelihood: "common",
        distinguishingHistory: ["BP elevated in office but normal at home", "Anxiety around medical settings", "No evidence of end-organ damage", "No cardiovascular risk factors"],
        distinguishingExam: ["Elevated office BP", "Normal home BP readings"],
        keyWorkup: ["Home blood pressure monitoring (twice daily x7 days, average excluding first day)", "Ambulatory blood pressure monitoring (ABPM) — gold standard (average <130/80 out-of-office = white-coat)"],
        redFlags: ["Masked hypertension: normal office BP but elevated home readings — check ABPM if suspicious"],
        clinicalPearl: "White-coat hypertension is NOT entirely benign — it carries an intermediate cardiovascular risk between normal BP and sustained hypertension. Monitor every 1–2 years.",
      },
      {
        rank: 3,
        conditionName: "Primary Aldosteronism (Conn's Syndrome)",
        likelihood: "less_common",
        distinguishingHistory: ["Hypertension + hypokalemia (may be asymptomatic)", "Resistant HTN (>3 drugs)", "Spontaneous hypokalemia", "Young age of onset", "Muscle weakness, fatigue, polyuria"],
        distinguishingExam: ["Hypertension", "Hypokalemia signs: muscle weakness, cramps"],
        keyWorkup: ["Aldosterone-to-renin ratio (ARR) — screen: aldosterone >10 ng/dL + ARR >20–30 suspicious", "Confirmatory: 24-hour urine aldosterone after sodium loading or saline suppression test", "Adrenal CT + adrenal vein sampling"],
        redFlags: ["Hypokalemia K+ <3.0 + HTN (primary aldosteronism until proven otherwise)"],
        clinicalPearl: "Primary aldosteronism is MUCH more common than previously thought — affects ~5–10% of hypertensives. Screen all patients with resistant HTN, spontaneous hypokalemia, or adrenal incidentaloma + HTN.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Elevated blood glucose found incidentally (possible diabetes)",
    differentials: [
      {
        rank: 1,
        conditionName: "Type 2 Diabetes Mellitus",
        likelihood: "common",
        distinguishingHistory: ["Obesity", "Physical inactivity", "Family history of T2DM", "History of gestational diabetes", "May be asymptomatic", "Mild polyuria/polydipsia"],
        distinguishingExam: ["Acanthosis nigricans", "Obesity (BMI ≥30)", "Peripheral neuropathy signs (late)"],
        keyWorkup: ["Confirm: FPG ≥126 on 2 occasions, OR HbA1c ≥6.5% confirmed, OR OGTT ≥200", "BMP, CBC, UA, lipid panel, urine albumin-to-creatinine ratio", "Foot exam, dilated eye exam referral"],
        redFlags: ["FPG >300 + symptoms (consider DKA in any patient)", "Unexplained weight loss (consider LADA or T1DM)"],
        clinicalPearl: "Confirm elevated glucose on a repeat test (unless patient is symptomatic + random glucose ≥200) — a single glucose value is not diagnostic. Glucose can be transiently elevated from stress, illness, or steroids.",
      },
      {
        rank: 2,
        conditionName: "Prediabetes",
        likelihood: "common",
        distinguishingHistory: ["FPG 100–125 (IFG), or HbA1c 5.7–6.4%, or 2h OGTT 140–199", "Obesity, sedentary", "Family history", "Prior gestational diabetes"],
        distinguishingExam: ["Overweight/obese", "Acanthosis nigricans (insulin resistance marker)"],
        keyWorkup: ["ADA criteria confirmation", "Annual HbA1c monitoring", "USPSTF: screen with lifestyle intervention (DPP program)", "Consider metformin in BMI ≥35 + age <60 + prior GDM"],
        redFlags: ["Rapid progression to overt diabetes within 1 year"],
        clinicalPearl: "Lifestyle intervention (7% weight loss + 150 min/week moderate activity) reduces progression from prediabetes to T2DM by 58% (Diabetes Prevention Program, 2002).",
      },
      {
        rank: 3,
        conditionName: "Steroid-Induced Hyperglycemia",
        likelihood: "common",
        distinguishingHistory: ["Recent corticosteroid use (oral, IV, inhaled — high dose)", "Hyperglycemia peaks 6–8 hours after AM dose", "No prior diabetes history"],
        distinguishingExam: ["Cushingoid features if prolonged steroid use"],
        keyWorkup: ["Blood glucose log (home monitoring)", "HbA1c (may be normal if recent onset)", "Monitor for persistent hyperglycemia after steroids discontinued"],
        redFlags: ["Glucose >300 with nausea/vomiting (DKA in a T1DM/LADA patient on steroids)"],
        clinicalPearl: "Steroid-induced hyperglycemia predominantly affects postprandial glucose and peaks in the afternoon. NPH insulin at noon matches the steroid's peak glucose effect — a useful clinical tool.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Shortness of breath",
    differentials: [
      {
        rank: 1,
        conditionName: "Asthma Exacerbation",
        likelihood: "common",
        distinguishingHistory: ["Known asthma", "Allergic trigger, URI, exercise, or cold exposure", "Wheeze, chest tightness", "Response to prior albuterol use"],
        distinguishingExam: ["Expiratory wheeze", "Prolonged expiration", "Accessory muscle use in severe exacerbation", "SpO2 often normal-low"],
        keyWorkup: ["Peak flow measurement (pre/post bronchodilator)", "SpO2", "CXR if first episode or unclear diagnosis"],
        redFlags: ["Silent chest (no wheeze = near-fatal bronchospasm)", "SpO2 <90%", "Altered mental status"],
        clinicalPearl: "In an acute asthma exacerbation, a normal PaCO2 is NOT reassuring — it suggests respiratory muscle fatigue and impending failure. PaCO2 should be LOW (hyperventilation) in mild-moderate asthma.",
      },
      {
        rank: 2,
        conditionName: "Heart Failure (Acute Decompensation)",
        likelihood: "common",
        distinguishingHistory: ["Orthopnea (dyspnea lying flat — number of pillows)", "PND (paroxysmal nocturnal dyspnea)", "Ankle edema", "History of CAD, HTN, prior HF"],
        distinguishingExam: ["Bibasilar crackles (pulmonary edema)", "Elevated JVP", "S3 gallop", "Peripheral edema", "Displaced PMI"],
        keyWorkup: ["CXR (cardiomegaly, Kerley B lines, pulmonary vascular congestion, pleural effusions)", "BNP or NT-proBNP (elevated)", "EKG", "Echo (assess EF)"],
        redFlags: ["SpO2 <90% (pulmonary edema)", "Rapidly rising troponin (acute MI triggering HF)"],
        clinicalPearl: "BNP >100 pg/mL (or NT-proBNP >300) supports heart failure as cause of dyspnea. BNP <100 essentially rules out HF as cause of dyspnea. Very useful in the ED and office to guide workup.",
      },
      {
        rank: 3,
        conditionName: "Pulmonary Embolism",
        likelihood: "must_not_miss",
        distinguishingHistory: ["Sudden onset dyspnea", "Pleuritic chest pain", "Risk factors: immobility, surgery, malignancy, DVT, OCP", "Tachycardia out of proportion to symptoms"],
        distinguishingExam: ["Tachycardia", "Tachypnea", "Low SpO2", "Leg asymmetry (DVT)"],
        keyWorkup: ["Wells PE score → D-dimer (if low/intermediate probability)", "CTPA (CT pulmonary angiography) — gold standard", "EKG (sinus tach, S1Q3T3, new RBBB)", "Lower extremity Doppler US (if CTPA not available)"],
        redFlags: ["Hemodynamic instability (massive PE → systemic thrombolysis or embolectomy)"],
        clinicalPearl: "Tachycardia disproportionate to the degree of dyspnea in a patient with risk factors = think PE. A PERC-negative low-risk patient can be discharged without D-dimer or imaging.",
      },
      {
        rank: 4,
        conditionName: "COPD Exacerbation",
        likelihood: "common",
        distinguishingHistory: ["Known COPD", "Increased dyspnea, sputum production, and/or cough", "Recent URI or cold exposure", "Smoking history"],
        distinguishingExam: ["Diffuse expiratory wheeze and prolonged expiration", "Barrel chest", "Accessory muscle use", "Pursed-lip breathing"],
        keyWorkup: ["SpO2, ABG (in severe exacerbation)", "CXR (rule out pneumonia, pneumothorax)", "CBC, BMP", "Peak flow or spirometry if available"],
        redFlags: ["PaCO2 rising (hypercapnic respiratory failure — need NIV)", "AMS (CO2 narcosis)"],
        clinicalPearl: "In COPD exacerbation, target SpO2 88–92% (NOT >95%) — over-oxygenation can suppress the hypoxic respiratory drive in chronic CO2 retainers.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "Sore throat",
    differentials: [
      {
        rank: 1,
        conditionName: "Viral Pharyngitis",
        likelihood: "common",
        distinguishingHistory: ["Associated with URI symptoms (rhinorrhea, cough, congestion)", "Gradual onset", "Low-grade or no fever", "Adenovirus, EBV, rhinovirus most common"],
        distinguishingExam: ["Pharyngeal erythema +/- mild exudate", "Tender anterior cervical lymphadenopathy", "Rhinorrhea, conjunctivitis (adenovirus = pharyngoconjunctival fever)"],
        keyWorkup: ["Clinical diagnosis — no strep test needed if clearly viral (cough + congestion present)", "Monospot test if EBV suspected (young adult, fatigue, hepatosplenomegaly, posterior LAD)"],
        redFlags: ["Drooling + inability to swallow (peritonsillar abscess or epiglottitis)", "Trismus (peritonsillar abscess)"],
        clinicalPearl: "The presence of COUGH makes streptococcal pharyngitis much less likely (Centor/McIsaac criteria). Prescribing antibiotics for viral pharyngitis contributes to antibiotic resistance.",
      },
      {
        rank: 2,
        conditionName: "Streptococcal Pharyngitis (Group A Strep)",
        likelihood: "common",
        distinguishingHistory: ["Sudden onset severe sore throat", "Fever >38°C", "Absence of cough (key distinguishing feature)", "Headache, abdominal pain in children", "Exposure to strep"],
        distinguishingExam: ["Pharyngeal erythema + tonsillar exudate", "Tender anterior cervical lymphadenopathy", "Palatal petechiae", "Scarlatiniform rash (scarlet fever — sandpaper-like, sparing perioral)"],
        keyWorkup: ["Rapid strep antigen test (85–90% sensitive, 95–99% specific)", "Throat culture (backup if rapid test negative + high suspicion in children)"],
        redFlags: ["Peritonsillar abscess (uvular deviation, trismus, 'hot potato' voice)", "Signs of rheumatic fever (carditis, migratory polyarthritis, chorea)"],
        clinicalPearl: "Centor/McIsaac criteria: Tonsillar exudate (1) + tender anterior LAD (1) + no cough (1) + fever >38°C (1) + age <15 (+1) or >45 (-1). Score ≥3 → test; ≥4 → treat empirically.",
      },
      {
        rank: 3,
        conditionName: "Infectious Mononucleosis (EBV)",
        likelihood: "common",
        distinguishingHistory: ["Young adult (15–25 years)", "Severe pharyngitis with exudate", "Profound fatigue (lasting weeks)", "Posterior cervical lymphadenopathy (key — strep has anterior)"],
        distinguishingExam: ["Splenomegaly (50%)", "Posterior cervical lymphadenopathy", "Bilateral tonsillar hypertrophy", "Periorbital edema (Hoagland's sign)", "Maculopapular rash if given amoxicillin (70–100%)"],
        keyWorkup: ["Monospot test (heterophile antibodies — specific but can be negative early)", "EBV-specific antibodies (VCA-IgM, EA-D) if monospot negative + strong suspicion", "CBC: lymphocytosis with atypical lymphocytes", "LFTs (transaminitis in 80%)"],
        redFlags: ["Splenomegaly + contact sports (risk of splenic rupture — no contact sports for ≥3–4 weeks after diagnosis)", "Airway compromise from massive tonsillar hypertrophy"],
        clinicalPearl: "NEVER give amoxicillin for sore throat without ruling out EBV — the classic maculopapular rash is a clinical clue to the diagnosis. The monospot can be negative in the first week — repeat or use EBV-specific antibodies.",
      },
      {
        rank: 4,
        conditionName: "Peritonsillar Abscess",
        likelihood: "less_common",
        distinguishingHistory: ["Severe unilateral throat pain", "Difficulty swallowing (odynophagia)", "Trismus (jaw stiffness — cannot open mouth fully)", "'Hot potato' muffled voice", "Prior episodes of tonsillitis"],
        distinguishingExam: ["Uvular deviation to opposite side", "Peritonsillar bulge (unilateral tonsillar fullness)", "Drooling", "Trismus"],
        keyWorkup: ["Clinical diagnosis", "CT neck with IV contrast if uncertain or to guide aspiration", "I&D or needle aspiration (diagnostic + therapeutic)"],
        redFlags: ["Spreading cellulitis into neck (Ludwig's angina, parapharyngeal abscess — airway emergency)", "Inability to protect airway"],
        clinicalPearl: "Trismus + uvular deviation = peritonsillar abscess until proven otherwise. This is the most common deep neck space infection and requires immediate ENT referral and aspiration.",
      },
    ],
  },
  {
    rotation: "family-medicine",
    chiefComplaint: "URI symptoms (runny nose, congestion, low-grade fever)",
    differentials: [
      {
        rank: 1,
        conditionName: "Common Cold (Viral URI)",
        likelihood: "common",
        distinguishingHistory: ["Nasal congestion, rhinorrhea (initially clear, may become mucopurulent), sneezing", "Sore throat (mild)", "Low-grade fever or afebrile", "Mild malaise", "Duration 7–10 days", "Cough (post-nasal drip)"],
        distinguishingExam: ["Turbinate edema, clear/white rhinorrhea", "Mild pharyngeal erythema", "Normal lung exam"],
        keyWorkup: ["No testing needed for typical presentation", "Consider flu swab if influenza season + fever + myalgias + abrupt onset"],
        redFlags: ["Worsening after day 5 (may be bacterial superinfection)", "High fever >39°C (consider flu or bacterial complication)"],
        clinicalPearl: "The color of nasal discharge (yellow/green) does NOT indicate bacterial infection — it simply reflects neutrophil activity as the immune response progresses. Antibiotics are NOT indicated for color change alone.",
      },
      {
        rank: 2,
        conditionName: "Influenza",
        likelihood: "common",
        distinguishingHistory: ["Abrupt onset within hours", "High fever >38.5°C", "Prominent myalgias and arthralgias", "Severe fatigue and headache", "Dry cough", "Less rhinorrhea than common cold", "Epidemic season (November–March)"],
        distinguishingExam: ["Fever, flushed appearance", "Pharyngeal erythema", "Myalgias on palpation", "Normal lungs (unless viral pneumonia)"],
        keyWorkup: ["Rapid influenza diagnostic test (RIDT): 50–70% sensitive (clinical diagnosis in epidemic season if negative)", "PCR nasopharyngeal swab (most accurate)", "CXR if respiratory compromise"],
        redFlags: ["Secondary bacterial pneumonia (worsening after initial improvement)", "Myocarditis (chest pain + arrhythmia during flu illness)", "Encephalitis (AMS)"],
        clinicalPearl: "Influenza classically causes 'knocked off feet' illness — a patient who walked into the office 2 hours ago feeling fine is now severely ill. This abrupt severity distinguishes flu from the common cold.",
      },
      {
        rank: 3,
        conditionName: "Allergic Rhinitis",
        likelihood: "common",
        distinguishingHistory: ["Clear watery rhinorrhea", "Sneezing paroxysms", "Itchy nose, eyes, palate", "Seasonal or perennial pattern", "Known allergies or atopic history", "No fever"],
        distinguishingExam: ["Pale, boggy, bluish nasal turbinates (characteristic)", "Allergic shiners (dark circles under eyes)", "Transverse nasal crease (allergic salute)", "Cobblestoning of posterior pharynx"],
        keyWorkup: ["Clinical diagnosis", "Skin prick testing or allergen-specific IgE panel (if allergen immunotherapy planned)"],
        redFlags: ["Unilateral nasal obstruction + blood-tinged discharge (nasal polyp vs. malignancy)"],
        clinicalPearl: "Pale, bluish, boggy turbinates = allergic rhinitis. Red, erythematous turbinates = viral URI. This is the key exam finding distinguishing the two.",
      },
      {
        rank: 4,
        conditionName: "COVID-19",
        likelihood: "common",
        distinguishingHistory: ["Fever, cough, fatigue", "Anosmia/dysgeusia (loss of smell/taste) — characteristic", "Myalgias, headache", "May have GI symptoms", "Variable severity: mild URI to severe pneumonia"],
        distinguishingExam: ["Variable presentation", "Anosmia (key clue)", "Fever, tachycardia if more severe", "CXR/CT: bilateral ground-glass opacities (severe)"],
        keyWorkup: ["COVID-19 rapid antigen test or PCR", "CXR if respiratory compromise", "CBC (lymphopenia), CRP, ferritin, D-dimer (if hospitalized)"],
        redFlags: ["SpO2 <94% (hypoxia despite comfortable appearance = 'happy hypoxia' — admit)", "High inflammatory markers (cytokine storm)"],
        clinicalPearl: "Anosmia (loss of smell) is highly specific for COVID-19 and rarely occurs with other respiratory viruses — ask about it routinely in URI presentations.",
      },
    ],
  },
];
