// @ts-nocheck
import { Procedure } from "@/types/seed";

export const generalSurgeryProcedures: Procedure[] = [
  {
    id: "gs-proc-paracentesis",
    rotation: "general-surgery",
    name: "Diagnostic and Therapeutic Paracentesis",
    overview:
      "Paracentesis is the aspiration of peritoneal (ascitic) fluid from the abdominal cavity. Diagnostic paracentesis (20–50 mL) evaluates the etiology of ascites and detects spontaneous bacterial peritonitis (SBP). Therapeutic paracentesis (large-volume, > 5 L) relieves symptoms of tense ascites — abdominal discomfort, dyspnea, and early satiety. Paracentesis is the most common bedside procedure performed in patients with cirrhosis and ascites.",
    indications: [
      "New-onset ascites (diagnostic workup — SAAG calculation, cytology, culture)",
      "Suspected spontaneous bacterial peritonitis (SBP) — fever, abdominal pain, or altered mental status in cirrhotic patient with ascites",
      "Symptomatic tense ascites causing respiratory compromise or abdominal discomfort (therapeutic)",
      "Evaluation of peritoneal carcinomatosis or secondary peritonitis",
      "Refractory ascites not responding to diuretic therapy",
    ],
    contraindications: [
      "ABSOLUTE: None (emergency paracentesis has no absolute contraindications)",
      "RELATIVE: Coagulopathy (INR > 2.5 — consider FFP; platelet < 50,000 — transfuse); avoid if overlying cellulitis; avoid disseminated intravascular coagulation (DIC) without treatment; avoid if visceromegaly distorts landmarks (use ultrasound guidance)",
    ],
    equipment: [
      "Ultrasound (mandatory for all procedures — reduces complications 3-fold)",
      "Sterile drape, sterile gloves, antiseptic (chlorhexidine preferred)",
      "Local anesthetic: lidocaine 1% with epinephrine, 10 mL syringe, 25-gauge needle (skin wheal), 22-gauge needle (deeper infiltration)",
      "Diagnostic: 20–22 gauge needle + 20–60 mL syringe; 3 specimen tubes (chemistry, culture, cytology), blood culture bottles",
      "Therapeutic: 14–18 gauge paracentesis catheter (e.g., Caldwell needle or dedicated paracentesis kit) + vacuum bottles (1 L each) or collection bags; IV tubing",
      "25% albumin solution (for large-volume paracentesis > 5 L)",
    ],
    procedure: [
      "PATIENT PREPARATION: Obtain informed consent. Review labs (INR, platelets, Cr) — prophylactic FFP/platelets generally not required for INR < 2.5 or platelets > 30,000. Have patient empty bladder (or Foley catheter). Position supine with mild left lateral tilt.",
      "SITE SELECTION (with ultrasound): Left lower quadrant (LLQ) preferred — 4–5 cm medial and superior to the anterior superior iliac spine (ASIS); avoids inferior epigastric artery (lateral to rectus sheath) and bowel. Alternatively, midline below umbilicus (caution — avoid ligamentum teres, previous incisions). Mark site and confirm pocket depth on US.",
      "STERILE TECHNIQUE: Cleanse with chlorhexidine in concentric circles. Apply sterile drape. Identify site with US again after draping.",
      "LOCAL ANESTHESIA: Raise skin wheal with 25-gauge needle. Switch to 22-gauge: infiltrate subcutaneous tissue, fascia, and peritoneum with 1% lidocaine. Aspiration of fluid confirms peritoneal entry.",
      "NEEDLE INSERTION — Z-TRACK TECHNIQUE: Pull skin 2 cm inferiorly while inserting needle/catheter. Advance slowly with continuous aspiration. Once fluid returns, hold needle steady. Release skin tension — Z-track seals entry point after withdrawal and prevents persistent leak.",
      "DIAGNOSTIC ASPIRATION: Withdraw 20–50 mL fluid with syringe. Distribute: (1) chemistry tube — total protein, albumin, glucose, LDH, amylase, triglycerides; (2) blood culture bottles (NEVER delay inoculation for transport) — bedside inoculation increases culture sensitivity from 40% to 80–90%; (3) cytology: 30–50 mL in cytology container if malignancy suspected; (4) cell count: EDTA tube — PMN count is diagnostic criterion for SBP.",
      "THERAPEUTIC DRAINAGE: Connect catheter to vacuum collection bottles via IV tubing. Drain desired volume (up to 6 L at a time is safe with albumin replacement; some centers drain to dryness in a single session). Do NOT allow patient discomfort or hemodynamic changes to dictate premature cessation.",
      "ALBUMIN REPLACEMENT (for > 5 L removed): Give 25% albumin 8 g per liter of ascites removed (e.g., 6 L removed = 48 g albumin = 192 mL of 25% albumin IV). Albumin replacement prevents paracentesis-induced circulatory dysfunction (PICD) — redistributive circulatory failure causing hepatic encephalopathy, hepatorenal syndrome, and increased mortality.",
      "POST-PROCEDURE: Remove needle/catheter with Z-track sealed. Apply pressure. Small sterile dressing. Instruct patient to lie on opposite side for 1–2 hours to prevent leak. Document: color/character of fluid, volume removed, specimens sent, patient tolerance.",
    ],
    interpretation: {
      title: "Ascitic Fluid Analysis and SAAG",
      rows: [
        {
          parameter: "Serum-Ascites Albumin Gradient (SAAG)",
          normal: "SAAG = serum albumin − ascitic albumin",
          abnormal: "> 1.1 g/dL = portal hypertension (97% accuracy); < 1.1 g/dL = non-portal hypertension",
          significance: "SAAG > 1.1: cirrhosis, CHF, Budd-Chiari, portal vein thrombosis. SAAG < 1.1: infection (TB peritonitis), malignancy, pancreatitis, nephrotic syndrome",
        },
        {
          parameter: "PMN Count",
          normal: "< 250 cells/mm³",
          abnormal: "≥ 250 PMN/mm³ = SBP (regardless of culture result)",
          significance: "SBP: start cefotaxime 2 g IV q8h immediately + albumin 1.5 g/kg day 1 and 1 g/kg day 3 (reduces hepatorenal syndrome and mortality). If culture-negative but PMN ≥ 250 = culture-negative neutrocytic ascites (treat same)",
        },
        {
          parameter: "Total Protein",
          normal: "< 2.5 g/dL (transudative pattern in portal hypertension)",
          abnormal: "> 2.5 g/dL suggests exudative process (TB, malignancy, peritonitis)",
          significance: "Low protein + SAAG > 1.1 = cirrhotic ascites. Low protein in cirrhosis is a risk factor for SBP prophylaxis indication (protein < 1.5 g/dL + CPS ≥ 9 or Child C or Cr > 1.2)",
        },
        {
          parameter: "Glucose",
          normal: "Similar to serum glucose",
          abnormal: "Low glucose < 50 mg/dL suggests secondary peritonitis (bowel perforation, abscess)",
          significance: "Secondary peritonitis (Runyon's criteria): glucose < 50, protein > 10 g/dL, LDH > ULN — requires CT and surgical evaluation",
        },
        {
          parameter: "Amylase",
          normal: "Similar to serum",
          abnormal: "> 2,000 U/L suggests pancreatic ascites or perforated hollow viscus",
          significance: "Pancreatic ascites: pancreatitis or pancreatic duct disruption → MRCP → consider ERCP with ductal stenting",
        },
        {
          parameter: "Appearance",
          normal: "Straw-yellow, clear",
          abnormal: "Bloody (traumatic tap vs malignancy); cloudy/turbid (infection); milky (chylous — TG > 200 mg/dL)",
          significance: "Chylous ascites: TG > 200 mg/dL = lymphatic disruption (trauma, lymphoma, retroperitoneal tumor). Grossly bloody without traumatic tap = malignancy or Budd-Chiari",
        },
      ],
    },
    complications: [
      "Abdominal wall hematoma (most common — reduce with US guidance and Z-track)",
      "Persistent ascitic leak (Z-track technique significantly reduces; apply pressure dressing)",
      "Bowel perforation (rare < 1 per 1,000 with US guidance; higher without US)",
      "Inferior epigastric artery laceration (avoid by staying lateral to rectus sheath if using LLQ approach)",
      "Paracentesis-induced circulatory dysfunction (PICD) — prevented with albumin replacement > 5 L",
      "Infection introduction (rare with strict sterile technique)",
    ],
    clinicalPearl:
      "Always send blood culture bottles for ascitic fluid culture at bedside — inoculation of 10 mL of fluid directly into aerobic and anaerobic blood culture bottles increases culture-positive rate from 40% to 80–90%. A positive culture does NOT change the diagnosis of SBP — PMN ≥ 250 is the diagnostic standard. Empiric treatment with cefotaxime should NOT be withheld pending culture results when PMN ≥ 250.",
    boardRecallTip: "SAAG > 1.1 = portal HTN (cirrhosis, CHF). PMN ≥ 250 = SBP → cefotaxime + albumin (1.5 g/kg day 1, 1 g/kg day 3). Large-volume paracentesis > 5 L → give albumin 8 g per liter removed.",
  },
  {
    id: "gs-proc-central-line",
    rotation: "general-surgery",
    name: "Central Venous Catheter (CVC) Placement — Internal Jugular Approach",
    overview:
      "Central venous catheter placement provides reliable large-bore venous access for hemodynamic monitoring (CVP), administration of vasopressors, concentrated electrolytes, TPN, chemotherapy, and certain medications that require a central line. The internal jugular (IJ) approach is preferred by most surgeons for its lower risk of pneumothorax compared to the subclavian approach, and lower infection risk compared to the femoral approach. Ultrasound guidance is mandatory — it reduces complications by 50% and is the standard of care.",
    indications: [
      "Hemodynamic monitoring (central venous pressure monitoring in septic shock, major surgery)",
      "Vasopressor administration (norepinephrine, vasopressin, phenylephrine) — causes tissue necrosis if extravasated peripherally",
      "Total parenteral nutrition (TPN) — high osmolarity requires central administration",
      "Inadequate peripheral venous access",
      "Rapid volume resuscitation (introducer sheath — 8.5 Fr)",
      "Pulmonary artery catheter introduction",
      "Long-term IV antibiotic therapy (PICC preferred for non-emergent; CVC for ICU)",
    ],
    contraindications: [
      "ABSOLUTE: Venous thrombosis at planned site; infection or cellulitis at insertion site; coagulopathy (correct before placement or use compressible site — femoral)",
      "RELATIVE: Contralateral pneumothorax (use same-side as pneumothorax or femoral); previous surgery with altered anatomy; known SVC thrombosis; uncorrected coagulopathy (INR > 3, platelets < 20,000)",
    ],
    equipment: [
      "Ultrasound with high-frequency linear probe (7–15 MHz) and sterile probe cover + gel",
      "Central line kit: sterile drape (full-body), gown, gloves, mask with face shield, cap — maximal barrier precautions mandatory",
      "Chlorhexidine 2% with 70% isopropyl alcohol applicator (preferred over povidone-iodine for CLABSI reduction)",
      "Lidocaine 1% with 10 mL syringe and 25-gauge needle",
      "Triple-lumen catheter (most common) or introducer (Cordis), sterile normal saline flushes",
      "Seldinger wire (J-tip), dilator, scalpel (#11 blade), suture (2-0 silk), BioPatch or chlorhexidine disk, transparent dressing (Tegaderm)",
    ],
    procedure: [
      "PREPARATION: Universal timeout (patient, site, procedure). Position patient: Trendelenburg 15–20° (distends IJ, reduces air embolism risk). Turn head 30–45° away from insertion side. Expose and landmark: IJ runs lateral to carotid artery, within carotid triangle (between sternal and clavicular heads of SCM).",
      "STERILE TECHNIQUE: Don cap, mask, sterile gown, and gloves. Prep entire neck and chest to nipple line with chlorhexidine. Apply full-body sterile drape. Maximal barrier precautions (the single most effective CLABSI prevention measure).",
      "ULTRASOUND SURVEY: Before needle placement, use US to identify IJ (compressible, thin-walled, lateral to pulsatile carotid artery) in transverse view. Confirm patency (no thrombus). Mark expected puncture site 2–3 cm above clavicle.",
      "LOCAL ANESTHESIA: Raise skin wheal with 25-gauge needle and 1% lidocaine. Use longer needle to infiltrate subcutaneous tissues along expected needle trajectory, aspirating before injecting.",
      "VENIPUNCTURE — REAL-TIME ULTRASOUND GUIDANCE: Mount sterile probe cover on ultrasound probe. Identify IJ in transverse view. Insert finder needle (22-gauge) at 45° angle. Use 'walk' technique to track needle tip until compression of IJ wall is seen, then advance through anterior wall — blood flash confirms IJ. Switch to guidewire syringe or insertion needle (18-gauge) for Seldinger technique.",
      "SELDINGER TECHNIQUE: (1) Remove finder needle; insert Seldinger needle. Confirm free blood return (dark, non-pulsatile = venous). (2) Advance J-tip guidewire through needle into vessel — should pass without resistance. (3) Remove needle over wire (keep wire secure at all times). (4) Nick skin with #11 scalpel along wire. (5) Pass dilator over wire (only advance 3–4 cm — to dilate subcutaneous tissue, not deep into vessel). Remove dilator. (6) Advance central line catheter over wire to appropriate depth: right IJ → 15 cm; left IJ → 17 cm; right subclavian → 13–14 cm. (7) Remove wire. Aspirate blood from all lumens to confirm intravascular placement. Flush with NS.",
      "SECURING AND DRESSING: Suture catheter to skin at hub (2-0 silk). Apply BioPatch (chlorhexidine-impregnated disc) around insertion site. Apply Tegaderm transparent dressing — allows visualization without opening dressing. Sterile gauze if draining.",
      "CONFIRMATION: Portable CXR — confirm catheter tip at carotid-atrial junction (right side of chest, at level of carina or just below). Rule out pneumothorax. Catheter tip should NOT be in the right atrium (arrhythmia, perforation risk).",
    ],
    complications: [
      "Arterial puncture (most common — 1–6%): apply 5–10 minutes compression; if large bore, vascular surgery consult for closure; US guidance reduces to < 1%",
      "Pneumothorax (0.5–2% subclavian; < 0.1% IJ with US): CXR post-placement; symptomatic or > 15% → chest tube",
      "Air embolism: Trendelenburg + left lateral decubitus if suspected; needle/catheter open to air → minimize by capping hubs promptly",
      "Hematoma (compressible site advantage of IJ over subclavian): direct pressure",
      "CLABSI (catheter-related bloodstream infection): prevented by maximal barrier precautions, chlorhexidine skin prep, and daily need reassessment + timely removal",
      "Catheter malposition (into subclavian, contralateral IJ, or cardiac): pull back to correct position if non-functional; replace if necessary",
      "Thrombosis: daily assessment; anticoagulation for symptomatic DVT; remove catheter",
    ],
    clinicalPearl:
      "CLABSI prevention bundles (the 'central line bundle'): (1) Hand hygiene, (2) Maximal barrier precautions, (3) Chlorhexidine skin antisepsis, (4) Optimal catheter site selection (avoid femoral when possible), (5) Daily review of line necessity and prompt removal. Adherence to all 5 elements reduces CLABSI rates by up to 66%. The femoral site has the highest CLABSI and DVT rate; subclavian has the lowest CLABSI rate but highest pneumothorax risk; IJ has lowest pneumothorax risk with US guidance.",
    boardRecallTip: "IJ approach: US-guided, Trendelenburg, Seldinger technique. CXR post-placement — tip at carina level. CLABSI prevention: maximal sterile barrier + chlorhexidine prep. Femoral = highest infection risk; subclavian = highest pneumothorax risk.",
  },
  {
    id: "gs-proc-chest-tube",
    rotation: "general-surgery",
    name: "Tube Thoracostomy (Chest Tube Insertion)",
    overview:
      "Tube thoracostomy (chest tube placement) drains air (pneumothorax), blood (hemothorax), pleural fluid (effusion, empyema), or chyle (chylothorax) from the pleural space. In trauma surgery, it is one of the most frequently performed procedures. Large-bore tubes (28–36 Fr) are used for hemothorax and empyema; smaller tubes (14–20 Fr) or pigtail catheters can be used for simple pneumothorax or transudative effusions. Ultrasound guidance reduces misplacement and complications.",
    indications: [
      "Pneumothorax: large (> 15–20%) or any symptomatic pneumothorax; tension pneumothorax (emergent, no imaging required)",
      "Hemothorax: blood in pleural space (trauma, postoperative, iatrogenic)",
      "Empyema: complicated parapneumonic effusion (pH < 7.2, glucose < 60, LDH > 1,000, or purulent) requiring drainage",
      "Large symptomatic pleural effusions not responsive to thoracentesis",
      "Post-thoracic surgery drainage (routine after thoracotomy, VATS, esophagectomy)",
      "Chylothorax (lymphatic injury after thoracic surgery or trauma)",
    ],
    contraindications: [
      "RELATIVE: Coagulopathy (correct INR < 2.0, platelets > 50,000 if not emergent); pleural adhesions from prior surgery (may require VATS for loculated collections); lung adherent to chest wall (rare — risk of lung parenchymal injury)",
      "No absolute contraindication in tension pneumothorax — emergent decompression takes priority",
    ],
    equipment: [
      "Chest tube: 28–36 Fr (hemothorax/empyema), 20–24 Fr (effusion), 14–20 Fr (pneumothorax); or pigtail catheter (Seldinger-based)",
      "Sterile drape, gown, gloves, chlorhexidine prep",
      "Lidocaine 1% with epinephrine, 20–30 mL, multiple syringes (10 mL), needles (25-gauge, 22-gauge)",
      "Scalpel (#10 blade), curved Kelly clamp (large), straight Mayo scissors, large curved hemostat",
      "Suture: #0 or 1-0 silk (anchoring) + 2-0 silk (purse-string or mattress) or staple gun",
      "Petrolatum-impregnated gauze (Vaseline gauze) for airtight seal",
      "Pleurevac drainage system (water-seal drainage) with suction tubing; connect to −20 cmH₂O wall suction",
      "Tape (non-adhesive dressing for tube), sterile gauze",
    ],
    procedure: [
      "POSITIONING AND LANDMARKING: Position supine with ipsilateral arm raised and externally rotated (hand behind head) to expose the lateral chest wall. Identify the triangle of safety: bordered by (1) lateral border of pectoralis major anteriorly, (2) lateral border of latissimus dorsi posteriorly, (3) base of axilla superiorly, (4) 5th intercostal space (nipple line) inferiorly. Insert in 4th–5th intercostal space (ICS) at midaxillary line (MAL). US confirmation of insertion site before incision.",
      "STERILE PREP AND ANESTHESIA: Chlorhexidine prep of the lateral hemithorax. Full sterile drape. Lidocaine 1%: raise skin wheal → subcutaneous infiltration → walk down the RIB and infiltrate superior margin (avoid neurovascular bundle which runs in inferior groove under each rib). Infiltrate parietal pleura — may elicit a 'pop' or gush of fluid/air confirming location.",
      "INCISION: Using #10 scalpel, make 2–3 cm transverse incision in the 4th–5th ICS at MAL, directly over the superior margin of the rib.",
      "BLUNT DISSECTION: Using curved Kelly clamp, bluntly dissect through subcutaneous fat and intercostal muscle layers, staying on TOP of the rib. Once at pleura, use controlled push-through to enter the pleural space — rush of air or blood confirms entry. Widen opening with clamp or finger.",
      "DIGITAL EXPLORATION: Insert gloved finger into pleural space to confirm correct position (feel lung expansion/recoil) and clear any clotted blood or fibrin at the insertion site. Sweep finger to ensure no adhesions.",
      "TUBE INSERTION: Guide chest tube with curved Kelly clamp (tip of tube clamped or the tube slid along the finger). Direct tube: posteriorly and superiorly for air (apical tube); posteriorly and inferiorly for fluid/blood (dependent drainage). Advance until all side holes are within the chest (approximately 8–10 cm).",
      "SECURING THE TUBE: Anchor suture around tube with 1-0 silk tied securely. Horizontal mattress suture on each side of incision. Apply petrolatum gauze around tube at skin. Tape tube to chest wall. Connect to Pleurevac — confirm oscillation with breathing (tidaling = tube is patent and in pleural space).",
      "CONFIRMATION: Stat portable CXR — confirm tube position (tip at apex for pneumothorax), full lung re-expansion, and absence of complications. If hemothorax, note amount of initial drainage.",
    ],
    interpretation: {
      title: "Chest Tube Output — Clinical Decision Making",
      rows: [
        {
          parameter: "Initial hemothorax drainage",
          normal: "< 200 mL",
          abnormal: "> 1,500 mL immediately or > 200 mL/hr for 4 hours = massive hemothorax",
          significance: "Massive hemothorax → emergent operative thoracotomy (VATS or open) for hemorrhage control",
        },
        {
          parameter: "Air leak (bubbling)",
          normal: "Bubbling stops at rest within 24–48h post-pneumothorax",
          abnormal: "Persistent bubbling at rest > 5 days = prolonged air leak (bronchopleural fistula)",
          significance: "Prolonged air leak > 5 days → thoracic surgery consult for VATS stapling or pleurodesis",
        },
        {
          parameter: "Tidaling (oscillation)",
          normal: "Fluid oscillates with respiration (rises with inspiration, falls with expiration)",
          abnormal: "No tidaling = tube kinked, clotted, or malpositioned; or full lung expansion",
          significance: "If no tidaling + persistent pneumothorax on CXR → reposition or replace tube",
        },
        {
          parameter: "Output for empyema",
          normal: "Decreasing purulent output with antibiotics and drainage",
          abnormal: "Persistent or loculated drainage despite chest tube",
          significance: "Fibropurulent stage empyema → VATS decortication. Late organizing stage → open decortication",
        },
        {
          parameter: "Criteria for removal",
          normal: "Output < 150–200 mL/day, no air leak at rest, CXR shows full expansion",
          abnormal: "Persistent air leak or high output — keep in place",
          significance: "Remove at end-expiration or Valsalva to prevent pneumothorax. Apply airtight dressing immediately. CXR 1 hour after removal.",
        },
      ],
    },
    complications: [
      "Malposition (not in pleural space, in lung parenchyma, or subdiaphragmatic) — confirmed by CXR; re-insertion required",
      "Bleeding from intercostal vessels (place superior to rib to avoid neurovascular bundle)",
      "Empyema from contamination (rare with sterile technique; prophylactic antibiotics recommended in trauma)",
      "Persistent air leak / bronchopleural fistula (VATS or thoracotomy if > 5 days)",
      "Re-expansion pulmonary edema (drain no more than 1.5 L at a time for large effusions)",
      "Subcutaneous emphysema (tube side-hole not within pleural space; reposition)",
      "Diaphragmatic or hepatic/splenic injury (avoid placing below 5th ICS)",
    ],
    clinicalPearl:
      "Tension pneumothorax is a clinical diagnosis — do NOT wait for CXR. Tracheal deviation away from the affected side + absent breath sounds + hypotension + JVD = tension physiology → immediate needle decompression: 2nd ICS, MCL with 14-gauge angiocath, then definitive chest tube. The 5th ICS MAL ('triangle of safety') minimizes risk to breast tissue, liver, spleen, and diaphragm compared to historical 2nd ICS MCL placement for all pneumothoraces.",
    boardRecallTip: "Triangle of safety: 4th–5th ICS, MAL. Stay on TOP of rib (neurovascular bundle runs below). Tension PTX: clinical diagnosis → needle decompression 2nd ICS MCL first. Massive hemothorax: > 1,500 mL initial output or > 200 mL/hr → emergent thoracotomy.",
  },
  {
    id: "gs-proc-wound-care",
    rotation: "general-surgery",
    name: "Surgical Wound Assessment and Complex Wound Management",
    overview:
      "Surgical site infections (SSIs) occur in 2–5% of clean-contaminated abdominal procedures and up to 15–20% of contaminated/dirty cases. They are the most common healthcare-associated infection. Proper wound assessment, classification, and management are core surgical PA competencies. Complex wounds — including dehiscence, infected wounds, and wounds requiring negative pressure wound therapy (NPWT) — require systematic evaluation and staged management.",
    indications: [
      "Post-operative wound assessment for all surgical patients (routine)",
      "Wound dehiscence — superficial (skin edges separated) or fascial (deeper layers open)",
      "Suspected SSI — erythema, warmth, induration, purulent drainage, wound pain > post-op day 4",
      "Non-healing wounds — diabetic foot ulcers, pressure ulcers, traumatic wounds",
      "Wounds requiring NPWT (vacuum-assisted closure — VAC therapy)",
      "Bite wounds, abscess, or infected traumatic wounds requiring debridement",
    ],
    contraindications: [
      "NPWT contraindications: malignant tissue in wound, untreated osteomyelitis, necrotic tissue with eschar (must debride first), exposed organs without protective layer, fistula to body cavity, high-output fistulas",
      "Primary closure: never close frankly infected or contaminated wounds (Category III/IV) primarily — delayed primary closure (DPC) at 4–5 days or secondary intention",
    ],
    equipment: [
      "Sterile gloves, sterile gauze and saline, chlorhexidine or betadine for wound cleaning",
      "Wound probe (metal or cotton-tipped for sinus tract assessment)",
      "Culture swab (Levine technique — avoid superficial contamination)",
      "Suture removal kit, staple remover",
      "Debridement: scalpel (#15), scissors (Metzenbaum), tissue forceps",
      "NPWT system (V.A.C. Therapy — KCI): foam (black = polyurethane/high porosity, white = polyvinyl alcohol/less adherent), adhesive drape, tubing, portable device",
      "Wound measurement tools: ruler, wound tracing paper, wound documentation sheet",
    ],
    procedure: [
      "WOUND DOCUMENTATION: Document in each note using PUSH tool or descriptive format: (1) Location and dimensions (length × width × depth in cm); (2) Wound bed: % granulation (beefy red), % slough (yellow/white fibrin), % eschar (black, necrotic); (3) Wound edges: undermining (probe under edges in cm), tunneling (sinus tract depth and direction on clock face); (4) Exudate: amount (none/scant/moderate/heavy), character (serous/serosanguineous/purulent/feculent); (5) Periwound skin: intact, macerated, calloused, erythematous (erythema > 2 cm from wound edge suggests cellulitis); (6) Odor: none, mild, strong (malodor suggests infection or necrotic tissue); (7) Signs of healing: granulation tissue formation, epithelialization at edges, contraction.",
      "WOUND OPENING FOR SUSPECTED SSI: Examine for fluctuance (loculated fluid = abscess). Open the superficial wound layers at the area of greatest concern with a cotton swab, suture scissors, or scalpel. Express purulent material. Irrigate copiously with NS. Culture wound base using Levine technique (press swab firmly into wound bed, rotate 5 seconds — NOT swabbing surface exudate). Probe for depth and sinus tracts. Pack wound loosely with saline-moistened gauze (wet-to-moist dressing) or apply NPWT. DO NOT pack tightly (impairs granulation).",
      "WOUND DEBRIDEMENT: Sharply excise all non-viable (necrotic, ischemic, fibrotic) tissue with scalpel or scissors until viable bleeding tissue is present at all wound margins. Autolytic debridement (moist wound dressings) is appropriate for minor slough. Enzymatic debridement (collagenase/Santyl) for patients who cannot tolerate sharp debridement. NEVER debride eschar on heel ulcers in patients with peripheral arterial disease without first assessing perfusion (ABI).",
      "NEGATIVE PRESSURE WOUND THERAPY (NPWT/VAC): Indications: complex open wounds, diabetic foot ulcers, dehisced wounds, open abdomens, or wounds with significant undermining. Steps: (1) Debride wound of all necrotic tissue. (2) Measure and trim black foam to fill wound cavity — do not fill more than 80% of wound volume. (3) Fill all tunnels/undermined areas with foam or gauze bridge. (4) Apply adhesive drape over foam extending 3–5 cm onto periwound skin — airtight seal critical. (5) Cut small hole in drape and apply VAC tubing; attach to device. (6) Set continuous or intermittent pressure (typical: −75 to −125 mmHg). (7) Confirm suction by observing foam contraction. Change VAC every 48–72 hours (more frequently if infected).",
      "WOUND CLOSURE TIMING: Primary closure = immediate closure in clean/clean-contaminated wounds. Delayed primary closure (DPC) = leave wound open 4–5 days → close if clean (used in contaminated wounds to allow healing without SSI). Secondary intention = allow wound to close by granulation, contraction, and epithelialization (appropriate for small, shallow infected wounds). Split-thickness skin graft (STSG) = for large granulating wound beds that cannot close by secondary intention or primary closure.",
    ],
    interpretation: {
      title: "Wound Classification and SSI Risk",
      rows: [
        {
          parameter: "Class I — Clean",
          normal: "No infection; no GI/GU/respiratory tract entered; elective",
          abnormal: "SSI rate: 1–2%",
          significance: "Hernia repair, breast biopsy, thyroidectomy — cefazolin prophylaxis standard",
        },
        {
          parameter: "Class II — Clean-Contaminated",
          normal: "Elective entry into GI/GU/respiratory without spillage",
          abnormal: "SSI rate: 2–5%",
          significance: "Cholecystectomy, bowel resection, appendectomy — cefazolin; add metronidazole for colorectal",
        },
        {
          parameter: "Class III — Contaminated",
          normal: "Gross spillage from GI tract; fresh traumatic wound; major break in technique",
          abnormal: "SSI rate: 5–15%",
          significance: "Ruptured appendix without abscess, GI perforation — broad-spectrum antibiotics; DPC vs secondary intention",
        },
        {
          parameter: "Class IV — Dirty",
          normal: "Old traumatic wound with devitalized tissue; perforated viscus; pre-existing clinical infection",
          abnormal: "SSI rate: 15–40%",
          significance: "Fecal peritonitis, necrotizing fasciitis — antibiotics are treatment (not prophylaxis); open wound management",
        },
      ],
    },
    complications: [
      "Wound dehiscence — superficial: daily dressing changes and NPWT; fascial dehiscence (evisceration) → immediate return to OR",
      "Evisceration: keep bowel moist with saline-soaked gauze, call surgery immediately, urgent OR",
      "SSI extending to fascia or muscle → aggressive debridement, may need tissue flaps for reconstruction",
      "NPWT-related: foam retention in wound, periwound skin breakdown under drape, pain with dressing changes",
    ],
    clinicalPearl:
      "The CDC SSI prevention bundle for abdominal surgery: (1) Correct antibiotic choice and timing (within 60 minutes of incision, redose if > 4 hours or blood loss > 1,500 mL), (2) Maintain normothermia (forced-air warming blanket — every 1°C decrease in core temp increases SSI risk 3-fold), (3) Maintain normoglycemia (blood glucose < 180 mg/dL in OR and first 24 hours post-op — hyperglycemia impairs neutrophil function), (4) Chlorhexidine-alcohol skin prep (superior to povidone-iodine), (5) Change gloves and instruments before closing fascia in contaminated cases.",
    boardRecallTip: "Wound classes: Clean (1–2%), Clean-contaminated (2–5%), Contaminated (5–15%), Dirty (15–40%). SSI prevention: cefazolin within 60 min + normothermia + normoglycemia + chlorhexidine prep. Evisceration = surgical emergency → saline gauze + emergent OR.",
  },
];
