import type { Guideline } from "@/types";

export const emergencyMedicineGuidelines: Guideline[] = [
  {
    id: "em-gl-01",
    rotation: "emergency-medicine",
    conditionName: "Cardiac Arrest",
    guidelineName: "Advanced Cardiovascular Life Support (ACLS)",
    issuingOrganization: "American Heart Association (AHA)",
    year: 2020,
    keyRecommendations: [
      "High-quality CPR is the cornerstone of resuscitation: push hard (≥2 inches), push fast (100–120/min), allow full chest recoil, minimize interruptions (<10 sec for rhythm check), avoid excessive ventilation.",
      "Defibrillation is the definitive treatment for shockable rhythms (VF/pVT); deliver shock as soon as possible and immediately resume CPR afterward.",
      "Epinephrine 1 mg IV/IO every 3–5 minutes is recommended for all cardiac arrest rhythms; administer as early as possible in non-shockable rhythms (asystole/PEA).",
      "Advanced airway (endotracheal intubation or supraglottic airway) should not delay defibrillation; bag-mask ventilation is acceptable during initial resuscitation.",
      "Identify and treat reversible causes (Hs and Ts): Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/Hyperkalemia, Hypothermia; Tension pneumothorax, Tamponade, Toxins, Thrombosis (pulmonary/coronary).",
      "Post-cardiac arrest care: targeted temperature management (32–36°C for 24 hours), coronary angiography if STEMI or suspected cardiac etiology, hemodynamic optimization.",
    ],
    firstLine: [
      "CPR: 30:2 compressions-to-ventilations ratio (2-provider: 15:2 for pediatric)",
      "Defibrillation 200 J biphasic for VF/pVT (shock immediately, then resume CPR 2 minutes before re-check)",
      "Epinephrine 1 mg IV/IO every 3–5 minutes (give ASAP for PEA/asystole; after first or second shock for VF/pVT)",
      "Amiodarone 300 mg IV/IO first dose, 150 mg second dose for refractory VF/pVT",
    ],
    secondLine: [
      "Lidocaine 1–1.5 mg/kg IV/IO as alternative antiarrhythmic if amiodarone unavailable",
      "Sodium bicarbonate 1 mEq/kg for known hyperkalemia or tricyclic antidepressant overdose",
      "Calcium chloride 1 g IV for hyperkalemia, calcium channel blocker toxicity, or hypocalcemia",
      "Vasopressin (no longer recommended as substitute; epinephrine preferred per 2020 update)",
    ],
    nonPharmacologic: [
      "Continuous waveform capnography to confirm ETT placement and monitor CPR quality (ETCO2 goal ≥10 mmHg; sudden rise to ≥40 mmHg suggests ROSC)",
      "Mechanical CPR device (LUCAS, AutoPulse) when manual CPR cannot be consistently performed",
      "Targeted temperature management post-ROSC: 32–36°C for 24 hours in comatose survivors",
      "Early coronary angiography/PCI if STEMI identified post-ROSC",
      "ECMO-CPR (ECPR) consideration at centers with capability for refractory cardiac arrest",
    ],
    whenToRefer: [
      "All resuscitated cardiac arrest patients require ICU admission post-ROSC",
      "Cardiology consultation for post-ROSC STEMI or suspected acute coronary occlusion",
      "Neurology consult for post-arrest coma and neuroprognostication (≥72 hours post-ROSC)",
      "Transfer to ECMO-capable center if refractory arrest and patient is a candidate",
    ],
    monitoringSchedule: [
      "Continuous cardiac monitoring post-ROSC",
      "Serial 12-lead EKGs every 15–30 minutes post-ROSC to detect STEMI",
      "ABG every 1–2 hours during TTM to maintain normoxia (PaO2 60–100 mmHg) and normocapnia (PaCO2 35–45 mmHg)",
      "Continuous temperature monitoring during TTM; avoid fever (>37.5°C) for 72 hours",
      "Neurologic assessment at 72 hours post-ROSC for prognostication (GCS, brainstem reflexes, EEG, SSEP)",
    ],
    patientEducation: [
      "Family education on bystander CPR and AED use in the community",
      "Survivors should receive ICD evaluation given high risk of recurrent arrest",
      "Cardiac rehabilitation referral for survivors with ischemic etiology",
      "Discuss driving restrictions post-arrest (typically 3–6 months depending on etiology and state law)",
    ],
  },
  {
    id: "em-gl-02",
    rotation: "emergency-medicine",
    conditionName: "Acute Coronary Syndrome / STEMI",
    guidelineName: "ACS/STEMI Management Guidelines",
    issuingOrganization: "American College of Cardiology / American Heart Association (ACC/AHA)",
    year: 2023,
    keyRecommendations: [
      "STEMI defined as ST elevation ≥1 mm in ≥2 contiguous limb leads or ≥2 mm in ≥2 contiguous precordial leads, or new LBBB with ischemic symptoms.",
      "Primary PCI is the preferred reperfusion strategy; door-to-balloon time goal is <90 minutes for PCI-capable hospitals.",
      "Fibrinolysis is indicated when PCI is unavailable within 120 minutes of first medical contact; administer within 30 minutes of arrival (door-to-needle time).",
      "Dual antiplatelet therapy (aspirin + P2Y12 inhibitor) should be initiated immediately in all ACS patients without absolute contraindications.",
      "Anticoagulation with unfractionated heparin, enoxaparin, or bivalirudin should be initiated in all STEMI patients undergoing reperfusion.",
      "High-intensity statin therapy should be started in all ACS patients in-hospital regardless of baseline LDL.",
    ],
    firstLine: [
      "Aspirin 325 mg PO/chewed immediately (non-enteric coated); then 81 mg daily indefinitely",
      "P2Y12 inhibitor: Ticagrelor 180 mg loading dose (preferred) or Clopidogrel 600 mg loading dose",
      "Unfractionated heparin (UFH): 60 units/kg IV bolus (max 4,000 units), then 12 units/kg/hr infusion (max 1,000 units/hr) titrated to aPTT 50–70 sec",
      "Primary PCI: door-to-balloon time <90 minutes at PCI-capable center",
      "Nitroglycerin 0.4 mg SL every 5 minutes × 3 for ongoing chest pain (hold if systolic BP <90 or inferior MI with RV involvement)",
    ],
    secondLine: [
      "Fibrinolysis (if PCI unavailable within 120 min): Alteplase, Tenecteplase, or Reteplase per weight-based dosing",
      "Enoxaparin 0.5 mg/kg IV bolus then 1 mg/kg SC BID (reduce to 1 mg/kg SC daily if CrCl <30)",
      "Bivalirudin 0.75 mg/kg IV bolus then 1.75 mg/kg/hr infusion (alternative anticoagulant, especially if HIT history)",
      "Beta-blocker (oral) within 24 hours if hemodynamically stable, no HF, no high-degree AV block",
      "ACE inhibitor within 24 hours if LVEF <40%, anterior STEMI, HTN, or DM",
    ],
    thirdLine: [
      "Glycoprotein IIb/IIIa inhibitors (eptifibatide, tirofiban) for large thrombus burden or no-reflow during PCI",
      "IV beta-blocker (metoprolol 5 mg IV × 3 doses) only if tachycardia or hypertension in hemodynamically stable patients",
      "Aldosterone antagonist (eplerenone) post-MI if LVEF ≤40% with HF symptoms or DM, no significant renal dysfunction",
    ],
    nonPharmacologic: [
      "Supplemental O2 only if SpO2 <90% (hyperoxia is harmful)",
      "12-lead EKG within 10 minutes of presentation; repeat if initial non-diagnostic",
      "Continuous cardiac monitoring from arrival",
      "Cardiac rehabilitation post-MI for all eligible patients",
      "Smoking cessation counseling and pharmacotherapy",
    ],
    whenToRefer: [
      "All STEMI patients: immediate cardiology/interventional cardiology activation",
      "Cardiogenic shock: consider IABP, Impella, or ECMO support with cardiac surgery availability",
      "Mechanical complications (VSD, papillary muscle rupture, free wall rupture): emergent cardiac surgery",
      "High-risk NSTEMI (TIMI ≥3, positive troponin, dynamic ST changes): urgent catheterization within 2 hours",
    ],
    monitoringSchedule: [
      "Continuous telemetry for minimum 24 hours post-PCI",
      "Serial troponins every 3–6 hours (high-sensitivity troponin 0 and 1–2 hours)",
      "Echocardiogram within 24–48 hours to assess LVEF and wall motion abnormalities",
      "Fasting lipid panel in all ACS patients",
      "HbA1c and fasting glucose to screen for DM",
    ],
    patientEducation: [
      "Recognize MI symptoms: chest pressure, radiation to arm/jaw, diaphoresis, nausea — call 911 immediately",
      "Take aspirin 325 mg immediately if MI suspected and no allergy (chew, do not swallow whole)",
      "Strict medication adherence: DAPT for at least 12 months post-DES implantation",
      "Activity restrictions: avoid strenuous activity for 4–6 weeks; follow-up with cardiology in 1–2 weeks",
      "Return precautions: call 911 for recurrent chest pain, dyspnea, or palpitations",
    ],
  },
  {
    id: "em-gl-03",
    rotation: "emergency-medicine",
    conditionName: "Acute Ischemic Stroke",
    guidelineName: "Guidelines for the Early Management of Patients with Acute Ischemic Stroke",
    issuingOrganization: "American Heart Association / American Stroke Association (AHA/ASA)",
    year: 2023,
    keyRecommendations: [
      "Door-to-needle time for IV alteplase should be ≤60 minutes (target ≤45 minutes at certified stroke centers).",
      "IV alteplase 0.9 mg/kg (max 90 mg) is indicated within 3–4.5 hours of symptom onset in eligible patients.",
      "NIHSS should be performed on all suspected stroke patients to quantify deficits and guide treatment decisions.",
      "Mechanical thrombectomy (MT) with stent retriever is indicated for large vessel occlusion (LVO) of the anterior circulation within 24 hours of last known well.",
      "Non-contrast CT head must be obtained immediately to exclude hemorrhage before thrombolytics.",
      "Blood pressure management: treat BP >185/110 mmHg before tPA; allow permissive hypertension up to 220/120 if tPA not given.",
    ],
    firstLine: [
      "IV Alteplase (tPA) 0.9 mg/kg IV (max 90 mg): 10% as IV bolus over 1 minute, remaining 90% infused over 60 minutes — within 3–4.5 hours of onset",
      "Mechanical thrombectomy for LVO (ICA, M1, M2, basilar): within 6 hours (extended to 24 hours with imaging selection — DAWN/DEFUSE-3 criteria)",
      "Aspirin 325 mg PO/NG tube within 24–48 hours of onset (not within 24 hours if tPA given)",
      "Labetalol 10–20 mg IV or Nicardipine 5 mg/hr IV to lower BP to <185/110 mmHg before tPA administration",
    ],
    secondLine: [
      "Tenecteplase 0.25 mg/kg IV (max 25 mg) as alternative to alteplase for LVO patients going to thrombectomy (2022 guideline update)",
      "Statins: continue pre-existing statin therapy; initiate high-intensity statin if not on one",
      "Clopidogrel 75 mg daily (or DAPT for 21 days in minor stroke/TIA per POINT trial) for non-cardioembolic stroke",
      "Anticoagulation for cardioembolic stroke (AF): initiate within 4–14 days depending on stroke severity",
    ],
    nonPharmacologic: [
      "Non-contrast CT head immediately on arrival (goal: CT within 25 minutes, read within 45 minutes of arrival)",
      "CT angiography (CTA) head and neck to identify LVO and assess collaterals",
      "Blood glucose management: treat hypoglycemia (<60 mg/dL) immediately; treat hyperglycemia (>180 mg/dL) with insulin",
      "Swallowing evaluation before oral intake; NPO until dysphagia screen passed",
      "Early mobilization and physical/occupational/speech therapy within 24 hours if stable",
      "Stroke unit admission with continuous monitoring",
    ],
    whenToRefer: [
      "All acute stroke: activate stroke team immediately (Stroke Code); neurology involvement mandatory",
      "LVO on CTA: neurointerventional radiology for mechanical thrombectomy",
      "Hemorrhagic transformation or symptomatic ICH post-tPA: neurosurgery consultation",
      "Malignant MCA infarction (>50% MCA territory): neurosurgery for decompressive hemicraniectomy within 48 hours",
    ],
    monitoringSchedule: [
      "Continuous cardiac monitoring for 24–72 hours to detect AF (telemetry)",
      "Neurological checks (NIHSS) every 15 minutes during tPA infusion, every 30 minutes × 6 hours, then every hour × 16 hours",
      "BP monitoring every 15 minutes during tPA and for 2 hours after, then every 30 minutes × 6 hours",
      "Repeat non-contrast CT at 24 hours or sooner if neurologic deterioration occurs",
      "Fasting lipid panel, HbA1c, and echocardiogram during admission workup",
    ],
    patientEducation: [
      "FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911",
      "Do not drive self to hospital; call 911 for faster activation of stroke protocol",
      "Strict BP control post-stroke: home BP goal <130/80 mmHg",
      "Medication adherence: antiplatelet or anticoagulant as prescribed to prevent recurrence",
      "Stroke rehabilitation: inpatient rehab or skilled nursing facility based on deficits; outpatient therapy after discharge",
    ],
  },
  {
    id: "em-gl-04",
    rotation: "emergency-medicine",
    conditionName: "Anaphylaxis",
    guidelineName: "World Allergy Organization (WAO) Anaphylaxis Guidelines",
    issuingOrganization: "World Allergy Organization (WAO)",
    year: 2020,
    keyRecommendations: [
      "Epinephrine IM is the FIRST and ONLY first-line treatment for anaphylaxis; there are NO absolute contraindications to epinephrine in anaphylaxis.",
      "Anaphylaxis is a clinical diagnosis; do not delay epinephrine while waiting for labs or further evaluation.",
      "Inject epinephrine into the anterolateral thigh (vastus lateralis) — faster absorption than the deltoid.",
      "Antihistamines and corticosteroids are ADJUNCT therapies only; they do not treat the life-threatening manifestations of anaphylaxis and must never replace epinephrine.",
      "Observe all anaphylaxis patients for minimum 4–6 hours after epinephrine (8–12 hours for severe or biphasic-risk patients) due to risk of biphasic reaction.",
      "Prescribe self-injectable epinephrine (EpiPen 0.3 mg or 0.15 mg for pediatric) and provide a written anaphylaxis action plan at discharge.",
    ],
    firstLine: [
      "Epinephrine 0.3–0.5 mg IM (1:1,000 concentration) into anterolateral thigh; repeat every 5–15 minutes if inadequate response (no absolute contraindications)",
      "Epinephrine auto-injector (EpiPen): 0.3 mg adult, 0.15 mg pediatric (<25 kg)",
      "Supine position with legs elevated (Trendelenburg) unless dyspneic; never allow sudden upright posturing",
      "Supplemental O2 via high-flow non-rebreather mask; prepare for airway management (intubation) if stridor or laryngeal edema",
      "IV/IO access: normal saline bolus 1–2 L rapidly for hypotension",
    ],
    secondLine: [
      "Diphenhydramine 25–50 mg IV/PO (H1 blocker) — adjunct, does not treat airway or hemodynamic compromise",
      "Ranitidine/famotidine (H2 blocker) — adjunct for urticaria/flushing",
      "Methylprednisolone 125 mg IV or prednisone 1 mg/kg PO (max 60 mg) — adjunct to prevent prolonged or biphasic reaction",
      "Albuterol 2.5 mg nebulized every 20 minutes for bronchospasm refractory to epinephrine",
      "IV epinephrine infusion 0.1–1 mcg/kg/min for refractory anaphylaxis/epinephrine-refractory shock",
    ],
    thirdLine: [
      "Glucagon 1–2 mg IV/IM every 5 minutes for patients on beta-blockers with refractory hypotension (reverses beta-blocker-mediated resistance to epinephrine)",
      "Vasopressin or norepinephrine infusion for refractory distributive shock",
      "Methylene blue for refractory vasodilatory shock (case reports, limited evidence)",
    ],
    nonPharmacologic: [
      "Remove or stop the offending trigger (e.g., discontinue IV medication infusion, remove bee stinger)",
      "Positioning: supine with legs elevated; do not allow patient to sit/stand (fatal pulseless electrical activity documented with upright posture)",
      "Airway management: early intubation for impending airway obstruction; have surgical airway equipment ready",
      "IV access: two large-bore IVs; intraosseous if no IV access in emergent hypotension",
    ],
    whenToRefer: [
      "Allergy/immunology follow-up within 1–4 weeks for all anaphylaxis patients for trigger identification, allergen testing, and venom immunotherapy consideration",
      "ICU admission for refractory anaphylaxis, hemodynamic instability, or respiratory failure requiring intubation",
      "Hospital admission (observation ≥8 hours) for severe reactions, prior biphasic reactions, or incomplete response to epinephrine",
    ],
    monitoringSchedule: [
      "Continuous cardiac monitoring and pulse oximetry during observation period",
      "Vital signs every 15 minutes × 1 hour, then every 30 minutes during observation",
      "Observe minimum 4–6 hours (8–12 hours for severe cases) for biphasic reaction",
      "Discharge criteria: complete symptom resolution, stable vitals, epinephrine prescription in hand, return precautions reviewed",
    ],
    patientEducation: [
      "Strict allergen avoidance: identify and carry a list of all triggers",
      "Always carry two epinephrine auto-injectors; use immediately at onset of anaphylaxis symptoms",
      "Call 911 after using epinephrine auto-injector — epinephrine is not definitive treatment alone",
      "Medical alert bracelet/necklace identifying anaphylaxis triggers",
      "Written anaphylaxis action plan provided at discharge; review with patient and family",
    ],
  },
  {
    id: "em-gl-05",
    rotation: "emergency-medicine",
    conditionName: "Sepsis and Septic Shock",
    guidelineName: "Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock",
    issuingOrganization: "Society of Critical Care Medicine / European Society of Intensive Care Medicine",
    year: 2021,
    keyRecommendations: [
      "Sepsis-3 definition: life-threatening organ dysfunction caused by a dysregulated host response to infection; SOFA score increase ≥2 from baseline.",
      "Septic shock: sepsis with persistent hypotension requiring vasopressors to maintain MAP ≥65 mmHg AND serum lactate >2 mmol/L despite adequate fluid resuscitation.",
      "Hour-1 Bundle (immediate actions): measure lactate, obtain blood cultures × 2 before antibiotics, give broad-spectrum antibiotics, administer 30 mL/kg crystalloid for hypotension or lactate ≥4 mmol/L, apply vasopressors if MAP remains <65 mmHg.",
      "Blood cultures must be drawn BEFORE antibiotics without delaying antibiotic administration >45 minutes.",
      "Broad-spectrum antibiotics should be administered within 1 hour of sepsis recognition.",
      "Antibiotic de-escalation should occur once pathogen and sensitivities are identified (typically 48–72 hours).",
    ],
    firstLine: [
      "Crystalloid resuscitation: 30 mL/kg IV bolus within 3 hours (normal saline or Lactated Ringer's); reassess after each bolus with dynamic fluid responsiveness measures",
      "Broad-spectrum antibiotics within 1 hour: Vancomycin + Piperacillin-Tazobactam (or Meropenem for high-risk/immunocompromised) — tailor to likely source",
      "Norepinephrine (vasopressor of choice): 0.01–3 mcg/kg/min IV infusion to maintain MAP ≥65 mmHg; titrate to effect",
      "Lactate measurement: obtain at presentation; remeasure at 2 hours if initial lactate ≥2 mmol/L to guide resuscitation",
    ],
    secondLine: [
      "Vasopressin 0.03–0.04 units/min IV (add to norepinephrine to achieve MAP target or to reduce norepinephrine dose)",
      "Hydrocortisone 200 mg/day IV (50 mg every 6 hours or continuous infusion) for septic shock refractory to vasopressors ≥0.25 mcg/kg/min norepinephrine equivalent",
      "Albumin 4–5% solution in patients who have received large volumes of crystalloid and remain hemodynamically unstable",
      "Epinephrine as additional vasopressor for refractory septic shock",
    ],
    thirdLine: [
      "Angiotensin II (Giapreza) for catecholamine-refractory vasodilatory shock",
      "Thiamine 200 mg IV BID if thiamine deficiency suspected (alcoholism, malnutrition) — reduces lactate clearance impairment",
      "Vitamin C + thiamine + hydrocortisone bundle (HAT therapy): evidence remains controversial; not routinely recommended",
    ],
    nonPharmacologic: [
      "Obtain at least 2 sets of blood cultures (aerobic and anaerobic) from 2 separate sites before antibiotics",
      "Source control: drain abscesses, remove infected catheters/devices, surgical debridement within 6–12 hours when source identified",
      "Dynamic fluid responsiveness assessment: passive leg raise, pulse pressure variation, stroke volume variation (avoid static measures like CVP alone)",
      "Glucose management: target blood glucose 140–180 mg/dL; avoid hypoglycemia",
      "Lung-protective ventilation if mechanically ventilated: Vt 6 mL/kg IBW, plateau pressure <30 cmH2O",
      "DVT prophylaxis with LMWH unless contraindicated",
    ],
    whenToRefer: [
      "All septic shock patients: ICU admission mandatory",
      "Surgical source (perforated viscus, necrotizing fasciitis, abdominal abscess): emergent surgery/interventional radiology",
      "Renal replacement therapy for AKI with fluid overload, refractory acidosis, hyperkalemia, or uremia",
      "Infectious disease consultation for complex or resistant organisms",
    ],
    monitoringSchedule: [
      "Repeat lactate at 2 hours; goal lactate clearance ≥10% per hour",
      "Hourly urine output monitoring (goal ≥0.5 mL/kg/hr)",
      "Continuous cardiac monitoring and arterial line for real-time BP in vasopressor-dependent patients",
      "Blood cultures at 48–72 hours if clinical deterioration; repeat cultures not routinely needed",
      "CBC, BMP, LFTs, coagulation panel every 6–12 hours in ICU",
      "Procalcitonin to guide antibiotic duration (de-escalate when <0.5 ng/mL or ≥80% reduction from peak)",
    ],
    patientEducation: [
      "Explain sepsis as a medical emergency requiring hospitalization",
      "Discuss the importance of completing the antibiotic course",
      "Post-sepsis syndrome: fatigue, cognitive impairment, PTSD can persist for months; follow-up with PCP within 1–2 weeks",
      "Vaccinations: pneumococcal, influenza, meningococcal as appropriate to reduce sepsis risk",
    ],
  },
  {
    id: "em-gl-06",
    rotation: "emergency-medicine",
    conditionName: "Deep Vein Thrombosis / Pulmonary Embolism",
    guidelineName: "Antithrombotic Therapy for VTE Disease: CHEST Guideline and Expert Panel Report",
    issuingOrganization: "American College of Chest Physicians (CHEST)",
    year: 2021,
    keyRecommendations: [
      "Wells criteria for DVT (pretest probability): ≥2 points = high probability; <2 = low probability. Include active cancer, paralysis/immobilization, bedridden >3 days/surgery within 12 weeks, localized tenderness, leg swelling, pitting edema, collateral superficial veins, prior DVT.",
      "Wells criteria for PE: score ≥5 = high probability; 2–4 = moderate; <2 = low. Includes clinical signs of DVT, no alternative diagnosis, HR >100, immobilization >3 days or surgery within 4 weeks, prior DVT/PE, hemoptysis, malignancy.",
      "PERC rule (if all 8 criteria met in low pre-test probability): age <50, HR <100, SaO2 ≥95%, no unilateral leg swelling, no hemoptysis, no recent trauma/surgery, no prior PE/DVT, no exogenous estrogen — rules out PE without further testing.",
      "D-dimer is highly sensitive but not specific; use age-adjusted D-dimer cutoff (age × 10 mcg/L for age >50) to increase specificity.",
      "DOAC therapy (rivaroxaban or apixaban) is preferred over LMWH/warfarin for most VTE (non-cancer, non-pregnant).",
      "Massive PE with hemodynamic instability: systemic thrombolysis or catheter-directed therapy indicated.",
    ],
    firstLine: [
      "Apixaban 10 mg PO BID × 7 days, then 5 mg PO BID (preferred DOAC for VTE; no bridging required)",
      "Rivaroxaban 15 mg PO BID with evening meal × 21 days, then 20 mg PO daily with evening meal",
      "LMWH (enoxaparin): 1 mg/kg SC BID or 1.5 mg/kg SC daily for outpatient DVT/PE (preferred in cancer-associated VTE)",
      "Heparin infusion (weight-based) for massive PE or patients requiring urgent reversal/procedures",
    ],
    secondLine: [
      "Warfarin with LMWH bridge (target INR 2–3) — for patients unable to use DOACs (severe renal impairment, drug interactions, valvular disease)",
      "Dabigatran 150 mg BID after 5–10 days of parenteral anticoagulation",
      "Fondaparinux weight-based SC dosing (alternative to LMWH in HIT patients)",
    ],
    nonPharmacologic: [
      "Compression stockings (30–40 mmHg) for symptomatic DVT; reduce post-thrombotic syndrome risk",
      "Early ambulation is safe and encouraged for DVT; bed rest only for massive/submassive PE with hemodynamic instability",
      "Inferior vena cava (IVC) filter: only for PE/proximal DVT with absolute contraindication to anticoagulation; retrievable filters preferred",
      "Catheter-directed thrombolysis (CDT) for massive PE or extensive ileofemoral DVT with high bleeding risk for systemic thrombolysis",
      "Surgical embolectomy for massive PE with contraindication to systemic thrombolysis",
    ],
    whenToRefer: [
      "Massive PE (hemodynamic instability): immediate resuscitation + systemic tPA alteplase 100 mg IV over 2 hours; emergent catheter-directed or surgical intervention if thrombolysis fails or contraindicated",
      "Submassive PE (RV strain, elevated troponin/BNP, stable BP): consider advanced therapy at PE response team (PERT) centers",
      "Hematology for recurrent VTE, hypercoagulable workup, or antiphospholipid syndrome",
      "Vascular surgery for phlegmasia cerulea dolens (limb-threatening DVT)",
    ],
    monitoringSchedule: [
      "Renal function (CrCl) at baseline to guide anticoagulant choice and dosing",
      "CBC at baseline and after 5–10 days of heparin (monitor for HIT)",
      "INR monitoring if on warfarin: every 3 days until therapeutic, then weekly × 1 month, then monthly",
      "Follow-up in 1–3 months to assess treatment duration (provoked vs. unprovoked VTE)",
      "Provoked VTE: 3 months anticoagulation; unprovoked: 3–6 months minimum, then reassess bleeding vs. clot recurrence risk",
    ],
    patientEducation: [
      "Signs of PE: sudden dyspnea, pleuritic chest pain, hemoptysis — return to ED immediately",
      "Leg DVT: worsening swelling, severe pain, bluish discoloration — seek immediate care",
      "Medication adherence critical; missing doses significantly increases recurrence risk",
      "Avoid NSAIDs/aspirin while on anticoagulation (increased bleeding risk)",
      "Activity: encourage ambulation; avoid prolonged immobility (long flights: walk every 1–2 hours, calf exercises, compression stockings)",
    ],
  },
  {
    id: "em-gl-07",
    rotation: "emergency-medicine",
    conditionName: "Opioid Overdose",
    guidelineName: "Opioid Overdose Prevention and Naloxone Guidelines",
    issuingOrganization: "Substance Abuse and Mental Health Services Administration (SAMHSA)",
    year: 2023,
    keyRecommendations: [
      "Classic opioid toxidrome: miosis (pinpoint pupils), respiratory depression, decreased LOC (coma) — treat empirically with naloxone without waiting for drug confirmation.",
      "Naloxone is safe in suspected opioid overdose with no harm in non-opioid overdose; administer immediately when clinical diagnosis suspected.",
      "Goal of naloxone is restoration of adequate spontaneous ventilation, NOT full reversal of sedation (over-reversal causes acute withdrawal and patient may leave before safe).",
      "Fentanyl and fentanyl analogs may require higher and/or repeated naloxone doses due to high potency and receptor affinity.",
      "Naloxone half-life (30–90 minutes) is shorter than most opioids; observe patients for re-narcotization for minimum 2–4 hours after last naloxone dose.",
      "Hospital-based harm reduction: discharge with naloxone prescription, overdose education, and referral to addiction medicine/MAT programs.",
    ],
    firstLine: [
      "Naloxone 0.4–2 mg IV/IM/intranasal every 2–3 minutes until adequate respirations (RR >12/min, SpO2 >92%)",
      "Intranasal naloxone 4 mg (NARCAN nasal spray) — preferred for community/prehospital; can administer without IV access",
      "IV naloxone infusion: 2/3 of the effective reversal dose per hour (for long-acting opioids like methadone or extended-release formulations)",
      "High-dose naloxone for fentanyl overdose: titrate up to 10 mg total if no response to standard dosing (rare but documented in fentanyl analog overdoses)",
    ],
    secondLine: [
      "IM naloxone 0.4–0.8 mg if IV access unavailable (onset 5–10 minutes vs. 1–2 minutes IV)",
      "Naloxone continuous infusion for methadone or long-acting opioid overdose: start 0.4 mg/hr, titrate to maintain respiratory rate and alertness",
      "Buprenorphine/naloxone initiation (Suboxone) in ED for opioid use disorder: 4 mg buprenorphine SL when in mild-moderate withdrawal (COWS score ≥8) — bridge-prescribe 3–7 days",
    ],
    nonPharmacologic: [
      "Bag-valve-mask ventilation and airway positioning (jaw thrust, head-tilt chin-lift) while preparing naloxone",
      "Recovery position (left lateral decubitus) to prevent aspiration if adequate respiratory effort established",
      "Continuous pulse oximetry and cardiac monitoring",
      "Establish IV access early for potential repeat dosing",
      "Harm reduction counseling: needle exchange, safe use education",
    ],
    whenToRefer: [
      "Addiction medicine / MAT program referral for all opioid overdose patients prior to discharge",
      "Psychiatric consult for intentional overdose (suicide attempt)",
      "ICU admission for hemodynamic instability, aspiration pneumonia, anoxic brain injury, or requirement for naloxone infusion",
      "Social work consultation for housing instability, food insecurity, and social determinants of health",
    ],
    monitoringSchedule: [
      "Continuous SpO2 and cardiac monitoring during observation",
      "Observe minimum 2–4 hours after last naloxone dose for re-narcotization",
      "Extended observation 4–6 hours for methadone, extended-release opioid overdose, or multi-substance ingestion",
      "Urine drug screen (UDS): may guide clinical decision-making but does not detect fentanyl analogs on standard immunoassay",
      "Reassess mental status, respiratory rate, and pupil size every 15–30 minutes",
    ],
    patientEducation: [
      "Never use opioids alone: use with others who can administer naloxone if overdose occurs",
      "Start low, go slow: risk is highest when tolerance has decreased (after incarceration, detox, hospitalization)",
      "Fentanyl test strips: available at harm reduction sites to test street drugs for fentanyl contamination",
      "Naloxone carry program: prescribe and demonstrate use of intranasal or auto-injector naloxone to patient and contacts",
      "MAT options: methadone (OTP clinic), buprenorphine/naloxone (office-based), naltrexone — review with patient before discharge",
    ],
  },
  {
    id: "em-gl-08",
    rotation: "emergency-medicine",
    conditionName: "Diabetic Ketoacidosis (DKA)",
    guidelineName: "Standards of Medical Care in Diabetes — Diabetic Ketoacidosis Management",
    issuingOrganization: "American Diabetes Association (ADA)",
    year: 2023,
    keyRecommendations: [
      "DKA diagnostic criteria: blood glucose >250 mg/dL (may be lower in euglycemic DKA on SGLT2i), serum bicarbonate <18 mEq/L, pH <7.30, anion gap >12, positive serum or urine ketones.",
      "Fluid resuscitation is the most critical initial intervention and improves outcomes independent of insulin.",
      "Do NOT start insulin until potassium is ≥3.5 mEq/L (insulin drives K+ into cells, worsening hypokalemia and risking fatal arrhythmia).",
      "Insulin infusion preferred over subcutaneous in moderate-severe DKA for reliable delivery; transition to SC insulin when AG has closed and patient is eating.",
      "Identify and treat the precipitating cause (infection most common — obtain UA, CXR, blood cultures).",
      "Cerebral edema is the most feared complication in pediatric DKA; avoid excessive free water, rapid correction of osmolality.",
    ],
    firstLine: [
      "NS (0.9% NaCl) 1 L IV bolus over 1 hour initially (1–2 L in first hour for hemodynamic instability); switch to 0.45% NaCl at 250–500 mL/hr once hemodynamically stable",
      "Add dextrose (D5W or D5-0.45% NaCl) when glucose falls to 200–250 mg/dL to prevent hypoglycemia while continuing insulin",
      "Regular insulin infusion 0.1 units/kg/hr IV (without bolus per 2023 ADA; bolus 0.1 units/kg if delay in infusion start); target glucose decrease 50–75 mg/dL/hr",
      "Potassium replacement: if K+ 3.5–5.5, add 20–40 mEq KCl per liter of IV fluid; if K+ <3.5, replace aggressively before insulin; if K+ >5.5, hold and recheck in 2 hours",
    ],
    secondLine: [
      "Sodium bicarbonate: ONLY if pH <6.9 (50–100 mEq NaHCO3 in 250 mL NS over 1–2 hours); routine use is not recommended and may worsen CNS acidosis",
      "Phosphate replacement: only if serum phosphate <1 mg/dL with symptomatic hypophosphatemia; routine replacement not recommended",
      "Subcutaneous insulin protocol: may use 0.1 units/kg regular insulin SC every hour in mild DKA at experienced centers",
    ],
    nonPharmacologic: [
      "Urinary catheter for accurate hourly urine output monitoring (goal ≥0.5 mL/kg/hr)",
      "NG tube if vomiting or altered consciousness (aspiration risk)",
      "Continuous cardiac monitoring for dysrhythmias secondary to electrolyte abnormalities",
      "NPO initially; resume oral intake when nausea resolved and patient alert/oriented",
      "Transition to SC insulin: overlap SC basal insulin with stopping insulin infusion by 2 hours",
    ],
    whenToRefer: [
      "Endocrinology consultation for new-onset type 1 DM presenting in DKA or complex management",
      "ICU admission for severe DKA: pH <7.0, bicarbonate <10, altered mental status, hemodynamic instability",
      "Nephrology for AKI or severe electrolyte disturbances requiring HD",
      "Diabetic educator and dietitian before discharge for self-management education",
    ],
    monitoringSchedule: [
      "Point-of-care glucose every 1 hour during insulin infusion",
      "Basic metabolic panel (BMP) every 2–4 hours: monitor K+, Na+, HCO3, creatinine, anion gap",
      "Anion gap closure criteria: AG <12 with pH ≥7.30 and bicarbonate ≥18 mEq/L — can transition to SC insulin",
      "Serum ketones (beta-hydroxybutyrate) at presentation and to confirm resolution (goal <0.6 mmol/L)",
      "Monitor for complications: cerebral edema (headache, altered consciousness, Cushing triad in pediatric patients), pulmonary edema from fluid overload",
    ],
    patientEducation: [
      "Sick-day management rules: never skip insulin even if not eating; check glucose and ketones every 2–4 hours when ill",
      "Ketone monitoring: check urine or blood ketones when glucose >240 mg/dL or when ill",
      "Call provider or return to ED if ketones positive, glucose >300 with vomiting, or unable to keep down fluids",
      "Medication adherence: SGLT2i-associated euglycemic DKA — hold SGLT2i when fasting or perioperatively",
      "Medical alert bracelet and diabetes action plan for sick-day management",
    ],
  },
  {
    id: "em-gl-09",
    rotation: "emergency-medicine",
    conditionName: "Hypertensive Emergency",
    guidelineName: "Hypertensive Emergency Management Guideline",
    issuingOrganization: "American Heart Association (AHA)",
    year: 2017,
    keyRecommendations: [
      "Hypertensive emergency: severely elevated BP (typically >180/120 mmHg) WITH evidence of acute target organ damage (aortic dissection, hypertensive encephalopathy, acute MI, acute HF, eclampsia, acute renal failure, ICH).",
      "Hypertensive urgency: severely elevated BP WITHOUT acute target organ damage — can be managed with oral agents and close outpatient follow-up.",
      "For most hypertensive emergencies: reduce MAP by NO MORE than 10–20% in the first hour, then by no more than 25% in the first 24 hours.",
      "Exception — aortic dissection: target systolic BP <120 mmHg and HR <60 within 20 minutes (esmolol + nitroprusside or nicardipine).",
      "Exception — ischemic stroke (no thrombolytics): allow BP up to 220/120 mmHg (permissive hypertension) unless >220/120.",
      "IV titratable agents preferred for precise BP control in hypertensive emergency; avoid sublingual nifedipine.",
    ],
    firstLine: [
      "Labetalol 10–20 mg IV bolus over 1–2 minutes, repeat every 10 minutes or infusion 0.5–2 mg/min (alpha + beta blockade; avoid in asthma, COPD, decompensated HF)",
      "Nicardipine 5 mg/hr IV infusion, titrate by 2.5 mg/hr every 5–15 minutes (max 15 mg/hr) — preferred for neurologic emergencies and most hypertensive emergencies",
      "Clevidipine 1–2 mg/hr IV infusion, titrate every 90 seconds (ultra-short acting; preferred perioperatively)",
      "Hydralazine 5–10 mg IV every 20–30 minutes (preferred in pregnancy/eclampsia, though nicardipine increasingly preferred)",
    ],
    secondLine: [
      "Nitroprusside 0.3–0.5 mcg/kg/min IV infusion (most potent; use for aortic dissection combined with esmolol; cyanide toxicity risk >72 hours)",
      "Esmolol 500 mcg/kg IV bolus then 50–200 mcg/kg/min infusion (ultra-short half-life; preferred for aortic dissection rate control and peri-operative hypertension)",
      "Phentolamine 5–10 mg IV for hypertensive emergency from catecholamine excess (pheochromocytoma, cocaine, MAOI interaction, clonidine withdrawal)",
      "Fenoldopam 0.1–0.3 mcg/kg/min IV (dopamine agonist; renal protective; alternative when renal impairment present)",
    ],
    nonPharmacologic: [
      "Emergent neuroimaging (CT head) to rule out hemorrhagic stroke or hypertensive encephalopathy",
      "Continuous arterial line placement for real-time BP monitoring in severe or labile hypertension",
      "Cardiac monitoring and 12-lead EKG",
      "Urine output monitoring (AKI assessment)",
      "Fundoscopic exam for papilledema, hemorrhages, exudates (indicates chronic end-organ damage)",
    ],
    whenToRefer: [
      "Cardiology for ACS, acute HF, or aortic dissection with hypertensive emergency",
      "Neurology/neurosurgery for hypertensive encephalopathy, ICH, or hypertension complicating ischemic stroke",
      "Nephrology for acute hypertensive nephrosclerosis with AKI",
      "Obstetrics for severe-range BP (≥160/110) in pregnancy — administer antihypertensive within 30–60 minutes (gestational hypertension/eclampsia protocol)",
      "Vascular surgery for Type A aortic dissection (emergency surgical repair)",
    ],
    monitoringSchedule: [
      "Continuous arterial line BP monitoring in ICU during IV antihypertensive titration",
      "Urine output hourly (goal ≥0.5 mL/kg/hr to assess renal perfusion)",
      "BMP every 4–6 hours (creatinine, electrolytes)",
      "Serial troponin if ACS suspected",
      "Repeat neurologic assessment every 1–2 hours for encephalopathy",
    ],
    patientEducation: [
      "Medication adherence: most hypertensive emergencies result from non-adherence to antihypertensives",
      "Daily home BP monitoring: target <130/80 mmHg (AHA 2017 guidelines)",
      "DASH diet: low sodium (<1,500 mg/day), high fruits/vegetables, low saturated fat",
      "Follow-up within 1 week of discharge with primary care provider",
      "Signs requiring return to ED: severe headache, vision changes, chest pain, facial droop, arm weakness, slurred speech",
    ],
  },
  {
    id: "em-gl-10",
    rotation: "emergency-medicine",
    conditionName: "Traumatic Hemorrhage",
    guidelineName: "Trauma Hemorrhage Management — ATLS / EAST Guidelines",
    issuingOrganization: "Eastern Association for the Surgery of Trauma (EAST) / American College of Surgeons ATLS Committee",
    year: 2018,
    keyRecommendations: [
      "Hemorrhage is the leading cause of preventable trauma death; early recognition and hemostatic resuscitation are paramount.",
      "Permissive hypotension: target systolic BP 80–90 mmHg (MAP 50 mmHg) in penetrating trauma without TBI to avoid coagulopathy and clot dislodgement; AVOID in TBI (target MAP ≥80 mmHg).",
      "Massive Transfusion Protocol (MTP): activate for hemorrhagic shock not responding to initial resuscitation; target 1:1:1 ratio of packed red blood cells (pRBC) : fresh frozen plasma (FFP) : platelets.",
      "Tranexamic acid (TXA) 1 g IV over 10 minutes MUST be given within 3 hours of injury (ideally within 1 hour); a second 1 g dose over 8 hours follows.",
      "Damage control resuscitation: minimize crystalloid (causes dilutional coagulopathy, hypothermia, acidosis); prioritize blood products.",
      "Damage control surgery: abbreviated initial surgery to control hemorrhage and contamination, followed by ICU resuscitation and planned re-exploration in 24–48 hours.",
    ],
    firstLine: [
      "Direct pressure, wound packing, tourniquet application (extremity hemorrhage) — hemorrhage control before airway in penetrating extremity trauma (MARCH protocol)",
      "Massive transfusion protocol (MTP) activation: 1:1:1 ratio pRBC:FFP:Platelets; give O-negative uncrossmatched blood emergently if type and crossmatch pending",
      "Tranexamic acid (TXA): 1 g IV over 10 minutes within 3 hours of injury, then 1 g IV over 8 hours — administer in prehospital setting when possible",
      "IV access: two large-bore IVs (16-gauge or larger); IO access if unable to obtain IV in 2 attempts",
    ],
    secondLine: [
      "Calcium chloride 1 g IV (or calcium gluconate 3 g) for every 4 units of blood products (citrate in blood products chelates calcium causing hypocalcemia and myocardial depression)",
      "Cryoprecipitate for fibrinogen <150 mg/dL (goal fibrinogen ≥200 mg/dL)",
      "Prothrombin complex concentrate (PCC) for anticoagulant reversal or factor deficiency",
      "Vasopressin 0.04 units/min for refractory vasodilatory component of hemorrhagic shock (adjunct only)",
    ],
    nonPharmacologic: [
      "ATLS primary survey (ABCDE) with simultaneous hemorrhage control: Airway, Breathing, Circulation, Disability, Exposure",
      "FAST ultrasound immediately to identify hemopericardium or hemoperitoneum",
      "Pelvic binder for pelvic ring fractures (stabilizes and reduces pelvic volume to tamponade hemorrhage)",
      "Hypothermia prevention: warm IV fluids, warming blankets, warm environment (lethal triad: hypothermia + acidosis + coagulopathy)",
      "Interventional radiology embolization for solid organ injury or pelvic hemorrhage in hemodynamically stable patients",
    ],
    whenToRefer: [
      "Trauma surgery (immediately) for penetrating torso trauma, blunt abdominal injury with hemodynamic instability, or peritoneal signs",
      "Orthopedic surgery for pelvic fractures, long bone fractures with ongoing hemorrhage",
      "Neurosurgery for TBI with hemorrhagic lesion requiring intervention",
      "Vascular surgery for vascular injury with ischemia",
      "Transfer to Level I trauma center if resources unavailable at current facility",
    ],
    monitoringSchedule: [
      "Point-of-care TEG or ROTEM every 30–60 minutes during active MTP to guide targeted hemostatic therapy",
      "ABG/lactate every 30–60 minutes during resuscitation (goal lactate clearance; base deficit trend)",
      "Ionized calcium every 4 units of blood products",
      "CBC, BMP, PT/INR/aPTT, fibrinogen every 2–4 hours during resuscitation",
      "Reassess and re-examine every 5–15 minutes in unstable trauma patient",
    ],
    patientEducation: [
      "Stop the Bleed training for community members: tourniquet application, wound packing for bystander hemorrhage control",
      "Post-trauma rehabilitation: physical and occupational therapy, pain management",
      "Blood transfusion risks explained when applicable (infection, transfusion reactions)",
      "Follow-up: trauma surgery clinic within 1–2 weeks post-discharge",
    ],
  },
  {
    id: "em-gl-11",
    rotation: "emergency-medicine",
    conditionName: "Ankle and Knee Injuries",
    guidelineName: "Ottawa Ankle Rules and Ottawa Knee Rules",
    issuingOrganization: "Ottawa Civic Hospital / University of Ottawa Research Group",
    year: 1994,
    keyRecommendations: [
      "Ottawa Ankle Rules (OAR): X-ray required if pain in malleolar zone AND any of: bone tenderness at posterior edge or tip of lateral malleolus, bone tenderness at posterior edge or tip of medial malleolus, OR inability to bear weight (4 steps) both immediately and in ED.",
      "Ottawa Foot Rules: X-ray required if pain in midfoot zone AND any of: bone tenderness at base of 5th metatarsal OR bone tenderness at navicular OR inability to bear weight.",
      "Ottawa Knee Rules (OKR): X-ray required if ANY of: age ≥55, isolated patellar tenderness (no other bony tenderness), tenderness at fibular head, inability to flex knee to 90°, inability to bear weight (4 steps) immediately and in ED.",
      "OAR sensitivity for ankle fractures: 98–100%; specificity ~40% (reduces unnecessary X-rays by ~30–40%).",
      "Rules are not applicable to: children <18 years (use clinical judgment), pregnant patients, patients with distracting injury, altered mental status, or neurological deficits.",
      "Apply rules only to acute injuries within 10 days; chronic injuries or re-injury require clinical judgment.",
    ],
    firstLine: [
      "Apply Ottawa Ankle/Knee Rules to determine need for X-ray (AP, lateral, mortise views for ankle; AP, lateral, tunnel views for knee)",
      "RICE protocol: Rest, Ice (20 minutes every 1–2 hours), Compression (ACE wrap), Elevation above heart level",
      "NSAIDs: Ibuprofen 400–600 mg PO every 6–8 hours with food for 5–7 days for soft tissue injuries",
      "Air cast or stirrup brace for Grade I–II ankle sprains; non-weight-bearing with crutches for Grade III or suspected fracture until X-ray review",
    ],
    secondLine: [
      "Short leg posterior splint or CAM boot for acute ankle fractures (definitive casting vs. operative repair based on fracture pattern/displacement)",
      "Knee immobilizer for significant ligamentous injury or effusion pending orthopedic follow-up",
      "Acetaminophen 500–1,000 mg every 6–8 hours as adjunct or alternative analgesic (preferred in elderly, renal impairment, or NSAID-intolerant patients)",
      "Opioids: only for severe fractures or dislocations; avoid for isolated sprains",
    ],
    nonPharmacologic: [
      "Stress radiographs for suspected syndesmotic injury or instability if plain films negative",
      "MRI for suspected ligamentous injury, osteochondral defect, or clinical presentation inconsistent with plain film findings",
      "Physical therapy referral for Grade II–III ankle sprains and most knee ligamentous injuries after acute phase",
      "Return-to-play/activity criteria: full ROM, pain-free weight bearing, sport-specific functional testing",
    ],
    whenToRefer: [
      "Orthopedic surgery for displaced or unstable fractures, bi-malleolar or tri-malleolar ankle fractures, complete ligament tears requiring surgical repair",
      "Orthopedic follow-up within 5–7 days for non-displaced fractures managed conservatively",
      "Emergency orthopedic consultation for neurovascular compromise, open fractures, or fracture-dislocations",
      "Sports medicine for complete ACL/MCL/PCL tears and complex knee injuries",
    ],
    monitoringSchedule: [
      "Repeat X-ray in 5–7 days for fractures not clearly evident on initial films (stress/avulsion fractures may not show on initial imaging)",
      "Neurovascular checks (sensation, pulses, capillary refill) after splinting or casting",
      "Follow-up at 1–2 weeks to assess swelling, pain, and functional recovery",
    ],
    patientEducation: [
      "RICE protocol instructions: written discharge instructions with illustrations",
      "Weight-bearing instructions: non-weight-bearing vs. toe-touch vs. partial weight-bearing based on injury",
      "Return precautions: increasing pain, numbness/tingling, color change, new deformity, cast tightness",
      "Expected recovery: Grade I sprain 1–2 weeks, Grade II 3–6 weeks, Grade III 6–12 weeks or longer with surgery",
      "Prevention: proprioceptive training, appropriate footwear, ankle bracing for return to sport",
    ],
  },
  {
    id: "em-gl-12",
    rotation: "emergency-medicine",
    conditionName: "Head Trauma",
    guidelineName: "PECARN Pediatric Head Trauma Rule and Canadian CT Head Rule (CanClear)",
    issuingOrganization: "Pediatric Emergency Care Applied Research Network (PECARN) / Canadian CT Head Rule Study Group",
    year: 2020,
    keyRecommendations: [
      "PECARN rule (pediatric <18 years, blunt head trauma, GCS ≥14): Age <2: CT NOT required if normal mental status, no scalp hematoma (except frontal), no LOC ≥5 sec, non-severe injury mechanism, no palpable skull fracture, acting normally per parent — can observe. Age ≥2: CT NOT required if GCS 15, no LOC, no vomiting, no severe HA, non-severe mechanism, no signs of basilar skull fracture.",
      "Canadian CT Head Rule (adults, GCS 13–15 after witnessed LOC, amnesia, or confusion): HIGH-risk factors requiring CT: GCS score <15 at 2 hours, suspected open or depressed skull fracture, any sign of basal skull fracture, vomiting ≥2 episodes, age ≥65. MEDIUM-risk: retrograde amnesia ≥30 minutes, dangerous mechanism (pedestrian struck by vehicle, ejected from vehicle, fall >3 feet).",
      "NOT applicable to: anticoagulated patients, seizure after head trauma, obvious penetrating injury, unstable patients — these all require CT.",
      "Anticoagulated patients with head trauma should receive CT regardless of symptoms due to higher risk of intracranial hemorrhage.",
      "Repeat neurologic assessment before discharge; observe pediatric patients (especially <2 years) for 4–6 hours if CT deferred.",
      "Return precautions for mild TBI/concussion are mandatory at discharge.",
    ],
    firstLine: [
      "Non-contrast CT head (gold standard for acute intracranial hemorrhage, skull fracture) in high-risk patients per clinical decision rules",
      "Cervical spine immobilization (C-collar) for all significant blunt head trauma until C-spine clearance (NEXUS criteria or Canadian C-Spine Rule)",
      "GCS assessment: document baseline and reassess every 15–30 minutes for deterioration",
      "Acetaminophen 500–1,000 mg PO for headache (avoid NSAIDs in early concussion — theoretical concern for increased bleeding risk)",
    ],
    secondLine: [
      "MRI brain for subacute or chronic hemorrhage, non-hemorrhagic contusions, or when CT is negative but clinical concern persists",
      "Neurosurgery consultation for: epidural or subdural hematoma, depressed skull fracture, intracerebral hemorrhage, hydrocephalus",
      "Mannitol 1 g/kg IV or hypertonic saline (3% NaCl 250 mL over 30 minutes) for signs of herniation (Cushing's triad, blown pupil) as bridge to neurosurgical intervention",
      "Levetiracetam or phenytoin for post-traumatic seizure prophylaxis (high-risk TBI: GCS <10, contusion, depressed skull fracture)",
    ],
    nonPharmacologic: [
      "Head of bed elevation 30 degrees in moderate-severe TBI (reduces ICP)",
      "Hyperventilation to ETCO2 35 mmHg only as TEMPORIZING measure for impending herniation (avoid routine hyperventilation — causes vasoconstriction)",
      "Concussion management: cognitive and physical rest for 24–48 hours; graduated return-to-activity protocol (Return to Learn, Return to Sport — 6-step protocol)",
      "Avoid anticoagulants, alcohol, and contact sport until fully recovered from concussion",
    ],
    whenToRefer: [
      "Neurosurgery immediately for epidural hematoma (biconvex lens-shaped, arterial — often requires emergent craniotomy), subdural hematoma with significant mass effect or midline shift >5 mm, or depressed skull fracture",
      "Trauma surgery for polytrauma",
      "Sports medicine or concussion specialist for concussion management and return-to-play clearance",
      "Neurology for post-traumatic seizures or prolonged post-concussive symptoms",
    ],
    monitoringSchedule: [
      "GCS, pupillary response, and vital signs every 15–30 minutes in acute TBI",
      "Repeat CT head at 6–8 hours or if neurologic deterioration (GCS drop ≥2 points, new focal deficits)",
      "ICP monitoring (ventriculostomy) for severe TBI (GCS ≤8) in neurosurgical ICU",
      "Daily neurologic exams in ICU; sedation vacations to allow accurate assessment",
      "Post-concussion follow-up at 1–2 weeks: symptom checklist (headache, cognitive fog, sleep disturbance, mood changes)",
    ],
    patientEducation: [
      "Concussion: strict cognitive and physical rest first 24–48 hours; avoid screens, loud environments, alcohol",
      "Return-to-sport protocol: cannot return same day of injury; must be symptom-free at rest before starting graduated protocol",
      "Return precautions (head injury instructions): worsening headache, repeated vomiting, one pupil larger than other, seizure, difficulty awakening, confusion, weakness/numbness — return to ED immediately",
      "Anticoagulated patients: even mild head trauma requires ED evaluation and CT",
      "Helmet use for bicycling, sports, motorcycle riding to prevent future TBI",
    ],
  },
];
