import type { QuizQuestion } from "@/types";

export const emergencyMedicineQuiz: QuizQuestion[] = [
  {
    id: "em-q-001",
    rotation: "emergency-medicine",
    category: "Management",
    difficulty: "easy",
    stem: "A 68-year-old man presents with sudden crushing chest pain radiating to the left arm with diaphoresis. EKG shows 2 mm ST elevation in leads II, III, and aVF. He arrives at a PCI-capable facility. What is the door-to-balloon time goal for this patient?",
    optionsStructured: [
      { label: "A", text: "60 minutes" },
      { label: "B", text: "90 minutes" },
      { label: "C", text: "120 minutes" },
      { label: "D", text: "180 minutes" },
    ],
    correctAnswer: "B",
    explanation:
      "The door-to-balloon (DTB) time goal for primary PCI in STEMI is ≤ 90 minutes from first medical contact at a PCI-capable facility. If the patient presents to a non-PCI-capable facility, the goal is to transfer and achieve balloon inflation within 120 minutes of first medical contact, or consider fibrinolysis (thrombolytics) if transfer time would exceed 120 minutes. This patient has an inferior STEMI (STE in II/III/aVF = RCA territory in 85% of cases). Note: also check V4R (right-sided lead) for right ventricular infarction — if present, avoid nitrates (preload-dependent RV).",
    relatedConditionId: "em-stemi",
  },
  {
    id: "em-q-002",
    rotation: "emergency-medicine",
    category: "Pharmacology",
    difficulty: "medium",
    stem: "A 72-year-old woman with atrial fibrillation presents with sudden-onset right-sided weakness and aphasia. Onset was 2 hours ago. BP is 170/95, glucose is 112. Non-contrast CT head is negative for hemorrhage. She takes apixaban 5 mg BID for AF. Which of the following is the most appropriate next step regarding thrombolysis?",
    optionsStructured: [
      { label: "A", text: "Administer tPA 0.9 mg/kg IV — she is within the 4.5-hour window" },
      { label: "B", text: "Withhold tPA — she is on a direct oral anticoagulant (DOAC) which is an absolute contraindication within 48 hours" },
      { label: "C", text: "Administer tPA after reversing apixaban with andexanet alfa" },
      { label: "D", text: "Order anti-Xa level and proceed with tPA only if level is undetectable" },
    ],
    correctAnswer: "B",
    explanation:
      "Oral anticoagulant use is an absolute contraindication to tPA in ischemic stroke if: INR > 1.7 (warfarin), aPTT > 40 seconds (heparin/direct thrombin inhibitors), or if the last dose of a DOAC was within 48 hours — regardless of measured drug level in most guidelines. This patient is on apixaban, a factor Xa inhibitor. The EXTEND-IA TNK and AHA/ASA 2019 guidelines list recent DOAC use as a contraindication. While andexanet alfa can reverse apixaban, giving tPA after reversal is not an established protocol. The preferred approach for this patient is to proceed to mechanical thrombectomy evaluation (CTA for LVO), as thrombectomy is not contraindicated by anticoagulation.",
    relatedConditionId: "em-stroke",
  },
  {
    id: "em-q-003",
    rotation: "emergency-medicine",
    category: "Management",
    difficulty: "easy",
    stem: "A 55-year-old man with septic shock from a urinary source has BP 80/50, MAP 52 mmHg, HR 118, after 30 mL/kg IV fluid resuscitation. Lactate is 6.2 mmol/L. Blood cultures have been drawn and broad-spectrum antibiotics administered. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "Give another 30 mL/kg IV fluid bolus" },
      { label: "B", text: "Start norepinephrine to achieve MAP ≥ 65 mmHg" },
      { label: "C", text: "Start dopamine to achieve MAP ≥ 65 mmHg" },
      { label: "D", text: "Start vasopressin as the first vasopressor" },
    ],
    correctAnswer: "B",
    explanation:
      "After adequate fluid resuscitation (30 mL/kg), persistent hypotension (MAP < 65 mmHg) requires vasopressor therapy. Norepinephrine is the first-line vasopressor for septic shock per the Surviving Sepsis Campaign guidelines and the SOAP II trial, which showed norepinephrine was superior to dopamine (lower 28-day mortality, fewer arrhythmias). Dopamine (C) is no longer first-line and has a higher arrhythmia rate. Vasopressin (D) 0.03 units/min is added as a SECOND agent when norepinephrine requirements are high (> 0.25 mcg/kg/min) — not first-line. Additional fluid beyond 30 mL/kg (A) without vasopressors is not appropriate when the patient remains hypotensive after initial resuscitation.",
    relatedConditionId: "em-sepsis",
  },
  {
    id: "em-q-004",
    rotation: "emergency-medicine",
    category: "Management",
    difficulty: "easy",
    stem: "A 28-year-old woman develops throat tightening, urticaria, and hypotension 5 minutes after her first penicillin injection. What is the MOST appropriate immediate first-line treatment?",
    optionsStructured: [
      { label: "A", text: "Diphenhydramine 50 mg IV" },
      { label: "B", text: "Epinephrine 0.3 mg IM into the anterolateral thigh" },
      { label: "C", text: "Methylprednisolone 125 mg IV" },
      { label: "D", text: "Albuterol nebulizer treatment" },
    ],
    correctAnswer: "B",
    explanation:
      "Epinephrine 0.3 mg IM into the anterolateral thigh is the ONLY first-line treatment for anaphylaxis. Nothing else replaces it. Antihistamines (A) and corticosteroids (C) are adjuncts only — they do NOT treat the life-threatening cardiovascular and airway components of anaphylaxis and should never be given instead of epinephrine. Albuterol (D) can treat bronchospasm but not anaphylactic shock or angioedema. Delaying epinephrine to give antihistamines is a common and potentially fatal error. The IM route into the anterolateral thigh achieves peak serum epinephrine 8× faster and higher than SQ injection in the arm.",
    relatedConditionId: "em-anaphylaxis",
  },
  {
    id: "em-q-005",
    rotation: "emergency-medicine",
    category: "Labs",
    difficulty: "medium",
    stem: "A 23-year-old man with Type 1 diabetes presents with nausea, vomiting, and Kussmaul respirations. His labs show: glucose 380, Na 128, Cl 92, HCO3 10, K+ 2.8 mEq/L, pH 7.15. What is the single most important step BEFORE starting insulin?",
    optionsStructured: [
      { label: "A", text: "Give 1 ampule of sodium bicarbonate IV" },
      { label: "B", text: "Replace potassium to ≥ 3.5 mEq/L before initiating insulin infusion" },
      { label: "C", text: "Start insulin drip immediately at 0.1 units/kg/hr" },
      { label: "D", text: "Correct the sodium abnormality first with hypertonic saline" },
    ],
    correctAnswer: "B",
    explanation:
      "Before starting insulin in DKA, the serum potassium must be ≥ 3.5 mEq/L. Insulin drives potassium into cells (transcellular shift), which will further decrease an already low potassium. This patient's K+ of 2.8 is dangerously low — starting insulin without first repleting potassium can cause fatal hypokalemia and cardiac arrhythmias (ventricular fibrillation). Replace K+ aggressively (20–40 mEq/hr IV with cardiac monitoring) until K+ ≥ 3.5, then start insulin. The corrected sodium in DKA: Na + 1.6 × [(glucose − 100)/100] = 128 + 1.6 × 2.8 = 132 — the apparent hyponatremia is from osmotic dilution by hyperglycemia and corrects as glucose normalizes. Bicarbonate (A) is generally NOT indicated unless pH < 6.9.",
    relatedConditionId: "em-dka",
  },
  {
    id: "em-q-006",
    rotation: "emergency-medicine",
    category: "Pharmacology",
    difficulty: "medium",
    stem: "A 34-year-old male is brought in by EMS in an unresponsive state. Bystanders report he was using heroin. His RR is 4 breaths/min, SpO2 71%, pinpoint pupils. You administer naloxone 0.4 mg IV. He wakes up aggressively and demands to leave. 30 minutes later, he becomes somnolent again with RR of 6. What is the most likely explanation and next step?",
    optionsStructured: [
      { label: "A", text: "Re-intoxication from street heroin — re-administer 0.4 mg IV naloxone and discharge" },
      { label: "B", text: "Re-sedation from opioid outlasting naloxone — start naloxone infusion and admit for observation" },
      { label: "C", text: "Benzodiazepine co-ingestion — naloxone does not reverse benzos, give flumazenil" },
      { label: "D", text: "Hypoglycemia — check glucose and treat" },
    ],
    correctAnswer: "B",
    explanation:
      "Re-sedation is the most critical clinical hazard with naloxone administration. Naloxone has a half-life of 30–90 minutes, which is SHORTER than most opioids (heroin's active metabolite morphine lasts several hours; fentanyl analogs can last much longer). After the initial reversal, the naloxone wears off and the underlying opioid effect returns — this is re-sedation. The management is continuous naloxone infusion (typically 2/3 of the reversal dose given per hour in D5W) and hospital admission for observation. All patients with opioid overdose should be monitored for at least 2 hours (longer for long-acting opioids: methadone, extended-release formulations).",
    relatedConditionId: "em-sepsis",
  },
  {
    id: "em-q-007",
    rotation: "emergency-medicine",
    category: "Pharmacology",
    difficulty: "hard",
    stem: "You are preparing to perform RSI on a 45-year-old burn victim who sustained a full-thickness burn covering 40% BSA 5 days ago. He is hemodynamically unstable. Which RSI induction + paralytic combination is MOST appropriate?",
    optionsStructured: [
      { label: "A", text: "Etomidate + succinylcholine" },
      { label: "B", text: "Ketamine + succinylcholine" },
      { label: "C", text: "Ketamine + rocuronium 1.2 mg/kg" },
      { label: "D", text: "Propofol + succinylcholine" },
    ],
    correctAnswer: "C",
    explanation:
      "Succinylcholine is ABSOLUTELY CONTRAINDICATED in burns > 72 hours post-injury. After severe burns, proliferation of extrajunctional acetylcholine receptors (upregulation) causes massive potassium efflux when succinylcholine depolarizes the membrane — resulting in fatal hyperkalemia and cardiac arrest. This patient is 5 days post-burn = well within the danger window (72 hours to 2 years post-burn). Succinylcholine should not be used in any burn patient after 72 hours of injury. Rocuronium 1.2 mg/kg is the appropriate non-depolarizing NMB alternative with similar rapid onset (60–90 sec). Ketamine is the preferred induction agent in hemodynamically unstable patients (maintains BP via catecholamine release and is a bronchodilator). Propofol (D) causes hypotension — contraindicated in hemodynamic instability.",
    relatedConditionId: "em-stemi",
  },
  {
    id: "em-q-008",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 42-year-old woman presents with sudden palpitations and near-syncope. Vital signs: BP 88/60, HR 180, RR 20, SpO2 95%. EKG shows a wide-complex irregular tachycardia with varying QRS morphology. She has a history of Wolff-Parkinson-White syndrome. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "Synchronized cardioversion" },
      { label: "B", text: "Adenosine 6 mg IV rapid push" },
      { label: "C", text: "Diltiazem 0.25 mg/kg IV" },
      { label: "D", text: "Digoxin 0.5 mg IV" },
    ],
    correctAnswer: "A",
    explanation:
      "This patient has pre-excited atrial fibrillation with WPW syndrome — an extremely dangerous arrhythmia. The wide, irregular, polymorphic complex tachycardia at 180 bpm with hemodynamic instability represents atrial fibrillation conducted through an accessory pathway. AV nodal blocking agents (adenosine, diltiazem, verapamil, digoxin, beta-blockers) are ABSOLUTELY CONTRAINDICATED — blocking the AV node forces all conduction through the accessory pathway, causing extremely rapid ventricular rates that can degenerate into ventricular fibrillation. Since this patient is hemodynamically UNSTABLE (BP 88/60), the immediate treatment is SYNCHRONIZED CARDIOVERSION. If she were stable, the preferred pharmacologic treatment would be IV procainamide (15 mg/kg over 60 min) which blocks the accessory pathway.",
    relatedConditionId: "em-stemi",
  },
  {
    id: "em-q-009",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 29-year-old male presents with acute vertigo, vomiting, and inability to walk. He has horizontal nystagmus and his HINTS exam shows: normal head impulse test, direction-changing nystagmus, and presence of vertical skew deviation. What is the most likely diagnosis?",
    optionsStructured: [
      { label: "A", text: "Benign paroxysmal positional vertigo (BPPV)" },
      { label: "B", text: "Vestibular neuritis" },
      { label: "C", text: "Posterior circulation stroke" },
      { label: "D", text: "Meniere's disease" },
    ],
    correctAnswer: "C",
    explanation:
      "The HINTS exam identifies posterior circulation stroke (central cause) vs peripheral vestibular disorder. This patient has 'CENTRAL HINTS' — the dangerous pattern: Head Impulse = NORMAL (no corrective catch-up saccade — indicates the vestibulo-ocular reflex is intact, suggesting a central lesion), Nystagmus = direction-CHANGING (nystagmus that changes direction with gaze — a central sign), Skew = PRESENT (vertical skew deviation — a central sign). This combination strongly suggests posterior circulation stroke (cerebellum or brainstem). Vestibular neuritis would show: ABNORMAL head impulse (corrective saccade = peripheral), unidirectional nystagmus, no skew deviation. HINTS exam has 100% sensitivity and 96% specificity for posterior stroke in acute continuous vertigo — more sensitive than early MRI.",
    relatedConditionId: "em-stroke",
  },
  {
    id: "em-q-010",
    rotation: "emergency-medicine",
    category: "Management",
    difficulty: "easy",
    stem: "A FAST exam is performed on a 32-year-old male with blunt abdominal trauma after a motor vehicle crash. The exam shows free fluid in Morrison's pouch and the splenorenal recess. BP is 82/50 despite 1L NS. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "CT abdomen/pelvis with IV contrast for injury characterization" },
      { label: "B", text: "Emergent exploratory laparotomy" },
      { label: "C", text: "Another 2 liters of crystalloid and repeat FAST in 30 minutes" },
      { label: "D", text: "Transfuse 2 units pRBC and reassess hemodynamics" },
    ],
    correctAnswer: "B",
    explanation:
      "Positive FAST (intraperitoneal free fluid = hemoperitoneum) + hemodynamic instability = emergent exploratory laparotomy. This is the correct pathway and no further imaging is needed. A CT scan (A) is appropriate for hemodynamically STABLE patients to characterize injuries before OR. In an unstable patient, CT delays lifesaving surgical intervention — even minutes delay can be fatal with ongoing hemorrhage. Crystalloid (C) in hemorrhagic shock causes dilutional coagulopathy ('lethal triad': hypothermia, acidosis, coagulopathy) — use massive transfusion protocol (MTP) with packed RBCs:FFP:platelets in 1:1:1 ratio. Transfusing 2 units alone (D) while delaying OR is insufficient.",
    relatedConditionId: "em-appendicitis",
  },
  {
    id: "em-q-011",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 65-year-old male on lisinopril presents with progressive facial and tongue swelling without urticaria or hypotension, beginning 30 minutes ago after taking his medication. He is anxious but maintaining his airway. What is the most likely diagnosis and initial treatment?",
    optionsStructured: [
      { label: "A", text: "Anaphylaxis — epinephrine 0.3 mg IM and diphenhydramine" },
      { label: "B", text: "ACEi-induced angioedema — icatibant or fresh frozen plasma; epinephrine has limited benefit" },
      { label: "C", text: "Hereditary angioedema — C1 esterase inhibitor concentrate" },
      { label: "D", text: "Allergic angioedema — diphenhydramine and corticosteroids alone are sufficient" },
    ],
    correctAnswer: "B",
    explanation:
      "ACE inhibitor-induced angioedema is mediated by bradykinin accumulation (ACEi prevents bradykinin breakdown) — it is NOT IgE-mediated. Therefore, epinephrine and antihistamines have LIMITED benefit (they target histamine-mediated pathways, not bradykinin). The specific treatment is bradykinin receptor antagonism: icatibant (Firazyr — bradykinin B2 receptor antagonist, SC injection) is FDA-approved for this indication. Fresh frozen plasma contains C1 esterase inhibitor and other serine proteases that degrade bradykinin — it is an acceptable alternative. Hereditary angioedema (HAE) also involves bradykinin but is due to C1 esterase inhibitor deficiency. Discontinue the ACEi permanently — risk of recurrence with rechallenge is high. Monitor airway closely — ACEi angioedema can involve the larynx and cause fatal airway obstruction.",
    relatedConditionId: "em-anaphylaxis",
  },
  {
    id: "em-q-012",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "hard",
    stem: "A 58-year-old male presents with hypertension (210/118), sudden severe headache, and confusion. CT head shows no hemorrhage. CT head MRI shows bilateral posterior white matter T2 hyperintensities in the occipital and parietal lobes. What is the diagnosis?",
    optionsStructured: [
      { label: "A", text: "Bilateral watershed zone ischemic infarctions" },
      { label: "B", text: "Posterior Reversible Encephalopathy Syndrome (PRES)" },
      { label: "C", text: "Multiple sclerosis plaques (Dawson's fingers)" },
      { label: "D", text: "Toxoplasmosis in HIV" },
    ],
    correctAnswer: "B",
    explanation:
      "PRES (Posterior Reversible Encephalopathy Syndrome) is the hallmark of hypertensive encephalopathy. At BP > 180–200/110–120, cerebrovascular autoregulation fails → forced hyperperfusion of posterior brain (occipital, parietal) → vasogenic edema in posterior white matter. MRI findings: bilateral symmetric T2/FLAIR hyperintensities in posterior cortex and subcortical white matter (occipital and parietal lobes most commonly). It is 'reversible' with BP control — most patients recover fully. Causes: severe hypertension (#1), eclampsia, calcineurin inhibitors (cyclosporine, tacrolimus), VEGF inhibitors, chemotherapy, TTP. Treatment: controlled BP reduction (IV nicardipine or labetalol — target 25% MAP reduction in first hour), discontinue offending agents. Do NOT aggressively lower BP (cerebral ischemia risk).",
    relatedConditionId: "em-hypertensive-emergency",
  },
  {
    id: "em-q-013",
    rotation: "emergency-medicine",
    category: "Pharmacology",
    difficulty: "medium",
    stem: "A 35-year-old patient in the ED develops a regular narrow-complex tachycardia at 190 bpm. BP is 102/70. You administer adenosine 6 mg IV with a 20 mL saline flush. The rhythm briefly converts to sinus rhythm, then returns immediately to the tachycardia. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "Administer adenosine 12 mg IV rapid push with saline flush" },
      { label: "B", text: "Perform immediate synchronized cardioversion" },
      { label: "C", text: "Administer diltiazem 0.25 mg/kg IV over 2 minutes" },
      { label: "D", text: "Attempt vagal maneuvers (Valsalva, carotid sinus massage)" },
    ],
    correctAnswer: "A",
    explanation:
      "After an initial 6 mg adenosine dose that produces temporary rhythm change but then recurrence, the next step is 12 mg adenosine IV rapid bolus with immediate 20 mL saline flush. If that fails, a second dose of 12 mg may be repeated. The protocol is: 6 mg → 12 mg → 12 mg (three doses maximum). This patient is hemodynamically stable (BP 102/70) so immediate cardioversion is not required. Vagal maneuvers (D) should be attempted BEFORE adenosine in stable SVT — in this case, adenosine has already been given. After three failed adenosine doses, AV nodal blocking agents (diltiazem or verapamil) are appropriate for stable SVT. If the tachycardia is atrial flutter, adenosine will temporarily unmask flutter waves (sawtooth pattern) but will not convert it — diltiazem is then used for rate control.",
    relatedConditionId: "em-stemi",
  },
  {
    id: "em-q-014",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 26-year-old woman at 8 weeks gestation presents with sudden severe right lower quadrant pain and vaginal spotting. She is diaphoretic with BP 90/58. Transvaginal US shows no intrauterine pregnancy and a large right adnexal mass with free fluid in the pelvis. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "Serum β-hCG — if < 5,000 mIU/mL, methotrexate is appropriate treatment" },
      { label: "B", text: "Emergent surgery for ruptured ectopic pregnancy" },
      { label: "C", text: "IV fluid resuscitation and repeat US in 4 hours" },
      { label: "D", text: "Transvaginal US-guided aspiration of the adnexal mass" },
    ],
    correctAnswer: "B",
    explanation:
      "This patient has a RUPTURED ectopic pregnancy — a surgical emergency. The classic triad of: (1) positive pregnancy test + (2) hemodynamic instability (BP 90/58, diaphoresis) + (3) free pelvic fluid with no IUP on US = ruptured ectopic requiring emergent OR. Methotrexate (A) is ONLY for UNRUPTURED ectopic pregnancy in a hemodynamically STABLE patient meeting criteria (β-hCG < 5,000, mass < 3.5 cm, no cardiac activity, no contraindications). With hemodynamic instability, there is no time for further serum levels or observation (C). While awaiting surgery: two large-bore IVs, O-negative blood, OB/GYN emergent consult, immediate transport to OR.",
    relatedConditionId: "em-appendicitis",
  },
  {
    id: "em-q-015",
    rotation: "emergency-medicine",
    category: "Labs",
    difficulty: "hard",
    stem: "A 52-year-old male presents with confusion after ingesting an unknown substance at a party. ABG shows: pH 7.22, PaCO2 28, HCO3 12, PaO2 94. Serum labs: Na 140, Cl 98, HCO3 12 (AG = 30). Serum osmolality = 340 mOsm/kg. Calculated osmolality = 310 mOsm/kg. Ethanol level is zero. What is the most likely ingestion?",
    optionsStructured: [
      { label: "A", text: "Aspirin (salicylate)" },
      { label: "B", text: "Isoniazid" },
      { label: "C", text: "Ethylene glycol" },
      { label: "D", text: "Lactic acidosis from cocaine" },
    ],
    correctAnswer: "C",
    explanation:
      "This patient has an elevated anion gap metabolic acidosis (AG = 30) AND an elevated osmol gap = 340 − 310 = 30 mOsm/kg (normal < 10). The combination of elevated AG + elevated osmol gap + negative ethanol + confusion = TOXIC ALCOHOL (methanol or ethylene glycol) until proven otherwise. Ethylene glycol (antifreeze) is the most common toxic alcohol ingestion and should be suspected here. Early findings: intoxication + high osmol gap (before oxidation to organic acids). Late findings: severe AG metabolic acidosis + renal failure (calcium oxalate crystals in urine). Treatment: fomepizole 15 mg/kg IV loading dose (alcohol dehydrogenase inhibitor) + emergent hemodialysis + thiamine + pyridoxine (cofactors). Aspirin causes primary respiratory alkalosis + metabolic acidosis (mixed picture) without osmol gap.",
    relatedConditionId: "em-dka",
  },
  {
    id: "em-q-016",
    rotation: "emergency-medicine",
    category: "Management",
    difficulty: "medium",
    stem: "A 78-year-old woman on warfarin (INR 2.8) presents after a ground-level fall with a progressively worsening headache. Non-contrast CT head shows a left subdural hematoma with 8 mm thickness and 4 mm midline shift. What is the most appropriate initial management of her coagulopathy?",
    optionsStructured: [
      { label: "A", text: "Fresh frozen plasma (FFP) 2 units IV" },
      { label: "B", text: "Vitamin K 10 mg IV alone" },
      { label: "C", text: "4-factor prothrombin complex concentrate (4F-PCC) + vitamin K 10 mg IV" },
      { label: "D", text: "Warfarin reversal is not needed if INR < 3.0" },
    ],
    correctAnswer: "C",
    explanation:
      "For warfarin reversal in life-threatening intracranial hemorrhage (ICH), the preferred approach is 4-factor PCC (Kcentra) + IV Vitamin K 10 mg. 4F-PCC (contains factors II, VII, IX, X) is superior to FFP for: (1) faster reversal (15 minutes vs 2+ hours), (2) much smaller volume (50 mL vs 750–1,000 mL of FFP for INR 3.0), (3) no need for blood typing/crossmatch, (4) lower risk of transfusion-related complications. Target INR < 1.5 for ICH reversal. Vitamin K alone (B) takes 12–24 hours to work (inadequate for acute ICH). FFP alone (A) achieves reversal but slowly and with large volumes — FFP is second-line if 4F-PCC is unavailable. With midline shift and SDH, urgent neurosurgical consultation is also required.",
    relatedConditionId: "em-stemi",
  },
  {
    id: "em-q-017",
    rotation: "emergency-medicine",
    category: "Diagnosis",
    difficulty: "medium",
    stem: "A 19-year-old college student presents with sudden severe headache he describes as 'the worst headache of my life,' with nausea, vomiting, and neck stiffness. Non-contrast CT head is read as normal. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "Discharge with migraine diagnosis and prescribe sumatriptan" },
      { label: "B", text: "MRI brain with gadolinium — more sensitive than CT for subarachnoid hemorrhage" },
      { label: "C", text: "Lumbar puncture to assess for xanthochromia or elevated RBC count" },
      { label: "D", text: "CT angiography (CTA) of head without LP — CT-negative rules out SAH" },
    ],
    correctAnswer: "C",
    explanation:
      "A thunderclap headache (sudden onset, maximum intensity at time zero, 'worst headache of life') requires exclusion of subarachnoid hemorrhage (SAH) even with a negative CT head. CT sensitivity for SAH is 98% in the first 6 hours but drops to 90% at 12 hours, 85% at 24 hours, and continues to decline. LP is required after CT-negative thunderclap headache (wait ≥ 2–4 hours from headache onset to allow xanthochromia to develop). Xanthochromia (yellow CSF from bilirubin) is pathognomonic for SAH — persists up to 2 weeks. Distinguishing SAH from traumatic tap: RBC count decreases from tube 1 to tube 4 (traumatic tap) vs remains constant (true SAH). MRI (B) is not more sensitive than CT in acute SAH and is not the standard protocol. CTA alone cannot reliably exclude SAH (D) — LP remains standard.",
    relatedConditionId: "em-stroke",
  },
  {
    id: "em-q-018",
    rotation: "emergency-medicine",
    category: "Guidelines",
    difficulty: "medium",
    stem: "A 44-year-old woman presents with pleuritic chest pain, dyspnea, and HR 110. She is on oral contraceptives. Wells PE score is 5 (high probability). Her D-dimer returns at 0.8 mcg/mL. What is the most appropriate next step?",
    optionsStructured: [
      { label: "A", text: "D-dimer is elevated — rule in PE and start anticoagulation without imaging" },
      { label: "B", text: "D-dimer is below 0.9 — rule out PE and discharge" },
      { label: "C", text: "Proceed to CTPA — Wells high probability does not use D-dimer to rule out PE" },
      { label: "D", text: "Obtain bilateral lower extremity US — if positive for DVT, treat without further imaging" },
    ],
    correctAnswer: "C",
    explanation:
      "D-dimer is only used to RULE OUT PE in LOW or INTERMEDIATE pretest probability patients. In HIGH probability (Wells > 6 in the revised model, or 'likely' in the 2-tier model), D-dimer should NOT be ordered — proceed directly to CTPA. A negative D-dimer in a high-probability patient still requires CTPA because the false-negative rate is not acceptable at high pretest probability. A positive D-dimer adds no information (you would need CTPA regardless). This patient's Wells score of 5 is 'PE likely' (in the dichotomized Wells: < 5 = PE unlikely, ≥ 5 = PE likely), which requires CTPA. The correct clinical algorithm: Calculate Wells FIRST → if low probability AND PERC negative → no workup → if low/intermediate → D-dimer → if negative: discharge → if positive: CTPA → if high probability → CTPA directly.",
    relatedConditionId: "em-pe",
  },
  {
    id: "em-q-019",
    rotation: "emergency-medicine",
    category: "Physical Exam",
    difficulty: "medium",
    stem: "A 55-year-old intubated ICU patient suddenly develops hypotension (BP 75/40), HR 130, SpO2 80%, and peak airway pressures rise from 28 to 54 cmH2O. Breath sounds are absent on the right. Which of the following is the MOST appropriate immediate action?",
    optionsStructured: [
      { label: "A", text: "Stat portable chest X-ray" },
      { label: "B", text: "Increase FiO2 to 100% and adjust ventilator settings" },
      { label: "C", text: "Needle decompression of the right chest at the 2nd ICS MCL" },
      { label: "D", text: "Withdraw the ETT 2 cm (rule out right mainstem intubation)" },
    ],
    correctAnswer: "C",
    explanation:
      "This is tension pneumothorax in an intubated patient — a clinical diagnosis. The classic findings in a ventilated patient: sudden hemodynamic deterioration + rising peak airway pressures + absent unilateral breath sounds. In mechanical ventilation, positive pressure inflates air through a bronchopleural fistula creating tension. This is fatal without immediate decompression — DO NOT wait for imaging. Needle decompression at 2nd ICS MCL (or 4th–5th ICS AAL — increasingly preferred due to higher success rate in obese/muscular patients) must be performed immediately. After needle decompression, place a chest tube. Right mainstem intubation (D) would cause absent LEFT breath sounds and would be suggested by pulling back ETT — but rising peak airway pressures + hypotension suggest tension PTX, not mainstem intubation. Remember: DOPE for intubated AMS (Dislodgment, Obstruction, Pneumothorax, Equipment).",
    relatedConditionId: "em-pe",
  },
  {
    id: "em-q-020",
    rotation: "emergency-medicine",
    category: "Pharmacology",
    difficulty: "hard",
    stem: "A 72-year-old male with known severe COPD presents with an acute exacerbation. He has paradoxical breathing and is using all accessory muscles. SpO2 is 82% on 4L NC, RR is 34, he is only speaking in single words. ABG shows pH 7.28, PaCO2 68, PaO2 48. You decide to intubate. Which induction agent is most appropriate?",
    optionsStructured: [
      { label: "A", text: "Propofol 1.5 mg/kg IV" },
      { label: "B", text: "Etomidate 0.3 mg/kg IV" },
      { label: "C", text: "Ketamine 1.5 mg/kg IV" },
      { label: "D", text: "Midazolam 0.1 mg/kg IV" },
    ],
    correctAnswer: "C",
    explanation:
      "Ketamine is the preferred RSI induction agent in severe COPD/asthma exacerbation for multiple reasons: (1) Bronchodilator — stimulates catecholamine release → beta-2 agonism → bronchial smooth muscle relaxation; (2) Maintains hemodynamic stability via catecholamine release (this patient has marginal hemodynamics from respiratory failure and hypoxia); (3) Maintains airway reflexes. Propofol (A) causes significant hypotension — contraindicated in hemodynamically compromised patients (also reduces airway reflexes). Etomidate (B) is hemodynamically neutral (preferred for most RSI) but does NOT have bronchodilatory properties — acceptable second choice if ketamine unavailable, but less ideal here. Midazolam (D) is an inadequate RSI induction agent alone (unreliable amnesia/sedation, hypotension). Post-intubation management: ventilate slowly (permissive hypercapnia acceptable initially), long expiratory time (I:E ratio 1:3 to 1:5), low respiratory rate (8–12/min), avoid breath stacking and auto-PEEP.",
    relatedConditionId: "em-stemi",
  },
];
